### ISSUE TITLE
[Bug] Crash when loading v1.1.7 with Apotheosis 6.3.0 on Minecraft 1.19.2

### ISSUE THREAD

**Issue by Korumaku** [iron431/Irons-Spells-n-Spellbooks#101]
### Observed behaviour

It dun broke. Startup with just Apotheosis and dependencies instantly crashed

### Expected behaviour

It dun worked

### Steps to reproduce

Start pack with Apotheosis and dependencies and run

### Server Type

Single Player

### Crashlog

https://gist.github.com/Korumaku/9cf88eb38675d55092f3ca07d30ba7a2

### Iron's Spells N Spellbooks version

1.19.2-1.1.7

### Forge version

1.19.2-43.2.19

### Other mods

MaxHealthFix-Forge-1.19.2-8.0.1.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar
caelus-forge-1.19.2-3.0.0.6.jar
Bookshelf-Forge-1.19.2-16.3.20.jar
forge-1.19.2-43.2.19-universal.jar
curios-forge-1.19.2-5.1.4.1.jar
Patchouli-1.19.2-77.jar
geckolib-forge-1.19-3.1.40.jar
Apotheosis-1.19.2-6.3.0.jar
player-animation-lib-forge-1.0.2.jar
irons_spellbooks-1.19.2-1.1.7.jar (obv)
Placebo-1.19.2-7.3.1.jar

**Comment by briarss** [comment]
Already fixed in #99 , just wait for update
