### ISSUE TITLE
Conflict with Apotheosis version 1.19.2 - 6.3.0

### ISSUE THREAD

**Issue by bumppo109** [iron431/Irons-Spells-n-Spellbooks#104]
### Observed behaviour

Game won't progress to starting screen, error during the common setup phase

### Expected behaviour

game continues to starting screen

### Steps to reproduce

1. install Apotheosis mod 1.19.2 - 6.3.0
2. install Iron's Spells mod 1.19.2 - 1.1.7
3. launch game

### Server Type

Single Player

### Crashlog

https://gist.github.com/robertflores100/60e58fddc16c3a849f560285862a1ec5

### Iron's Spells N Spellbooks version

1.19.2 - 1.1.7

### Forge version

1.19.2 - 43.2.14

### Other mods

Apotheosis 1.19.2 - 6.3.0

**Comment by iron431** [comment]
yes we know + third duplicate + fixed in latest version
