### ISSUE TITLE
Ticking Entity Error caused by Epic Fight Mod

### ISSUE THREAD

**Issue by Kxrik** [iron431/Irons-Spells-n-Spellbooks#105]
### Observed behaviour

Whenever the spells "Shield" and "Cone of Cold" are cast the game freezes, crashes, and give me a ticking entity error
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/139735218/9895f3c8-951c-4fe4-af71-6542faa41eba)

After looking at the crash log I'm assuming it is caused by the epic fight mod.

### Expected behaviour

The game no to crash then this happens.

### Steps to reproduce

1. Install the mod and the Epic Fight mod
2. Set the Forge version to 40.1.80
3. Play

### Server Type

Single Player

### Crashlog

https://gist.github.com/Kxrik/baa6e10f5dddeb1f43f1f0183d851e3e

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.2

### Forge version

1.18.2-40.1.80

### Other mods

Epic Fight 
Epic Knight
Ice and Fire
Sophisticated Backpacks
Serene Seasons
Champions
Corpse
Guard Villagers
Pam's HarvestCraft 2
Paragliders
Tetra
Waystone
Xaero's Minimap

**Comment by iron431** [comment]
this is a known issue causes by shitty epic fight code. nothing we can really do about it

**Comment by iron431** [comment]
duplicated by #55

**Comment by iron431** [comment]
this mod should fix it https://www.curseforge.com/minecraft/mc-mods/mod-compat-fixes
