### ISSUE TITLE
[Bug] Cone of Cold Crashes server

### ISSUE THREAD

**Issue by SeppyBeep** [iron431/Irons-Spells-n-Spellbooks#107]
### Observed behaviour

whenever my friend casts cone of cold the server crashes

### Expected behaviour

should be able to use the spell normally

### Steps to reproduce

Login, friend casts cone of cold, instant crash

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/SeppyBeep/16c5a7ea076ce33392f0c2c192e584dd

### Iron's Spells N Spellbooks version

1.20.1-1.1.8

### Forge version

1.20.1

**Comment by iron431** [comment]
i cannot reproduce this. what other mods are you using?

**Comment by SeppyBeep** [comment]
we just tested it with Gust and only the mods required for this mod, still crash and whenever my friend tries to rejoin it crashes immediatly, it seems to affect most Spells you hold like Electrocute and dragon's breath  https://gist.github.com/SeppyBeep/648ada25e7f2536e5068e6407d981faa

**Comment by iron431** [comment]
ah. this is a forge bug

> - 47.1.24 Fix Entity eye height for multipart entities.

update to 47.1.24 or higher
