### ISSUE TITLE
[Bug-1.20.1] Instant disconnect when entering server. (MobSyncedCastingData?)

### ISSUE THREAD

**Issue by Gbergz** [iron431/Irons-Spells-n-Spellbooks#108]
### Observed behaviour

After playing some time in The Nether a player got instantly disconnect and can't rejoin due to some error.
![bild](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/26634554/b4f05587-6a73-4586-bb1a-f91dc3c5ad8a)

```
    at TRANSFORMER/irons_spellbooks@1.20.1-1.1.7/io.redspace.ironsspellbooks.entity.mobs.MobSyncedCastingData$1.read(MobSyncedCastingData.java:28)
    at TRANSFORMER/irons_spellbooks@1.20.1-1.1.7/io.redspace.ironsspellbooks.entity.mobs.MobSyncedCastingData$1.m_6709_(MobSyncedCastingData.java:15)
```

### Expected behaviour

Not to crash while joining.

### Steps to reproduce

Not sure how to reproduce the issue entirely.
Be in The Nether. Is one of the steps.
Bit of a head scratcher really.

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Gbergz/a6e8fbb5c9129a71697cf18d6a95a95c

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.7.jar & 1.1.8

### Forge version

47.1.3

### Other mods

a modpack so there's a few.
https://gist.github.com/Gbergz/6a55ed1e24851224c632bfccf51d2e7e

**Comment by Gbergz** [comment]
Anything on this?

**Comment by lab3** [comment]
This should resolve it.  Need to port to all versions
https://github.com/iron431/Irons-Spells-n-Spellbooks/commit/d6758f20bca68889637f6e890d3c30bab1773748

**Comment by iron431** [comment]
this should be fixed in the latest version
