### ISSUE TITLE
[Bug] Compatibility issues with Iron's Spells 'n Spellbooks

### ISSUE THREAD

**Issue by CN-QianShi** [iron431/Irons-Spells-n-Spellbooks#110]
### Observed behaviour

Iron's Spells 'n Spellbooks (irons_spellbooks) encountered an error during the common_setup event phase
  java.lang.NoSuchMethodError: 'shadows.apotheosis.adventure.loot.LootCategory shadows.apotheosis.adventure.loot.LootCategory.register(shadows.apotheosis.adventure.loot.LootCategory, java.lang.String, java.util.function.Predicate, java.util.function.Function)'

### Expected behaviour

Start the game normally

### Steps to reproduce

1. Added both Iron's Spells 'n Spellbooks 1.1.8 and Spellbooks 6.3.0 to the modpack
2. Launch the game

### Server Type

Single Player

### Crashlog

https://gist.github.com/CN-QianShi/eb146504ff558f572b4a8d1aba266254

### Iron's Spells N Spellbooks version

1.19.2-1.1.8

### Forge version

1.19.2 - 43.2.21

### Other mods

    目录: D:\game\mc\.minecraft\versions\mohouRGB\mods

Mode                 LastWriteTime         Length Name                                                                 
----                 -------------         ------ ----                                                                 
-a----         2023/7/19      8:53        3001239 arsomega-3.0.1.jar                                                   
-a----         2023/7/19      8:54          59827 ars_creo-1.19.2-3.2.1.jar                                            
-a----         2023/7/19      8:54         144989 ars_instrumentum-1.19.2-3.4.5.jar                                    
-a----         2023/7/19      8:56         492420 ars_scalaes-1.19.2-1.10.0c.jar                                       
-a----         2023/7/18     18:04          45741 AutoRegLib-1.8.2-55.jar                                              
-a----         2023/7/18     18:04         314638 balm-forge-1.19.2-4.5.7.jar                                          
-a----         2023/7/18     22:57         320523 Bookshelf-Forge-1.19.2-16.3.20.jar                                   
-a----         2023/7/19      8:12          37254 caelus-forge-1.19.2-3.0.0.6.jar                                      
-a----         2023/7/18     23:18        3063232 citadel-2.1.4-1.19.jar                                               
-a----         2023/7/18     22:58        1163374 cloth-config-8.3.103-forge.jar                                       
-a----         2023/7/18     21:30         285958 CorgiLib-forge-1.19.2-1.0.0.34.jar                                   
-a----         2023/7/18     22:56         278432 curios-forge-1.19.2-5.1.4.1.jar                                      
-a----         2023/7/18     18:36        2938383 geckolib-forge-1.19-3.1.40.jar                                       
-a----         2023/7/19      8:12        5494824 irons_spellbooks-1.19.2-1.1.5.jar                                    
-a----         2023/7/18     18:04         275378 JustEnoughResources-1.19.2-1.2.2.200.jar                             
-a----         2023/7/18     23:09        7365976 kotlinforforge-3.12.0-all.jar                                        
-a----         2023/7/18     23:09         678640 libIPN-forge-1.19-3.0.2.jar                                          
-a----         2023/7/19      8:51         512495 lodestone-1.19.2-1.4.2.jar                                           
-a----         2023/7/19      8:48           8572 MaxHealthFix-Forge-1.19.2-8.0.1.jar                                  
-a----         2023/7/19      9:32              0 mods.txt                                                             
-a----         2023/7/18     22:59         848723 moonlight-1.19.2-2.2.43-forge.jar                                    
-a----         2023/7/19      9:10         101782 mutil-1.19.2-5.1.0.jar                                               
-a----         2023/7/19      8:48         247572 Placebo-1.19.2-7.3.1.jar                                             
-a----         2023/7/19      8:13         181297 player-animation-lib-forge-1.0.2.jar                                 
-a----         2023/7/19      8:57        1978537 Sorcerium 1.1.3 (1.19.2).jar                                         
-a----         2023/7/19      8:59         744742 spellblademod-1.19.2.release.11.3.jar                                
-a----         2023/7/19      9:09        1034537 spells_and_shields-1.19.2-2.13.0.jar                                 
-a----         2023/7/18     21:26        1243852 Structory_1.19.3_v1.3.1a.jar                                         
-a----         2023/7/18     19:01         477865 Structory_Towers_1.19.3_v1.0.2.jar                                   
-a----         2023/7/18     18:36          96810 TerraBlender-forge-1.19.2-2.0.1.166.jar                              
-a----         2023/7/18     18:06         712090 totw_additions-1.2.3-1.19.x-forge.jar                                
-a----         2023/7/18     18:42         219061 TravelersTitles-1.19.2-Forge-3.1.2.jar                               
-a----         2023/7/19      9:10         268693 trolldom-1.19.2-1.1.0.jar                                            
-a----         2023/7/18     18:43         293349 YungsApi-1.19.2-Forge-3.8.9.jar                                      
-a----         2023/7/18     23:18       25655463 [Alex 的生物] alexsmobs-1.21.1.jar                                      
-a----         2023/7/18     18:03        1090499 [JEI物品管理器] jei-1.19.2-forge-11.6.0.1016.jar                          
-a----         2023/7/18     23:09        1343135 [一键背包整理Next] InventoryProfilesNext-forge-1.19-1.10.6.jar             
-a----         2023/7/19      8:49          49719 [不死图腾插槽] charmofundying-forge-6.2.1+1.19.2.jar                       
-a----         2023/7/18     18:04         409028 [传送石碑／指路石] waystones-forge-1.19.2-11.4.1.jar                         
-a----         2023/7/18     18:36       37200014 [你将去的生物群系] Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.4.jar          
-a----         2023/7/18     23:01        2752746 [农夫乐事] FarmersDelight-1.19.2-1.2.2.jar                               
-a----         2023/7/18     23:20          41302 [冰中有宝] rare-ice-0.5.1.jar                                            
-a----         2023/7/18     23:15         256024 [多态合成] polymorph-forge-0.46.4+1.19.2.jar                             
-a----         2023/7/18     22:55           1892 [夸克-奇思妙想] QuarkOddities-1.18.jar                                     
-a----         2023/7/18     18:04       14435906 [夸克] Quark-3.4-405.jar                                               
-a----         2023/7/18     22:56          34873 [夸克背包饰品] CuriosQuarkOBP-1.19.2-1.2.3.jar                             
-a----         2023/7/18     22:58          19425 [属性修复] AttributeFix-Forge-1.19.2-17.2.7.jar                          
-a----         2023/7/18     22:57         635370 [帕秋莉手册] Patchouli-1.19.2-77.jar                                      
-a----         2023/7/18     23:13         691052 [懒人厨房] cookingforblockheads-forge-1.19.2-13.3.2.jar                  
-a----         2023/7/18     23:15         440111 [搬运] carryon-forge-1.19.2-2.0.5.17.jar                               
-a----         2023/7/19      8:54       14468134 [新生魔艺] ars_nouveau-1.19.2-3.17.9.jar                                 
-a----         2023/7/18     22:53        7091512 [旅行地图] journeymap-1.19.2-5.9.7-forge.jar                             
-a----         2023/7/18     22:55         838999 [旅行者背包] TravelersBackpack-1.19.2-8.2.30.jar                          
-a----         2023/7/18     23:12         295119 [更多箱子] ironchest-1.19.2-14.2.7.jar                                   
-a----         2023/7/18     23:08         449544 [更好的F3] BetterF3-4.0.0-Forge-1.19.2.jar                              
-a----         2023/7/18     22:57          73255 [更好的进度] BetterAdvancements-1.19.2-0.3.0.148.jar                      
-a----         2023/7/19      8:47       14741075 [机械动力] create-1.19.2-0.5.1.c.jar                                     
-a----         2023/7/19      8:15         375173 [机械动力：咖啡馆] createcafe-1.2.1-1.19.2.jar                               
-a----         2023/7/19      8:15        2121033 [机械动力：甜食] create-confectionery1.19.2_v1.0.9.jar                      
-a----         2023/7/19      8:51        8908147 [灵灾] malum-1.19.2-1.5.0.2.jar                                        
-a----         2023/7/18     21:25         383269 [独特的附魔：基础] Unique Enchantments Base-1.19.2-3.0.2.1.jar               
-a----         2023/7/18     21:25         154535 [独特的附魔：战斗扩展] Unique Enchantments Battle-1.19.2-3.0.2.jar             
-a----         2023/7/18     23:01         420224 [玉 🔍] Jade-1.19.1-forge-8.8.1.jar                                   
-a----         2023/7/18     18:35         102384 [生活调味料：胡萝卜版] SoL-Carrot-1.19.2-1.14.0.jar                            
-a----         2023/7/19      9:14        1490564 [神化] Apotheosis-1.19.2-6.0.0.jar.disabled                            
-a----         2023/7/19      8:48        2082408 [神化] Apotheosis-1.19.2-6.3.0.jar                                     
-a----         2023/7/18     18:03          19083 [经验机制改革] Clumps-forge-1.19.2-9.0.0+14.jar                            
-a----         2023/7/18     22:57         210023 [自然罗盘／生物群系指南针] NaturesCompass-1.19.2-1.10.0-forge.jar                
-a----         2023/7/18     18:03          46991 [苹果皮] appleskin-forge-mc1.19-2.4.2.jar                               
-a----         2023/7/18     23:15       21401992 [超多生物群系] BiomesOPlenty-1.19.2-17.1.2.544.jar                         
-a----         2023/7/18     23:01         116824 [铁氧体磁芯] ferritecore-5.0.3-forge.jar                                  
-a----         2023/7/18     22:59       14622948 [锦致装饰] supplementaries-1.19.2-2.3.20.jar                             
-a----         2023/7/18     22:57          63128 [附魔描述] EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar              
-a----         2023/7/19      9:09        3828965 [额外扩展] additionaladditions-5.1.0.jar                                 
-a----         2023/7/19      9:10        3984635 [魔法使] mahoutsukai-1.19.2-v1.34.52.jar                                
-a----         2023/7/18     22:53          75983 [鼠标手势] MouseTweaks-forge-mc1.19-2.23.jar

**Comment by iron431** [comment]
Your log says you're using version 1.1.5 of Spells n Spellbooks

**Comment by CN-QianShi** [comment]
Sorry, there was a bug in my launcher when I organized the mods, so I didn't find that I was using an old version, and the latest version has no problems
