### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by cauebonito** [iron431/Irons-Spells-n-Spellbooks#111]
### Observed behaviour

a bug with the mod where on servers(im using ploudos) when you start casting a spell the spells starts for like 0.3 seconds and then it stops
spells like magic missile and teleport doenst have this, but fire breath, heal does, spells that have a casting time

### Expected behaviour

the spell should just cast it

### Steps to reproduce

im on a server made with ploudos irons and its dependencies are the only mods installed
take a spell that has casting time, like magma bomb or fire breath
right click it to cast it
doenst work

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2 1.1.8

### Forge version

1.19.2 43.2.21

**Comment by iron431** [comment]
closed for duplicate and poor description
