### ISSUE TITLE
[Bug] 1.20.1 Forge crashes Multipart entities 

### ISSUE THREAD

**Issue by mark0master** [iron431/Irons-Spells-n-Spellbooks#113]
### Observed behaviour

Playing on a server using the TNP Limitless 7 modpack and whenever I go to use fire breath, cone of ice, or electrocute it starts to cast and then the server crashes.

### Expected behaviour

The spells should activate and not crash the server.

### Steps to reproduce

Get a server with TNP Limitless 7 v0.10.0
Grab a spellbook
Add fire breath, cone of ice, or electrocute
Try to cast any of the 3 spells

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/mark0master/63b218201212e107ccebd45fc3abef60

### Iron's Spells N Spellbooks version

1.20.1 1.1.7

### Forge version

1.20.1 47.1.3

**Comment by iron431** [comment]
you are using forge version 47.1.17, which is known to have issues. update or downgrade forge
