### ISSUE TITLE
[Bug] Geckolib Display Issues on Legendary Tooltips

### ISSUE THREAD

**Issue by Dr-WeiAL** [iron431/Irons-Spells-n-Spellbooks#119]
### Observed behaviour

I found that Spellbooks gear was showing up on Legendary Tooltips with a problem, and came here to post an issue since Spellbooks was the only one having this problem.
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/47446553/edfc9ca6-dc77-40d8-9164-33bc5b80a068)

### Expected behaviour

Normal display of item models

### Steps to reproduce

1. Install Legendary Tooltips
2. Enter the game

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-1.1.8

### Forge version

1.20.1 - 47.1.3

### Other mods

Legendary Tooltips

**Comment by iron431** [comment]
This is a Geckolib issue. report it to them
