### ISSUE TITLE
Guardian Vex Spell/Vex Summon replacement

### ISSUE THREAD

**Issue by kaairu** [iron431/Irons-Spells-n-Spellbooks#12]
### Feature description

improve the vex spell or make a new spell that is similar to the Minecraft Dungeons Guardian Vex/Vexing Chant

### How it improves the player experience

a new spell that has a fun new vex to fight with you

### Iron's Spells N Spellbooks synergies

this mod already takes some inspiration from MC dungeons like the ice chunk spell and takes some icons from the game as well. artifacts are basically spells so why not add the Vexing Chant to this mod. i think it would fit very well with the goal/focus. 

https://minecraft.fandom.com/wiki/Minecraft_Dungeons:Vexing_Chant

![image](https://user-images.githubusercontent.com/121336317/235571696-fd33902f-5dca-4698-86bb-d51d0227259c.png)
![image](https://user-images.githubusercontent.com/121336317/235571715-c816afa9-4665-400c-8926-ae5cff10a8b5.png)
![image](https://user-images.githubusercontent.com/121336317/235571726-6bcd4b0a-c596-480c-8027-f2fdcdd8da97.png)

**Comment by iron431** [comment]
Variations of spells are something I've thought of and would definitely like to implement at some point, especially for spells like summon horse. Right now they're not a big priority however, but you're 100% right about all the mcd inspirations, and I will definitely keep this in mind in the future.
