### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ToxicDwaechi** [iron431/Irons-Spells-n-Spellbooks#120]
### Observed behaviour

game crashes on world creation

### Expected behaviour

waiting for the world to be created

### Steps to reproduce

1. Try to create a world

### Server Type

Single Player

### Crashlog

https://gist.github.com/ToxicDwaechi/2b4e2aeb53bf62a7a74cae796398f598

### Iron's Spells N Spellbooks version

irons_spellbooks-1.18.2-1.1.4.3

### Forge version

1.18.2-40.2.0

### Other mods

modpack: Vault Hunter 3rd Edition

**Comment by iron431** [comment]
The log says it is crashing due to a debug wizard. How can you be creating a world if there's already a debug wizard in it?

**Comment by ToxicDwaechi** [comment]
No idea how it happened. Launched the world for the first time.

**Comment by thicc-penguin** [comment]
Sorry if this reopens this, but to anyone getting this same error it seems that Iron's Spellbooks doesn't play well with something in the Vault Hunters 3rd Edition modpack. I'm not sure exactly which mod is causing the conflict but my theory is it relates to entities being assigned extraneous attributes by Vault Hunters applying to the debug wizard.

**Comment by iron431** [comment]
1.18 is not supported
