### ISSUE TITLE
[Bug] Summoned creatures preventing sleep

### ISSUE THREAD

**Issue by lab3** [iron431/Irons-Spells-n-Spellbooks#121]
### Observed behaviour

Summoned creatures are triggering 

"block.minecraft.bed.not_safe": "You may not rest now; there are monsters nearby",

Need to handle Monster.isPreventingPlayerRest

### Expected behaviour

Allow sleep when friendly summons are nearby

### Steps to reproduce

Summon undead
Try to sleep

### Server Type

Single Player

### Iron's Spells N Spellbooks version

All

### Forge version

All

**Comment by iron431** [comment]
woops this got released a while ago
