### ISSUE TITLE
Config option for mage tower spawn rate

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#122]
### Feature description

There are these walled towers that have a little parkour trick with candles and trapdoors leading to a miniboss fight on the top against an evoker mage.  
It would be nice to control how often they spawn as the default seems a bit high, thanks!

### How it improves the player experience

I believe it would benefit the exploration experience to reduce the spawn rate of these towers a little.

**Comment by iron431** [comment]
As it stands, it is possible to manually override the structure spawning settings with a datapack. Otherwise, extended config options for structures are something we would like to add some time in the future.

**Comment by MarioSMB** [comment]
Fair enough - I would still suggest lowering their default by a bit as the mod's structures are way too common.
