### ISSUE TITLE
[Bug] Não consigo abrir o game quando coloco o mod na pasta

### ISSUE THREAD

**Issue by Peladinhopro** [iron431/Irons-Spells-n-Spellbooks#123]
### Observed behaviour

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/75514182/615d04d3-df9a-46ab-bbca-81e4fe98e3d9)

### Expected behaviour

Abrir o jogo e jogar

### Steps to reproduce

Só coloquei o arquivo na pasta mods e ocorreu o problema

### Server Type

Single Player

### Iron's Spells N Spellbooks version

todas da 1.118.2

### Forge version

1.18.2-Forge-40.2.10

### Other mods

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/75514182/e20cf087-4c86-47a1-acdc-1d62cec69b74)

**Comment by iron431** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks/relations/dependencies
