### ISSUE TITLE
[Suggestion] Craft frozen bones into bonemeal

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#124]
### Feature description

Once you've crafted the items that need ice bones they don't really have a use. It would be nice to be able to craft them into bonemeal like normal bones, thanks!

### How it improves the player experience

Helps with excess materials.

**Comment by MarioSMB** [comment]
Perhaps this could be "solved" by simply allowing frozen bones to be smelted into regular bones, i.e. defrosting them?

**Comment by MarioSMB** [comment]
Was anything done about this? I'm not a fan of stale-bots auto closing valid issues...

**Comment by iron431** [comment]
yeah we made it so the bot can only close stale issues, but we have to mark them manually. now we use it for people who don't post logs and never check back...

this idea is simple enough and we could definitely do it
