### ISSUE TITLE
Disable tutorial book at the start

### ISSUE THREAD

**Issue by Niconoko** [iron431/Irons-Spells-n-Spellbooks#125]
### Feature description

As the title said, just wondering where the setting is. :3

### How it improves the player experience

Immersive choice then.

**Comment by iron431** [comment]
Currently, it's assumed that if patchouli is installed, the book is wanted, though many people seem to want this option regardless. For the time being, you can disable it with a datapack

**Comment by Niconoko** [comment]
Which line to disable the book?

Edit - Nvm, me got it.

**Comment by Kogomre** [comment]
@Niconoko where did you find the data file that is responsible for issuing a book on the first respawn in the world?

**Comment by iron431** [comment]
https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.19.2/src/main/resources/data/irons_spellbooks/advancements/grant_patchouli.json
