### ISSUE TITLE
[Bug] Alchemy Cauldron Crash with JEI when looking at the use at the Cauldron item

### ISSUE THREAD

**Issue by BiggestBruhMoment** [iron431/Irons-Spells-n-Spellbooks#126]
### Observed behaviour

[crash-2023-08-02_09.17.48-client.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/12236727/crash-2023-08-02_09.17.48-client.txt)

### Expected behaviour

Able to see any recipe thats available with Alchemy Cauldron without crashing

### Steps to reproduce

-In game with JEI installed
-Put Alchemy Cauldron in your inventory
-Press "U" to look at the use of the item
-Crashing

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-1.20

### Forge version

1.19.2-43.2.8

**Comment by iron431** [comment]
The version of JEI you are using is incompatible. Update JEI
