### ISSUE TITLE
[Bug] Crash when using spell on a mob [possible mod incompatibility] 

### ISSUE THREAD

**Issue by JohnnyProxo** [iron431/Irons-Spells-n-Spellbooks#127]
### Observed behaviour

When attacking a mob with a spell the game crashes and creates a server crash report despite being single player. Its worth mentioning that it could be another mod that is making the game crash because when removing TugkanDeMan's Weaponry from the mod list, this crash does not happen. I am attempting to get in contact with that mod creator to see if they can offer insight but I wanted to post here as well. 

### Expected behaviour

Damage to mob

### Steps to reproduce

Get a scroll 
Look at a mob
Cast spell on a mob

### Server Type

Single Player

### Crashlog

https://gist.github.com/JohnnyProxo/b1f3324b18f148434f00f9e056580987

### Iron's Spells N Spellbooks version

1.20.1-1.2.0

### Forge version

1.20.1 47.1.1

### Other mods

its a lot. Its in the crash report.

**Comment by iron431** [comment]
This problem is 100% caused by TugkanDeMan's Weaponry. I wouldn't be surprised if shooting something with an arrow caused the game to crash. Report issue to them.

**Comment by iron431** [comment]
I just tested it. Shooting something with a bow crashes the game too.

**Comment by JohnnyProxo** [comment]
I reached out to them and they were able to fix the issue. Thanks for the quick response.
