### ISSUE TITLE
[Bug] Necromancers don't respect Monster spawns

### ISSUE THREAD

**Issue by emoace** [iron431/Irons-Spells-n-Spellbooks#128]
### Observed behaviour

I am using the Brazier mod to get rid of monster spawns around a certain area, but doing that makes only Necromancers spawn, despite being a Monster.

### Expected behaviour

Necromancers would not spawn if monster spawns were removed from an area/biome

### Steps to reproduce

1. Install Brazier Mod (https://www.curseforge.com/minecraft/mc-mods/brazier)
2. Make a Brazier
3. Wait for mobs to spawn
4. Necromancers will still spawn

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2 - 1.1.5

### Forge version

1.19.2 - 4.3.28

**Comment by iron431** [comment]
The brazier mod offers a blacklist where you can manually add necromancers to fix your issue. This is caused by the fact that necromancers are not technically considered a monster by the game, as spellcasters are separate from monsters.

**Comment by emoace** [comment]
Thank you for the explanation! I will add them to the blacklist then!
