### ISSUE TITLE
[Bug] REI Plugin Compatibilities breaks REI 

### ISSUE THREAD

**Issue by Pixl64** [iron431/Irons-Spells-n-Spellbooks#129]
### Observed behaviour

When using REI along with REI Plugin Compatibilities, REI shows the error message:
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/85389249/46e1ddcc-b810-42c3-87b2-7c64dbbcad50)
and the recipe screen (by pressing R or U) cannot be opened for any item. I have tried loading without the Plugin Compat mod, and the recipes work fine, but modded recipes are not shown so it is necessary to have installed. The log attached below also shows it is the two mods conflicting.

### Expected behaviour

The recipes would be able to be viewed, and the error message wouldn't be shown

### Steps to reproduce

1. Install REI and REI Plugin Compatibilities
2. Install Iron's Spells and Spellbooks
3. Load the game
4. Attempt to open the recipe screen by pressing R or U on an item.

### Server Type

Single Player

### Crashlog

https://gist.github.com/Pixl64/eb65ecd1368ca8e2adaa6f0dee48e264

### Iron's Spells N Spellbooks version

v1.18.2-1.1.4.3

### Forge version

1.18.2 - 40.2.4

**Comment by iron431** [comment]
This seems like an REI issue to me. Make sure you're using the latest version of REI, but if you want JEI plugins, use JEI. No plans to fix this for 1.18
