### ISSUE TITLE
[Suggestion][1.19.2] Interact with the Consolidation mod

### ISSUE THREAD

**Issue by Diemoerm** [iron431/Irons-Spells-n-Spellbooks#130]
### Feature description

Existing situation：
When both the Consolidation mod and this mod are installed at the same time，
Item.of('irons_spellbooks:scroll', '{ISB_spell:{level:10,type:18}}') Unable to deal damage to undead creatures，
Ideal situation：
Item.of('irons_spellbooks:scroll', '{ISB_spell:{level:10,type:18}}') can deal damage to undead creatures

### How it improves the player experience

This can make spells more in line with common sense

**Comment by SiverDX** [comment]
you should link the mod youre talking about (e.g. curseforge or modrinth)

**Comment by Diemoerm** [comment]
> 你应该链接你正在谈论的模组（例如诅咒锻造或模组）

This is the mod I am discussing：  https://www.curseforge.com/minecraft/mc-mods/consecration

**Comment by SiverDX** [comment]
isnt that what the config is there for...?

![grafik](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/22003703/a61b8b17-8304-4682-8b4c-c083643ed998)

**Comment by Diemoerm** [comment]
> isnt that what the config is there for...?
> 
> ![grafik](https://user-images.githubusercontent.com/22003703/258788962-a61b8b17-8304-4682-8b4c-c083643ed998.png)

After filling out this text, it seems that it did not take effect properly after testing, and a highest level spell only deals 3 damage.
This module will continuously restore health to undead creatures, which can only be made fragile by giving them a "connection: strong_holly" effect. I don't know much about programming and how to achieve this effect
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/118152499/002cc2f4-d961-4873-8ce3-3fcb365a06e1)

**Comment by Diemoerm** [comment]
> 

"consecration:holy" and "consecration:strong_holy" effect can cause undead creatures to lose their ability to restore life, but the 'sacred' type magic in the irons spell book cannot cause the same effect

**Comment by SiverDX** [comment]
then you did something wrong

level 6 guiding bolt scroll, stops life regen as intended
also works for wisp ("wisp_spell")

![grafik](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/22003703/c9387d5b-d8f6-4f90-82b8-539702bf4c1c)

**Comment by iron431** [comment]
It looks like they already have config support, and there doesn't seem to be an API for me to interact with anyways
