### ISSUE TITLE
Crashes at start (1.18.2 - TLauncher)

### ISSUE THREAD

**Issue by XennT** [iron431/Irons-Spells-n-Spellbooks#132]
Hi! My game crashes at start in 1.18.2 release. It works with 1.19.2 but I can't enter the game with 1.18.2 one.

Forge version: 
1.18.2 - 40.2.9

My downloaded mods:
irons_spellbooks-1.18.2-1.1.4.3
geckolib-quilt-1.18-3.0.46
player-animation-lib-fabric-1.0.2+1.18
curios-forge-1.18.2-5.0.9.1
caelus-forge-1.18.1-3.0.0.2
OptiFine_1.18.2_HD_U_H9 (I tried without it, still not working)

https://gist.github.com/XennT/ea53735093c7e148676d2a4b66a78457
https://gist.github.com/XennT/afd0d05ba805f013350c180afea8da09

**Comment by iron431** [comment]
we don't support t launcher
