### ISSUE TITLE
[Bug] Crashes at start (1.18.2)

### ISSUE THREAD

**Issue by XennT** [iron431/Irons-Spells-n-Spellbooks#134]
### Observed behaviour

Hi! I opened a issue yesterday about this problem. I was playing the game with TLauncher so you said that you don't support TLauncher. I tried to enter game on official Minecraft Launcher and I'm still having the same problem. My game crashes at start in 1.18.2 release.

### Expected behaviour

-

### Steps to reproduce

-

### Server Type

Single Player

### Crashlog

https://gist.github.com/XennT/d99389223cad77501251d22321d21897

### Iron's Spells N Spellbooks version

1.18.2 - 1.1.4.3

### Forge version

1.18.2 - 40.2.9

### Other mods

geckolib-quilt-1.18-3.0.46
player-animation-lib-fabric-1.0.2+1.18
curios-forge-1.18.2-5.0.9.1
caelus-forge-1.18.1-3.0.0.2
OptiFine_1.18.2_HD_U_H9 (I tried without it, still not working)

**Comment by iron431** [comment]
you're using the fabric version of the dependencies
