### ISSUE TITLE
Add armour toughness and more config options 

### ISSUE THREAD

**Issue by HatsuneCrusher** [iron431/Irons-Spells-n-Spellbooks#135]
### Feature description

pls add some armour toughness to the armour sets or let us set it by upgrading or by config file.
In config file add an option to set the base damage of the spells and make the per level damage augment editable.

(OT) bring back the old arcana cloth sprite it was way better

i love this mod 

### How it improves the player experience

Armour toughness is essential to the player in order to not be popped by monsters too easly,
this is useful if the player is playing different mods and chooses to be a wizard, the option to let the player to set his armour toughness helps in balancing the damage taken by the player by mobs form other mods, in my opinion making possible to set it by config file is the best option.

Setting the base damage of the spell not only just by multiplying it helps in general to make a more precise balancing in early game phases, an example: 

zombie has 20 hp a spell casts 10 dmgs  by default.
in late game a mob by any mod has 200+ hp.
in order to balance the spell right now i have to multiply the default spell dmg making it way too hight for early phases of the gameplay.

with more precise config options the problem is solved.

**Comment by iron431** [comment]
This may get added in the future, but for the time being, you can always use mods like Crafttweaker to add toughness to your armor. Also, the best way to increase a spell's power ceiling while not making lower levels OP is to increase it's max level, not its power multiplier.

**Comment by HatsuneCrusher** [comment]
i have to be honest, the problem is that i never coded in my life so is very difficult for me to use CraftTweaker, but if u have any template to start with maybe i can give it a try ... btw the balance using the level system worked well tnx a lot
