### ISSUE TITLE
[Bug] Infinite casts for spell

### ISSUE THREAD

**Issue by Zanckor** [iron431/Irons-Spells-n-Spellbooks#136]
### Observed behaviour

If player cast a scroll/spell and instead of releasing the right click, if player switches slot and releases the right click, the spell won't consume.

### Expected behaviour

Once player change slot, if was being casted (and effect was used) remove the item from inventory.

### Steps to reproduce

1. Charge a scroll
2. With keyboard or scrolling the mouse wheel, change the slot to another slot. 

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-1.2.1

### Forge version

1.20.1-47.1.44

**Comment by iron431** [comment]
This should be fixed in 2.0.0
