### ISSUE TITLE
[Bug] INMORTAL PYROMANCER

### ISSUE THREAD

**Issue by Maxthon6** [iron431/Irons-Spells-n-Spellbooks#137]
### Observed behaviour

inmortal pyromancer, even commands can't kill the pyromancer 

### Expected behaviour

Pyromancer inmortal even to change difficult to peaceful

### Steps to reproduce

1.- Spawn
2.- Exist
3.- Inmortality 

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2-1.1.8

### Forge version

1.19.2 - 43.2.21

### Other mods

![2023-08-15_22 23 22](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/123339462/e2ab5123-6dc2-4e15-b049-cad9731a6346)
[modlist.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/12360807/modlist.txt)

**Comment by iron431** [comment]
do /modlist and update "Other Mods"

**Comment by Maxthon6** [comment]
updated
