### ISSUE TITLE
[Bug] Invisibility spell does not work on mobs

### ISSUE THREAD

**Issue by TheMispelledWord** [iron431/Irons-Spells-n-Spellbooks#138]
### Observed behaviour

Invisibility does not work for creatures or hostile entities.

### Expected behaviour

Casting Invisibility of any level will make creatures and hostile mobs not be able to see you, therefor enemies will not attack.

### Steps to reproduce

1. Cast Invisibility
2. Walk in front of a skeleton
3. Get shot and double check the wiki

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.2.1

### Forge version

43.2.11

**Comment by iron431** [comment]
https://minecraft.fandom.com/wiki/Invisibility#Notes
How close were you to the skeleton?

**Comment by TheMispelledWord** [comment]
According to the wiki

**Comment by TheMispelledWord** [comment]
According to the wiki, close enough for them to see me. Thanks for posting that, I didn't know that invis worked like that before this. 
I was sure this was a bug because true invis gets rid of armor and held items. I assumed that this meant that the detection range taking into account armor and held items would be equal to that of normal invis without any armor no matter what. I was wrong.
