### ISSUE TITLE
Infinite mana for Creative mode and functional /mana add or set

### ISSUE THREAD

**Issue by michaelmj850** [iron431/Irons-Spells-n-Spellbooks#139]
### Feature description

Currently if you are on creative mode you have to wait for cooldowns and wait for mana to refill just as if you were on survival mode. Mana on creative mode should be infinite and allow for the command /mana set or add to actually work.. It’s such a hassle trying to test spells interactions when you have to abide by those mana refill wait times. I don’t know if this is already a thing but whenever I type /mana set () and add a number bigger the the current capacity it gets capped to that max capacity. Please allow the command to increase max mana capacity and not just instantly refill the current capacity.

### How it improves the player experience

If you allow the command for “infinite” mana to it can greatly optimize feature testing and can make things go so much smoother when testing different interactions on survival mode.

**Comment by iron431** [comment]
if you want to change your max mana, use /attribute
