### ISSUE TITLE
Optifine Texture armor problem

### ISSUE THREAD

**Issue by MrSeal696** [iron431/Irons-Spells-n-Spellbooks#140]
### Observed behaviour

Texture not showing when wearing armor.
![изображение_2023-08-20_181541040](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/65753830/e99352f9-830e-40d5-839b-cb45725a3720)

### Expected behaviour

Armor should be displayed

### Steps to reproduce

1. Put on any armor from the mod

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

1.20.1 - 47.1.0

### Other mods

Optifine, Minecolonies, jei

**Comment by iron431** [comment]
optifine isnt meant to be used with mods. use oculus
