### ISSUE TITLE
[Bug] Tooltips blank

### ISSUE THREAD

**Issue by AstrielRiv** [iron431/Irons-Spells-n-Spellbooks#141]
### Observed behaviour

I was playing with my friend, wanted to craft a spell on the scroll forge and when I wanted to read the description of the spell.... no text...
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/76536468/c18315d1-2a1a-4d3b-8b31-face66ed29bd)

### Expected behaviour

There should be text

### Steps to reproduce

1. go on a scroll forge
2. put the material to craft any spell
3. put your mouse on a spell to try to read the description.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-1.2.0

### Forge version

47.1.0

### Other mods

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/76536468/baa5319b-f387-45bc-b094-f58f0f20e24c)

**Comment by iron431** [comment]
it looks like a mod you have is reformatting tooltips. what mod adds that arrow button?
