### ISSUE TITLE
[Bug] Quick cast crash

### ISSUE THREAD

**Issue by turbo514** [iron431/Irons-Spells-n-Spellbooks#142]
### Observed behaviour

I set the quick cast slot 05,but there is only four spells in my spellbook.When I press the key "quick cast slot 05",the game will crash.

### Expected behaviour

the game doesn't crash and nothing happened.

### Steps to reproduce

1.Set set the quick cast slot.
2.make sure that there is not enough spells in the spellbook
3.hold the spellbook and press the key just set
4.the game crash

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.3

### Forge version

40.2.10

**Comment by iron431** [comment]
fixed in 1.1.4.4
