### ISSUE TITLE
[Bug] In most places, incorrect localization into Russian

### ISSUE THREAD

**Issue by WolfAvenger** [iron431/Irons-Spells-n-Spellbooks#143]
### Observed behaviour

In tooltips there is mixed translation which sometimes misses cases, plurals and mix english and russian localizations.

### Expected behaviour

Most of localizations into Russian is correct. Please contact me in discord (k.o._patich) to agree with localizations.

### Steps to reproduce

1. In game open JEI or hover mouse over the scroll / book / some rings / talismans / armors / non-placeable items / poison rune
![изображение](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/37224922/127c4e98-4934-4654-844b-37e7cc287f0e)
![изображение](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/37224922/2b534a22-e8df-462b-b90e-81da6b84b2a7)
![изображение](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/37224922/f7f6e58a-759b-49a6-b0a5-8e0c204df2be)
![изображение](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/37224922/f3cc2ae3-c74c-421b-8310-a3a4c756eb80)

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2-1.1.3

### Forge version

1.19.2-last

### Other mods

- Jade-1.19.1-forge-8.8.1
- jei-1.19.2-forge-11.4.0.286

**Comment by iron431** [comment]
All non-english translations were done by community members. I assume the mix of russian and english is caused by missing language entries. You can make a pull request if you are interested in doing translations, but otherwise I don't know russian and will not be working on this
