### ISSUE TITLE
[Bug] Geckolib rendering issues with oculus after turning on Shaders

### ISSUE THREAD

**Issue by fzrdwa123456** [iron431/Irons-Spells-n-Spellbooks#144]
### Observed behaviour

![MOR}B}9DQ5V5L(DM~8MU FM](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/130232431/f8a487d2-07fa-42ba-9501-21b6337c7329)
Player reflection appears in the sky

### Expected behaviour

Player reflection appears in the sky

### Steps to reproduce

1 Open Shaders
2 Wear Iron's Spells 'n Spellbooks gear
3 Look to the sky

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.19.2-1.2.1

### Forge version

forge 43.2.21

**Comment by kaairu** [comment]
this is an issue with geckolib. which is a dependency for ISS armors. any mod that uses geckolib for armors will have this bug

**Comment by fzrdwa123456** [comment]
> 这是壁虎的一个问题。这是国际空间站装甲的依赖。任何使用壁虎作为盔甲的模组都会有这个错误

Thank you for answering, so can this issue be fixed in the future?

**Comment by iron431** [comment]
it is fixed on 1.20+. geckolib no longer supports 1.19
