### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BiakCeu** [iron431/Irons-Spells-n-Spellbooks#148]
### Observed behaviour

The players would crash but the server would remain opened. It happened when exploring a dungeon for one instance and the other when simply fighting mobs. Both times the necromancer was mentioned in the logs along with something was "null". I believe both instances the necromancer was trying to wear armor. That ability to wear armor is provided by improved mobs.

### Expected behaviour

Nothing else to be expected. I simply didn't think it would crash until it did.

### Steps to reproduce

Not sure what steps to provide as both instances that were mentioned were simply through gameplay by me and my friends. Perhaps load up a world and set difficulty to hard and wait until you crash perhaps.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-1.2.1

### Forge version

47.1.3

### Other mods

https://gist.github.com/BiakCeu/105205282254f3177bd6b69d8ced0241

**Comment by iron431** [comment]
This might be an issue with geckolib's latest update. I'll look into it, but downgrading to 4.2.1 might just fix it for now

**Comment by iron431** [comment]
geckolib 4.2.2 is fine, it actually seems to be an issue with ad astra. report it to them 

> at earth.terrarium.ad_astra.client.renderer.armor.ArmourRenderers.lambda$init$2(ArmourRenderers.java:32) ~[ad_astra-forge-1.20.1-1.15.3.jar%23531!/:?] {re:classloading}
