### ISSUE TITLE
[Bug]  Crash when on a dedicated server

### ISSUE THREAD

**Issue by turbomulot** [iron431/Irons-Spells-n-Spellbooks#15]
### Observed behaviour

Hi. when Using the latest version of Iron spells n spellbook, the server will not be able to launch because the mod try to call a clientside only object

### Expected behaviour

I expected the server to not crash on startup.

### Steps to reproduce

1. Install the mod on a server
2. Try to launch the server
3. ???
4. Profit

### Crashlog

https://gist.github.com/turbomulot/588ddeb19c419afe680548e5ff104e52

### Iron's Spells N Spellbooks version

1.0.4

### Forge version

1.19.2.43.2.6

### Other mods

<details>
  <summary>Click here</summary>
  

abnormals_delight-1.19.2-4.0.2.jar
adaptive_performance_tweaks_core_1.19.2-6.5.0.jar
adaptive_performance_tweaks_gamerules_1.19.2-6.5.0.jar
AdLods-1.19.2-7.0.7.1-build.0759.jar
AI-Improvements-1.19.2-0.5.2.jar
alexsdelight-1.4.1.jar
alexsmobs-1.21.1.jar
allurement-1.19.2-3.1.0 (1).jar
almostunified-forge-1.19.2-0.3.5.jar
ambientadditions-1.19.2-0.1.3.jar
AmbientSounds_FORGE_v5.2.13_mc1.19.2.jar
Amplified_Nether_1.19.3_v1.2.1.jar
appleskin-forge-mc1.19-2.4.2.jar
Aquaculture-1.19.2-2.4.8.jar
Architects-Palette-1.19.2-1.3.2.jar
architectury-6.4.62-forge.jar
armorpointspp-forge-1.19.3-3.0.9.jar
ars_artifice-1.19.2-1.0.4.jar
ars_creo-1.19.2-3.1.3.jar
ars_elemental-1.19.2-0.5.8.2.jar
ars_instrumentum-1.19.2-3.3.1.jar
ars_nouveau-1.19.2-3.13.2.jar
ars_scalaes-1.19.2-1.9.0.jar
arsarmiger-1.19.2-1.4.0.jar
artifacts-1.19.2-5.0.2.jar
atmospheric-1.19.2-5.0.0.jar
AttributeFix-Forge-1.19.2-17.1.3.jar
AutoRegLib-1.8.2-55.jar
autumnity-1.19.2-4.0.0.jar
auudio_forge_1.0.3_MC_1.19.jar
baby_delight_1.0.0_forge_1.19.2.jar
babyfat-forge-1.19.2-1.1.2.jar
balm-4.5.3.jar
BarteringStation-v4.0.3-1.19.2-Forge.jar
baubley-heart-canisters-1.19.2-2.0.0.jar
beautify-1.4.3.jar
bedspreads-forge-6.0.0+1.19.2.jar
bendy-lib-forge-2.1.1.jar
berry_good-1.19.2-6.0.1.jar
bettas-forge-1.19.2-1.1.0.jar
BetterAdvancements-1.19.2-0.2.2.142.jar
bettercombat-forge-1.6.2+1.19.jar
BetterF3-4.0.0-Forge-1.19.2.jar
biome_backlog-1.19.2-1.1.2.jar
biomemakeover-FORGE-1.19.2-1.6.4.jar
blueprint-1.19.2-6.1.2.jar
boatload-1.19.2-4.2.1.jar
Bookshelf-Forge-1.19.2-16.2.17.jar
Botania-1.19.2-438-FORGE.jar
botarium-forge-1.19.2-1.8.2.jar
BrewinAndChewin-1.19-2.0.jar
buzzier_bees-1.19-5.0.1.jar
caelus-forge-1.19.2-3.0.0.6.jar
canary-mc1.19.2-0.1.9.jar
casting_crystals-1.0.3.jar
catalogue-1.7.0-1.19.2.jar
cave-enhancements-1.19.2-2.1.11-forge.jar
caverns_and_chasms-1.19.2-1.0.0-beta1.jar
chipped-forge-1.19.2-2.1.4.jar
citadel-2.1.1-1.19.jar
clayworks-1.19.2-2.0.1.jar
clienttweaks-forge-1.19-8.1.0.jar
cloth-config-8.2.88-forge.jar
Cluttered-2.0.1-1.19.2.jar
CNB-1.19-1.5.2.jar
CoffeeDelight-Forge-1.19.2-1.2.jar
collectorsreap-1.19-1.2.3.jar
comforts-forge-6.0.3+1.19.2.jar
CompletionistsIndex-v4.0.0-1.19.2-Forge.jar
compressedcreativity-1.19.2-0.1.5.jar
connectedglass-1.1.6-forge-mc1.19.jar
connectivity-1.19.2-3.4.jar
coroutil-1.19.2-1.2.37.jar
CosmeticArmorReworked-1.19.2-v1a.jar
CozyHome-1.19.2-1.2.0.jar
create_central_kitchen-1.19.2-for-create-0.5.0.i-1.3.4.jar
create_crystal_clear-0.1.2e-1.19.2.jar
create_enchantment_industry-1.19.2-for-create-0.5.0.i-1.2.0.jar
create_jetpack-2.1.3.jar
create-1.19.2-0.5.0.i.jar
Create+Train+Additions+0.2.0.jar
createaddition-1.19.2-20230313a.jar
createaddition-1.19.2-20230404a.jar
createarmoryv0.5.2.jar
createcafe-1.1.6-1.19.2.jar
createchunkloading-1.3.0-forge.jar
createdeco-1.3.1-1.19.2.jar
createlectrified1.19.2pre-v0.1.jar
createoreexcavation-1.19-1.1.0.jar
createplus-1.19.2_v0.5.2a.jar
CreativeCore_FORGE_v2.9.3_mc1.19.2.jar
creeperoverhaul-2.0.9-forge.jar
Critters++Cryptids+1.2.0.jar
crittersandcompanions-1.19.2-1.1.2.jar
Croptopia-1.19.2-FORGE-2.2.2.jar
CTM-1.19.2-1.1.6+8.jar
culturaldelights-1.19.2-0.15.2.jar
curios-forge-1.19.2-5.1.4.0.jar
CuriosQuarkOBP-1.19.2-1.2.2.jar
davespotioneering-1.19.2-1.1.2.jar
Decorative+Blocks-forge-1.19.2-3.0.0.jar
Delightful-1.19.2-3.2.4.jar
Ding-1.19.2-1.3.0.jar
Display+Case-forge-1.19-1.0.3.jar
do-a-barrel-roll-2.6.1+1.19.2-forge.jar
DoggyTalentsNext-1.19.2-1.11.2.jar
domesticationinnovation-1.6.1-1.19.2.jar
dragon_enchants-1.0.4-1.19.2.jar
drinkbeer-refill-1.19.2-1.0.1.jar
dungeonnowloading-18.2-1.19.2.jar
dungeons_plus-1.19.2-1.3.0.jar
DungeonsArise-1.19-2.1.51-beta.jar
DustrialDecor-1.3.3-1.19.2.jar
dustydecorations-1.0-1.19.2.jar
dynview-1.19.1-2.9.jar
earthtojavamobs-forge-mc1.19.2-1.9.3+1.19.2.jar
easy_piglins-1.19.2-1.0.0.jar
easy_villagers-1.19.2-1.0.0.jar
eatinganimation-1.19-3.1.0.jar
ecologics-forge-1.19.2-2.1.11.jar
effective_fg-1.3.4.jar
elytraslot-forge-6.0.0+1.19.2.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar
endergetic-1.19.2-4.0.0.jar
endersdelight-1.19-1.0.2.jar
endsdelight-1.19.2-1.1.1.jar
engineersdecor-1.19.2-forge-1.3.28.jar
EnigmaticLegacy-2.26.5.jar
enlightend-1.19.2-v5.0.0.1.jar
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
environmental-1.19.2-3.0.0.jar
everycomp-1.19.2-2.2.3.jar
exoticbirds-1.19.2-2.6.0.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
extendedflywheels-1.2.5-1.19.2-0.5.f.jar
extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar
Fallingleaves-1.19.1-2.0.0-alpha+20221129-2000.jar
fantasyfurniture-1.19.2-6.7.0.jar
FarmersDelight-1.19-1.2.0.jar
FarmersRespite-1.19-2.0.jar
FastFurnace-1.19.2-7.0.0.jar
FastSuite-1.19.2-4.0.0.jar
FastWorkbench-1.19.2-7.0.1.jar
ferritecore-5.0.3-forge.jar
Festive_Delight_1.0_1.19.2.jar
finsandtails-1.19.2-1.0.1.jar
FixMySpawnR-forge-1.19.2-1.1.2.jar
ForgeEndertech-1.19.2-10.0.5.2-build.0735.jar
forgivingvoid-forge-1.19-7.0.0.jar
FramedBlocks-6.7.0.jar
friendsandfoes-forge-mc1.19.2-1.8.1.jar
ftb-library-forge-1902.3.11-build.166.jar
ftb-ultimine-forge-1902.3.5-build.65.jar
geckolib-forge-1.19-3.1.39.jar
GottschCore-mc1.19.2-f43.2.0-v2.0.0.jar
habitat-1.2.2.jar
handcrafted-forge-1.19.2-2.0.5.jar
healingflasks1.2.1.jar
hearth_and_home-forge-1.19.2-1.0.1.jar
idas_forge-1.6.3+1.19.2.jar
IKnowWhatImDoing-5.1.1-forge.jar
immersive_paintings-0.4.4+1.19.2-forge.jar
ImmersiveEngineering-1.19.2-9.2.1-164.jar
ImmersivePosts-1.19.2-4.3.0-6.jar
incubation-1.19-3.0.0.jar
infernal-expansion-1.19.2-2.5.3.jar
infinidrill-1.1.7.jar
integrated_api_forge-1.0.0+1.19.2.jar
integrated_api_forge-1.2.2+1.19.2.jar
integrated_stronghold_forge-1.0.1+1.19.2.jar
irons_spellbooks-1.0.4.jar
ItalianDelight-1.19.2+1.5-MAR_FIX.jar
Jade-1.19.1-forge-8.7.0.jar
JadeAddons-1.19.2-forge-3.3.0.jar
jamd-forge-2.0.5-build.12+mc1.19.2.jar
javd-forge-4.0.1-build.2+mc1.19.2.jar
jeed-1.19.2-1.18.jar
jei-1.19.2-forge-11.5.2.1007.jar
jeimultiblocks-1.19.2-0.0.3.jar
jepp-1.19-1.0.1.jar
JER-Integration-4.3.1.jar
journeymap-1.19.2-5.9.2-forge.jar
jumpboat-1.19-0.1.0.5.jar
jumpoverfences-forge-1.19.2-1.1.0.jar
JustEnoughProfessions-forge-1.19.2-2.0.2.jar
JustEnoughResources-1.19.2-1.2.2.200.jar
kiwiboi-1.19.2-1.1.0.jar
kleeslabs-forge-1.19-12.1.0.jar
konkrete_forge_1.6.0_MC_1.19-1.19.2.jar
kotlinforforge-3.9.1-all.jar
lazydfu-1.19-1.0.2.jar
LGH-1.4.2-beta2.jar
maenchants-1.19.2-6.0.0.jar
mavapi-1.0.1-mc1.19.2.jar
mavm-1.2.0-mc1.19.2.jar
mcw-bridges-2.0.6-mc1.19.2forge.jar
mcw-doors-1.0.7-mc1.19.2.jar
mcw-fences-1.0.7-mc1.19.2forge.jar
mcw-furniture-3.0.2-mc1.19.2.jar
mcw-lights-1.0.5-mc1.19.2forge.jar
mcw-paintings-1.0.4-mc1.19.2.jar
mcw-paths-1.0.2forge-mc1.19.2.jar
mcw-roofs-2.2.2-mc1.19.2forge.jar
mcw-trapdoors-1.0.8-mc1.19.2forge.jar
mcw-windows-2.1.1-mc1.19.2forge.jar
meetyourfight-1.19.2-1.3.2.jar
miners_delight-1.19.2-1.1.1.jar
modernfix-mc1.19.2-3.4.1.jar
modonomicon-1.19.2-1.27.0.jar
molten_vents-1.19.2-0.1.3.jar
moonlight-1.19.2-2.2.29-forge.jar
More+Wandering+Trades+1.0.0+-+1.19.2.jar
moremobvariants-forge_1.19.2-1.1.0.jar
MouseTweaks-forge-mc1.19-2.23.jar
MutantMonsters-v4.0.0-1.19.2-Forge.jar
mutantmore-1.19.2-early-access-1.0.7.jar
mutil-1.19.2-5.1.0.jar
naturalist-forge-3.0.2-1.19.2.jar
neapolitan-1.19.2-4.0.2.jar
netherdepthsupgrade-2.0.3-1.19.2.jar
NethersDelight-1.19-3.0.jar
NoChatReports-FORGE-1.19.2-v1.4.0.jar
Nullscape_1.19.3_v1.2.1.jar
occultism-1.19.2-1.73.0.jar
oceansdelight-1.0.1-1.19.2.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar
OnlyLooking-1.19.2-4.1.1.jar
origins-accessbilities-1.19.2-1.1.1.jar
origins-forge-1.19.2-1.7.1.0-all.jar
out_of_sight-1.19.2-1.0.2.jar
Patchouli-1.19.2-77.jar
paucal-forge-1.19.2-0.5.0.jar
peculiars-4.0.1.jar
Pehkui-3.7.0+1.19.2-forge.jar
personality-1.19-3.0.1.jar
pet_cemetery-1.19.2-1.0.3.jar
PineappleDelight-Forge-1.19.2-1.0.6.jar
Placebo-1.19.2-7.1.7 (1).jar
player-animation-lib-forge-1.0.2.jar
pneumaticcraft-repressurized-1.19.2-4.3.1-20.jar
polymorph-forge-0.46.1+1.19.2.jar
PresenceFootsteps-1.19.2-1.6.4.1-forge.jar
projectvibrantjourneys-1.19.2-5.1.0.jar
PuzzlesLib-v4.4.0-1.19.2-Forge.jar
pyrotastic-1.19.2+2.0.3.jar
Quark-3.4-397.jar
QuarkOddities-1.18.jar
Reaper-1.0.4.jar
RegionsUnexploredForge-0.4.0+1.19.2.jar
relics-1.19.2-0.4.5.3.jar
reliquary-1.19.2-2.0.20.1166.jar
repurposed_structures_forge-6.3.9+1.19.2 (1).jar
resourcefulconfig-forge-1.19.2-1.0.20.jar
resourcefullib-forge-1.19.2-1.1.23.jar
respiteful-1.19.2-1.1.0-patch.1.jar
respiteful-1.19.2-1.1.0.jar
rhino-forge-1902.2.2-build.264.jar
RingsOfAscension-1.19-1.0.1.jar
rsgauges-1.19.2-forge-1.2.18.jar
saturn-mc1.19.2-0.0.1.jar
savage_and_ravage-1.19.2-5.0.4.jar
sculpt-1.19.2-forge-v3.jar
simplehats-forge-1.19.2-0.1.6.jar
sliceanddice-forge-2.1.0-forge.jar
SmartBrainLib-forge-1.19.2-1.8.jar
smoothboot(reloaded)-mc1.19.2-0.0.2.jar
sophisticatedbackpacks-1.19.2-3.18.40.779.jar
sophisticatedcore-1.19.2-0.5.38.203.jar
sophisticatedstorage-1.19.2-0.6.16.276.jar
soulfired-1.19.2-3.0.0.0-forge.jar
soundphysics-forge-1.19.2-1.0.18.jar
spelunkery-1.19.2-0.2.0-forge.jar
spiderstpo-1.19.2-2.0.4.jar
spirit-forge-1.19.2-2.2.4.jar
starlight-1.1.1+forge.cf5b10b.jar
Steam_Rails-1.2.6+forge-mc1.19.2.jar
Stoneworks-v4.0.1-1.19.2-Forge.jar
Structory_1.19.3_v1.3.1.jar
structure_gel-1.19.2-2.7.1.jar
supermartijn642configlib-1.1.6b-forge-mc1.19.jar
supermartijn642corelib-1.1.2-forge-mc1.19.jar
supplementaries-1.19.2-2.3.7.jar
swingthroughgrass-1.19.2-1.10.0.jar
tarotcards-1.19.2-1.2-release.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
Terralith_1.19.3_v2.3.7b.jar
tetra-1.19.2-5.2.1.jar
tetranomicon-1.4.2-1.19.2.jar
tetrasdelight-1.19.2-1.jar
tetratic-combat-1.19-2.6.jar
tetrawear-1.19.2-0.0.0-pre.7.jar
TextruesRubidiumOptions-1.0.4-mc1.19.2.jar
toolbooster-1.0-1.19.2.jar
TradingPost-v4.2.0-1.19.2-Forge.jar
trolldom-1.19.2-1.1.0.jar
twilightforest-1.19.2-4.2.1518-universal.jar
UniversalEnchants-v4.2.14-1.19.2-Forge.jar
upgrade_aquatic-1.19.2-5.0.0.jar
VanillaTweaks-forge-1.19.2-1.5.63.jar
vinery-1.19.2-1.1.8.jar
vitalize-forge-1.19.2-1.1.1.jar
voidtotem-forge-1.19.2-2.1.0.jar
VTweaks-1.19.2-4.0.6.jar
WarriorRage-1.19.2-1.2.2.jar
whatareyouvotingfor2022-1.19.2-1.8.jar
woodworks-1.19.2-2.2.1.jar
WWOO-FORGE-3.1.9+1.19.x.jar
xercapaint-1.19.2-1.0.1.jar
yeetusexperimentus-1.0.1-build.2+mc1.19.1.jar
YungsApi-1.19.2-Forge-3.8.8.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.1.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar
</details>

**Comment by iron431** [comment]
I've Uploaded the hotfix to curseforge, it may take a minute to actually appear. Please let me know if this fixes your issue and that there are no other conflicts with the mods you're using. @turbomulot
