### ISSUE TITLE
[Bug] [Better Combat] Left-Handed Players Hold The Decrepit Flamberge By The Edge

### ISSUE THREAD

**Issue by Archidrakona** [iron431/Irons-Spells-n-Spellbooks#150]
### Observed behaviour

When Better Combat is installed, The Decrepit flamberge is reversed when holding in main hand when your player's main hand is set as Left.

![2023-09-05_00 19 35](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/144069567/1cf0e1eb-b83a-47d1-b002-d78602df3679)
![2023-09-05_00 19 18](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/144069567/70eb9739-8a91-4c7d-9df8-5a9c34c61e89)

### Expected behaviour

I would expect the left handed player to not attempt half-swording (holding a sword by the cutting edge) with the Decrepit flamberge when Better Combat is installed.

### Steps to reproduce

1. Have Better Combat and Iron's spells 'n spellbooks installed;
2. Create a world and find a decrepit flamberge;
3. Be left-handed;
4. Enjoy beating everyone to death with the sword's pommel !

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-1.2.1

### Forge version

47.1.46

### Other mods

Better Combat 1.7.3+1.20.1
and a lot of other mods, all at their latest version as of this date (exept for carry on) you'll have to refer to the screens and, if you want, i can try again with only the two (three) specific mods required for this bug to occur cuz testing with all this would be just hell for y'all.

![Capture d’écran 2023-09-05 003252](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/144069567/883685cf-9540-48d4-a450-ebc108797198)
![Capture d’écran 2023-09-05 003145](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/144069567/6748d599-48c2-4ef4-ac0b-5780057c52f5)
![Capture d’écran 2023-09-05 003210](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/144069567/5644d8bc-d395-4be1-9afb-13f55e856d39)
![Capture d’écran 2023-09-05 003235](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/144069567/fbe7a50c-a373-415e-b836-edabb7c2e40e)

**Comment by iron431** [comment]
yeah i made it so that holding it in your left hand makes you half sword it for aesthetics, i did not consider it would always be like that on left handed mode

**Comment by Archidrakona** [comment]
That explains it, there might be a way to make it work while left handed too but i have no experience in coding so i can't suggest anything. Hope you'll find a way to keep your half swording reference !
