### ISSUE TITLE
[Bug]Armour texture not showing

### ISSUE THREAD

**Issue by TheJewSchniffe** [iron431/Irons-Spells-n-Spellbooks#151]
### Observed behaviour

when i wear armour specific to spells n spellbooks, it just shows a pink and black texture, its happened ever since ive been playing in my world
![Screenshot 2023-09-05 203150](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/144119624/5c5f62d6-cb45-4e5a-a01d-4e05e4818acf)

### Expected behaviour

my armour shows what its supposed to look like

### Steps to reproduce

1.start world
2.play like normal until i get wandering magician robe
3.craft and put it on
4.test all other armours(doesnt work)

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.2.1.jar

### Forge version

47.1.0

### Other mods

just downloaded a modpack a youtuber was using, who seemed to have no problem in the video

**Comment by Sketano** [comment]
it's probably optifine if you're using it

**Comment by iron431** [comment]
stop using optifine, a vanilla client mod
