### ISSUE TITLE
Add curios support to upgrade orbs

### ISSUE THREAD

**Issue by CallyKoh** [iron431/Irons-Spells-n-Spellbooks#154]
### Feature description

Allowing the player to add upgrades to certain curios (off by default, but easily changable with a datapack) would give them more options to vary their playstyle and customize their upgrades.

### How it improves the player experience

It would give the player more to do as they would have a long route to max out all of their items, as well as giving modpacks more control over max mana/damage output.

**Comment by iron431** [comment]
added in 3.0.0
