### ISSUE TITLE
How can I use Commandblock for take Scroll's?

### ISSUE THREAD

**Issue by Yuuzinhozi** [iron431/Irons-Spells-n-Spellbooks#157]
### Feature description

Hey! One question, how I can use the commandblock for generate scrolls? I was trying found the scrolls in the list, but i didn't found, only the simple Scroll, so I guess, need to use the same system of a potion.. but, more different?..

/give @p irons_spellbooks:scroll{scroll:Summon_vex}

how can I do for really works? i was thinking about create a button that takes some scrolls for specific classes.
(I'm using the 1.19.2 version)

### How it improves the player experience

I think the game already is amazing, but some tips of commands would be good, this is my only one problem.

**Comment by iron431** [comment]
use `/data get entity @s SelectedItem` to look at the nbt structure

**Comment by Yuuzinhozi** [comment]
Really thank u, i didn't know that option! so.. ''/give @p irons_spellbooks:scroll{ISB_spell:{type:9,level:2}}'' should work, ty!
