### ISSUE TITLE
[Bug] Scrolls/Spell Book canceling long casting spells in Multiplayer

### ISSUE THREAD

**Issue by Yuuzinhozi** [iron431/Irons-Spells-n-Spellbooks#158]
### Observed behaviour

Appear don't happen in SinglePlayer, only in Multiplayer.

 Skills that require a long time to cast, like:

- Fireball
- Summon Vex
- Raise Dead
- [...]

Or continuous abilities like:

- Electrocute
- Fire breath
- Starfall
- [...]

Are getting canceled at the beginning of the casting. For example, I click to start using them, and it cancels and goes on cooldown/spends mana. (Or if it's a Scroll, it only cancels in the first few seconds).

I don't think it's bad latency because it's a paid host, and it happens to almost all players.. but just for remember, is it not always, like, every 10 attempts, 5 works.. 

The best way I found to work 100%, is in the key blinds, changing some Quick cast Slot, for some LETTER, if use Button 5/4 will not work for some reason.. 

### Expected behaviour

Still casting/Conjuring

### Steps to reproduce

- Take the scroll or Book Scroll with long casting or continuos
- Right Button
- Will automatic cancel before end the casting

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.19.2-1.2.1

### Forge version

forge-1.19.2-43.2.14

### Other mods

naturalist-forge-3.0.4-1.19.2
VisualWorkbench-v4.2.4-1.19.2-Forge
weaponmaster-multiplayer-forge-1.19.2-3.0.5
The_Graveyard_2.5.3_(FORGE)_for_1.19.2.
Weeping-Angels-43.0.9-forge
spiderstpo-1.19.2-2.0.4
Prism-1.19.1-1.0.2
Iceberg-1.19.2-forge-1.1.4
Droplight-1.19.2-forge-1.0.6
obscure_api-9-1.19
obscure_tooltips-1.0.api9-1.19
coroutil-1.19.2-1.2.37
zombieawareness-1.19.2-1.12.3
mobsunscreen-forge-1.19.2-3.0.9
soundphysics-forge-1.19.2-1.2.1
CreativeCore_FORGE_v2.9.4_mc1.19.2
EnhancedVisuals_FORGE_v1.5.9_mc1.19.2
bloodandgore1.19.2v1.1(beta)
humancompanions-1.19.2-1.7.4
Horror_elements_mod_1.19.2_1.5
cluttered-2.1.1-1.19.2
twm-1.19.2-1.11.4
PuzzlesLib-v4.4.3-1.19.2-Forge
EasyMagic-v4.3.3-1.19.2-Forge
swingthroughgrass-1.19.2-1.10.0
Ryan's+Zombies+v5
irons_spellbooks-1.19.2-1.2.1
caelus-forge-1.19.2-3.0.0.6
jei-1.19.2-forge-11.6.0.1018
dungeons-and-taverns-2.0.2+forge
tlc_forge-1.0.2-R-1.19.2
[1.19.2]-Medieval-Siege-Machines-v1.10
OptiFine_1.19.2_HD_U_I2
immersive_armors-1.5.6+1.19.2-forge
spore_1.19.2_1.9.9b
crittersandcompanions-1.19.2-2.0.3
architectury-6.5.85-forge
bettercombat-forge-1.7.1+1.19
cloth-config-8.3.103-forge
configured-2.1.1-1.19.2
curios-forge-1.19.2-5.1.4.1
FarmersDelight-1.19.2-1.2.3
geckolib-forge-1.19-3.1.40
journeymap-1.19.2-5.9.7-forge
Natural+Decoration+1.1.0
player-animation-lib-forge-1.0.2
simplyswords-forge-1.47.0-1.19.2
Strawgolem-forge-1.19.2-2.0.0-beta.5
walljump

**Comment by iron431** [comment]
Does this happen in the latest version? (2.0.0)

**Comment by iron431** [comment]
this should be fixed in v2.0.0
