### ISSUE TITLE
[Bug] 1.19.2 server bricked due to chunk gen and or chunk cache and or Async chunk gen idrk

### ISSUE THREAD

**Issue by Luviam** [iron431/Irons-Spells-n-Spellbooks#159]
### Observed behaviour

Generating something from this mod will brick your server at somepoint, I'm not sure what it was besides it being this mod and chunk generation and or chunk caching related. I Used Chunky to pre-generate chunks to automate the process of reproducing the crash on my server (No Chunky is not the issue, this issue was ran into without Chunky, it was simply installed for reproducing the crash idly) I'd get to around 200k chunks pre-generated before any sort of crash occurred. After removing Iron's Spells 'n Spellbooks, I never ran into the crash and was able to pre-generate 600k+ chunks without a hitch. And no this wasn't a one time thing, I had pre-generated chunks on roughly 6 worlds and never got past 300k chunks until right after I removed this mod.

Also here's a notepad relating to my modlist and the mods I personally excluded from being the issue over 16+ hours of testing.
[Mod Conforimr Yes.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/12643748/Mod.Conforimr.Yes.txt)

### Expected behaviour

I Expected my server to not brick itself, that's about it.

### Steps to reproduce

Step 1: Generate Chunks on a dedicated server (Preferably with Chunky as it'll easily take over 100k+ chunks generated before you run into any crashes, yes it is time consuming I personally experienced it lmfao) (Another NOTE: Add Fullstack Watchdog as a mod if you can, might help with debugging. I personally didn't have it at the time)

Step 2: java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
...Suspected Mods: Minecraft (minecraft)

### Server Type

Dedicated Forge server

### Crashlog

https://gist.github.com/Luviam/b221073557fc9247b4ffbc8b982c050b

### Iron's Spells N Spellbooks version

1.19.2-1.2.1

### Forge version

43.2.21 and 43.2.23

### Other mods

I Mean, the log tells you this lmao.

**Comment by lab3** [comment]
I'm starting to look into this issue.  By any chance were you able to replicate this with only ISS installed or was it only in combination with other mods?

**Comment by iron431** [comment]
@Luviam Does this happen with supplementaries removed? Also, could you provide a link for this modpack so we can do some debugging on our end?

**Comment by lab3** [comment]
I did some testing. I used ISS and supplementaries (we have seen this conflict in the past).
I was able to get a server crash after about 5 hours of chunk gen but it doesn't point the finger at anything at this point.

The root of the issue was: **"Accessing LegacyRandomSource from multiple threads"**

https://gist.github.com/lab3/255263b85064a4361aa1378773c93afd
