### ISSUE TITLE
Quark and runes

### ISSUE THREAD

**Issue by GigaEgo** [iron431/Irons-Spells-n-Spellbooks#160]
### Observed behaviour

Quark blank runes replace spellbooks's blank runestones within structures generated by spellbooks's

### Expected behaviour

That the correct runestones spawn within the structures 

### Steps to reproduce

Have quark installed 

### Server Type

Single Player

### Iron's Spells N Spellbooks version

Latest

### Forge version

1.19.2

### Other mods

Quark

**Comment by iron431** [comment]
This does not seem to be true. Make sure you're actually in our structures and that you are talking about the correct rune
<img width="363" alt="image" src="https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/34083081/61654c07-eb58-4aa6-84ef-ced40dd1ac5e">

**Comment by GigaEgo** [comment]
Huh. Well me and the lada kept finding the quark ones, how rare are blank runestones on a scale from 1 to 10 if you don't mind me asking?

**Comment by iron431** [comment]
the rarity changes based on where you're looking. treasure chests like the one in the screenshot have them very frequently

**Comment by GigaEgo** [comment]
my mates forgot to tell me that they COULD find spellbook runes just very rarely, like 2 in the whole catacombs dungeon. is that normal or should there be more?

**Comment by iron431** [comment]
it depends on how close you're looking. finding secrets is where you'll find the treasure chests. however, luck is a factor in generating rooms that might have more or less secrets

**Comment by GigaEgo** [comment]
How long should it approximately take a player to craft a full set of armor with these slabs? A few hours or days? Because I made it so quark blank runes can be converted to spellbook blank runes and I'm worried I mightve messed up the balance
