### ISSUE TITLE
Add a mana regen attribute

### ISSUE THREAD

**Issue by Silvertide7** [iron431/Irons-Spells-n-Spellbooks#161]
### Feature description

Add an attribute that changes the mana regeneration rate of a player.

### How it improves the player experience

As a modpack maker this would open a lot of doors for customization and configuration. I can slow down the rate of regeneration for players in general requiring them to use the spells more situationally instead of just spamming them. 

For players who don't specialize in magic they would have to be more careful and use these spells more like special abilities. For players who take half or full caster classes (my modpack is designed similar to DND) I can then safely increase mana regen and max mana depending on the class to open up more / higher level spells and allow them to cast spells more often. It would also allow me to create items with that attribute on it.

It just adds more levers for a modpack maker to tweak to make the perfect magic system.

**Comment by Luviam** [comment]
Surprised this isn't in the mod. This is like a basic feature of any mana system.
