### ISSUE TITLE
Config for starting mana (and possibly base mana regen)

### ISSUE THREAD

**Issue by Silvertide7** [iron431/Irons-Spells-n-Spellbooks#162]
### Feature description

A config option that sets the players starting mana instead of the default 100. It would also be awesome to set the mana regen rate (this would link to my other feature for mana regen attribute).

### How it improves the player experience

This would allow server owners / modpack makers more control over balancing the games skills and abilities and the cadence of how often they can be used. They can make minor adjustments as they see fit to balance the overall potential to cast spells along with the cost and cooldowns of each spell themselves, giving them complete control over the flow of the game.

**Comment by iron431** [comment]
if you're building a modpack, there are already mods that allow you to edit starting attributes, so this will not be worked on
