### ISSUE TITLE
[Bug] First Person mod causes two arms when using spells

### ISSUE THREAD

**Issue by Puffle2K** [iron431/Irons-Spells-n-Spellbooks#163]
### Observed behaviour

When using a spell, the arm is rendered in a way that First-person Model doesn't seem to recognize. This causes both the first and third person version of the arm to render, showing two arms and books.

### Expected behaviour

Only one arm is shown when casting spells.

### Steps to reproduce

1. Install https://www.curseforge.com/minecraft/mc-mods/first-person-model
2. Use a spell that has a cast time/animation (tested with poison arrow 1 and Flimsy Journal)

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-1.2.1

### Forge version

1.20.1 - 47.1.3

### Other mods

I am using a decently sized modpack, however the only mods that I believe to be related to this issue are:
FirstPersonModel Mod - 2.2.3-mc1.20
NotEnoughAnimations Mod - 1.6.4
Possible Issue (unsure if it matters, but I'll add it here anyway):
Better Combat - 1.7.3+1.20.1

**Comment by iron431** [comment]
this would be an issue with playeranimator, a library we use, not us. report it to them https://github.com/KosmX/minecraftPlayerAnimator/issues
