### ISSUE TITLE
[Celestisynth weapons incompatible with iron's spells 'n spellbooks scrolls] 

### ISSUE THREAD

**Issue by KiraKayn** [iron431/Irons-Spells-n-Spellbooks#164]
### Observed behaviour

Whenever I put a celestisynth weapon into an arcane anvil and put a scroll on it (any scroll) the weapon can only use the scrolls abiltity, the weapon's ability becomes completely unusable.

### Expected behaviour

I thought I could use both the abilites, not only the scrolls ability, so this is definetly a bug

### Steps to reproduce

1. get yourself a celestisynth weapon (any)
2. place down an arcane anvil 
3. obtain a scroll and put it on the weapon through the arcane anvil

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-2.0.0.

### Forge version

1.19.2 43.2.23

### Other mods

mod: celestisynth
version: 1.19.2 
forge version: 43.2.23
mod version: 1.19.2-1.1.3

**Comment by iron431** [comment]
Currently this is the intended behavior. For as long as spells are cast with the interact key, the underlying interaction must be disabled.
