### ISSUE TITLE
[Bug] optifine breaks armor

### ISSUE THREAD

**Issue by Junsack** [iron431/Irons-Spells-n-Spellbooks#166]
### Observed behaviour

I started my Minecraft world with the mod and when it came to putting on the clothes that the mod included, it turned out that it didn't let me see the textures of these clothes.

### Expected behaviour

I hope you can help me with a solution for this problem and to be able to see the textures of this mod since they are an important and beautiful piece to fully immerse yourself in the magic of the mod.

### Steps to reproduce

1. I start minecraft with the mod
2. I open my world
3. The entire mod works except the textures of the clothing

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-1.2.1

### Forge version

1.20.1-47.0.46

### Other mods

alexsmobs, betterarchelogy, caelus, citadel, curios, geckolib, jade, jei, multiverse, phantasmic, player animator, optifine, tombstone, u team core, useful backpacks, wandering bags, xaeros minimap, xaeros worldmap

**Comment by iron431** [comment]
Stop using optifine. Optifine is meant for vanilla clients. Use the many alternatives (such as Oculus) that work with forge

**Comment by Junsack** [comment]
Thanks, it worked

**Comment by Junsack** [comment]
Bro a question, does Oculus also include dynamic lights or is there something else that includes dynamic lights?
