### ISSUE TITLE
[Bug] Broken Zombie Model on Raise Dead with Resource pack

### ISSUE THREAD

**Issue by NotAPotter** [iron431/Irons-Spells-n-Spellbooks#167]
### Observed behaviour

When using the spell Raise Dead, zombies become disconnected shapes with zombie textures.

### Expected behaviour

Risen Zombies to retain model functionality, even without being affected by resourcepack.

### Steps to reproduce

Install EMF and ETF
Install Fresh Animations
Install Iron's Spells
Install Spryzeen Zombie Variants and embedded Fresh Ani. Addon.
In-game, use any level of Raise Dead

### Server Type

Single Player

### Iron's Spells N Spellbooks version

v1.20.1-2.0.0

### Forge version

47.1.47

**Comment by Quartofel** [comment]
Same issue, but with skeletons. Using Fresh Animations, BVB Mobs and BVB Mobs/Fresh Animation compat resource packs. Also, glitched model only affects the summoned skeletons, naturally spawning skellies work without a hitch.
