### ISSUE TITLE
[Bug] Epic Fight crash

### ISSUE THREAD

**Issue by Ecderebi** [iron431/Irons-Spells-n-Spellbooks#168]
### Observed behaviour

Well, fighting any of the hostile mobs cause a crash mid fight. Probably because of the combat changes. Only crashes while fighting. Cyromancer casts the spells and here we go game crashes.

Edit: Now Im not sure what exactly causes the crash. Does anyone understand?

Here is what it gives me:

The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot assign field "f_19802_" because "trueEntity" is null

### Expected behaviour

Well I expect it not to crash of course.

### Steps to reproduce

1 - Find a Cryomancer

2 - Fight it. The game will crash mid fight.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.3

### Forge version

1.18.2-40.2.10

### Other mods

mowziesmobs-1.5.32.jar
player-animation-lib-forge-1.0.2+1.18.jar
[1.18.2][Forge]+RPG-HUD-3.9.2.jar
caelus-forge-1.18.1-3.0.0.2.jar
reap-1.18.2-1.0.0.jar
nyfsquiver-1.18.2-0.7.3.jar
waystones-forge-1.18.2-10.2.1.jar
Clumps-forge-1.18.2-8.0.0+17.jar
integrated_api_forge-1.2.7+1.18.2.jar 
citadel-1.11.3-1.18.2.jar
alexsmobs-1.18.6.jar 
soul+like+armors+reworked+1.18.2+-+11.0.jar
feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
rpglevels-0.1.4.jar
forgivingvoid-forge-1.18.1-6.0.1.jar
balm-3.2.6.jar
walljump-forge-1.18.1-1.3.7.jar 
cloth-config-6.5.102-forge.jar
EpicfightPirates-1.2.jar
idas_forge-1.6.6+1.18.2.jar
selene-1.18.2-1.17.14.jar
supplementaries-1.18.2-1.5.18.jar
DualGreatsword-1.8.jar
another_furniture-forge-1.2.2-1.18.2.jar
yamatomoveset-18.0.6.jar
EpicFight-18.3.7.jar
CreativeCore_FORGE_v2.6.17_mc1.18.2.jar
weaponmaster-multi-forge-1.18.1-3.0.3.jar
RoughlyEnoughItems-8.3.656.jar
Apwna+-+1.1.2+-+1.18.2.jar
HealthDisease-1.18.2-beta-0-0-9.jar
curios-forge-1.18.2-5.0.9.1.jar
flywheel-forge-1.18.2-0.6.10-105.jar
create-1.18.2-0.5.1.e.jar
sedparties-1.18.2-1.0.3.jar
AutoRegLib-1.7-53.jar
Quark-3.2-358.jar
Throwability-1.18.2-2.0.0.0-R.jar
backpacked-forge-1.18.2-2.1.13.jar
architectury-4.11.93-forge.jar
CosmeticArmorReworked-1.18.2-v2a.jar
PlayerRevive_FORGE_v2.0.13_mc1.18.2.jar
geckolib-forge-1.18-3.0.57.jar
responsiveshields-1.1-mc1.18.x.jar
xptome-1.18.2-2.1.7.jar

**Comment by iron431** [comment]
This is a known issue with Epic Fight Mod. This compat mod fixes it: https://www.curseforge.com/minecraft/mc-mods/mod-compat-fixes
