### ISSUE TITLE
[Bug] Server Config Crash

### ISSUE THREAD

**Issue by WenXin20** [iron431/Irons-Spells-n-Spellbooks#17]
### Observed behaviour

The server crashed after loading the game, it seems to be related to server configs, which I have not changed.

### Expected behaviour

No crashes

### Steps to reproduce

1. Load on server
2. Crash

### Crashlog

https://gist.github.com/WenXin20/00a89719aa51abfaf8efabdb0c4682c0

### Iron's Spells N Spellbooks version

1.0.5

### Forge version

1.19.2-43.2.7

**Comment by iron431** [comment]
Can you zip the mods you're playing with an submit them in the Other Mods section of the bug report? This issue does not occur on a clean installation so I need the mods to be able to test it.

**Comment by WenXin20** [comment]
I couldn't replicate it either when I tried again. But here is the mod pack

**Comment by WenXin20** [comment]
Let me know when you've downloaded it so I can remove the link, thanks.

**Comment by iron431** [comment]
Actually just got done testing. I was also unable to reproduce it, but I still went over and refined the config code to hopefully similar issues don't arise in the future.

**Comment by WenXin20** [comment]
ok, thanks!
