### ISSUE TITLE
[Bug] The "Magic Arrow" spell does not work correctly.

### ISSUE THREAD

**Issue by Arogura** [iron431/Irons-Spells-n-Spellbooks#170]
### Observed behaviour

The magic arrow does not pass through blocks.

### Expected behaviour

According to the spell description, the magic arrow must pass through blocks.

### Steps to reproduce

Shoot a Magic Arrow at the mob that is behind the block.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 2.0.0 and 1.20.1 - 1.2.1

### Forge version

47.2.1 and 47.2.0

### Other mods

Doesn't work even if there are no other mods.

**Comment by iron431** [comment]
Can confirm that sometimes the arrow doesn't seem to pass through blocks, although it is inconsistent

**Comment by Arogura** [comment]
> Can confirm that sometimes the arrow doesn't seem to pass through blocks, although it is inconsistent

I played with this spell for a while and I can say that the arrow hits the mob that is behind the blocks once every 20 shots, and not always. It is very rare, as if there is a probability of passing through the walls, and not so that the arrow always passes through the walls.
