### ISSUE TITLE
optifine

### ISSUE THREAD

**Issue by JuandiPro190** [iron431/Irons-Spells-n-Spellbooks#171]
### Observed behaviour

When I craft the magic clothes I can't see the clothes. The texture it's not working.

### Expected behaviour

I expect see the cryomancer hood and all the other clothes good, but it's not working

### Steps to reproduce

1) Craft my clothes.
2) Put the magic clothes on me.
3) Not seeing my clothes because the textures don't work.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

v1.20.1-2.0.0

### Forge version

1.20.1-47.1.47

### Other mods

1.20.1SecurityCraftv1.9.7-beta2
Aquaculture-1.20.1-2.5.0
architectury-9.1.12-forge
artifacts-forge-9.1.0
AttributeFix-Forge-1.20.1-21.0.2
AutoLeveling-1.20-1.18
balm-forge-1.20-7.0.7
caelus-forge-3.1.01.20
cloth-config-12.0.109-forge
curios-forge-5.3.4+1.20.1
elytraslot-quilt-6.3.01.20.1
EnchantingInfuser-v8.0.1-1.20.1-Forge
epicsamurai-0.0.26.1-1.20.1-forge
geckolib-forge-1.20.1-4.2.3
Incendium_1.20.1_v5.3.1
irons_spellbooks-1.20.1-2.0.0
Jade-1.20.1-forge-11.5.1
jei-1.20.1-forge-15.2.0.27
journeymap-1.20.1-5.9.12-forge
MaxHealthFix-Forge-1.20.1-12.0.2
mysticsbiomes-1.20.1-3.1.2
netherportalfix-forge-1.20-13.0.0
OptiFine_1.20.1_HD_U_I6_pre6_MOD
PassiveSkillTree-1.20.1-BETA-0.5.8
Patchouli-1.20.1-81-FORGE
player-animation-lib-forge-1.0.2-rc11.20
PuzzlesLib-v8.0.24-1.20.1-Forge
starlight-1.1.2forge.1cda73c
Stellarity-v2-0e
TerraBlender-forge-1.20.1-3.0.0.169
The_Graveyard_3.0_FORGE_for_1.20.1
tombstone-8.5.3-1.20.1
TravelersBackpack-1.20.1-9.1.4
vanillaplustools-1.20-1.0

**Comment by iron431** [comment]
Stop using optifine. Optifine is meant for vanilla clients. Use the many alternatives (such as Oculus) that work with forge

**Comment by JuandiPro190** [comment]
Thanks, its working now. :D
