### ISSUE TITLE
[1.19.2Bug] Mod loading error has occurred

### ISSUE THREAD

**Issue by OcrSu** [iron431/Irons-Spells-n-Spellbooks#175]
### Observed behaviour

It Was Crashed After Launch the Game

### Expected behaviour

No Crashes

### Steps to reproduce

Launch The Minecraft.
Game Crashes.

### Server Type

Single Player

### Crashlog

https://gist.github.com/OcrSu/dae478966a13d8d58252ac7dd2383dfc

### Iron's Spells N Spellbooks version

irons_spellbooks-1.19.2-2.0.0

### Forge version

1.19.2-43.3.2

### Other mods

		YungsBetterDungeons-1.19.2-Forge-3.2.2.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.2-Forge-3.2.2  |COMMON_SET|Manifest: NOSIGNATURE
		Fastload-Reforged-mc1.19.2-3.4.0.jar              |Fastload-Reforged             |fastload                      |3.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.19.2-Forge-2.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		limitedchunks-1.19.2-3.9.jar                      |Limited Chunkloading          |limitedchunks                 |1.8                 |COMMON_SET|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2.jar              |Player Animator               |playeranimator                |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar       |The Graveyard                 |graveyard                     |2.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		keebszs_battle_towers-0.5.0-1.19.x.jar            |Keebsz's Battle Towers        |keebszs_battle_towers         |0.5.0-1.19          |COMMON_SET|Manifest: NOSIGNATURE
		mmoparties-2.4.4.1.19.2.jar                       |MMOParties                    |mmoparties                    |2.4.3               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.19.2-Forge-2.1.1.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.19.2-Forge-2.1.1  |COMMON_SET|Manifest: NOSIGNATURE
		ghostjump-0.0.1.jar                               |GhostJump                     |ghostjump                     |0.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		eventhorizon-1.0.2.jar                            |EventHorizon                  |eventhorizon                  |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |COMMON_SET|Manifest: NOSIGNATURE
		Incendium_1.19.3_v5.1.6.jar                       |Incendium                     |incendium                     |5.1.6               |COMMON_SET|Manifest: NOSIGNATURE
		gpumemleakfix-1.19.2-1.6.jar                      |Gpu memory leak fix           |gpumemleakfix                 |1.19.2-1.6          |COMMON_SET|Manifest: NOSIGNATURE
		FastSuite-1.19.2-4.1.1.jar                        |Fast Suite                    |fastsuite                     |4.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		Placebo-1.19.2-7.3.3.jar                          |Placebo                       |placebo                       |7.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		papi-1.19.2-1.2.0.jar                             |Papi                          |papi                          |1.19.2-1.2.0        |COMMON_SET|Manifest: NOSIGNATURE
		modernfix-forge-5.7.4+mc1.19.2.jar                |ModernFix                     |modernfix                     |5.7.4+mc1.19.2      |COMMON_SET|Manifest: NOSIGNATURE
		alternate-current-mc1.19-1.7.0.jar                |Alternate Current             |alternate_current             |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		Above_and_Below-1.1.1-1.19.2.jar                  |Above and Below               |above_and_below               |1.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.9.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.9  |COMMON_SET|Manifest: NOSIGNATURE
		does_potato_tick-1.19.2-3.6.2.jar                 |Does Potato Tick              |does_potato_tick              |1.19.2-3.6.2        |COMMON_SET|Manifest: NOSIGNATURE
		Ryoamiclights-0.1.1+1.19.2.jar                    |RyoamicLights                 |lambdynlights                 |0.1.1+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-rc.4.jar                  |MixinExtras                   |mixinextras                   |0.2.0-rc.4          |COMMON_SET|Manifest: NOSIGNATURE
		clientcrafting-1.19.2-1.6.jar                     |clientcrafting mod            |clientcrafting                |1.19.2-1.6          |COMMON_SET|Manifest: NOSIGNATURE
		neruina-1.2.4-forge+1.18.2-1.20.1.jar             |Neruina                       |neruina                       |1.2.4               |COMMON_SET|Manifest: NOSIGNATURE
		MemorySweep-1.19.3-0.8.jar                        |MemorySweep                   |memorysweep                   |1.19.3-0.8          |COMMON_SET|Manifest: NOSIGNATURE
		another_nan_health_fix-1.19.2-0.0.1.jar           |AnotherNaNHealthFix           |another_nan_health_fix        |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		AchievementOptimizer-1.19.2-1.0.2.jar             |AchievementOptimizer          |achiopt                       |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		AnimaticaReforged-1.19.2-0.0.2.jar                |AnimaticaReforged             |animatica                     |1.19.2-0.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		idf-0.1.7-1.19.2.jar                              |Improved Damage Framework     |idf                           |0.1.7-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		arrowcollector-1.18.2-0.0.1.jar                   |ArrowCollector                |arrowcollector                |0.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.2-Forge-2.2.2  |COMMON_SET|Manifest: NOSIGNATURE
		DrinkIt-Forge-1.19.2-1.0.0.jar                    |Drink It!                     |drinkit                       |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		memoryleakfix-forge-1.17+-1.0.0.jar               |Memory Leak Fix               |memoryleakfix                 |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar|YUNG's Better Nether Fortresse|betterfortresses              |1.19.2-Forge-1.0.6  |COMMON_SET|Manifest: NOSIGNATURE
		keepcuriosinventory-1.19.2-0.0.2.jar              |KeepCuriosInventory           |keepcuriosinventory           |1.19.2-0.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-8.3.103-forge.jar                    |Cloth Config v8 API           |cloth_config                  |8.3.103             |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.3.2-universal.jar                 |Forge                         |forge                         |43.3.2              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		toofast-1.19-0.2.2.4.jar                          |Too Fast                      |toofast                       |0.2.2.4             |COMMON_SET|Manifest: NOSIGNATURE
		safefall-0.0.2.jar                                |Safefall                      |safefall                      |0.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		irons_rpg_tweaks-1.19.2-1.1.1.jar                 |Iron's RPG Tweaks             |irons_rpg_tweaks              |1.19.2-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		staaaaaaaaaaaack-forge-1.19.2-1.4-63.jar          |Staaaaaaaaaaaack              |staaaaaaaaaaaack              |1.19.2-1.4-63       |COMMON_SET|Manifest: NOSIGNATURE
		embeddium-0.1.12+mc1.19.2.jar                     |Embeddium                     |embeddium                     |0.1.12+mc1.19.2     |COMMON_SET|Manifest: NOSIGNATURE
		novillagerdm-1.19-4.0.0.jar                       |No Villager Death Messages    |novillagerdm                  |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Log-Begone-Forge-1.19-1.0.6.jar                   |Log Begone                    |logbegone                     |1.0.6               |COMMON_SET|Manifest: NOSIGNATURE
		DungeonsArise-1.19.2-2.1.54-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.54-1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
		tectonic-mod-mc1.19.2-v2.1.1.jar                  |Tectonic                      |tectonic                      |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		EasyLAN-v1.2-[1.19.2].jar                         |EasyLAN                       |easylan                       |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		no_nv_flash-1.19.2-1.5.0.3.jar                    |No Night Vision Flashing      |no_nv_flash                   |1.5.0.3             |COMMON_SET|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		smoothchunk-1.19.2-3.4.jar                        |Smoothchunk mod               |smoothchunk                   |1.19.2-3.4          |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.46-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.46       |COMMON_SET|Manifest: NOSIGNATURE
		Potattributes-1.19.2-0.0.5.jar                    |Potattributes                 |potattributes                 |1.19.2-0.0.4        |COMMON_SET|Manifest: NOSIGNATURE
		mixinsquared-forge-0.0.2.jar                      |MixinSquared                  |mixinsquared                  |0.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		remodifier-1.19.2-2.1.1.jar                       |Remodified                    |modifiers                     |1.19.2-2.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		comparties-0.0.2.jar                              |Comparties                    |comparties                    |0.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		dimtpcmd-1.19.2-0.0.1.jar                         |DimtpCommand                  |dimtpcmd                      |1.19.2-0.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		YungsBridges-1.19.2-Forge-3.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.19.2-Forge-3.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		fastpaintings-1.19-1.1.1.jar                      |Fast Paintings                |fastpaintings                 |1.19-1.1.1          |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
		despawn_tweaker-1.19.2-0.0.4.jar                  |DespawnTweaker                |despawn_tweaker               |1.19.2-0.0.4        |COMMON_SET|Manifest: NOSIGNATURE
		solsweetpotato-1.19.2-2.0.0.jar                   |Spice of Life: Sweet Potato Ed|solsweetpotato                |1.19.2-2.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.2-6.66.jar                        |Collective                    |collective                    |6.66                |COMMON_SET|Manifest: NOSIGNATURE
		bocchium-mc1.19.2-mc1.20.1-v1.0.0.jar             |Bocchium                      |bocchium                      |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		FastWorkbench-1.19.2-7.1.4.jar                    |Fast Workbench                |fastbench                     |7.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		obsidianui-0.1.3+1.19.2.jar                       |ObsidianUI                    |spruceui                      |0.1.3+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		YungsExtras-1.19.2-Forge-3.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.19.2-Forge-3.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		irons_spellbooks-1.19.2-2.0.0.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.19.2-2.0.0        |ERROR     |Manifest: NOSIGNATURE
		redirector-1.19.2-3.4.0-forge.jar                 |Redirector                    |redirector                    |1.19.2-3.4.0        |COMMON_SET|Manifest: NOSIGNATURE
		betterchunkloading-1.19.2-2.2.jar                 |betterchunkloading mod        |betterchunkloading            |1.19.2-2.2          |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.2-Forge-3.2.0  |COMMON_SET|Manifest: NOSIGNATURE
		fruitstack-1.19.2-1.7.3.jar                       |果栈丰萦（Fruit Stack）             |fruitstack                    |1.19.2-1.7.3        |COMMON_SET|Manifest: NOSIGNATURE
		FastFurnace-1.19.2-7.0.0.jar                      |FastFurnace                   |fastfurnace                   |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |COMMON_SET|Manifest: NOSIGNATURE
		RuOK-1.3.0_1.19.2-Forge.jar                       |RuOK Mod                      |ruokmod                       |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		accelerated-decay-forge-1.0.0+mc1.19.2.jar        |Accelerated Decay             |accelerateddecay              |1.0.0+mc1.19.2      |COMMON_SET|Manifest: NOSIGNATURE
		visuality-forge-2.0.2.jar                         |Visuality: Reforged           |visuality                     |2.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		cupboard-1.19.2-2.0.jar                           |Cupboard utilities            |cupboard                      |1.19.2-2.0          |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.19.2-Forge-1.0.jar         |YUNG's Better End Island      |betterendisland               |1.19.2-Forge-1.0    |COMMON_SET|Manifest: NOSIGNATURE
		flamesweeping-1.19.2-1.0.0.jar                    |FlameSweeping                 |flamesweeping                 |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		textrues_embeddium_options-0.1.1+mc1.19.2.jar     |TexTrue's Embeddium Options   |textrues_embeddium_options    |0.1.1+mc1.19.2      |COMMON_SET|Manifest: NOSIGNATURE
		realmrpg_dragon_wyrms_1.0.0_forge_1.19.2.jar      |Realm RPG: Dragon Wyrms       |realmrpg_wyrms                |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar        |Towns and Towers              |t_and_t                       |1.10                |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.0  |COMMON_SET|Manifest: NOSIGNATURE
		chunksending-1.19.2-2.7.jar                       |chunksending mod              |chunksending                  |1.19.2-2.7          |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
		pumpkillagersquest-1.19.2-3.2.jar                 |Pumpkillager's Quest          |pumpkillagersquest            |3.2                 |COMMON_SET|Manifest: NOSIGNATURE
		OpenLoader-Forge-1.19.2-15.0.1.jar                |OpenLoader                    |openloader                    |15.0.1              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Phenomena-2.1.4-1.19.2.jar                        |Phenomena Structures          |phenomena                     |2.1.4-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		caupona-1.19.2-0.2.7.jar                          |Caupona                       |caupona                       |1.19.2-0.2.7        |COMMON_SET|Manifest: NOSIGNATURE
		drinkbeer-refill-1.19.2-1.0.3.jar                 |Drink Beer Refill             |drinkbeer                     |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.19.2-Forge-1.0.1.jar   |YUNG's Better Jungle Temples  |betterjungletemples           |1.19.2-Forge-1.0.1  |COMMON_SET|Manifest: NOSIGNATURE

**Comment by OcrSu** [comment]
I found it incompatible with the Improved Damage Framework Mod idf-0.1.7-1.19.2.jar

**Comment by iron431** [comment]
This is an issue of the addons being out of date for the latest version of the mod

**Comment by OcrSu** [comment]
I removed this irons_rpg_tweaks-1.19.2-1.1.1 Mod  , but the crash still occurred.
[crash-2023-10-02_09.10.45-fml.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/12778738/crash-2023-10-02_09.10.45-fml.txt)

		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.3.2-universal.jar                 |Forge                         |forge                         |43.3.2              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
		idf-0.1.7-1.19.2.jar                              |Improved Damage Framework     |idf                           |0.1.7-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2.jar              |Player Animator               |playeranimator                |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		irons_spellbooks-1.19.2-2.0.0.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.19.2-2.0.0        |ERROR     |Manifest: NOSIGNATURE

**Comment by OcrSu** [comment]
> This is an issue of the addons being out of date for the latest version of the mod


I understand what you said.
The Improved Damage Framework is only compatible with irons_ Spellbooks 1.19.2-1.2.1 QWQ
