### ISSUE TITLE
[Bug] Pyromancer fight causes dedicated server crash.

### ISSUE THREAD

**Issue by MiscrosoftIsStupid** [iron431/Irons-Spells-n-Spellbooks#176]
### Observed behaviour

When a player encounters, and tries to fight a pyromancer the dedicated server crashes.

### Expected behaviour

The pyromancer fight should be able to be completed without issue.

### Steps to reproduce

1. Find pyromancer structure
2. Attack pyromancer, and make it hostile towards player
3. Wait for it to use a scroll attack on the player, causing the crash

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/MiscrosoftIsStupid/aee3d43fa33e202207e268e10f14a682

### Iron's Spells N Spellbooks version

1.20.1-1.1.7

### Forge version

1.20.1-47.1.0

### Other mods

mod_id,mod_name,mod_version,mod_file,mod_url,display_url,issue_tracker_url
alchemylib,AlchemyLib,1.0.24,alchemylib-1.20.1-1.0.24.jar,,,https://github.com/smashingmods/alchemylib/issues
cucumber,Cucumber Library,7.0.0,Cucumber-1.20.1-7.0.0.jar,,https://blakesmods.com/cucumber,
trajanscore,Trajan's Core,1,trajanscore-1.51-1.20.1.jar,,,
geckolib,GeckoLib 4,4.2.1,geckolib-forge-1.20.1-4.2.1.jar,,http://geckolib.com/,https://github.com/bernie-g/geckolib/issues
playeranimator,Player Animator,1.0.2-rc1+1.20,player-animation-lib-forge-1.0.2-rc1+1.20.jar,,,
treeharvester,Tree Harvester,8.2,treeharvester-1.20.1-8.2.jar,,https://curseforge.com/minecraft/mc-mods/tree-harvester,https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Tree%20Harvester
travelanchors,Travel Anchors,1.20.1-5.0.0,TravelAnchors-1.20.1-5.0.0.jar,,https://www.curseforge.com/minecraft/mc-mods/travel-anchors,
caelus,Caelus API,3.1.0+1.20,caelus-forge-3.1.0+1.20.jar,,https://github.com/TheIllusiveC4/Caelus,https://github.com/TheIllusiveC4/Caelus/issues
immersive_aircraft,Immersive Aircraft,0.5.1+1.20.1,immersive_aircraft-0.5.1+1.20.1-forge.jar,,https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft,https://github.com/Luke100000/ImmersiveAircraft/issues
ironjetpacks,Iron Jetpacks,7.0.0,IronJetpacks-1.20.1-7.0.0.jar,,https://blakesmods.com/iron-jetpacks,
diolib,DiaboloLib,6.7.33,diabololib-6.7.33.jar,,https://github.com/Janoeo/DiaboloLib,https://github.com/Janoeo/DiaboloLib/issues
clumps,Clumps,12.0.0.3,Clumps-forge-1.20.1-12.0.0.3.jar,,https://www.curseforge.com/minecraft/mc-mods/clumps,https://github.com/jaredlll08/Clumps/issues
xaeroworldmap,Xaero's World Map,1.30.6,XaerosWorldMap_1.30.6_Forge_1.20.jar,,,https://minecraft.curseforge.com/projects/xaeros-world-map/issues
citadel,Citadel,2.4.2,citadel-2.4.2-1.20.1.jar,,https://github.com/Alex-the-666/Citadel,https://github.com/Alex-the-666/Citadel/issues
alexsmobs,Alex's Mobs,1.22.5,alexsmobs-1.22.5.jar,,https://www.curseforge.com/minecraft/mc-mods/alexs-mobs,https://github.com/Alex-the-666/AlexsMobs/issues
travelersbackpack,Traveler's Backpack,9.1.4,TravelersBackpack-1.20.1-9.1.4.jar,,https://www.curseforge.com/minecraft/mc-mods/travelers-backpack,
naturescompass,Nature's Compass,1.0.0,NaturesCompass-1.20.1-1.11.1-forge.jar,,https://github.com/MattCzyr/NaturesCompass,https://github.com/MattCzyr/NaturesCompass/issues
storagenetwork,Simple Storage Network,1.9.0,SimpleStorageNetwork-1.20-1.9.0.jar,,https://minecraft.curseforge.com/projects/simple-storage-network,https://github.com/Lothrazar/Storage-Network/issues
sereneseasons,Serene Seasons,9.0.0.43,SereneSeasons-1.20.1-9.0.0.43.jar,,,https://github.com/Glitchfiend/SereneSeasons/issues
badpackets,Bad Packets,0.4.2,badpackets-forge-0.4.2.jar,,,https://github.com/badasintended/badpackets/issues
libx,LibX,1.20.1-5.0.5,LibX-1.20.1-5.0.5.jar,,https://www.curseforge.com/minecraft/mc-mods/libx,https://github.com/ModdingX/LibX/issues
mixinextras,MixinExtras,0.2.0-beta.8,mixinextras-forge-0.2.0-beta.8.jar,,https://github.com/LlamaLad7/MixinExtras,
janoeo_foundation,Janoeo Foundation,9.13.4.96,janoeo-foundation-9.13.4.96.jar,,https://www.curseforge.com/minecraft/mc-mods/janoeo,https://github.com/Janoeo/Foundation/issues
cloth_config,Cloth Config v10 API,11.1.106,cloth-config-11.1.106-forge.jar,,,https://github.com/architectury/ClothConfig/issues/
skinlayers3d,3dSkinLayers,1.5.4,3dskinlayers-forge-1.5.4-mc1.20.1.jar,,,
forge,Forge,47.1.0,forge-1.20.1-47.1.0-universal.jar,,,http://www.minecraftforge.net/
twilightforest,The Twilight Forest,4.3.1740,twilightforest-1.20.1-4.3.1740-universal.jar,,https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest,https://github.com/TeamTwilight/twilightforest/issues
ultris_mr,Ultris: Boss Expansion,5.6.9b,ultris-v5.6.9b.jar,,https://modrinth.com/datapack/ultris,
friendsandfoes,Friends&Foes,1.9.3,friendsandfoes-forge-mc1.20.1-1.9.3.jar,,,https://github.com/Faboslav/friends-and-foes/issues
corpse,Corpse,1.20.1-1.0.3,corpse-1.20.1-1.0.3.jar,,https://www.curseforge.com/minecraft/mc-mods/corpse,https://github.com/henkelmax/corpse/issues
alchemistry,Alchemistry,2.3.0,alchemistry-1.20.1-2.3.0.jar,,,https://github.com/smashingmods/alchemistry/issues
minecraft,Minecraft,1.20.1,client-1.20.1-20230612.114412-srg.jar,,,
mcwbridges,Macaw's Bridges,2.1.1,mcw-bridges-2.1.1-mc1.20.1forge.jar,,https://www.curseforge.com/minecraft/mc-mods/macaws-bridges,
farmersdelight,Farmer's Delight,1.20.1-1.2.2a,FarmersDelight-1.20.1-1.2.2a.jar,,https://github.com/vectorwing/FarmersDelight,https://github.com/vectorwing/FarmersDelight/issues
terrablender,TerraBlender,3.0.0.167,TerraBlender-forge-1.20.1-3.0.0.167.jar,,,https://github.com/Glitchfiend/TerraBlender/issues
trajanstanks,Trajan's WW2 Tank Mod (Forge) (1.19.4),2.4,trajans-tanks-forge-1.20.1-2.4.jar,,,
biomesoplenty,Biomes O' Plenty,18.0.0.592,BiomesOPlenty-1.20.1-18.0.0.592.jar,,,https://github.com/Glitchfiend/BiomesOPlenty/issues
explorify,Explorify,1.3.0-mc1.20u1.20.1,explorify-v1.3.0-mc1.20u1.20.1.jar,,https://modrinth.com/datapack/explorify,
mcwfences,Macaw's Fences and Walls,1.0.7,mcw-fences-1.0.7-mc1.20.1forge.jar,,https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls,
spectrelib,SpectreLib,0.13.13+1.20.1,spectrelib-forge-0.13.13+1.20.1.jar,,,
supermartijn642corelib,SuperMartijn642's Core Lib,1.1.9,supermartijn642corelib-1.1.9-forge-mc1.20.jar,,https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib,https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/issues
medievalmusic,medievalmusic mod,1.20.1-2.1,zmedievalmusic-1.20.1-2.1.jar,,,
wthit,wthit,8.4.0,wthit-forge-8.4.0.jar,,,https://github.com/badasintended/wthit/issues
waila,waila,8.4.0,wthit-forge-8.4.0.jar,,,https://github.com/badasintended/wthit/issues
portablemobs,Portable Mobs,1.1.2,portablemobs-1.1.2-forge-mc1.20.jar,,https://www.curseforge.com/minecraft/mc-mods/portable-mobs,https://github.com/Dremoline/PortableMobs/issues
car,Ultimate Car Mod,1.20.1-1.0.5,car-1.20.1-1.0.5.jar,,https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod,https://github.com/henkelmax/ultimate-car-mod/issues
kotlinforforge,Kotlin For Forge,4.4.0,kffmod-4.4.0.jar,,,
curios,Curios API,5.2.0-beta.3+1.20.1,curios-forge-5.2.0-beta.3+1.20.1.jar,,https://www.curseforge.com/minecraft/mc-mods/curios,https://github.com/TheIllusiveC4/Curios/issues
xaerominimap,Xaero's Minimap,23.5.0,Xaeros_Minimap_23.5.0_Forge_1.20.jar,,,https://minecraft.curseforge.com/projects/xaeros-minimap/issues
croptopia,Croptopia,2.3.2,Croptopia-1.20.1-FORGE-2.3.2.jar,,,
collective,Collective,6.65,collective-1.20.1-6.65.jar,,https://curseforge.com/minecraft/mc-mods/collective,https://github.com/ricksouth/serilum-mc-mods/labels/Library%3A%20Collective
chemlib,ChemLib,2.0.17,chemlib-1.20.1-2.0.17.jar,,,
experienceobelisk,Experience Obelisk,1.4.5-1.20.1,experienceobelisk-v1.4.5-1.20.1.jar,,,
simplehats,SimpleHats,1.20.1-0.2.1,simplehats-forge-1.20.1-0.2.1.jar,,https://www.curseforge.com/minecraft/mc-mods/simplehats,https://github.com/fonnymunkey/SimpleHats/issues
polymorph,Polymorph,0.49.0+1.20.1,polymorph-forge-0.49.0+1.20.1.jar,,,https://github.com/illusivesoulworks/polymorph/issues
measurements,Measurements,2.0.0,Measurements-forge-1.20.1-2.0.0.jar,,https://www.curseforge.com/minecraft/mc-mods/measurements,https://github.com/Mrbysco/measurements/issues
almostunified,AlmostUnified,1.20.1-0.5.0,almostunified-forge-1.20.1-0.5.0.jar,,,https://github.com/AlmostReliable/almostunified/issues
jei,Just Enough Items,15.2.0.23,jei-1.20.1-forge-15.2.0.23.jar,,https://www.curseforge.com/minecraft/mc-mods/jei,https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
irons_spellbooks,Iron's Spells 'n Spellbooks,1.20.1-1.1.7,irons_spellbooks-1.20.1-1.1.7.jar,,https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks,https://github.com/iron431/Irons-Spells-n-Spellbooks/issues
spells_and_shields,Spells & Shields,1.20.1-2.13.0,spells_and_shields-1.20.1-2.13.0.jar,,https://github.com/CAS-ual-TY/Spells-And-Shields,https://github.com/CAS-ual-TY/Spells-And-Shields/issues
dungeonsweaponry,Dungeons Weaponry,1.13.0-1.20.1,dungeonsweaponry-1.13.0-1.20.1.jar,,,
cfm,MrCrayfish's Furniture Mod,7.0.0-pre36,cfm-forge-1.20.1-7.0.0-pre36.jar,,https://mrcrayfish.com/mods?id=cfm,https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues
architectury,Architectury,9.1.10,architectury-9.1.10-forge.jar,,,https://github.com/shedaniel/architectury/issues
magistuarmory,Epic Knights Mod,8.1,[1.20.1-forge]-Epic-Knights-8.1.jar,,,https://github.com/Magistu/Epic-Knights/issues
aquaculture,Aquaculture 2,2.5.0,Aquaculture-1.20.1-2.5.0.jar,,https://minecraft.curseforge.com/projects/aquaculture,
veinmining,Vein Mining,1.2.0+1.20.1,veinmining-forge-1.2.0+1.20.1.jar,,,https://github.com/illusivesoulworks/veinmining/issues

**Comment by iron431** [comment]
can you reproduce this with the latest version of the mod?

**Comment by iron431** [comment]
> can you reproduce this with the latest version of the mod?

@MiscrosoftIsStupid

**Comment by iron431** [comment]
closed for inactivity.
