### ISSUE TITLE
[Bug] Continuous Casting spells stop mid cast in servers

### ISSUE THREAD

**Issue by Thedarkcube** [iron431/Irons-Spells-n-Spellbooks#182]
### Observed behaviour

When using any spell that is casted continuously, such as firebreath, ice cone or lightning, they cast for half a second and then stop, regardless of continuously holding the mouse key.
Only way to deal with this is via quick bind.

This was a bug for long casting spells, but the click to cancel feature fixed it.

### Expected behaviour

Only real way i see of fixing it is recreating the same behavior of 1 click to cast and 1 to cancel as long spells have.

### Steps to reproduce

1. equip any continuous casting spell
2. try casting it
3. the spell is cast for 1 second max and then stops

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20 - 2.0.1

### Forge version

1.20 - 47.1.46

### Other mods

Better combat
Parcool

**Comment by iron431** [comment]
How is the server being hosted?

**Comment by Thedarkcube** [comment]
It's an aternos server, so a dedicated one.

**Comment by iron431** [comment]
I've seen this issue before on aternos, but ive never been able to replicate it on a server of my own hosting. We don't know what causes this

**Comment by Thedarkcube** [comment]
I think it's ping related, Since whenever i use the spell and hold, it usually stops casting even quicker, leading me to believe it's counting as clicking twice. The only way around this i can do is either use a quick bind, or click and then click again as soon as the spell starts casting, but the second option is a crapshot wich can send the spell to cooldown anyway. As said the only way i can see around this is using the same method the long casting ones use, or add an option to use that method.

**Comment by darthmeme** [comment]
I have the same issue, server hosted on CreeperHost.
