### ISSUE TITLE
Disable RMB for Book/Staff in offhand config option

### ISSUE THREAD

**Issue by akitasiffu** [iron431/Irons-Spells-n-Spellbooks#183]
### Feature description

i might have missed it, but what im asking is for a way to make it so RMB doesnt activate spells in the offhand. Maybe even mainhand. 

### How it improves the player experience

End goal is no more accidental spell misfires. For the who use quickcast hotkeys, disabling or reassigning spellcast/RMB for the book/staff cast can alleviate blasting passive mobs or accidentally burning a spell. Also, some mods like simply swords have items that also use RMB for special item abilities. Some take priority from the books, but others don't

**Comment by diamondmind220108** [comment]
This would improve compatibility with other mods (especially combat-focused mods). It could be an option in the mod config or a keybind in the controls.

**Comment by iron431** [comment]
Yeah it would definitely be a good addition but it's not a simple one. It is hard to dedicate our limited development time to it over other features right now

**Comment by iron431** [comment]
this will not become a config option
