### ISSUE TITLE
[Bug] Wayward Compass Won't change

### ISSUE THREAD

**Issue by alexwilli14** [iron431/Irons-Spells-n-Spellbooks#184]
### Observed behaviour

When I craft a new compass to try and find a new dungeon. The compass still points to the old dungeon and even if I travel a couple thousand blocks away it still doesn't change.

### Expected behaviour

Compass Changes to new dungeon after killing dead king boss

### Steps to reproduce

Clear Dungeon
Kill boss
Make new compass

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

1.20.1 - 47.1.3

**Comment by iron431** [comment]
are you crafting the new one far away from the original catacombs structure?

**Comment by alexwilli14** [comment]
I have not I will try that

**Comment by iron431** [comment]
closing because it sounds like user error
