### ISSUE TITLE
[Bug] Game Crashes with all the required mods downloaded

### ISSUE THREAD

**Issue by JackYevhen** [iron431/Irons-Spells-n-Spellbooks#185]
### Observed behaviour

Just crashes on start.

### Expected behaviour

Normal launch.

### Steps to reproduce

1. Download Mods
2. Put them when they need to be
3. [ NOTE: I use PollyMC for so steps 1, 2 are automated ]
4. Run the game (java 19.0.2)
5. Wait a bit
6. Look at your perfectly unreadable and huge log without any understaffing why game crashed.
7. [ If it was becuse I was using mod version 1.20.1 for MC 1.20.2 then its still a bug because it should have shown other error and not the mess I see ]

### Server Type

Single Player

### Crashlog

https://gist.github.com/JackYevhen/fc48de8ed41423cc50801d5f12978ed1

### Iron's Spells N Spellbooks version

1.20.1-2.0.1

### Forge version

1.20.2-48.0.26

### Other mods

```
bettercreeper-1.20.2 - 1.3.2
caelus-forge-3.1.0+1.20
collective-1.20.2-6.66
curios-forge-6.0.1+1.20.2
geckolib-forge-1.20.2-4.2.3
ironchests-5.0.2-forge
larger-ore-veins-classic-1.0.6
nutritiousmilk-1.20.2-3.1
opolisutilities-1.20.1-2.5.0
OverpoweredMending-1.20.2-2.13.0
player-animation-lib-forge-1.0.2-rc1+1.20
puffish_skills-0.9.0-1.20.2-forge
purpurpacks-iron-to-diamond-armor-upgrades-1.2
purpurpacks-iron-to-diamond-tools-upgrades-1.2
purpurpacks-stone-to-iron-tools-upgrades-1.2
strainers-1.20.1-1.4.9
```

**Comment by iron431** [comment]
~~What forge version are you using~~ nvm i see it, you're using 1.20.2 my guy

**Comment by JackYevhen** [comment]
So, basically you can't run 1.20.1 on 1.20.2? (Asking it separately because in most cases you can do it if major version matches)

**Comment by SiverDX** [comment]
if you can run a mod on a newer version you got lucky but it's not guaranteed 

doesn't matter which one
also not crashing does not mean that the mod is actually working correctly
