### ISSUE TITLE
Shooting spell from hand

### ISSUE THREAD

**Issue by Niconoko** [iron431/Irons-Spells-n-Spellbooks#186]
### Feature description

It's more like a nitpick from me opinion, but it feels kinda weird when seeing spell shooting out from player face.
It would be great if it's actually coming out from player hand.

### How it improves the player experience

So the animations are already there in most spells, just need some adjustment to where the spell coming out as mentioned above. *Maow* :3

**Comment by iron431** [comment]
The spells have to come out of the center of the player, otherwise they would be inaccurate and not actually go where you're looking. If you notice in vanilla, all projectiles come out of the center of the screen, like shooting a bow or throwing a trident. Not something that can really change.
