### ISSUE TITLE
Generate structures in modded biomes through the config.

### ISSUE THREAD

**Issue by iLoveChipotle** [iron431/Irons-Spells-n-Spellbooks#187]
### Feature description

For clients and servers running any mod that adds biomes, ex. Biomes O' Plenty & BYG.
Structures tend to generate thousands of blocks away if any default minecraft:biome is generated.

### How it improves the player experience

By allowing users to input custom biomes in the config to force generation in more than just the default biomes, players are not required to travel 3000 blocks to be able to acquire recipes and resources.

**Comment by iron431** [comment]
This can already be done via datapack and will not become a config feature. Better native support for modded biome gen is planned, but may take some time to get to.
