### ISSUE TITLE
[Crash Issue] 

### ISSUE THREAD

**Issue by Morisillen** [iron431/Irons-Spells-n-Spellbooks#188]
### Observed behaviour

Game crashes when trying to add scroll to spell book at table

### Expected behaviour

Dont crash and add the spell to the book without any issue

### Steps to reproduce

1. Place the book to slot
2. Add scroll
3. Click to the button that adds the scroll to book

### Server Type

Single Player

### Crashlog

https://gist.github.com/Morisillen/e8a214d2861b6126ae4cfd61524e2e23

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.3

### Forge version

1.18.2-40.2.10

### Other mods

Theres no other mod except the required libraries.

**Comment by iron431** [comment]
I've seen this issue before. It's not an issue with the mod, usually it's an issue with the user's setup. What language are you playing the game in?

**Comment by Morisillen** [comment]
> I've seen this issue before. It's not an issue with the mod, usually it's an issue with the user's setup. What language are you playing the game in?

Game is english but my computer is using Turkish, you think thats the problem?
