### ISSUE TITLE
Give summoned creatures the {Owner:} nbt

### ISSUE THREAD

**Issue by alexhowell610** [iron431/Irons-Spells-n-Spellbooks#19]
### Feature description

Make it so all summoned creatures have the {Owner:player} tag. Currently, summoned zombies and vex are attacked by owned mobs from other mods because they aren't considered allies. 

### How it improves the player experience

This allows mobs from other mods and summoned creatures from this one to not kill each other. 

### Iron's Spells N Spellbooks synergies

Allows ISnSB mobs to not be killed by owned mobs from other mods.

**Comment by iron431** [comment]
Summoned mobs do have a tag of the player who summoned them, although it is "Summoner" instead of "Owner". Is there a mod in specific that uses the "Owner" tag to determine allies?

**Comment by alexhowell610** [comment]
The tamed mobs from Alex's Mobs attack the summoned dead and vex but I noticed that a tamed wolf from vanilla will attack them as well.

**Comment by alexhowell610** [comment]
Plus the {Owner:player} tag is what vanilla uses to make something your ally so having it for the summoned creatures would probably be the best way to ensure compatibility across the board.

**Comment by iron431** [comment]
Will be fixed in an upcoming update. As long as alexmobs and other mods use the vanilla framework, it'll be compatible. Otherwise they might need specific solutions
