### ISSUE TITLE
Make attacking spells' damage source recognized as magic damage

### ISSUE THREAD

**Issue by betterworld-sjq** [iron431/Irons-Spells-n-Spellbooks#191]
### Feature description

As title

### How it improves the player experience

I‘ve noticed that the attack of spells can be reduced with armor. But they are spells! Yes, they can still not bypass the protection, but they should bypass armor. If you think this might not balance well, you can add config whether to change the damagetype to magic, or if this sounds like a hard work, just be busy doing your own things. Gratitude in advance!

**Comment by iron431** [comment]
no. magic damage is treated differently, such as ignoring armor as you said. we specifically want to avoid this treatment

**Comment by betterworld-sjq** [comment]
> no. magic damage is treated differently, such as ignoring armor as you said. we specifically want to avoid this treatment

Thank you anyway! Oh, then do you have plans to make config file more comprehensive? For eg, some attacking spells may appear too weak in some modpacks, while some buff-adding spells may be overpowered.

**Comment by iron431** [comment]
there is already config to change the power of each spell individually

**Comment by betterworld-sjq** [comment]
> there is already config to change the power of each spell individually

Oh,sorry,it's in serverconfig,not noticed before.Love U :D. Every mod makers who make their work highly configurable deserve giant appreciation.
