### ISSUE TITLE
[Bug and Compatibility Request] Crash when casting spell after attacking with Epic Fights.

### ISSUE THREAD

**Issue by snoozytrooze** [iron431/Irons-Spells-n-Spellbooks#192]
### Feature description

This is an Epic Fight mod compatibility issue. While in battle mode, casting a "Cone of Cold" spell immediately after attacking will crash the game. Entering the world will continue to result in a crash.

### How it improves the player experience

ISSB and Epic Fight mods are the single best combat mod combination out right now, something akin to Skyrim's combat, everything should be done to make sure these two mods are compatible.

**Comment by iron431** [comment]
This is a known issue with Epic Fight Mod. This compat mod fixes it: https://www.curseforge.com/minecraft/mc-mods/mod-compat-fixes
