### ISSUE TITLE
Config to modify armor values for armor sets

### ISSUE THREAD

**Issue by Silvertide7** [iron431/Irons-Spells-n-Spellbooks#193]
### Feature description

Allow config options to configure the armor values that the armor sets in the game give. Currently the armor sets give way too much armor for how much value they give, and there's no reason not to use another armor set.

### How it improves the player experience

This would help mod pack makers out a lot. Currently the end game armors give the same armor value as netherite gear, plus a bunch of other better stats. There's no reason to use netherite gear at all at this point. It would be really great to be able to customize that and lower the armor so there are trade offs / choices to make for the player.

**Comment by RafaelGuiFernandes** [comment]
I second this . Robes that give as much protection as any other heavy armor is completely unbalanced for any RPG modpack . It should not only have a config option, but the default values should also be significantly reduced .

**Comment by Silvertide7** [comment]
I ended up implementing this myself with CraftTweaker. If you download CraftTweaker and make a file say `scripts/armor.zs`, then put
```
<item:irons_spellbooks:plagued_helmet>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor>, "2ad3f246-fee1-4e67-b886-69fd380bb150", "Armor modifier", 2, AttributeOperation.ADDITION, [<constant:minecraft:equipmentslot:head>]);
```
It will change the armor value of the plaqued helmet to 2. 
Since you are overriding an existing attribute on the armor you will need to use the correct UUID (that one should work I think unless they are randomly generated on load).
To verify, get the plagued helmet in your hand, type `/ct hand attribute` and check the armor entry. It will have a UUID there that you will copy and past in it's spot. 

If you're not familiar with UUID's, its the long crazy string `"2ad3f246-fee1-4e67-b886-69fd380bb150"`

**Comment by iron431** [comment]
will continue tracking this issue in #310

**Comment by killerpackman** [comment]
@Silvertide7 are you sure this works? I just downloaded all the stuff and followed your step-by-step process and it won't change anything. Are there more spets I have to do? Can you do this with kubejs because I know how to use that better but have 0 clue on how to use craftteaker.

**Comment by Silvertide7** [comment]
This works for my 1.20.1 forge modpack with crafttweaker. In 1.21.1 it has changed though. Im not sure on what that looks like yet, I'm still in the middle of updating, haven't gotten this far yet. I dont know of a way to use kubejs to add permanent attribute modifiers. If you find out let me know, id rather use that as well. Zenscript is not my favorite.

**Comment by killerpackman** [comment]
Can you get ahold of me somehow or can you send the code again with a step-by-step thing, because I followed your tutorial, and it didn't work, so I don't know what I'm doing wrong.
