### ISSUE TITLE
Make lingering arrows available through Alchemist Cauldron

### ISSUE THREAD

**Issue by betterworld-sjq** [iron431/Irons-Spells-n-Spellbooks#194]
### Feature description

Since I can fill the cauldron with potions, what about holding arrows and right-clicking at the cauldron to get lingering arrows?

### How it improves the player experience

A pretty pratical way to enhance the cauldron.

**Comment by iron431** [comment]
its a neat idea but we'll likely never get around to adding it, to be completely honest, with the amount time we already need to dedicate to our prioritized features and fixes
