### ISSUE TITLE
[Bug] log spam, with non full spell book

### ISSUE THREAD

**Issue by fayer3** [iron431/Irons-Spells-n-Spellbooks#195]
### Observed behaviour

when opening the spell wheel, and the spell book is not filled from the beginning, an ArrayIndexOutOfBoundsException is thrown, because it tries to select a spell that doesn't exist

https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/ec1a75058f9274019e4c765fd92fc5bcac3aeee1/src/main/java/io/redspace/ironsspellbooks/gui/overlays/SpellWheelOverlay.java#L105

checked on both 1.20.1 and 1.19.2
this is not a major issue, since forge has a fail safe when rendering overlays, but spams the log 

how I filled the spell book 
![grafik](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/8282299/aff0ea82-aeac-45be-adef-efff582b0508)

log:
[latest.log](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/13192819/latest.log)

### Expected behaviour

no log spam

### Steps to reproduce

- fill a spell book , with the first slot free
- open the spell wheel

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-2.0.1, 1.20.1-2.0.1

### Forge version

1.19.2 - 43.2.21

### Other mods

only the required dependencies

**Comment by FoxMcloud5655** [comment]
Can confirm.
```
Error rendering overlay 'irons_spellbooks:spell_wheel'
java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 2
```

**Comment by iron431** [comment]
i dont think this happens anymore
