### ISSUE TITLE
[Bug] Souls like armor

### ISSUE THREAD

**Issue by Moses24713** [iron431/Irons-Spells-n-Spellbooks#197]
### Observed behaviour

crash when Iron's spells n spell books necromancer summons entitys while souls like armor is installed
https://pastebin.com/k7cu1rTN

### Expected behaviour

should just summon them with the armor n all surely

### Steps to reproduce

Iron's spells n spell books necromancer summons entitys while souls like armor is installed, not sure if crash happens 100% of the time yet and maybe it has something to do with version of geckolib I am using I don't know but reporting it here incase anyone else runs into this issue (Geckolib 4 | 4.2.4)

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

47.2.1

### Other mods

souls like armors
+ a uh.. few more..

**Comment by kaairu** [comment]
mcreator issue, report it to soullikearmors

**Comment by iron431** [comment]
^. it has to be fixed on their end
