### ISSUE TITLE
[Bug] Game crashes when necromancer summons 

### ISSUE THREAD

**Issue by Frog1en** [iron431/Irons-Spells-n-Spellbooks#199]
### Observed behaviour

when necromancer summons zombies game crashes, however server still works.

### Expected behaviour

i guess it happens because zombies spawned with modified data

### Steps to reproduce

reentering server emmideately crashes game.

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Frog1en/aea8c58a5df59fc5843789ff5e24e159

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-2.0.2

### Forge version

47.2.1

### Other mods

alex caves, spelunky charm.

**Comment by iron431** [comment]
This is a known issue with Alex's Cave that will be fixed in their next version
