### ISSUE TITLE
Game Crash when hovering over scroll in creative with REI installed

### ISSUE THREAD

**Issue by Trepppy** [iron431/Irons-Spells-n-Spellbooks#20]
### Observed behaviour

when I scroll through the mod's scrolls on the little compass search menu in creative the game crashes

### Expected behaviour

not crash

### Steps to reproduce

- I was on a flat world
- go to the compass tab on the creative menu
- scroll until you reach the scrolls from the mod
- game crashes

### Crashlog

https://gist.github.com/Trepppy/a6cc464c1e6556c8e55200d0fc58e1a8

### Iron's Spells N Spellbooks version

1.0.6

### Forge version

1.19.2 43.2.10

### Other mods

client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		player-animation-lib-forge-1.0.2.jar              |Player Animator               |playeranimator                |1.0.2               |DONE      |Manifest: NOSIGNATURE
		Architects-Palette-1.19.2-1.3.2.jar               |Architect's Palette           |architects_palette            |1.3.1               |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughItems-9.1.595.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |9.1.595             |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.0.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.0      |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a-14.jar              |Flywheel                      |flywheel                      |0.6.8.a-14          |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |DONE      |Manifest: NOSIGNATURE
		createdeco-1.3.2-1.19.2.jar                       |Create Deco                   |createdeco                    |1.3.2-1.19.2        |DONE      |Manifest: NOSIGNATURE
		REIPluginCompatibilities-forge-9.0.48.jar         |REI Plugin Compatibilities    |rei_plugin_compatibilities    |9.0.48              |DONE      |Manifest: NOSIGNATURE
		irons_spellbooks-1.0.6.jar                        |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.0.6               |DONE      |Manifest: NOSIGNATURE
		extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar|Extended Cogwheels            |extendedgears                 |2.0.2-1.19.2-0.5.0.i|DONE      |Manifest: NOSIGNATURE
		create_dragon_lib-1.19.2-1.1.2.jar                |Create: Dragon Lib            |create_dragon_lib             |1.1.2               |DONE      |Manifest: NOSIGNATURE
		architectury-6.5.82-forge.jar                     |Architectury                  |architectury                  |6.5.82              |DONE      |Manifest: NOSIGNATURE
		create_crystal_clear-0.1.2e-1.19.2.jar            |Create: Crystal Clear         |create_crystal_clear          |1.19.2 - 0.1.1e     |DONE      |Manifest: NOSIGNATURE
		blueprint-1.19.2-6.1.2.jar                        |Blueprint                     |blueprint                     |6.1.2               |DONE      |Manifest: NOSIGNATURE
		clayworks-1.19.2-2.0.1.jar                        |Clayworks                     |clayworks                     |2.0.1               |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.6.2+1.19.jar                 |Better Combat                 |bettercombat                  |1.6.2+1.19          |DONE      |Manifest: NOSIGNATURE
		combatroll-forge-1.1.5+1.19.jar                   |Combat Roll                   |combatroll                    |1.1.5+1.19          |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.10-universal.jar                |Forge                         |forge                         |43.2.10             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		valhelsia_core-forge-1.19.2-0.5.0.jar             |Valhelsia Core                |valhelsia_core                |1.19.2-0.5.0        |DONE      |Manifest: NOSIGNATURE
		forbidden_arcanus-1.19.2-2.1.3.jar                |Forbidden & Arcanus           |forbidden_arcanus             |1.19.2-2.1.3        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |DONE      |Manifest: NOSIGNATURE
		create_enchantment_industry-1.19.2-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.2.0               |DONE      |Manifest: NOSIGNATURE
		createaddition-1.19.2-20230426a.jar               |Create Crafts & Additions     |createaddition

**Comment by iron431** [comment]
It seems like this is due to invalid config entries. Working on a fix now.

**Comment by lab3** [comment]
@Trepppy Could you attach the irons_spellbooks-server.toml config file please?

**Comment by Trepppy** [comment]
> @Trepppy Could you attach the irons_spellbooks-server.toml config file please?
do I just copy and paste the stuff on the txt file here?

**Comment by iron431** [comment]
Fixed in v1.0.7

**Comment by lab3** [comment]
@Trepppy the easiest way would be for you to paste it into a gist https://gist.github.com/ and link the gist in a comment here.  I think we fixed it but it looks like a config related issue that we would like to verify.

**Comment by Trepppy** [comment]
https://gist.github.com/Trepppy/a8769137f4153e62388dccdb81e852ad

**Comment by lab3** [comment]
Thanks

**Comment by lab3** [comment]
@Trepppy Would you mind adding your latest.log and debug.log to that gist or a new one?

**Comment by iron431** [comment]
> @Trepppy Would you mind adding your latest.log and debug.log to that gist or a new one?

Looks like we fixed it, no need for another gist.
