### ISSUE TITLE
[Bug] Crash with Chain Lightning ticking or something, i dont know

### ISSUE THREAD

**Issue by Sketano** [iron431/Irons-Spells-n-Spellbooks#200]
### Observed behaviour

I used Chain Lightning on a bunch of creepers, Then the game crashed.

### Expected behaviour

not crash

### Steps to reproduce

1. Summon a bunch of Creepers
2. Use Chain Lightning on Them

### Server Type

Single Player

### Crashlog

https://gist.github.com/Sketano/332f6a5e7b40afdf9b874b90334c7a5b

### Iron's Spells N Spellbooks version

1.20.1-2.0.2

### Forge version

1.20.1-47.2.1

### Other mods

Shown in Crash Report

**Comment by iron431** [comment]
does this happen consistently

**Comment by Sketano** [comment]
> does this happen consistently

yeah i went back in game with a hole filled with creepers, used chain lightning, everything stopped for a second then it crashed

**Comment by lab3** [comment]
Can't seem to reproduce this.

https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/1099358/693494aa-93d2-45e7-a2d0-e61e86a71a5b

**Comment by XCPika** [comment]
[crash-2024-01-11_09.48.59-server.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/13906728/crash-2024-01-11_09.48.59-server.txt)
This exact crash has happened to me too but on a server. Modpack is ATM9.
I was in The Other, in the Dungeon so it was a mix of vex, evokers, vindicators and wither skeletons.
