### ISSUE TITLE
[Bug] Fireward Ring is not synchronized client side when changing dimensions

### ISSUE THREAD

**Issue by SiverDX** [iron431/Irons-Spells-n-Spellbooks#201]
### Observed behaviour

When changing dimensions I cannot see the fire resistance effect on my effect list
And the negative client-side effects of https://www.curseforge.com/minecraft/mc-mods/cold-sweat are present
But I'm not taking damage due to high temperature (which is handled server-side)

So my assumption is that the effect is not re-checked / added on the client-side when changing dimensions
Re-equipping the ring fixes it

### Expected behaviour

N/A

### Steps to reproduce

N/A

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2-2.0.3

### Forge version

1.19.2 - 43.3.0

### Other mods

A lot

**Comment by SiverDX** [comment]
To add to this:
It seems like the duration of the effect can run out without being re-applied
(and this affects client and server side)

**Comment by iron431** [comment]
fixed in 2.1.0
