### ISSUE TITLE
[Bug] Necromancer spell crash

### ISSUE THREAD

**Issue by DecoXFE** [iron431/Irons-Spells-n-Spellbooks#202]
### Observed behaviour

When the necromancer uses one of his spells the game crashes giving this crash report:
Cannot invoke net.minecraft.world.entity.LivingEntity.m_6144_() because "living" is null.
I think the problem is with the RaiseDeadSpell when it tries to spawn Skeletons, but I don't really know, that's just my guess after reviewing the code a little.

Version this happened: 1.20.1

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/64306897/4f849b3a-5131-486b-b112-600b9e61f573)

### Expected behaviour

Not crash lol.

### Steps to reproduce

1. Summon the necromancer.
2. Wait till he starts using some spells.
3. Enjoy the crash.

### Server Type

Dedicated Server

### Crashlog

CrashReport
[crash-2023-11-04_17.40.28-client.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/13257189/crash-2023-11-04_17.40.28-client.txt)

Debug.log
https://gist.github.com/DecoPoxa/20b5a8a683505c73621ee1fcfea14d70

### Iron's Spells N Spellbooks version

1.20.1 - 2.0.3

### Forge version

1.20.1 47.2.1

### Other mods

No more mods

**Comment by lab3** [comment]
@DecoPoxa Please attach the full crashlog and debug log

**Comment by DecoXFE** [comment]
Updated! Sorry about that, first time using this.

**Comment by lab3** [comment]
The issue is in soullikearmorsreworked not ISS.  You can report the issue to them but they are using mcreator to make the mod so they may not be able to to anything about it.  If you remove that mod and summon or find a necromancer it will work fine.

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_6144_()" because "living" is null
	at net.mcreator.soullikearmorsreworked.item.RustysteelItem$Helmet$1.getHumanoidArmorModel(RustysteelItem.java:90) ~[soul_like_armors_reworked_1.20.1_(v54.0).jar%23295!/:?] {re:classloading}
	at software.bernie.geckolib.renderer.layer.ItemArmorGeoLayer.getModelForItem(ItemArmorGeoLayer.java:205) ~[geckolib-forge-1.20.1-4.2.4.jar%23261!/:4.2.4] {re:classloading}
	at software.bernie.geckolib.renderer.layer.ItemArmorGeoLayer.renderForBone(ItemArmorGeoLayer.java:138)
```
