### ISSUE TITLE
[Bug]  Necromancer spell crash

### ISSUE THREAD

**Issue by dynqp** [iron431/Irons-Spells-n-Spellbooks#203]
### Observed behaviour

was playing minecraft and all of a sduden my game crashed

### Expected behaviour

i expected it not to crash

### Steps to reproduce

1. find necromancer
2.  say hello
3. wait for crash

### Server Type

Single Player

### Crashlog

https://gist.github.com/dynqp/30cc2791548676d12cda9845f45de495

### Iron's Spells N Spellbooks version

 irons_spellbooks-1.20.1-2.0.3.jar

### Forge version

1.20.1, forge - 47.2.0

### Other mods

- additionalstructures 4.2.1
	- aether 1.20.1-1.0.0-beta.1.4-neoforge
	- ambientsounds 5.2.24
	- architectury 9.0.8
	- artifacts 9.1.0
	- backpacked 2.2.5
	- bagus_lib 1.20.1-4.0.3
	- balm 7.1.4
	- betteradvancements 0.3.2.161
	- bettercombat 1.8.1+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterfortresses 1.20-Forge-2.0.5
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.3
	- betterstrongholds 1.20-Forge-4.0.3
	- betterwitchhuts 1.20-Forge-3.0.3
	- biomesoplenty 18.0.0.592
	- bookshelf 20.1.6
	- botarium 2.2.0
	- brutalbosses 1.20.1-6.6
	- caelus 3.1.0+1.20
	- cloth_config 11.0.99
	- clumps 12.0.0.3
	- combatroll 1.3.0+1.20.1
	- controlling 12.0.2
	- cosmeticarmorreworked 1.20.1-v1a
	- creativecore 2.11.8
	- creeperoverhaul 3.0.1
	- cristellib 1.1.3
	- ctov 3.3.6
	- cucumber 7.0.4
	- cumulus_menus 1.20.1-1.0.0-beta.1-neoforge
	- cupboard 1.20.1-2.1
	- curios 5.4.2+1.20.1
	- doggytalents 1.17.3
	- dragonmounts 1.1.5.b3
	- dungeoncrawl 2.3.14
	- dungeons_arise 2.1.57-1.20.1
	- dynamiclightsreforged 1.20.1_v1.6.0
	- enchdesc 17.0.8
	- enderitemod 1.5.0
	- endofherobrine 1.20.1-1.0.8.2
	- essential 14565+deploy-staging+g7d1e613e0b
	- expandability 9.0.0
	- explorify 1.3.0-mc1.20
	- farmersdelight 1.20.1-1.2.3
	- ferritecore 6.0.1
	- flib 0.0.11
	- forge 47.2.0
	- framework 0.6.16
	- ftblibrary 2001.1.3
	- ftbquests 2001.1.7
	- ftbteams 2001.1.4
	- geckolib 4.2.4
	- goblintraders 1.9.3
	- godly_vampirism 1.0.6
	- guardvillagers 1.20.1-1.6.3
	- hunters_return 1.20.1-11.2.0
	- impactfulweather 4.1.0
	- improvedmobs 1.20.1-1.11.6
	- insanelib 1.12.1
	- inventoryessentials 8.2.1
	- inventoryhud 3.4.18
	- inventorysorter 23.0.1
	- ironchest 1.20.1-14.4.4
	- ironfurnaces 4.1.3
	- ironjetpacks 7.0.2
	- irons_spellbooks 1.20.1-2.0.3
	- itemfilters 2001.1.0-build.59
	- jade 11.6.3
	- jei 15.2.0.27
	- lootr 0.7.29.68
	- lost_aether_content 1.2.2
	- majruszsdifficulty 1.8.1
	- mcjtylib 1.20-8.0.3
	- minecraft 1.20.1
	- mixinextras 0.2.0-beta.9
	- mlib 5.0.0
	- modernfix 5.9.0+mc1.20.1
	- mousetweaks 2.25
	- mutantmonsters 8.0.4
	- mysticaladaptations 1.20.1-1.0
	- mysticalagradditions 7.0.1
	- mysticalagriculture 7.0.6
	- nameless_trinkets 1.20.1-1.7.8
	- nitrogen_internals 1.20.1-0.1.3-neoforge
	- notenoughanimations 1.6.4
	- nyfsspiders 2.1.1
	- octolib 0.1
	- packedup 1.0.30
	- piglinproliferation 1.20-1.1.1
	- playeranimator 1.0.2-rc1+1.20
	- progressivebosses 3.9.4-mc1.20.1
	- puffish_skills 0.10.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.5
	- questsadditions 1.4.3a
	- raided 0.1.3
	- relics 0.4.9
	- reliquary 1.20.1-2.0.36.1199
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.13
	- rubidium 0.7.1
	- searchables 1.0.2
	- simplefarming 1.20.1-2.0.6
	- simplehats 1.20.1-0.2.2
	- simpleplanes 1.20.1-5.2.4
	- sodium 0.5.2
	- sophisticatedbackpacks 3.18.65.935
	- sophisticatedcore 0.5.100.457
	- sound_physics_remastered 1.20.1-1.2.1
	- spark 1.10.53
	- spelunkers_charm 1.0.0
	- spore 2.0.0
	- structory 1.3.3
	- structure_gel 2.15.0
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.15
	- t_and_t 0.0NONE
	- taxfreelevels 1.3.6
	- teamlapenlib 1.9.3
	- tenshilib 1.20.1-1.7.2
	- terrablender 3.0.0.169
	- toms_storage 1.6.5
	- toolleveling 1.20.1-2.0.0
	- totw_additions 1.3.1
	- twigs 1.20.1-3.1.0
	- vampiresneedumbrellas 1.0.1
	- vampiricageing 1.20.1-1.3.4
	- vampirism 1.9.3
	- vampirism_integrations 1.8.0-beta.1
	- villagersplus 3.0
	- villagertools 1.0.3
	- visuality 2.0.2
	- wardenhorn 1.8
	- waystones 14.0.2
	- xaerominimap 23.8.4
	- xaeroworldmap 1.36.0
	- yungsapi 1.20-Forge-4.0.2

**Comment by lab3** [comment]
The issue is with spelunkerscharm.  You will need to report the issue to them.  You can remove that mod until they resolve the issue

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_6144_()" because "living" is null
	at net.mcreator.spelunkerscharm.item.CandleOnItem$Helmet$1.getHumanoidArmorModel(CandleOnItem.java:98) ~[SpelunkersCharm-3.4.5-1.20.1.jar%23389!/:?]
	at software.bernie.geckolib.renderer.layer.ItemArmorGeoLayer.getModelForItem(ItemArmorGeoLayer.java:205) ~[geckolib-forge-1.20.1-4.2.4.jar%23335!/:4.2.4]
```
