### ISSUE TITLE
[Bug] Mod failed to load

### ISSUE THREAD

**Issue by GodHyper** [iron431/Irons-Spells-n-Spellbooks#204]
### Observed behaviour

Mod fails to load upon launching the game

### Expected behaviour

loading properly

### Steps to reproduce

Cannot reproduce as I don't know what mod cases incompatability

### Server Type

Single Player

### Crashlog

https://gist.github.com/GodHyper/2fa6cb9762b576d5a5d795177354cec5

### Iron's Spells N Spellbooks version

1.19.2-2.0.3

### Forge version

1.19.2 - 43.2.23

**Comment by lab3** [comment]
@GodHyper 

Everything seems to start breaking after comparties mixins are loaded.  You can try removing that and see if this resolves.  Also, the log references a crash report which I would need to dig any deeper.  Please attach that as well.  The path in the log is:
```
Crash report saved to D:\Games\Minecraft\���������\Prism ������\1.19.2\.minecraft\crash-reports\crash-2023-11-05_16.58.15-fml.txt
```

Also, you can see the first fatal error here: 
```
[05Nov2023 16:57:55.588] [modloading-worker-0/FATAL] [mixin/]: Mixin apply failed comparties.mixins.json:MixinDamageSources
```

**Comment by GodHyper** [comment]
https://gist.github.com/GodHyper/60e1055dfd32233edc890480f0d4b44e
Sorry for making you wait

**Comment by GodHyper** [comment]
also 

> Everything seems to start breaking after comparties mixins are loaded. You can try removing that and see if this resolves. 

I don't know how code in mods work so I have no clue where or how to temporarily remove that part

**Comment by iron431** [comment]
This is an issue with comparties's mixins being out of date with the latest api. Report it to them for them to fix it
