### ISSUE TITLE
crash whenever using raise dead

### ISSUE THREAD

**Issue by halfcatman2** [iron431/Irons-Spells-n-Spellbooks#205]
### Observed behaviour

i tried to use raise dead, but it always crashes my game whenever i or one of the enemies uses it.

### Expected behaviour

summoning undead, not crashing my game

### Steps to reproduce

get book
use raise dead
crash

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/halfcatman2/6d82bc71532744dd1153932147de4d49

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

1.20.1 - 47.2.4

### Other mods

-alexscaves-1.0.6.jar                                                 
-alexsmobs-1.22.6.jar                                                 
-Apotheosis-1.20.1-7.0.5.jar                                          
-ApothicAttributes-1.20.1-1.1.4.jar                                   
-appleskin-forge-mc1.20.1-2.5.1.jar                                   
-aquamirae-6.API15.jar                                                
-architectury-9.1.12-forge.jar                                        
-ars_creo-1.20.1-4.0.1.jar                                            
-ars_elemental-1.20.1-0.6.2.4.jar                                     
-ars_nouveau-1.20.1-4.7.4-all.jar                                     
-artifacts-forge-9.1.0.jar                                            
-AttributeFix-Forge-1.20.1-21.0.2.jar                                 
-balm-forge-1.20.1-7.1.4.jar                                          
-baubley-heart-canisters-1.20.1-1.0.5.jar                             
-Bookshelf-Forge-1.20.1-20.1.6.jar                                    
-caelus-forge-3.1.0+1.20.jar                                          
-cfm-forge-1.20.1-7.0.0-pre36.jar                                     
-citadel-2.4.7-1.20.1.jar                                             
-cloth-config-11.1.106-forge.jar                                      
-colorfulhearts-forge-1.20.1-4.0.4.jar                                
-comforts-forge-6.3.4+1.20.1.jar                                      
-corpse-1.20.1-1.0.5.jar                                              
-cosmeticarmorreworked-1.20.1-v1a.jar                                 
-create-1.20.1-0.5.1.f.jar                                            
-create-stuff-additions1.20.1_v2.0.4a.jar                             
-curios-forge-5.4.2+1.20.1.jar                                        
-Dungeon Crawl-1.20.1-2.3.14.jar                                      
-elevatorid-1.20.1-lex-1.9.jar                                        
-embeddium-0.2.5+mc1.20.1.jar                                         
-EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar                      
-enchantmenttransfer-0.0.6-1.20.1.jar                                 
-EpicFight-20.5.16.jar                                                
-essential_1-2-3_forge_1-20-1.jar                                     
-experienceobelisk-v1.4.10-1.20.1.jar                                 
-geckolib-forge-1.20.1-4.2.4.jar                                      
-inventorysorter-1.20.1-23.0.1.jar                                    
-ironchest-1.20.1-14.4.4.jar                                          
-irons_spellbooks-1.20.1-2.0.3.jar                                    
-jei-1.20.1-forge-15.2.0.27.jar                                       
-journeymap-1.20.1-5.9.16-forge.jar                                   
-JustEnoughResources-1.20.1-1.4.0.238.jar                             
-kotlinforforge-4.5.0-all.jar                                         
-kubejs-forge-2001.6.3-build.83.jar                                   
-lootr-1.20-0.7.30.73.jar                                             
-modlist.txt                                                          
-MouseTweaks-forge-mc1.20-2.25.jar                                    
-NaturesCompass-1.20.1-1.11.2-forge.jar                               
-obscure_api-15.jar                                                   
-origins-forge-1.20.1-1.10.0.2-all.jar                                
-overloadedarmorbar-1.20.1-1.jar                                      
-Patchouli-1.20.1-81-FORGE.jar                                        
-Placebo-1.20.1-8.3.7.jar                                             
-player-animation-lib-forge-1.0.2-rc1+1.20.jar                        
-polymorph-forge-0.49.1+1.20.1.jar                                    
-rhino-forge-2001.2.2-build.11.jar                                    
-SereneSeasons-1.20.1-9.0.0.46.jar                                    
-soul_like_armors_reworked_1.20.1_(v54.0).jar                         
-storagedrawers-1.20.1-12.0.2.jar                                     
-TravelersBackpack-1.20.1-9.1.11.jar                                  
-waystones-forge-1.20-14.0.2.jar                                      
-WeaponsOfMiracles-20.1.7.31.jar                                      
-YungsApi-1.20-Forge-4.0.2.jar                                        
-YungsBetterDesertTemples-1.20-Forge-3.0.3.jar                        
-YungsBetterDungeons-1.20-Forge-4.0.3.jar                             
-YungsBetterEndIsland-1.20-Forge-2.0.4.jar                            
-YungsBetterJungleTemples-1.20-Forge-2.0.4.jar                        
-YungsBetterMineshafts-1.20-Forge-4.0.4.jar                           
-YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar                     
-YungsBetterOceanMonuments-1.20-Forge-3.0.3.jar                       
-YungsBetterStrongholds-1.20-Forge-4.0.3.jar                          
-YungsBetterWitchHuts-1.20-Forge-3.0.3.jar                            
-YungsBridges-1.20-Forge-4.0.3.jar                                    
-[1.20.1-forge]-Epic-Knights-8.8.jar

**Comment by lab3** [comment]
This is a bug in soullikearmorsreworked.  Please report it to them.  If they have questions they can reach out to us on discord.


java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_6144_()" because "living" is null
	at net.mcreator.soullikearmorsreworked.item.DarkKnightItem$Leggings$1.getHumanoidArmorModel(DarkKnightItem.java:149)
