### ISSUE TITLE
[Bug] Apotheosis Gems not appearing in JEI in version 1.20.1

### ISSUE THREAD

**Issue by gameknight102xx** [iron431/Irons-Spells-n-Spellbooks#206]
### Observed behaviour

The Apotheosis alpha version 1.20.1 is unable to register the gems in this modpack properly. Currently only the spell resistance gem seems to be appearing in JEI, but every gem aside from that does not appear on the menu and, presumably, the game proper.

### Expected behaviour

I expected the gems from this mod to appear in JEI.

### Steps to reproduce

1. Download Apotheosis for minecraft version 1.20.1
2. Download iron's spells and spellbooks for minecraft version 1.20.1
3. Download JEI
4. Create a single-player world
5. Open inventory and use JEI interface to search for gems

### Server Type

Single Player

### Iron's Spells N Spellbooks version

v1.20.1-2.0.3

### Forge version

1.20.1 - 47.2.4

**Comment by iron431** [comment]
This is due to apotheosis compat just not being up to date with apoth 1.20.1.will be fixed eventually

**Comment by iron431** [comment]
This is fixed in 3.0.0 with apothic curios
