### ISSUE TITLE
[Bug] Null Entity Render Attempt Causes Crash

### ISSUE THREAD

**Issue by RomanStabbyStab** [iron431/Irons-Spells-n-Spellbooks#207]
### Observed behaviour

I was exploring one of Alex's Caves and a boss spawned that instantly crashed my game with an error saying "failed to render entity".

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot read field "f_267362_" because "entity" is null

### Expected behaviour

My game to not crash

### Steps to reproduce

"The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot read field "f_267362_" because "entity" is null"

### Server Type

Single Player

### Crashlog

https://gist.github.com/RomanStabbyStab/02c7e135244e0ee3d4c40760b1649aec

### Iron's Spells N Spellbooks version

1.20.1-2.0.3

### Forge version

most recent

**Comment by iron431** [comment]
This is an issue with Alex's Caves, not Spell 'n Spellbooks
