### ISSUE TITLE
[Bug] Can't cast spells with "Cast duration"

### ISSUE THREAD

**Issue by icpacilol725** [iron431/Irons-Spells-n-Spellbooks#208]
### Observed behaviour

Same as issue #116, spells with "Cast time" have same problem with "Cast duration" spells (Dragon's breath, Blaze storm,..)

They only start for 1 moment then stop abruptly.

### Expected behaviour

It should cast the spell normally without interuption.

### Steps to reproduce

Select spell book.
Select a spell.
Right click (or hold) to use spell.
Spell casting for a bit and it stopped.

(Same as #116)

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2 - 2.

### Forge version

1.19.2 - 43.2.8

**Comment by iron431** [comment]
closing for duplicate
