### ISSUE TITLE
[Bug] Can't hold any spells on dedicated server

### ISSUE THREAD

**Issue by flatwan** [iron431/Irons-Spells-n-Spellbooks#209]
### Observed behaviour

When my friend tries to cast a spell that you have to hold (like fire wall for example) it immediatly stops. When I try it works normally, and my other friend also doesn't have that problem, only her. I'm personnaly Hosting the server, and I post forward it with playit.gg, we all have the same settings, and it doesn't seem to be a mouse problem, since she can use a bow normally.

### Expected behaviour

When you hold RMB with a holdable spell (like fire wall) it's supposed to last as long as you hold RMB.

### Steps to reproduce

1. Have a modpack created with Curseforge
2. Have a dedicated server hosted personnally
3. Post forward-it with playit.gg
4. Use a holdable spell
5. For some people (?) you can't hold it

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1 - 2.0.3 (latest at current time on curseforge)

### Forge version

1.20.1 - 47.2.0

**Comment by iron431** [comment]
this is a ping issue. we are looking into it. 
duplicated by #182 , closing for duplicate. 
also, considering a wave of these reports just hit discord and github, if the members of your server are all reporting the same issue, please stop. cluttering discord and the issue tracker with the same issue does not make solving it faster.
