### ISSUE TITLE
[Suggestion] Option to replace XP Bar with Mana bar

### ISSUE THREAD

**Issue by PotionSeeker** [iron431/Irons-Spells-n-Spellbooks#21]
### Feature description

As a potential config option, it might be an interesting idea to change the mana bar slightly and have it completely overlay the XP bar when using magic.

Here is a mock up of what it might look like:
![mana bar change](https://user-images.githubusercontent.com/85715437/236571512-bd67f6ae-5c2a-481c-81f0-f5331864e968.png)

### How it improves the player experience

Players don't need to know how much XP they have at all times, which means that knowing how much mana they have would be a more important feature, which means that the replacement wouldn't get in the way of normal play.

Replacing the XP bar also means that player's don't have to worry about fitting another bar on their screen. This change provides some easy/intuitive compatibility with other mods that add their own bar onto the screen; such as a temperature meter or energy bar.

It also provides some parallel to how, when riding a horse, the 'XP bar' changes into the 'Jump Bar' (interaction between the Mana Bar and Jump Bar when riding a horse would probably need to change as a result). 

### Iron's Spells N Spellbooks synergies

User Interface quality of life change ; Design change to the Mana Bar design that could enhance user experience and ease of use ; It provides a more intuitive UI design that plays into minecrafts already existing UI?

**Comment by iron431** [comment]
I like this. When we work on the more extensive UI config options, we can include this.

**Comment by exdj158** [comment]
> I like this. When we work on the more extensive UI config options, we can include this.

Please add an option to hide mana bar always

**Comment by PotionSeeker** [comment]
I tested out the new features and they work really well! I just got another idea for a config; I think it would be nice if players could set how much Mana players starts or respawn with and control whether mana regenerates naturally or not. 

For example, setting the config to 'FULL' means that players always start and respawn with full mana, just like how the hunger and health bar start out full. 
Changing the mana regenration config to 'False' would mean that players don't naturally regenerate mana and they would have to use an item like a mana potion to regenerate their mana. This could probably be achieved by adding a command, just like how there is a '/gamerule naturalRegeneration' command for health. You could also add an extra config to hide the mana bar unless mana is actively regenerating; like it fades away over time if the player hasn't lost or gained mana recently and they aren't actively holding a magic item.

**Comment by iron431** [comment]
> I tested out the new features and they work really well! I just got another idea for a config; I think it would be nice if players could set how much Mana players starts or respawn with and control whether mana regenerates naturally or not.
> 
> For example, setting the config to 'FULL' means that players always start and respawn with full mana, just like how the hunger and health bar start out full. Changing the mana regenration config to 'False' would mean that players don't naturally regenerate mana and they would have to use an item like a mana potion to regenerate their mana. This could probably be achieved by adding a command, just like how there is a '/gamerule naturalRegeneration' command for health. You could also add an extra config to hide the mana bar unless mana is actively regenerating; like it fades away over time if the player hasn't lost or gained mana recently and they aren't actively holding a magic item.

These are good ideas. Mana potions and a mana command have been on the todo list but aren't being focused on. The regen stuff will have to wait until potions and etc come out though.

**Comment by PotionSeeker** [comment]
My guy, you are quick with these edits! Really well done stuff!
