### ISSUE TITLE
[Bug] The "+X to all stats" gem in Apotheosis breaks some spells.

### ISSUE THREAD

**Issue by bob6784558** [iron431/Irons-Spells-n-Spellbooks#210]
### Observed behaviour

The Magic Missile spell can 3 hit the Wither and 1 hit anything else.

### Expected behaviour

Maybe a 5% increase to damage but it seems like that's not how it works.

### Steps to reproduce

1. Obtain Gem with "+x to all stats" effect.
2. Slot gem into helmet.
3. Cast Magic Missile at enemies.
4. Beat the game with a super early spell.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.0.3

### Forge version

47.2.1

### Other mods

Apotheosis (https://www.curseforge.com/minecraft/mc-mods/apotheosis)

**Comment by iron431** [comment]
this is an issue with apotheosis. other mods suffer from this affect as well. 

the gem boosts all attributes, which includes our own attributes, like Spell Power and School Spell Power (immediately granting over 2x the buff), as well as overall projectile damage from apotheosis, as well as any other damage modifying attributes from any other mods, stacking into an insanely overpowered multiplier.

generally speaking, it's an oversight on apotheosis's end and we can't do anything about it. if you think its unbalanced, you can report it to them
