### ISSUE TITLE
Ability to Modify Casting Times

### ISSUE THREAD

**Issue by AetheriMC** [iron431/Irons-Spells-n-Spellbooks#212]
### Feature description

The ability to modify spell casting times via the configs.

### How it improves the player experience

This would allow further customization of spells to better suit each individual's taste. For example, to prevent teleportation spam, it would be nice if Teleport had a 1s channel. With the config, I could just do this myself and not impact others. :)

**Comment by iron431** [comment]
Most spells have functionality built in the their casting time and mode, so this couldn't be a simple configurable feature. All spells would additionally need extra sounds effects, which is just not really gonna happen.
