### ISSUE TITLE
[Bug] Boss [The Dead King] not dropping the Staff

### ISSUE THREAD

**Issue by Evantek** [iron431/Irons-Spells-n-Spellbooks#213]
### Observed behaviour

When defeated the boss does not drop the The Blood Staff 

### Expected behaviour

When defeated the Boss should drop the Blood Staff

### Steps to reproduce

Linux Debian 11
Running in Docker with AMP software

Kill The Dead King - will drop other items but not the The Blood Staff 

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

47.2.4

### Other mods

mod_id,mod_name,mod_version,mod_file,mod_url,display_url,issue_tracker_url
minecraft,Minecraft,1.20.1,server-1.20.1-20230612.114412-srg.jar,,,
smoothchunk,Smoothchunk mod,1.20.1-3.3,smoothchunk-1.20.1-3.3.jar,,,
amplifiednether,Amplified Nether,1.2.2,Amplified_Nether_1.20.1_v1.2.2.jar,,https://www.stardustlabs.net/,
openpartiesandclaims,Open Parties and Claims,0.20.1,open-parties-and-claims-forge-1.20.1-0.20.1.jar,,https://www.curseforge.com/minecraft/mc-mods/open-parties-and-claims,https://github.com/thexaero/open-parties-and-claims/issues
geckolib,GeckoLib 4,4.2.4,geckolib-forge-1.20.1-4.2.4.jar,,http://geckolib.com/,https://github.com/bernie-g/geckolib/issues
playeranimator,Player Animator,1.0.2-rc1+1.20,player-animation-lib-forge-1.0.2-rc1%2B1.20.jar,,,
irons_spellbooks,Iron's Spells 'n Spellbooks,1.20.1-2.0.3,irons_spellbooks-1.20.1-2.0.3.jar,,https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks,https://github.com/iron431/Irons-Spells-n-Spellbooks/issues
cupboard,Cupboard utilities,1.20.1-2.1,cupboard-1.20.1-2.1.jar,,,
terralith,Terralith,2.4.8,Terralith_1.20.2_v2.4.8.jar,,https://www.stardustlabs.net/,
weaponmaster,YDM's Weapon Master,3.0.6,weaponmaster-multi-forge-1.20.1-3.0.6.jar,,https://www.curseforge.com/minecraft/mc-mods/ydms-weapon-master,
configurabledespawntimer,Configurable Despawn Timer,3.2,configurabledespawntimer-1.20.1-3.2.jar,,https://curseforge.com/minecraft/mc-mods/configurable-despawn-timer,https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Configurable%20Despawn%20Timer
cloth_config,Cloth Config v10 API,11.1.106,cloth-config-11.1.106-forge.jar,,,https://github.com/architectury/ClothConfig/issues/
bettercombat,Better Combat,1.8.1+1.20.1,bettercombat-forge-1.8.1%2B1.20.1.jar,,,
caelus,Caelus API,3.1.0+1.20,caelus-forge-3.1.0+1.20.jar,,https://github.com/TheIllusiveC4/Caelus,https://github.com/TheIllusiveC4/Caelus/issues
forge,Forge,47.2.4,forge-1.20.1-47.2.4-universal.jar,,https://minecraftforge.net/,https://minecraftforge.net/
incendium,Incendium,5.3.1,Incendium_1.20.1_v5.3.1.jar,,https://www.stardustlabs.net/,
curios,Curios API,5.4.2+1.20.1,curios-forge-5.4.2+1.20.1.jar,,https://www.curseforge.com/minecraft/mc-mods/curios,https://github.com/TheIllusiveC4/Curios/issues
collective,Collective,7.7,collective-1.20.1-7.7.jar,,https://curseforge.com/minecraft/mc-mods/collective,https://github.com/ricksouth/serilum-mc-mods/labels/Library%3A%20Collective
citadel,Citadel,2.4.9,citadel-2.4.9-1.20.1.jar,,https://github.com/Alex-the-666/Citadel,https://github.com/Alex-the-666/Citadel/issues
cataclysm,Cataclysm Mod,1.0,L_Enders_Cataclysm-1.39+-1.20.1.jar,,,

**Comment by iron431** [comment]
The Blood Staff is not a guaranteed drop. If you think there is an actual bug you can reopen the issue, but all you should have to do is kill him more. You can test it in creative to be sure.
