### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Javgar10** [iron431/Irons-Spells-n-Spellbooks#214]
### Observed behaviour

The icons for the robes, shoes and other cosmetic items loosks fine, but when I try it on it looks like a single purple box, as if the item didn't have a texture (it looks the same in the guidebook that you get when you start a new world)

### Expected behaviour

All cosmetic items should look good when putting them on

### Steps to reproduce

1. Craft Wandering Magician Robe
2. Put it on

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

47.2

### Other mods

Create
Sophisticated Backpacks
Lootr
Just Enough Items
Waystones
JourneyMap
Corpse
When Dungeons Arise
Cataclysm

**Comment by iron431** [comment]
Are you also using optifine?
