### ISSUE TITLE
[Bug] Necromancer spawn rate appears to be quite high

### ISSUE THREAD

**Issue by mickey-barron** [iron431/Irons-Spells-n-Spellbooks#215]
### Observed behaviour

The Necromancers,  `type=irons_spellbooks:necromancer`, appear to spawn very frequently, especially in certain areas. For some areas, I've observed over 40 spawning. 

### Expected behaviour

I'd expect at most 10, preferably closer to 2-4, to spawn.

### Steps to reproduce

1. Join a world
2. Wait for night or enter a cave
3. Wait ~5 minutes

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-2.0.3

### Forge version

1.20.1-47.2.0

**Comment by iron431** [comment]
I observe no such issues. Are you using any other mods?

**Comment by Darkmega18** [comment]
you might find [spawn balance utility](https://www.curseforge.com/minecraft/mc-mods/spawn-balance-utility) useful @mickey-barron . if iron won't make a spawn weight config.

**Comment by mickey-barron** [comment]
Hi @iron431  - my apologies for not getting back to you sooner, yes, there are other mods. I've attached the mod list. I used @Darkmega18's suggestion and that worked well.
[mod-list.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/13680735/mod-list.txt)
