### ISSUE TITLE
[Bug] Alchemist Cauldron dupe (with Carry On mod)

### ISSUE THREAD

**Issue by TemanSv1n** [iron431/Irons-Spells-n-Spellbooks#217]
### Observed behaviour

When i used Carry On with the cauldron, i couldn't get rid of the cauldron in my hands, so i could place cauldrons infinetely. Only death saved me.

### Expected behaviour

Expected basic Carry On behaviour. Just pick up and place in another location.

### Steps to reproduce

1) Install Carry On
2) Shift + RMB the cauldron
3) suffer

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-2.0.3

### Forge version

1.20.1-47.2.0

### Other mods

Carry On version "carryon-forge-1.20.1-2.1.0.1"

**Comment by iron431** [comment]
Is this not a problem with carry on?
