### ISSUE TITLE
[Bug] Compatability Crash with Alex's Mobs for the Necromancer

### ISSUE THREAD

**Issue by WardenDrew** [iron431/Irons-Spells-n-Spellbooks#219]
### Observed behaviour

Rendering an irons_spellbooks:necromancer causes a game crash if Alex's Mobs is also installed.

### Expected behaviour

No crash

### Steps to reproduce

Play until a necromancer spawns

### Server Type

Single Player

### Crashlog

https://gist.github.com/WardenDrew/a52573fc95e04c14bcd8ca244360a201

### Iron's Spells N Spellbooks version

1.20.1-2.0.2

### Forge version

1.20.1-47.2.0

### Other mods

Alex's Mobs 1.22.6

**Comment by iron431** [comment]
This is an issue with alex's mobs. report it to them
