### ISSUE TITLE
Spelunker's charm 2 crash [crash]

### ISSUE THREAD

**Issue by SeppyBeep** [iron431/Irons-Spells-n-Spellbooks#222]
### Observed behaviour

If a necromancer summons underground and summons a zombie or skeleton with a candle helmet, the mobs will crash your game, it is fine after they are ingame, only during summoning and underground since they can only have candle helmets underground

### Expected behaviour

the mobs should be summoned without crashing you

### Steps to reproduce

fight a necromancer underground with spelunker's charm 2 installed

### Server Type

Single Player

### Crashlog

file:///F:/CurseForge/Instances/Forge%20Sheep%20Pack/crash-reports/crash-2023-11-22_17.58.39-client.txt

### Iron's Spells N Spellbooks version

2.0.3

### Forge version

1.20.1

**Comment by iron431** [comment]
@SeppyBeep Can you fix the crash log please
