### ISSUE TITLE
Re-opening of: Right click to use spells / spells will override other interactions with weapons

### ISSUE THREAD

**Issue by Darkmega18** [iron431/Irons-Spells-n-Spellbooks#224]
### Feature description

bot killed the old thread and closed it. please notice us.
https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/56

### How it improves the player experience

yes.

**Comment by iron431** [comment]
fixed in 3.0.0

**Comment by Darkmega18** [comment]
amazing.
