### ISSUE TITLE
[Bug] ] imbued Spell HUD error - Unknown Cause 

### ISSUE THREAD

**Issue by TheGyspyBard** [iron431/Irons-Spells-n-Spellbooks#226]
### Observed behaviour

![2023-11-26_23 09 46](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/152135047/f9d7ad9a-61d5-48b3-aeb5-fb3f0d9790da)
![2023-11-26_23 09 47](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/152135047/e4f731ab-c690-433b-88ad-97748c3122dc)

### Expected behaviour

only having one cooldown maker on screen.

### Steps to reproduce

Here's my mod list, because thats the only thing, other then the mod itself, the issue could come from.
mod_id,mod_name,mod_version,mod_file,mod_url,display_url,issue_tracker_url
tetra,tetra,6.1.0,tetra-1.20.1-6.1.0.jar,,,
saturn,Saturn,0.0.7,saturn-mc1.20.1-0.0.7.jar,,https://legacy.curseforge.com/minecraft/mc-mods/saturn,https://github.com/AbdElAziz333/Saturn/issues
notenoughcrashes,Not Enough Crashes,4.4.6+1.20.1,notenoughcrashes-4.4.6+1.20.1-forge.jar,,,https://github.com/natanfudge/Not-Enough-Crashes/issues
fabric_renderer_api_v1,Fabric Renderer API (v1),3.2.0+1d29b44577,fabric-renderer-api-v1-3.2.0+1d29b44577.jar,,,
runes,Runes,0.9.101.20.1,runes-fabric-0.9.10+1.20.1_mapped_srg_1.20.1.jar,https://github.com/ZsoltMolnarrr/Runes,https://github.com/ZsoltMolnarrr/Runes,
transmog,Transmog,1.2.4+1.20,transmog-forge-1.2.4+1.20.jar,,,
supermartijn642configlib,SuperMartijn642's Config Library,1.1.8,supermartijn642configlib-1.1.8-forge-mc1.20.jar,,https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib,https://github.com/SuperMartijn642/SuperMartijn642sConfigLib/issues
trinkets,Trinkets,3.7.1,trinkets-3.7.1_mapped_srg_1.20.1.jar,https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric,https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric,
epicempires,EpicEmpires,0.0.4-neo,epicempires-0.0.4-neo.jar,,,
geckolib,GeckoLib 4,4.2.4,geckolib-forge-1.20.1-4.2.4.jar,,http://geckolib.com/,https://github.com/bernie-g/geckolib/issues
playeranimator,Player Animator,1.0.2-rc1+1.20,player-animation-lib-forge-1.0.2-rc1+1.20.jar,,,
fabric_item_api_v1,Fabric Item API (v1),2.1.27+2272fc7f77,fabric-item-api-v1-2.1.27+2272fc7f77.jar,,,
com_github_llamalad7_mixinextras,MixinExtras,0.2.0,archers-1.0.6+1.20.1$mixinextras-fabric-0.2.0_mapped_srg_1.20.1.jar,https://github.com/LlamaLad7/MixinExtras,https://github.com/LlamaLad7/MixinExtras,
fabric_rendering_fluids_v1,Fabric Rendering Fluids (v1),3.0.27+4ac5e37a77,fabric-rendering-fluids-v1-3.0.27+4ac5e37a77.jar,,,
cardinal_components_entity,Cardinal Components API (entities),5.2.0,trinkets-3.7.1$cardinal-components-entity-5.2.0_mapped_srg_1.20.1.jar,https://minecraft.curseforge.com/projects/318449,https://minecraft.curseforge.com/projects/318449,
fabric_models_v0,Fabric Models (v0),0.4.1+7c3892a477,fabric-models-v0-0.4.1+7c3892a477.jar,,,
dynamiclights,Dynamic Lights,1.20.1.2,dynamiclights-1.20.1.2.jar,,http://atomicstryker.org/,https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues
sophisticatedcore,Sophisticated Core,0.5.107.496,sophisticatedcore-1.20.1-0.5.107.496.jar,,,https://github.com/P3pp3rF1y/SophisticatedCore/issues
rubidium,Rubidium,0.7.1,rubidium-mc1.20.1-0.7.1.jar,,,
sodium,Sodium,0.5.2,rubidium-mc1.20.1-0.7.1.jar,,,
fabric_convention_tags_v1,Fabric Convention Tags,1.5.4+fa3d1c0177,fabric-convention-tags-v1-1.5.4+fa3d1c0177.jar,,,
placebo,Placebo,8.5.8,Placebo-1.20.1-8.5.8.jar,,,
modernfix,ModernFix,5.9.3+mc1.20.1,modernfix-forge-5.9.3+mc1.20.1.jar,,https://modrinth.com/mod/modernfix,https://github.com/embeddedt/ModernFix/issues
citadel,Citadel,2.4.9,citadel-2.4.9-1.20.1.jar,,https://github.com/Alex-the-666/Citadel,https://github.com/Alex-the-666/Citadel/issues
fabric_command_api_v1,Fabric Command API (v1),1.2.33+f71b366f77,fabric-command-api-v1-1.2.33+f71b366f77.jar,,,
fabric_command_api_v2,Fabric Command API (v2),2.2.12+561530ec77,fabric-command-api-v2-2.2.12+561530ec77.jar,,,
fabric_block_view_api_v2,Fabric BlockView API (v2),1.0.0+0767707077,fabric-block-view-api-v2-1.0.0+0767707077.jar,,,
maxhealthfix,MaxHealthFix,12.0.2,MaxHealthFix-Forge-1.20.1-12.0.2.jar,,https://www.curseforge.com/minecraft/mc-mods/max-health-fix,https://github.com/Darkhax-Minecraft/Max-Health-Fix/issues
mixinextras,MixinExtras,0.2.0,mixinextras-forge-0.2.0.jar,,https://github.com/LlamaLad7/MixinExtras,
connectorextras_rei_bridge,Connector Extras REI Bridge,1.6.1+1.20.1,rei-bridge-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
bookshelf,Bookshelf,20.1.6,Bookshelf-Forge-1.20.1-20.1.6.jar,,https://www.curseforge.com/minecraft/mc-mods/bookshelf,https://github.com/Darkhax-Minecraft/Bookshelf/issues
sophisticatedbackpacks,Sophisticated Backpacks,3.18.68.952,sophisticatedbackpacks-1.20.1-3.18.68.952.jar,,,https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues
connectorextras_continuity_compat,Connector Extras Continuity Compat,1.6.1+1.20.1,continuity-compat-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
relics,Relics,0.5.1.2,relics-1.20.1-0.5.1.2.jar,,https://www.curseforge.com/minecraft/mc-mods/relics-mod,https://discord.gg/pHren9yxzW
apotheosis,Apotheosis,7.1.0,Apotheosis-1.20.1-7.1.0.jar,,,
ec_apotheosis_plugin,EC Compat for Apotheosis,1.0.0,ec_apotheosis_plugin-1.20.1-1.0.0-all.jar,,,
sculkhornid,Sculk Horn Mod,1.4.5,(Forge)SculkHorn-1.20.x-1.4.5.jar,,https://www.curseforge.com/minecraft/mc-mods/sculk-horn,https://github.com/anviaan/SculkHorn/issues
fabric_screen_api_v1,Fabric Screen API (v1),2.0.7+45a670a577,fabric-screen-api-v1-2.0.7+45a670a577.jar,,,
projectile_damage,Projectile Damage Attribute,3.2.2+1.20.1,projectile_damage-forge-3.2.2+1.20.1.jar,,,https://github.com/ZsoltMolnarrr/ProjectileDamage/issues
cloth_config,Cloth Config v10 API,11.1.106,cloth-config-11.1.106-forge.jar,,,https://github.com/architectury/ClothConfig/issues/
fabric_api,Forgified Fabric API,0.90.7+1.10.2+1.20.1,fabric-api-0.90.7+1.10.2+1.20.1.jar,,,
connectorextras_modmenu_bridge,Connector Extras ModMenu Bridge,1.6.1+1.20.1,modmenu-bridge-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
modmenu,ModMenu (Connector Extras),7.2.2,modmenu-bridge-1.6.1+1.20.1.jar,,,https://github.com/Sinytra/ConnectorExtras/issues
fabric_content_registries_v0,Fabric Content Registries (v0),4.0.10+a670df1e77,fabric-content-registries-v0-4.0.10+a670df1e77.jar,,,
archers,Archers (RPG Series),1.0.61.20.1,archers-1.0.6+1.20.1_mapped_srg_1.20.1.jar,https://github.com/ZsoltMolnarrr/Archers,https://github.com/ZsoltMolnarrr/Archers,
durabilitytooltip,Durability Tooltip,1.1.5,durabilitytooltip-1.1.5-forge-mc1.20.jar,,https://www.curseforge.com/minecraft/mc-mods/durability-tooltip,https://github.com/SuperMartijn642/DurabilityTooltip/issues
connectorextras_terrablender_bridge,Connector Extras Terrablender Bridge,1.6.1+1.20.1,terrablender-bridge-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
structure_gel,Structure Gel API,2.15.0,structure_gel-1.20.1-2.15.0.jar,,https://moddinglegacy.com/,https://gitlab.com/modding-legacy/structure-gel-api/-/issues
fabric_game_rule_api_v1,Fabric Game Rule API (v1),1.0.39+461110ab77,fabric-game-rule-api-v1-1.0.39+461110ab77.jar,,,
fabric_api_lookup_api_v1,Fabric API Lookup API (v1),1.6.35+67f9824077,fabric-api-lookup-api-v1-1.6.35+67f9824077.jar,,,
cataclysmiccombat,Cataclysmic Combat,1.1,cataclysmiccombat+1.1.jar,,,
colorfulhearts,Colorful Hearts,4.0.4,colorfulhearts-forge-1.20.1-4.0.4.jar,,,https://github.com/Terrails/colorful-hearts
supermartijn642corelib,SuperMartijn642's Core Lib,1.1.15,supermartijn642corelib-1.1.15-forge-mc1.20.jar,,https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib,https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/issues
reach_entity_attributes,Reach Entity Attributes,2.4.0,reach-entity-attributes-2.4.0.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
bendylib,Bendy lib,4.0.0,bendy-lib-forge-4.0.0.jar,,,
reeses_sodium_options,TexTrue's Rubidium Options,1.0.5+mc1.20.1,TextruesRubidiumOptions-1.0.5+mc1.20.1.jar,,https://github.com/ThinkingStudios/ReesesSodiumOptions-Forge,
connectorextras_architectury_bridge,Connector Extras Architectury Bridge,1.6.1+1.20.1,architectury-bridge-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
modelfix,Model Gap Fix,1.14,modelfix-1.14.jar,,https://www.curseforge.com/minecraft/mc-mods/model-gap-fix,
spell_power,Spell Power Attribute,0.9.181.20.1,spell_power-fabric-0.9.18+1.20.1_mapped_srg_1.20.1.jar,https://github.com/ZsoltMolnarrr/SpellPower,https://github.com/ZsoltMolnarrr/SpellPower,
cataclysm,Cataclysm Mod,1.0,L_Enders_Cataclysm-1.39+-1.20.1.jar,,,
curios,Curios API,5.4.2+1.20.1,curios-forge-5.4.2+1.20.1.jar,,https://www.curseforge.com/minecraft/mc-mods/curios,https://github.com/TheIllusiveC4/Curios/issues
patchouli,Patchouli,1.20.1-83-FORGE,Patchouli-1.20.1-83-FORGE.jar,,,https://github.com/VazkiiMods/Patchouli
collective,Collective,7.7,collective-1.20.1-7.7.jar,,https://curseforge.com/minecraft/mc-mods/collective,https://github.com/ricksouth/serilum-mc-mods/labels/Library%3A%20Collective
basicweapons,Basic Weapons,1.2.0,basicweapons-forge-mc1.20.1+1.2.0.jar,,,
attributeslib,Apothic Attributes,1.2.0,ApothicAttributes-1.20.1-1.2.0.jar,,,
betterthirdperson,Better Third Person,1.9.0,BetterThirdPerson-Forge-1.20-1.9.0.jar,,,
connectormod,Connector,1.0.0-beta.25+1.20.1,Connector-1.0.0-beta.25+1.20.1-mod.jar,,https://github.com/Sinytra/Connector,https://github.com/Sinytra/Connector/issues
fabric_entity_events_v1,Fabric Entity Events (v1),1.5.22+b909fbe377,fabric-entity-events-v1-1.5.22+b909fbe377.jar,,,
cardinal_components_base,Cardinal Components API (base),5.2.0,trinkets-3.7.1$cardinal-components-base-5.2.0_mapped_srg_1.20.1.jar,https://minecraft.curseforge.com/projects/318449,https://minecraft.curseforge.com/projects/318449,
architectury,Architectury,9.1.12,architectury-9.1.12-forge.jar,,,https://github.com/shedaniel/architectury/issues
com_github_zsoltmolnarrr_tinyconfig,TinyConfig,2.3.2,archers-1.0.6+1.20.1$TinyConfig-2.3.2_mapped_srg_1.20.1.jar,,,
fabric_loot_api_v2,Fabric Loot API (v2),1.2.0+eb28f93e77,fabric-loot-api-v2-1.2.0+eb28f93e77.jar,,,
cupboard,Cupboard utilities,1.20.1-2.1,cupboard-1.20.1-2.1.jar,,,
connectorextras,Connector Extras,1.6.1+1.20.1,ConnectorExtras-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
fabric_rendering_data_attachment_v1,Fabric Rendering Data Attachment (v1),0.3.36+a6081afc77,fabric-rendering-data-attachment-v1-0.3.36+a6081afc77.jar,,,
rubidium_extra,Rubidium/Embeddium Extra,0.5.3.1+mc1.20.1-build.110,rubidium-extra-0.5.3.1+mc1.20.1-build.110.jar,,https://curseforge.com/minecraft/mc-mods/rubidium-extra,https://github.com/dima-dencep/rubidium-extra/issues
fabric_networking_api_v1,Fabric Networking API (v1),1.3.10+503a202477,fabric-networking-api-v1-1.3.10+503a202477.jar,,,
framework,Framework,0.6.16,framework-forge-1.20.1-0.6.16.jar,,https://mrcrayfish.com/mods?id=framework,
shulkerboxtooltip,ShulkerBoxTooltip,4.0.4+1.20.1,shulkerboxtooltip-forge-4.0.4+1.20.1.jar,,,https://github.com/MisterPeModder/ShulkerBoxTooltip/issues
fabric_lifecycle_events_v1,Fabric Lifecycle Events (v1),2.2.21+afab492177,fabric-lifecycle-events-v1-2.2.21+afab492177.jar,,,
simplyskills,SimplySkills,1.0.01.20.1,simplyskills-1.0.0+1.20.1_mapped_srg_1.20.1.jar,https://www.curseforge.com/minecraft/mc-mods/simply_skills,https://www.curseforge.com/minecraft/mc-mods/simply_skills,
fabric_key_binding_api_v1,Fabric Key Binding API (v1),1.0.36+561530ec77,fabric-key-binding-api-v1-1.0.36+561530ec77.jar,,,
fabric_client_tags_api_v1,Fabric Client Tags,1.1.1+5d6761b877,fabric-client-tags-api-v1-1.1.1+5d6761b877.jar,,,
wizards,Wizards (RPG Series),1.0.41.20.1,wizards-1.0.4+1.20.1_mapped_srg_1.20.1.jar,https://github.com/ZsoltMolnarrr/Wizards,https://github.com/ZsoltMolnarrr/Wizards,
fabric_transfer_api_v1,Fabric Transfer API (v1),3.3.2+51502a0077,fabric-transfer-api-v1-3.3.2+51502a0077.jar,,,
fabric_dimensions_v1,Fabric Dimensions API (v1),2.1.53+8005d10d77,fabric-dimensions-v1-2.1.53+8005d10d77.jar,,,
puffish_skills,Pufferfish's Skills,0.10.0,puffish_skills-0.10.0-1.20-forge.jar,,,
spell_engine,Spell Engine,0.12.41.20.1,spell_engine-0.12.4+1.20.1_mapped_srg_1.20.1.jar,https://github.com/ZsoltMolnarrr/SpellEngine,https://github.com/ZsoltMolnarrr/SpellEngine,
tonsofenchants,Tons Of Enchants,1.0.0,TonsOfEnchants-1.20.1-1.0.jar,,,
octolib,OctoLib,0.1,octolib-0.1.jar,,,https://discord.gg/pHren9yxzW
fabric_model_loading_api_v1,Fabric Model Loading API (v1),1.0.2+142e25ab77,fabric-model-loading-api-v1-1.0.2+142e25ab77.jar,,,
jei,Just Enough Items,15.2.0.27,jei-1.20.1-forge-15.2.0.27.jar,,https://www.curseforge.com/minecraft/mc-mods/jei,https://github.com/mezz/JustEnoughItems/issues?q=is%3Aissue
adaptive_tooltips,Adaptive Tooltips,1.3.0,AdaptiveTooltips-1.3.0-fabric-1.20.2_mapped_srg_1.20.1.jar,https://isxander.dev,https://isxander.dev,
attributefix,AttributeFix,21.0.3,AttributeFix-Forge-1.20.1-21.0.3.jar,,https://www.curseforge.com/minecraft/mc-mods/attributefix,https://github.com/Darkhax-Minecraft/AttributeFix/issues
pehkui,Pehkui,3.7.11+1.20.1-forge,Pehkui-3.7.11+1.20.1-forge.jar,,https://www.curseforge.com/minecraft/mc-mods/pehkui/,https://github.com/Virtuoel/Pehkui/issues
fabric_screen_handler_api_v1,Fabric Screen Handler API (v1),1.3.29+561530ec77,fabric-screen-handler-api-v1-1.3.29+561530ec77.jar,,,
fabric_resource_loader_v0,Fabric Resource Loader (v0),0.11.9+142e25ab77,fabric-resource-loader-v0-0.11.9+142e25ab77.jar,,,
epicsamurai,Epic Samurai,0.0.29-1.20.1-forge,epicsamurai-0.0.29-1.20.1-forge.jar,,,
ec_es_plugin,EC Epic Samurais Plugin,1.0.1,ec_es_plugin-1.20.1-1.0.1-all.jar,,,
caelus,Caelus API,3.1.0+1.20,caelus-forge-3.1.0+1.20.jar,,https://github.com/TheIllusiveC4/Caelus,https://github.com/TheIllusiveC4/Caelus/issues
enchantingcommands,Enchanting Commands,3.1,enchantingcommands-1.20.1-3.1.jar,,https://curseforge.com/minecraft/mc-mods/enchanting-commands,https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Enchanting%20Commands
tetracelium,tetracelium,1.0.1,tetracelium-1.20.1-1.0.1.jar,,,
fabric_rendering_v1,Fabric Rendering (v1),3.0.7+1c0ea72177,fabric-rendering-v1-3.0.7+1c0ea72177.jar,,,
fabric_renderer_indigo,Fabric Renderer - Indigo,1.5.0+67f9824077,fabric-renderer-indigo-1.5.0+67f9824077.jar,,,
shield_overhaul,Shield Overhaul,1.0.3,Shield_Overhaul-FORGE-MC1.20.1-1.0.3_mapped_srg_1.20.1.jar,https://curseforge.com/members/elocindev/projects,https://curseforge.com/members/elocindev/projects,
fabric_mining_level_api_v1,Fabric Mining Level API (v1),2.1.49+561530ec77,fabric-mining-level-api-v1-2.1.49+561530ec77.jar,,,
travelersbackpack,Traveler's Backpack,9.1.11,TravelersBackpack-1.20.1-9.1.11.jar,,https://www.curseforge.com/minecraft/mc-mods/travelers-backpack,
artifacts,Artifacts,9.2.0,artifacts-forge-9.2.0.jar,,https://www.curseforge.com/minecraft/mc-mods/artifacts,https://github.com/ochotonida/artifacts/issues
connectorextras_geckolib_fabric_compat,Connector Extras Geckolib-Fabric Compat,1.6.1+1.20.1,geckolib-fabric-compat-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
starlight,Starlight,1.1.2+forge.1cda73c,starlight-1.1.2+forge.1cda73c.jar,,https://www.curseforge.com/minecraft/mc-mods/starlight-forge,
catalogue,Catalogue,1.8.0,catalogue-forge-1.20.1-1.8.0.jar,,https://mrcrayfish.com/mods?id=catalogue,https://github.com/MrCrayfish/Catalogue/issues
connectorextras_energy_bridge,Connector Extras Energy Bridge,1.6.1+1.20.1,energy-bridge-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
fabric_particles_v1,Fabric Particles (v1),1.1.1+78e1ecb877,fabric-particles-v1-1.1.1+78e1ecb877.jar,,,
forge,Forge,47.2.0,forge-1.20.1-47.2.0-universal.jar,,,http://www.minecraftforge.net/
fabric_transitive_access_wideners_v1,Fabric Transitive Access Wideners (v1),4.3.0+1880499877,fabric-transitive-access-wideners-v1-4.3.0+1880499877.jar,,,
ironchest,Iron Chests,1.20.1-14.4.4,ironchest-1.20.1-14.4.4.jar,,https://minecraft.curseforge.com/projects/iron-chests,https://github.com/progwml6/ironchest/issues
minecraft,Minecraft,1.20.1,client-1.20.1-20230612.114412-srg.jar,,,
alexscaves,Alex's Caves,1.0.8,alexscaves-1.0.8.jar,,,https://github.com/AlexModGuy/AlexsCavesBetaTest/issues
enchdesc,EnchantmentDescriptions,17.0.8,EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar,,https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions,https://github.com/Darkhax-Minecraft/Enchantment-Descriptions/issues
fabric_api_base,Fabric API Base,0.4.30+ef105b4977,fabric-api-base-0.4.30+ef105b4977.jar,,,
bettercombat,Better Combat,1.8.1+1.20.1,bettercombat-forge-1.8.1+1.20.1.jar,,,
combatroll,Combat Roll,1.3.0+1.20.1,combatroll-forge-1.3.0+1.20.1.jar,,,https://github.com/ZsoltMolnarrr/CombatRoll/issues
twm,Tugkan's Weaponry Mod,1.12.2,twm-1.12.2.jar,,,
fabric_blockrenderlayer_v1,Fabric BlockRenderLayer Registration (v1),1.1.40+1d0da21e77,fabric-blockrenderlayer-v1-1.1.40+1d0da21e77.jar,,,
jade,Jade,11.6.3,Jade-1.20.1-forge-11.6.3.jar,,https://minecraft.curseforge.com/projects/jade,
amecsapi,Amecs API,1.5.3+mc1.20-pre1,amecsapi-1.5.3+mc1.20-pre1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
fabric_block_api_v1,Fabric Block API (v1),1.0.10+0e6cb7f777,fabric-block-api-v1-1.0.10+0e6cb7f777.jar,,,
smoothboot,Smooth Boot (Reloaded),0.0.3,smoothboot-mc1.20.1-0.0.3.jar,,https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded,https://github.com/AbdElAziz333/Smooth-Boot-Reloaded/issues
nbt_ac,NBT Autocomplete,1.1.7,NBTac-FORGE-1.20.1-1.1.7.jar,,https://github.com/mt1006/mc-nbtac-mod,https://github.com/mt1006/mc-nbtac-mod/issues
fabric_resource_conditions_api_v1,Fabric Resource Conditions API (v1),2.3.6+369cb3a477,fabric-resource-conditions-api-v1-2.3.6+369cb3a477.jar,,,
azurelibarmor,AzureLib Armor,2.0.0,azurelibarmor-neo-1.20.1-2.0.0.jar,,ttps://modrinth.com/mod/azurelib-armor,https://github.com/AzureDoom/AzureLib-Armor/issues
flywheel,Flywheel,0.6.10-7,flywheel-forge-1.20.1-0.6.10-7.jar,,https://www.curseforge.com/minecraft/mc-mods/flywheel,https://github.com/Jozufozu/Flywheel/issues
effortlessbuilding,Effortless Building,3.6,effortlessbuilding-1.20.1-3.6-all.jar,,https://minecraft.curseforge.com/projects/effortless-building,https://bitbucket.org/Requios/effortless-building/issues?status=new&status=open&status=submitted&is_spam=%21spam
mutil,mutil,6.1.1,mutil-1.20.1-6.1.1.jar,,,
fabric_item_group_api_v1,Fabric Item Group API (v1),4.0.11+9801bf5177,fabric-item-group-api-v1-4.0.11+9801bf5177.jar,,,
irons_spellbooks,Iron's Spells 'n Spellbooks,1.20.1-2.1.0,irons_spellbooks-1.20.1-2.1.0.jar,,https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks,https://github.com/iron431/Irons-Spells-n-Spellbooks/issues
entityculling,EntityCulling,1.6.2,entityculling-forge-1.6.2-mc1.20.1.jar,,,
backpacked,Backpacked,2.2.5,backpacked-forge-1.20.1-2.2.5.jar,,https://mrcrayfish.com/mods?id=backpacked,https://github.com/MrCrayfish/Backpacked/issues
canary,Canary,0.2.7,canary-mc1.20.1-0.2.7.jar,,https://www.curseforge.com/minecraft/mc-mods/canary,https://github.com/AbdElAziz333/Canary/issues
fabric_biome_api_v1,Fabric Biome API (v1),13.0.12+dd0389a577,fabric-biome-api-v1-13.0.12+dd0389a577.jar,,,
suggestion_tweaker,Suggestion Tweaker,1.20-1.5.1,suggestion-tweaker-1.20-1.5.1-forge.jar,,https://www.curseforge.com/minecraft/mc-mods/suggestion-tweaker,
library_of_exile,Library Of Exile,1.3.6,Library_of_Exile-1.20.1-1.3.6.jar,,,https://github.com/RobertSkalko/Library-of-Exile-Rework
fabric_registry_sync_v0,Fabric Registry Sync (v0),2.3.2+1c0ea72177,fabric-registry-sync-v0-2.3.2+1c0ea72177.jar,,,
appleskin,AppleSkin,2.5.1+mc1.20.1,appleskin-forge-mc1.20.1-2.5.1.jar,,https://github.com/squeek502/AppleSkin,https://github.com/squeek502/AppleSkin
fabric_recipe_api_v1,Fabric Recipe API (v1),1.0.20+514a076577,fabric-recipe-api-v1-1.0.20+514a076577.jar,,,
structure_pool_api,Structure Pool API,1.01.20.1,archers-1.0.6+1.20.1$structure-pool-api-1.0+1.20.1_mapped_srg_1.20.1.jar,https://github.com/FabricExtras/StructurePoolAPI,https://github.com/FabricExtras/StructurePoolAPI,
ferritecore,Ferrite Core,6.0.1,ferritecore-6.0.1-forge.jar,,,
fabric_object_builder_api_v1,Fabric Object Builder API (v1),11.1.2+2174fc8477,fabric-object-builder-api-v1-11.1.2+2174fc8477.jar,,,
yet_another_config_lib_v3,YetAnotherConfigLib,3.2.1+1.20,yet-another-config-lib-forge-3.2.1+1.20.jar,,,
fabric_sound_api_v1,Fabric Sound API (v1),1.0.12+4f23bd8477,fabric-sound-api-v1-1.0.12+4f23bd8477.jar,,,
fabric_message_api_v1,Fabric Message API (v1),5.1.8+52cc178c77,fabric-message-api-v1-5.1.8+52cc178c77.jar,,,
expandability,ExpandAbility,9.0.0,expandability-9.0.0.jar,,,https://github.com/florensie/expandability/issues
cosmeticarmorreworked,CosmeticArmorReworked,1.20.1-v1a,cosmeticarmorreworked-1.20.1-v1a.jar,,,
connectorextras_emi_bridge,Connector Extras EMI Bridge,1.6.1+1.20.1,emi-bridge-1.6.1+1.20.1.jar,,https://github.com/Sinytra/ConnectorExtras,https://github.com/Sinytra/ConnectorExtras/issues
overloadedarmorbar,Overloaded Armor Bar,1.20.1-1,overloadedarmorbar-1.20.1-1.jar,,,https://github.com/Tfarcenim/OverloadedArmorBar/issues
expanded_combat,Expanded Combat,2.8.1,expanded_combat-1.20.1-2.8.1-all.jar,,,
chunksending,chunksending mod,1.20.1-2.8,chunksending-1.20.1-2.8.jar,,,
fabric_data_generation_api_v1,Fabric Data Generation API (v1),12.3.2+369cb3a477,fabric-data-generation-api-v1-12.3.2+369cb3a477.jar,,,
fabric_events_interaction_v0,Fabric Events Interaction (v0),0.6.1+25d9948677,fabric-events-interaction-v0-0.6.1+25d9948677.jar,,,

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.1.0

### Forge version

47.2.0

**Comment by iron431** [comment]
fixed in latest version
