### ISSUE TITLE
[Bug] mahoutsukai  SpellData.getDisplayName

### ISSUE THREAD

**Issue by Sultia** [iron431/Irons-Spells-n-Spellbooks#227]
### Observed behaviour

two players have experienced corrupt / crashing due to Exception caught during firing event: 'net.minecraft.network.chat.Component io.redspace.ironsspellbooks.capabilities.spell.SpellData.getDisplayName()'

### Expected behaviour

Not have players on the server crash and or not have corrupt player data.

### Steps to reproduce

N/A

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Sultia/84f4ba299d9122b96ac380ed552f5fc4

### Iron's Spells N Spellbooks version

2.1.0

### Forge version

47.2.6

### Other mods

	- ad_astra 1.15.5
	- ad_astra_giselle_addon 5.8
	- ae2 15.0.15
	- ae2wtlib 15.1.4-forge
	- aiimprovements 0.5.2
	- alchemistry 2.3.4
	- alchemylib 1.0.29
	- alexsmobs 1.22.6
	- allthemodium 2.4.4
	- alltheores 2.2.3
	- apexcore 10.0.0
	- apotheosis 7.1.0
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.0
	- architectury 9.1.12
	- armourers_workshop 2.0.9
	- ars_creo 4.0.1
	- ars_nouveau 4.7.4
	- artifacts 9.2.0
	- attributefix 21.0.3
	- attributeslib 1.2.0
	- automobility 0.4.2+1.20.1-forge
	- balm 7.1.4
	- bcc 4.0.8
	- bendylib 4.0.0
	- betteradvancements 0.3.2.161
	- betterdungeons 1.20-Forge-4.0.3
	- bettermineshafts 1.20-Forge-4.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- bhc 1.20.1-1.0.5
	- bigreactors 1.20.1-2.0.76
	- blockui 1.20.1-1.0.125-BETA
	- bonfires 1.2.14
	- bookshelf 20.1.6
	- botanypots 13.0.17
	- botanypotstiers 6.0.0
	- botanytrees 9.0.7
	- botarium 2.2.1
	- bountiful 6.0.3+1.20.1
	- cabletiers 1.20.1-1.2
	- caelus 3.1.0+1.20
	- camera 1.20.1-1.0.6
	- car 1.20.1-1.0.8
	- casualness_delight 1.20.1-0.2n
	- cccbridge 1.6.3-forge
	- cfm 7.0.0-pre36
	- chalk 1.6.3
	- charginggadgets 1.11.0
	- chefsdelight 1.0.3-forge-1.20.1
	- chemlib 2.0.18
	- chicken_roost 2.1.1
	- chimes 2.0.1
	- chunky 1.3.92
	- citadel 2.4.9
	- cloth_config 11.1.106
	- clumps 12.0.0.3
	- collective 7.8
	- comforts 6.3.4+1.20.1
	- commonality 7.0.0
	- commoncapabilities 2.9.0
	- computercraft 1.108.4
	- connectivity 1.20.1-4.8
	- constructionwand 1.20.1-2.11
	- controlling 12.0.2
	- cookingforblockheads 16.0.1
	- corn_delight 1.0.3-1.20.1
	- cosmeticarmorreworked 1.20.1-v1a
	- crabbersdelight 1.1.3a
	- craftingtweaks 18.2.1
	- crafttweaker 14.0.26
	- crawlondemand 1.20.x-1.0.0
	- create 0.5.1.f
	- create_confectionery 1.1.0
	- create_dragon_lib 1.3.3
	- create_enchantment_industry 1.2.7.g
	- create_sa 2.0.4.
	- create_things_and_misc 1.0.0
	- creativecore 2.11.10
	- croptopia 2.3.2
	- croptopia_additions 2.0.0
	- cucumber 7.0.5
	- cupboard 1.20.1-2.1
	- curios 5.4.3+1.20.1
	- curiotiab 1.20.1-2.0.2
	- curious_armor_stands 1.20-5.0.1
	- customportalapi 0.0.1-beta1-1.20
	- cyclopscore 1.18.14
	- dankstorage 1.20.1-1.1
	- darkutils 17.0.3
	- dcintegration 3.0.3
	- deeperdarker 1.2.1
	- deepresonance 1.20-5.0.2
	- dimstorage 8.0.1
	- domum_ornamentum 1.20-1.0.147-BETA
	- dragonmounts 1.1.5.b3
	- drinkbeer 1.0.4
	- dynamiclights 1.20.1.2
	- edivadlib 2.0.1
	- elevatorid 1.20.1-lex-1.9
	- emotecraft 2.2.7-b.build.50
	- enchdesc 17.0.8
	- enderchests 1.20.1-1.2
	- endersdelight 1.0.3
	- ends_delight 1.0.1
	- entityculling 1.6.2
	- epicfight 20.6.1
	- evenmoreinstruments 2.1
	- evilcraft 1.2.34
	- evilcraftcompat 1.2.34
	- expandability 9.0.0
	- experienceobelisk 1.4.10-1.20.1
	- explorerscompass 1.20.1-1.3.3-forge
	- extradisks 1.20.1-3.0.1
	- extrastorage 4.0.4
	- fantasyfurniture 9.0.0
	- farmersdelight 1.20.1-1.2.3
	- farmingforblockheads 14.0.2
	- fastleafdecay 31
	- fastload 3.4.0
	- ferritecore 6.0.1
	- festive_delight 1.0.0
	- flib 0.0.11
	- fluxnetworks 7.2.0.14
	- flywheel 0.6.10-7
	- foodables 1.0.0-forge
	- forge 47.2.6
	- framedblocks 9.1.6
	- framework 0.6.16
	- ftbbackups2 1.0.23
	- ftbchunks 2001.2.3
	- ftbessentials 2001.2.2
	- ftblibrary 2001.1.4
	- ftbquests 2001.2.0
	- ftbranks 2001.1.3
	- ftbteams 2001.1.4
	- ftbultimine 2001.1.2
	- ftbxmodcompat 2.0.1
	- fuelgoeshere 1.20.0-1.0.1
	- gateways 4.2.1
	- geckolib 4.2.4
	- genshinstrument 3.3.1
	- geore 2.4.2
	- georenouveau 0.4.1
	- goblintraders 1.9.3
	- handcrafted 3.0.5
	- healingbed 1.20.1
	- healingcampfire 5.2
	- horse_colors 1.20.1-12.0
	- hostilenetworks 5.2.0
	- iceberg 1.1.16
	- immersive_armors 1.6.1+1.20.1
	- incontrol 1.20-9.1.2
	- industrialforegoing 3.5.9
	- infernalmobs 1.20.1.1
	- integratedcrafting 1.1.6
	- integrateddynamics 1.20.2
	- integrateddynamicscompat 1.20.2
	- integratedterminals 1.4.11
	- integratedterminalscompat 1.4.11
	- integratedtunnels 1.8.24
	- integratedtunnelscompat 1.8.24
	- interiors 0.5.2
	- inventorysorter 23.0.1
	- ironchest 1.20.1-14.4.4
	- ironjetpacks 7.0.2
	- irons_spellbooks 1.20.1-2.1.0
	- itemcollectors 1.1.8
	- itemfilters 2001.1.0-build.59
	- itemphysic 1.6.16
	- jade 11.6.3
	- jadeaddons 5.2.1
	- jadecolonies 1.4.1
	- jei 15.2.0.27
	- jeresources 1.4.0.238
	- journeymap 5.9.18
	- jumbofurnace 4.0.0.5
	- justenoughprofessions 3.0.1
	- k_turrets 3.0.18-1.20.1
	- kambrik 6.1.1+1.20.1
	- kotlinforforge 4.7.0
	- laserio 1.6.7
	- letmedespawn 1.2.0
	- leveltextfix 7.0.2
	- libx 1.20.1-5.0.7
	- magistuarmory 8.8
	- mahoutsukai 1.20.1-v1.34.58
	- marbledsvillagerhats 1.0.0
	- maturidelight 1.20.1-2.1.0
	- maxhealthfix 12.0.2
	- mcjtylib 1.20-8.0.3
	- measurements 2.0.0
	- mekanism 10.4.5
	- mekanismadditions 10.4.5
	- mekanismgenerators 10.4.5
	- mekanismtools 10.4.5
	- mffs 5.1.9
	- mighty_mail 1.0.14
	- minecolonies 1.20.1-1.1.328-BETA
	- minecraft 1.20.1
	- minepop 1.0.0
	- mining_dimension 1.20.1-1.0.4
	- mixinextras 0.2.0-rc.4
	- mob_grinding_utils 1.20.1-1.0.3
	- modernfix 5.9.3+mc1.20.1
	- modonomicon 1.40.0
	- modularrouters 12.0.2+mc1.20.1
	- morebeautifultorches 2.5.2-1.20.1_forge
	- moremekanismprocessing 4.0
	- morered 4.0.0.4
	- moreredxcctcompat 1.20.1-1.0.0
	- multipiston 1.20-1.2.31-ALPHA
	- mysterious_mountain_lib 1.2.7-1.20
	- mysticalagriculture 7.0.6
	- mysticalcustomization 5.0.0
	- naturesaura 39.3
	- naturescompass 1.20.1-1.11.2-forge
	- netherportalfix 13.0.0
	- nomowanderer 1.20.1_1.6.1
	- occultism 1.91.0
	- oceansdelight 1.0.2-1.20
	- overloadedarmorbar 1.20.1-1
	- pamhc2crops 1.0.3
	- paraglider 20.1.1
	- patchouli 1.20.1-83-FORGE
	- pigpen 15.0.2
	- pineapple_delight 1.0.7-Fix
	- pipez 1.20.1-1.1.5
	- placebo 8.5.8
	- playeranimator 1.0.2-rc1+1.20
	- polylib 2000.0.3-build.97
	- polymorph 0.49.1+1.20.1
	- potionsmaster 0.6.0
	- powah 5.0.4
	- productivebees 1.20.1-12.2.10
	- puffish_skills 0.10.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.9
	- pylons 4.2.0
	- quarryplus 1201.0.26
	- railways 1.5.3+forge-mc1.20.1
	- rangedpumps 1.1.0
	- refinedcooking 4.0.0
	- refinedstorage 1.12.4
	- refinedstorageaddons 0.10.0
	- reliquary 1.20.1-2.0.36.1199
	- resourcefulconfig 2.1.0
	- resourcefullib 2.1.18
	- rftoolsbase 1.20-5.0.2
	- rftoolsbuilder 1.20-6.0.2
	- rftoolscontrol 1.20-7.0.1
	- rftoolspower 1.20-6.0.1
	- rftoolsstorage 1.20-5.0.1
	- rftoolsutility 1.20-6.0.3
	- rightclickharvest 3.2.3+1.20.1-forge
	- rsinfinitybooster 1.20.1-1.0+32
	- rsrequestify 2.3.3
	- runelic 18.0.2
	- satako 7.0.14-1.20.1
	- scalinghealth 8.0.1+8
	- scuba_gear 1.0.6
	- searchables 1.0.2
	- sebastrnlib 4.0.0
	- sereneseasonfix 1.20.1-1.0.8
	- sereneseasons 9.0.0.46
	- shetiphiancore 1.20.1-1.2
	- shieldexp 1.1.7
	- silentgear 3.5.2
	- silentlib 8.0.0
	- simply_swords_with_epicfight 3.0
	- simplylight 1.20.1-1.4.6-build.50
	- simplyswords 1.51.5-1.20.1
	- smallships 2.0.0-a2.3.3
	- smartbrainlib 1.12
	- solapplepie 1.20.1-2.3.0
	- sophisticatedbackpacks 3.18.68.952
	- sophisticatedcore 0.5.107.496
	- spectrelib 0.13.14+1.20.1
	- storagedrawers 12.0.2
	- structure_gel 2.15.1
	- structurize 1.20.1-1.0.662-BETA
	- stylecolonies 1.2
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.15
	- swplanets 1.1.0
	- tempad 2.1.1
	- terrablender 3.0.0.169
	- terralith 2.4.8
	- tesseract 1.0.35a
	- tiab 4.0.4-mc1.20.1
	- timecontrol 1.4.0
	- titanium 3.8.23
	- tofucraft 1.20.1-5.8.1.1
	- tofudelight 1.20.1-2.4.1
	- tombstone 8.5.5
	- torchmaster 20.1.5
	- towntalk 1.0.0
	- trade_cycling 1.20.1-1.0.7
	- trashcans 1.0.18b
	- trashslot 15.1.0
	- travelersbackpack 9.1.11
	- undergarden 0.8.9
	- useitemonblockevent 1.0.0.2
	- utilitix 1.20.1-0.8.9
	- voicechat 1.20.1-2.4.28
	- waystones 14.0.2
	- weaponmaster 3.0.6
	- well 1.0.0
	- wildfire_gender 1.20.1-3.0.1
	- wirelesschargers 1.0.9
	- wormhole 1.1.15
	- xnet 1.20-6.0.2
	- yungsapi 1.20-Forge-4.0.2
	- zerocore 1.20.1-2.1.40

**Comment by iron431** [comment]
This is an issue with mahoutsukai trying to access item names from the server, where our code assumes you should only be accessing them from the client. We can work on a workaround in our code
