### ISSUE TITLE
[Bug] Propbable incopmpatability with DMCLoot

### ISSUE THREAD

**Issue by mysteryfungus** [iron431/Irons-Spells-n-Spellbooks#228]
### Observed behaviour

I have this mod and DMCLoot on my server. When opening Arcane Anvil UI, server crashes. In logs I see, that error is caused by DMCLoot, that _probably_ tries to add rarity and affixes to something when opening Arcane Anvil UI, ptobably counting anvil as a container

### Expected behaviour

I expected server to not crash

### Steps to reproduce

1. Have Iron's Spells And Spellbooks and DMCLoot on your server
2. Try to use Arcane Anvil

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2-2.1-0

### Forge version

1.19.2-43.3.5

### Other mods

DMCLoot-1.19.2-2.5

**Comment by iron431** [comment]
attach a crashlog, i can try to take a look
