### ISSUE TITLE
[Bug] Picking up spell causes kick from server

### ISSUE THREAD

**Issue by jamesipod** [iron431/Irons-Spells-n-Spellbooks#229]
### Observed behaviour

I threw a spell scroll on the ground. Upon getting near it, I got kicked from my server

### Expected behaviour

I should pick the item up

### Steps to reproduce

1. Throw a level one chain lightning spell on the ground in a server
2. Attempt to pick it up
3. Get kicked for "internal error"

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/jamesipod/9a9e6d3e60ded3dbe717bee5e63ea104

### Iron's Spells N Spellbooks version

1.20.1-2.1.0

### Forge version

1.20.1 47.2.16

**Comment by iron431** [comment]
update the mod
