### ISSUE TITLE
Crash when hover mouse over scrolls

### ISSUE THREAD

**Issue by Trepppy** [iron431/Irons-Spells-n-Spellbooks#23]
### Observed behaviour

at first like on my previous issue I thought it was crashing from being in the compass menu but ever after the latest update what actually is causing it to crash is hovering over the scrolls anywhere, I found the structure and hovering over the scroll inside the loot barrel crashed the game, tryed it again on another world same thing

### Expected behaviour

not crash

### Steps to reproduce

just hover the mouse over one of the scrolls

### Server Type

Single Player

### Crashlog

https://gist.github.com/Trepppy/a8360853d719102a2a6adbb34e884f40

### Iron's Spells N Spellbooks version

1.0.7

### Forge version

1.19.2 43.2.10

### Other mods

player-animation-lib-forge-1.0.2.jar
Architects-Palette-1.19.2-1.3.2.jar
RoughlyEnoughItems-9.1.595.jar
caelus-forge-1.19.2-3.0.0.6.jar
curios-forge-1.19.2-5.1.4.1.jar
flywheel-forge-1.19.2-0.6.8.a-14.jar
create-1.19.2-0.5.0.i.jar
createdeco-1.3.2-1.19.2.jar
REIPluginCompatibilities-forge-9.0.48.jar
irons_spellbooks-1.0.7.jar
extendedgears-2.0.2-1.19.2-0.5.0.iforge-1.19.2.jar
create_dragon_lib-1.19.2-1.1.2.jar
architectury-6.5.82-forge.jar
create_crystal_clear-0.1.2e-1.19.2.jar
blueprint-1.19.2-6.1.2.jar
clayworks-1.19.2-2.0.1.jar
cloth-config-8.2.88-forge.jar
bettercombat-forge-1.7.0+1.19.jar
combatroll-forge-1.1.5+1.19.jar
forge-1.19.2-43.2.10-universal.jar
valhelsia_core-forge-1.19.2-0.5.0.jar
forbidden_arcanus-1.19.2-2.1.3.jar
geckolib-forge-1.19-3.1.40.jar
create_enchantment_industry-1.19.2-for-create-0.5.
createaddition-1.19.2-20230426a.jar

**Comment by iron431** [comment]
A hotfix is uploading to curseforge that should be the final nail in the coffin for all this REI stuff. Please reply once you get the update and see if it works.

**Comment by Trepppy** [comment]
@iron431  hovered over a few of them and it was fine until it was over a blood slash scroll then it crashed again. Sorry if I'm causing annoyance for you guys with this REI stuff
https://gist.github.com/Trepppy/901f58d7e0b4ac2bc1059a0e07c7a77f

**Comment by lab3** [comment]
@Trepppy It's no problem. We appreciate you working through this with us. We will get it sorted out.
