### ISSUE TITLE
[Bug] [1.19.2-2.1-0] when necromancer summoned zombie to be hurt ,game going crash

### ISSUE THREAD

**Issue by Lanzr64** [iron431/Irons-Spells-n-Spellbooks#232]
### Observed behaviour

necromancer summoned zombie to be hurt

### Expected behaviour

game still run and zombie lose hp

### Steps to reproduce

1.Fighting against many mobs, including necromancers and Summoned zombies
2. in sometime， game crash

### Server Type

Single Player

### Crashlog

https://gist.github.com/Lanzr64/c36a2d73b4173f1fa3f9bf2cfb5e74c4

### Iron's Spells N Spellbooks version

1.19.2-2.1-0

### Forge version

1.19.2-43.3.0

### Other mods

AE2-Things-1.1.1.jar
AE2WTLib-12.9.7.jar
alexsmobs-1.21.1.jar
appliedenergistics2-forge-12.9.8.jar
architectury-6.5.85-forge.jar
Argentina's Delight 1.19.2 (ver1.21).jar
ars_creo-1.19.2-3.2.1.jar
ars_nouveau-1.19.2-3.21.4.jar
AutoRegLib-1.8.2-55.jar
balm-forge-1.19.2-4.6.0.jar
bettercombat-forge-1.7.1+1.19.jar
buildinggadgets-3.16.2-build.22+mc1.19.2.jar
caelus-forge-1.19.2-3.0.0.6.jar
castle_in_the_sky-1.19.2-0.5.2.jar
cc-tweaked-1.19.2-1.101.3.jar
cccbridge-mc1.19.2-forge-v1.5.1.jar
citadel-2.1.4-1.19.jar
cloth-config-8.3.103-forge.jar
cookingforblockheads-forge-1.19.2-13.3.3.jar
create-1.19.2-0.5.1.f.jar
create-confectionery1.19.2_v1.0.9.jar
createaddition-1.19.2-1.2.0.jar
create_enchantment_industry-1.19.2-for-create-0.5.1.f-1.2.7.d.jar
create_misc_and_things_ 1.19.2_4.0A.jar
create_sabers-1.19.2-1.3.0.jar
curios-forge-1.19.2-5.1.4.3.jar
CustomSkinLoader_ForgeActive-14.18.1.jar
DungeonsArise-1.19.2-2.1.54-release.jar
endsdelight-1.19.2-1.2.1.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
FarmersDelight-1.19.2-1.2.3.jar
farmingforblockheads-forge-1.19.2-11.3.5.jar
ftb-chunks-forge-1902.4.1-build.290.jar
ftb-chunks-forge-1902.4.2-build.302.jar
ftb-library-forge-1902.4.1-build.236.jar
ftb-teams-forge-1902.2.14-build.123.jar
ftb-ultimine-forge-1902.4.1-build.90.jar
geckolib-forge-1.19-3.1.40.jar
hexal-forge-1.19.2-0.2.18.jar
hexcasting-forge-1.19.2-0.10.3.jar
hexgloop-1.19.2-0.1.1-forge.jar
hextweaks-3.2.3-forge.jar
idas_forge-1.7.6+1.19.2.jar
Incendium_1.19.3_v5.1.6.jar
integrated_api_forge-1.2.7+1.19.2.jar
integrated_stronghold_forge-1.0.2+1.19.2.jar
irons_spellbooks-1.19.2-2.1.0.jar
jei-1.19.2-forge-11.6.0.1018.jar
JustEnoughResources-1.19.2-1.2.3.243.jar
kotlinforforge-3.12.0-all.jar
lootr-1.19-0.4.24.64.jar
L_Enders_Cataclysm-1.38 -1.19.2.jar
mcjtylib-1.19-7.2.5.jar
mediaworks-forge-1.19.2-1.0.4.jar
megacells-forge-2.0.4-1.19.2.jar
Mekanism-1.19.2-10.3.9.13.jar
MekanismGenerators-1.19.2-10.3.9.13.jar
miners_delight-1.19.2-1.1.2.jar
modlist.txt
modonomicon-1.19.2-1.34.0.jar
moonlight-1.19.2-2.3.5-forge.jar
moreiotas-forge-1.19.2-0.0.4.jar
MorePeripherals_1.19.2-1.8.8.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
NethersDelight-1.19-3.1.jar
observable-3.3.1.jar
occultism-1.19.2-1.88.0.jar
oceansdelight-1.0.2-1.19.2.jar
PackMenu-1.19.2-5.1.0.jar
Patchouli-1.19.2-77.jar
paucal-forge-1.19.2-0.5.0.jar
Placebo-1.19.2-7.3.4.jar
player-animation-lib-forge-1.0.2.jar
Quark-3.4-418.jar
relics-1.19.2-0.4.7.4.jar
rftoolsbase-1.19-4.1.7.jar
SimpleLogin-1.19.2-1.0.1.jar
SmartBrainLib-forge-1.19.2-1.9.jar
SoL-Carrot-1.19.2-1.14.0.jar
solsweetpotato-1.19.2-2.0.0.jar
sophisticatedbackpacks-1.19.2-3.18.66.951.jar
sophisticatedcore-1.19.2-0.5.105.498.jar
supplementaries-1.19.2-2.4.11.jar
Terralith_1.19.3_v2.3.12.jar
wnboi-0.0.4-forge.jar
xnet-1.19-5.1.4.jar
xnetgases-1.19.2-4.0.1.jar
YungsApi-1.19.2-Forge-3.8.10.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterEndIsland-1.19.2-Forge-1.0.jar
YungsBetterJungleTemples-1.19.2-Forge-1.0.1.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.1.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.1.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
YungsBridges-1.19.2-Forge-3.1.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar
[Xaero的世界地图] XaerosWorldMap_1.36.0_Forge_1.19.1.jar
[Xaero的小地图] Xaeros_Minimap_23.8.4_Forge_1.19.1.jar
[奇异饰品] artifacts-1.19.2-5.0.4.jar
[时装盔甲重置版] CosmeticArmorReworked-1.19.2-v1a.jar
[玉 ??] Jade-1.19.1-forge-8.9.1.jar
[禁用聊天举报] NoChatReports-FORGE-1.19.2-v1.5.1.jar
[聊天头像] chat_heads-0.10.25-forge-1.19.2.jar
[自动汉化更新] I18nUpdateMod-3.5.2-all.jar
[跑酷！] ParCool-1.19.2-3.1.0.4-R.jar
[铷 · 扩展] rubidium-extra-0.4.19+mc1.19.2-build.105.jar
[铷] rubidium-mc1.19.2-0.6.2c.jar
[键位冲突显示] Controlling-forge-1.19.2-10.0+7.jar
[镁／铷：动态光源] dynamiclightsreforged-1.19.2_v1.4.0.jar
[鼠标手势] MouseTweaks-forge-mc1.19-2.23.jar

**Comment by Sergegrom** [comment]
Same problem but on server...
