### ISSUE TITLE
Mahou Tsukai Projectors[Bug] 

### ISSUE THREAD

**Issue by yutoe** [iron431/Irons-Spells-n-Spellbooks#233]
### Observed behaviour

Using the Mahoujin Projectors from Mahou Tsukai on my armor. When i cast a spell the animation for the spell makes them visable in first person

Before casting a spell
![2023-12-03_02 42 26](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/1342774/43987036-5d98-4b3d-a36f-f3f41944598c)

After casting a spell
![2023-12-03_02 42 13](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/1342774/fd821011-946a-4dc9-ba45-caf915e548ea)

What my character looks like in third person
![2023-12-03_02 40 09](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/1342774/c6794ea1-2a12-4e02-b59f-4cde7210189c)

### Expected behaviour

Usually you shouldn't be able to see the projectors on the armor in first person, its only when doing a spell casting animation

### Steps to reproduce

1. While having the projectors on your armor, cast any spell

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-2.0.3.jar

### Forge version

Forge - 47.2.0

### Other mods

Playing on ATM 9 0.2.23.

Side note, not sure if i should post a bug report on Mahou Tsukai too

**Comment by iron431** [comment]
this is because you have playeranimator's third person model showing while you animate. you can turn it off in client config
