### ISSUE TITLE
[Bug] Abyssal shroud marked as "Ender" instead of "Eldritch"

### ISSUE THREAD

**Issue by Molioron** [iron431/Irons-Spells-n-Spellbooks#234]
### Observed behaviour

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/53093045/2c7cac9f-045b-4470-92e4-b0d994a29d08)
The Abyssal Shroud spell is categorized as an Ender spell rather than an Eldritch spell.

### Expected behaviour

The spell should be categorized as an Eldritch spell.

### Steps to reproduce

1. create a new world (superflat in my case)
2. unlock spell with manuscript
3. look at the spell's scroll

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.1.1

### Forge version

47.2.6

**Comment by iron431** [comment]
Reset your config
