### ISSUE TITLE
[Bug] Crashing upon Necromancer start casting

### ISSUE THREAD

**Issue by TashiroHawaki** [iron431/Irons-Spells-n-Spellbooks#236]
### Observed behaviour

Hello, I've been testing and my minecraft crash upon the necromancer start casting a spell, here is the log of the crash
"java.lang.NullPointerException: Cannot read field "f_267362_" because "entity" is null"

This is a variant of this crash:
"java.lang.NullPointerException: Cannot read field "f_19797_" because "entity" is null"

[crash-2023-12-05_02.03.19-client.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/13555860/crash-2023-12-05_02.03.19-client.txt)

### Expected behaviour

idk what to put here im sorry.

### Steps to reproduce

Summon a Necromancer
:D

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

47.2.16

### Other mods

Suspected Mods: 
	Iron's Spells 'n Spellbooks (irons_spellbooks), Version: 1.20.1-2.0.3
		Issue tracker URL: https://github.com/iron431/Irons-Spells-n-Spellbooks/issues
		at TRANSFORMER/irons_spellbooks@1.20.1-2.0.3/io.redspace.ironsspellbooks.entity.mobs.raise_dead_summons.SummonedZombieMultiRenderer.render(SummonedZombieMultiRenderer.java:30)

	GeckoLib 4 (geckolib), Version: 4.3
		Issue tracker URL: https://github.com/bernie-g/geckolib/issues
		at TRANSFORMER/geckolib@4.3/software.bernie.geckolib.renderer.layer.ItemArmorGeoLayer.getModelForItem(ItemArmorGeoLayer.java:205)

	Alex's Mobs (alexsmobs), Version: 1.22.6
		Issue tracker URL: https://github.com/Alex-the-666/AlexsMobs/issues
		at TRANSFORMER/alexsmobs@1.22.6/com.github.alexthe666.alexsmobs.client.model.layered.ModelFrontierCap.withAnimations(ModelFrontierCap.java:38)

**Comment by iron431** [comment]
> at com.github.alexthe666.alexsmobs.client.render.item.CustomArmorRenderProperties.getHumanoidArmorModel(CustomArmorRenderProperties.java:64)

This is an issue with Alex's mobs
