### ISSUE TITLE
[Bug] Arcane Debris on 1.18.2

### ISSUE THREAD

**Issue by DariusZeBaguette** [iron431/Irons-Spells-n-Spellbooks#237]
### Observed behaviour

i cant find any arcane debris in my 1.18 latest version iron's spellbook world

### Expected behaviour

there should be arcane debris in the overworld below y:-38, but i scanned hundred of chunks and thousands of blocks with worldedit (//replace irons_spellbooks:arcane_debris air) and cant find any

### Steps to reproduce

go in the latest version of iron's spellbooks in 1.18. and search up for arcane debris

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.3

### Forge version

1.18 - 40.2.10

### Other mods

im playing on a modpack with almost 150 mods, but the only ones that change generations are the latest 1.18 versions of:
create, expanded caves, immersive weathering, quark, tectonic

**Comment by iron431** [comment]
fixed in 1.1.4.4
