### ISSUE TITLE
make it possible to config the gen rate of every strucutre in the mod

### ISSUE THREAD

**Issue by immood** [iron431/Irons-Spells-n-Spellbooks#238]
### Feature description

There is no easy way to change the spawn rate of the structures of the mod, so making this possible would help when dealing with too many of the same structure in a modpack with other 100 structure mods.

### How it improves the player experience

This config would make it possible for the player to easily change the gen rate of the exxagerated amount of structures such as the Mountain Tower and the Evoker Fort.

**Comment by iron431** [comment]
we are not interested in spending time on this feature due to ease of using a datapack to change structure spawn rates
