### ISSUE TITLE
[Bug] /kill dead king corpse crashes the game

### ISSUE THREAD

**Issue by DariusZeBaguette** [iron431/Irons-Spells-n-Spellbooks#239]
### Observed behaviour

when you execute the command /kill @e[type:irons_spellbooks:dead_king_corpse] the game crashes entierly, it can be annoying for people who wants to get rid of the corpse

### Expected behaviour

the corpse should just dissapear

### Steps to reproduce

1. get near the catacombs
2. execute /kill @e[type:irons_spellbooks:dead_king_corpse]
3. Enjoy

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/DariusZeBaguette/c7e01f728b830e49ab87a6ddaaadba72

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.3

### Forge version

1.18 - 40.2.10

**Comment by iron431** [comment]
@lab3 does this affect other versions too?

**Comment by lab3** [comment]
@iron431 Yes, Although it doesn't crash the game in 1.19 but `/kill @e[type=irons_spellbooks:dead_king_corpse]` doesn't actually remove the corpse.

**Comment by lab3** [comment]
I also made the change in curio-casting branches for 1.19 and 1.20

**Comment by iron431** [comment]
fixed in 1.1.4.4
