### ISSUE TITLE
[Bug] The Void Tentacles spell is invisible with Shaders (Oculus) 

### ISSUE THREAD

**Issue by SelnerenX** [iron431/Irons-Spells-n-Spellbooks#24]
### Observed behaviour

Just tested out a moment ago and found out that with shaders (while using oculus), the void tentacles doesn't show. You can still get damage and felt the tentacles are there but you don't see it. Only thing that you can see is the purple mist. 

### Expected behaviour

I expect to see the void tentacles. When the shader is off, I can see it's glorious form. Turning on shader just make it invisible. 

### Steps to reproduce

1. Cast the Void Tentacles spell
2. Turn on shader (While using Oculus) 
3. Observe

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.0.8

### Forge version

1.19.2 - 43.2.8

### Other mods

Oculus and Rubidium

**Comment by iron431** [comment]
fixed in 1.1.1
