### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Jawsching** [iron431/Irons-Spells-n-Spellbooks#240]
### Observed behaviour

When a player finds a structure from the Iron's mod (Happened near a Mountain Tower) as soon they're near the structure or attempt to enter it results into a crash

### Expected behaviour

Expect to enter the structure without any hassle 

### Steps to reproduce

1. Find an Iron's structure
2. Be in its proximity
3. Wait for a bit
4. Crash

### Server Type

Dedicated Server

### Crashlog

The game crashed whilst encountered exception while building chunk meshes Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.texture.TextureAtlasSprite.m118367(double)" because "sprite" is null

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

47.2.0

### Other mods

[Alex's Caves (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-caves)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Fusion (Connected Textures) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
[Create Confectionery (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-confectionery)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Create Big Cannons (by rbasamoyai)](https://www.curseforge.com/minecraft/mc-mods/create-big-cannons)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
[Sildur's Vibrant shaders (by SildurFX)](https://www.curseforge.com/minecraft/shaders/sildurs-vibrant-shaders)
[Just Enough Professions (JEP) (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/just-enough-professions-jep)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Connected Glass (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/connected-glass)
[Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Pig Pen Cipher (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/pig-pen-cipher)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Torchmaster (by xalcon)](https://www.curseforge.com/minecraft/mc-mods/torchmaster)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Easy Villagers (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/easy-villagers)
[Relics (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/relics-mod)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[Runelic (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/runelic)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Iron Ender Chests (by lupiiin_)](https://www.curseforge.com/minecraft/mc-mods/iron-ender-chests)
[Structory (by botanydev)](https://www.curseforge.com/minecraft/mc-mods/structory)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Silent Lib (silentlib) (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)
[Iron Jetpacks (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/iron-jetpacks)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[MrCrayfish's Furniture Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Iron Chests: Restocked (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/ironchests)
[Silent's Gems (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silents-gems)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Create Compact Exp (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-compact-exp)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Mod Name Tooltip (by mezz)](https://www.curseforge.com/minecraft/mc-mods/mod-name-tooltip)
[OpenBlocks Elevator (by vsngarcia)](https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Stay True (by haimcyfly)](https://www.curseforge.com/minecraft/texture-packs/stay-true)
[More Dragon Eggs (by Darkere)](https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[Corail Tombstone (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-tombstone)
[Dark Utilities (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/dark-utilities)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Mandala's GUI - Dark mode (by cesar_zorak)](https://www.curseforge.com/minecraft/texture-packs/mandalas-gui-dark-mode)
[Iron Furnaces [FORGE] (by XenoMustache)](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces)
[Simple Storage Network (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/simple-storage-network)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Cucumber Library (by BlakeBr0)](https://www.curseforge.com/minecraft/mc-mods/cucumber)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[Complementary Shaders - Reimagined (by EminGTR)](https://www.curseforge.com/minecraft/shaders/complementary-reimagined)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Create Chunkloading (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/create-chunkloading)
[FLIB (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/flib)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[OctoLib (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/octo-lib)
[Silent Gear (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-gear)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[FTB Ultimine (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-ultimine-forge)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Mob Grinding Utils (by vadis365)](https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils)
[Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
[Create: Diesel Generators (by george8188262)](https://www.curseforge.com/minecraft/mc-mods/create-diesel-generators)
[xali's Enchanted Books (by xalixilax)](https://www.curseforge.com/minecraft/texture-packs/xalis-enchanted-books)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)

**Comment by iron431** [comment]
attach a crashlog

**Comment by lab3** [comment]
How did you come to the conclusion that this is related to ISS?

**Comment by iron431** [comment]
@Jawsching
