### ISSUE TITLE
[Bug] [ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag irons_spellbooks:antiquated_compass_locator as it is missing following references: irons_spellbooks:citadel (from irons_spellbooks-1.20.1-2.1.1.jar)

### ISSUE THREAD

**Issue by MrLoLf** [iron431/Irons-Spells-n-Spellbooks#242]
### Observed behaviour

I get this on startup of my server 
```
ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag irons_spellbooks:antiquated_compass_locator as it is missing following references: irons_spellbooks:citadel (from irons_spellbooks-1.20.1-2.1.1.jar)
```
you can see it in my 
[debug.log](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/13636421/debug.log)

### Expected behaviour

No Error of this in my debug log

### Steps to reproduce

1. Start a dedicated atm9-0.2.28 Server
2. Look in the debug log

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-2.1.1

### Forge version

1.20.1 - 47.2.16

### Other mods

atm9 modpack on version 0.2.28

**Comment by Qruim** [comment]
+1

MC version 1.21.1
Forge version 47.2.19
Iron's Spells N Spellbooks version 1.20.1-2.2.1

here is my logs
[debug.log](https://github.com/iron431/irons-spells-n-spellbooks/files/13968893/debug.log)

here is my modlist 
[modlis.txt](https://github.com/iron431/irons-spells-n-spellbooks/files/13969000/modlis.txt)

**Comment by iron431** [comment]
that tag is not used in the game, this doesnt affect anything. we'll delete the file though
