### ISSUE TITLE
[Bug] Spell hotbar doesn't render icons with ImmediatelyFast

### ISSUE THREAD

**Issue by BookerCatch** [iron431/Irons-Spells-n-Spellbooks#244]
### Observed behaviour

The spell hotbar does not render spell icons if the mod ImmediatelyFast is loaded.

### Expected behaviour

The spell hotbar renders spell icons when the appropriate spell book item is held.

### Steps to reproduce

1. Install Iron's Spells 'n Spellbooks and dependencies
2. Install ImmediatelyFast
3. Launch game and hold spell book with spells inscribed

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.1.2

### Forge version

1.20.1 - 47.2.17

### Other mods

ImmediatelyFast

**Comment by pvzfan1** [comment]
its a bug on immediatelyfast's end, its being fixed soon iirc

**Comment by iron431** [comment]
closing for duplicate of #231
