### ISSUE TITLE
[Bug] When used with OptiFine, the armor texture is broken

### ISSUE THREAD

**Issue by Chymistries** [iron431/Irons-Spells-n-Spellbooks#245]
### Observed behaviour

![2023-12-15_21 33 37](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/153918739/56f9dacc-14f6-4da4-82d2-09aad7182dcf)
![2023-12-15_21 35 35](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/153918739/59ec5241-82aa-4026-9851-612e57266fa4)

I've seen others use Iron's Spells 'n Spellbooks mode while using the shader but when I did it, it changed like this

### Expected behaviour

I expected the shader to be applied without breaking the texture

### Steps to reproduce

I using forge-1.20.1-47.2.0-installer.jar and preview_OptiFine_1.20.1_HD_U_I6_pre5.jar or pre6.jar
If left OptiFine, texture returns to normal

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 2.0.2, 1.20.1 - 2.1.2 

### Forge version

1.20.1- 47.2.0

### Other mods

![1](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/153918739/937dcf67-2a61-4d4d-bc2e-156e74372d23)
![2](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/153918739/285f4d22-8722-489a-9009-20a87379d8f0)

**Comment by kaairu** [comment]
this is an optifine issue not irons spells. remove optifine and use oculus

**Comment by iron431** [comment]
>Q: My Models are are broken/won’t render
A:  If you have Optifine, it’s that. Optifine is meant for vanilla clients. Use the many alternatives (such as Oculus) that work with forge
