### ISSUE TITLE
Armor Render Fix for EFM

### ISSUE THREAD

**Issue by tablenitro** [iron431/Irons-Spells-n-Spellbooks#248]
### Observed behaviour

Long story short, going into battle mod with epic fight mod breaks the armors.
Some armors work with the help of the mod "EFM Render Fix" like shadow walker and pyromancer armor but the other ones break, do me a favor pls fix the rendering.
I tried fixing it with datapacks but its impossible. I dont ask to put compatibility with epic fight mod, i am just asking for render fixes so it wont break.
Currently am looking for mods that can fix this, if you have any idea of mods that fix rendering pls give me some to test out.
Thanks

### Expected behaviour

Help ;-;

### Steps to reproduce

1. I dunno your the boss

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 2.1.0

### Forge version

47.2.17

### Other mods

Epic Fight Mod and other mods that dont play role except maybe oculus and embedium

**Comment by iron431** [comment]
> I dont ask to put compatibility with epic fight mod, i am just asking for render fixes so it wont break.

you should explain or screenshot what is actually broken

**Comment by CyaniideDrive** [comment]
Epic Fight uses a smooth player model for it's animations, so any armor that strays from vanilla "extra skin layer" style armor usually breaks, so pretty much every armor set would need unique models for Epic Fight.

**Comment by CyaniideDrive** [comment]
As a temporary "fix" it may be best for you to install cosmetic armor and use a supported armor set or just hide your armor till support is added, if it even is added.

**Comment by tablenitro** [comment]
> As a temporary "fix" it may be best for you to install cosmetic armor and use a supported armor set or just hide your armor till support is added, if it even is added.

Is there any texture packs for irons spellbooks that i could use?
