### ISSUE TITLE
[Bug] Spell UI not working correctly (no performance mods ?)

### ISSUE THREAD

**Issue by stevesalko** [iron431/Irons-Spells-n-Spellbooks#249]
### Observed behaviour

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/64847428/33171e6c-13a5-44b3-86de-a923fadf9356)
there is only the selected spell visible and when it is on cooldown it is white not transparent

### Expected behaviour

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/64847428/6abdeca0-36fa-4281-9f00-9224ad3169ea)
it should look like this with all the spells shown

### Steps to reproduce

This has happened randomly, I am not sure why it happened. It just randomly did, at first I thought it could be iris shaders, but when I removed it, nothing changed. 

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.0.3

### Forge version

47.2.5

### Other mods

alexsmobs-1.22.6
allomancy-4.6.6
Apotheosis-1.20.1-7.1.0
ApothicAttributes-1.20.1-1.2.0
appleskin-forge-mc1.20.1-2.5.1
aquacombat 1.1
aquamirae-6.API15
architectury-9.1.12-forge
ars_nouveau-1.20.1-4.7.4-all
ars_ocultas-1.20.1-1.1.0-all
AttributeFix-Forge-1.20.1-21.0.3
auudio_forge_1.0.3_MC_1.19.3
balm-forge-1.20.1-7.1.4
bettercombat-forge-1.8.1+1.20.1
BetterThirdPerson-Forge-1.20-1.9.0
BHMenu-Forge-1.20.1-2.4.1
blockui-1.20.1-1.0.125-BETA
brutalbosses-1.20.1-6.6
caelus-forge-3.1.0+1.20
cataclysmiccombat 1.1
cave_dweller-1.20.1-1.6.5
citadel-2.4.9-1.20.1
cloth-config-11.1.106-forge
collective-1.20.1-7.7
combatroll-forge-1.3.0+1.20.1
comforts-forge-6.3.4+1.20.1
Controlling-forge-1.20.1-12.0.2
CorgiLib-forge-1.20.1-4.0.0.4
cosmeticarmorreworked-1.20.1-v1a
CraterLib-forge-1.20-1.0.2
create-1.20.1-0.5.1.f
CreativeCore_FORGE_v2.11.10_mc1.20.1
cupboard-1.20.1-2.1
curios-forge-5.4.2+1.20.1
CyclopsCore-1.20.1-1.18.13
deeperdarker-forge-1.20.1-1.2.1
Divine_Weaponry_v1.7_1.20.1
domum_ornamentum-1.20-1.0.147-BETA-universal
dragonmounts-1.20.1-1.1.5.b3
dungeons-and-taverns-3.0.3 [Forge]
DungeonsArise-1.20.1-2.1.57-release
dungeons_enhanced-1.20.1-5.2.1
embeddium-0.2.13+mc1.20.1
EnchantingInfuser-v8.0.2-1.20.1-Forge
EnhancedVisuals_FORGE_v1.6.9_mc1.20.1
Enhanced_Celestials-forge-1.20.1-5.0.0.2
EvilCraft-1.20.1-1.2.33
ExplorersCompass-1.20.1-1.3.3-forge
explorify-v1.3.0-mc1.20
EyesInTheDarkness-1.20.1-1.3.10
Fallingleaves-1.20.1-2.1.0
fancymenu_forge_2.14.9-3_MC_1.20.1
FastWorkbench-1.20.1-8.0.2
Female-Gender-Mod-forge-1.20.1-3.0.1
ferritecore-6.0.1-forge
filenames.txt
fm_audio_extension_forge_1.1.1_MC_1.20
framework-forge-1.20.1-0.6.16
ftb-chunks-forge-2001.2.3
ftb-library-forge-2001.1.4
ftb-quests-forge-2001.2.0
ftb-teams-forge-2001.1.4
ftb-xmod-compat-forge-2.0.1
geckolib-forge-1.20.1-4.2.4
goblintraders-forge-1.20.1-1.9.3
HammerLib-1.20.1-20.1.24
handcrafted-forge-1.20.1-3.0.5
harderspawners-1.20-46.25.1
heracles-forge-1.20.1-1.1.4
ImprovableSkills-1.20.1-20.1.6
infernalmobs-1.20.1.1
iris-mc1.20.1-1.6.9
irons_spellbooks-1.20.1-2.0.3
item-filters-forge-2001.1.0-build.59
Jade-1.20.1-forge-11.6.3
jei-1.20.1-forge-15.2.0.27
JustEnoughResources-1.20.1-1.4.0.238
konkrete_forge_1.6.1-2_MC_1.20
L_Enders_Cataclysm-1.39 -1.20.1
majrusz-library-1.20.1-5.1.2
majruszs-difficulty-1.20.1-1.8.1
MaxHealthFix-Forge-1.20.1-12.0.2
medieval_paintings-1.20-7.0
minecolonies-1.20.1-1.1.321-BETA
modonomicon-1.20.1-forge-1.40.0
MouseTweaks-forge-mc1.20-2.25
multipiston-1.20-1.2.31-ALPHA
MutantMonsters-v8.0.4-1.20.1-Forge
NaturesCompass-1.20.1-1.11.2-forge
neruina-1.3.0-forge+1.18.2-1.20.1
obscure_api-15
occultism-1.20.1-1.90.0
Patchouli-1.20.1-81-FORGE
Placebo-1.20.1-8.5.8
player-animation-lib-forge-1.0.2-rc1+1.20
polymorph-forge-0.49.1+1.20.1
primalmagick-4.0.8
PuzzlesLib-v8.1.9-1.20.1-Forge
resourcefullib-forge-1.20.1-2.1.16
Searchables-forge-1.20.1-1.0.2
SmartBrainLib-forge-1.20.1-1.12
sophisticatedbackpacks-1.20.1-3.18.68.952
sophisticatedcore-1.20.1-0.5.107.496
soundphysics-forge-1.20.1-1.2.1
structureessentials-1.20.1-3.2
structure_gel-1.20.1-2.15.0
structurize-1.20.1-1.0.662-BETA
theurgy-1.20.1-1.7.1
tombstone-8.5.5-1.20.1
towntalk-1.20.1-1.0.0
treeharvester-1.20.1-8.3
twilightforest-1.20.1-4.3.1893-universal
Vampirism-1.20.1-1.9.3
vampirism_integrations-1.20.1-1.8.0-beta.1
voicechat-forge-1.20.1-2.4.28
waystones-forge-1.20-14.0.2
Werewolves-1.20.1-1.1.0.3
XaerosWorldMap_1.36.0_Forge_1.20
Xaeros_Minimap_23.8.4_Forge_1.20
zmedievalmusic-1.20.1-2.1

**Comment by MarioSMB** [comment]
This is an incompatibility with Vampirism - if you're playing as a vampire or hunter the GUI elements for spellbooks will be broken as shown.

**Comment by Scurv-a** [comment]
> This is an incompatibility with Vampirism - if you're playing as a vampire or hunter the GUI elements for spellbooks will be broken as shown.

Is there any known fix to this issue as im getting the same thing and any possible config patch would be nice

**Comment by MarioSMB** [comment]
I get that managing an issue tracker is time-consuming, but bots that automatically close valid issues generally do more harm than good.  

This issue could be indicative of poor handling of GUIs and would be worth investigating - especially since it impedes one's ability to play with the aforementioned mod.
