### ISSUE TITLE
[Bug] The Void Tentacles is Pink when using shaders with Optifine

### ISSUE THREAD

**Issue by SelnerenX** [iron431/Irons-Spells-n-Spellbooks#25]
### Observed behaviour

The Void tentacles is pink color with no textures when using shader with Optifine. It show with the miss and physical form but without the color or textures except for being pink

### Expected behaviour

Seeing the Void Tentacles in it's full glorious form. 

### Steps to reproduce

1. Use Optifine and select a shader. 
2. Cast The Void Tentacles
3. Observe

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.0.8

### Forge version

1.19.2 - 43.2.8

### Other mods

Optifine

**Comment by iron431** [comment]
can you test if this still happens with the new textures in v1.1.1?
