### ISSUE TITLE
[Bug] Tetra max mana benefit not stacking between offhand/mainhand

### ISSUE THREAD

**Issue by haltalt** [iron431/Irons-Spells-n-Spellbooks#252]
### Observed behaviour

Perhaps this isn't a bug, but a balancing decision - close this issue.
Tetra swords and shields using arcane metal give the benefit of more max mana. This doesn't seem to stack properly.

### Expected behaviour

I don't know if this is meant to be a balancing decision or not, but I thought those would stack. Using /attribute get confirms that the attribute of max mana is not stacking.

### Steps to reproduce

1. Install tetra, version 6.1.0.
2. Get yourself a shield and a sword. Modify both using tetra to have parts out of arcane metal.
3. Hold shield in offhand, blade in main hand.
4. Despite their descriptions saying they add max mana, they don't. In fact, only one bonus applies - the one of the latest "equipped" piece of gear.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.0.3

### Forge version

1.20.1 - 47.2.1

### Other mods

Tetra 6.1.0. Also other mods which I doubt influence the bug; if I reproduce this without them, I'll update this issue.

**Comment by iron431** [comment]
do modified shields usually have attributes for the offhand? you should attach a screenshot of two modified shields, one with base tetra materials, and one with spells n spellbooks materials

**Comment by haltalt** [comment]
> do modified shields usually have attributes for the offhand? you should attach a screenshot of two modified shields, one with base tetra materials, and one with spells n spellbooks materials

The buckler does in fact provide armour toughness, so there's definitely that. The attributes are both for offhand and mainhand, meaning the alleged bug happens also with two shields in both hands. As said - it seems that whether the mainhand attribute or the offhand one applies is only determined by the last equipped piece of gear.
![obraz](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/91082490/14e12c32-f42d-4b0b-bc7d-240722d72e60)
![obraz](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/91082490/b79cc2b3-5c4d-4d31-b0a3-ad57e435c4a3)
Nonbuckler shields also provide attributes relates to the abilities tetra adds.
![obraz](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/91082490/fe5f415e-23b4-4d8b-9353-f79b11c34f43)

**Comment by iron431** [comment]
>  it seems that whether the mainhand attribute or the offhand one applies is only determined by the last equipped piece of gear

That is a result of the two items sharing a UUID for the same attribute. This is an issue with tetra, and will affect all attributes
