### ISSUE TITLE
[Bug] Breake textures with OptiFine HD every UX preX for 1.20.1

### ISSUE THREAD

**Issue by Sk6ll9** [iron431/Irons-Spells-n-Spellbooks#253]
### Observed behaviour

Breake textures with OptiFine HD every UX preX for 1.20.1
![Снимок экрана 2023-12-24 034319](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/154712595/6b8f72a8-8290-49e3-a872-db0b39fb1cb5)

### Expected behaviour

Help to fix this trouble, please :( 

### Steps to reproduce

1. Install version minecraft 1.20.1 forge 47.2.0 with any version Optifine and to see this problem.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 2.1.2 and others

### Forge version

1.20.1 47.2.0

### Other mods

Without mods, only Optifine.

**Comment by iron431** [comment]
Optifine is meant for vanilla clients. Use the many alternatives (such as Oculus) that work with forge

**Comment by Sk6ll9** [comment]
> Optifine предназначен для ванильных клиентов. Используйте множество альтернатив (например, Oculus), которые работают с forge

Oculus crushed my client
