### ISSUE TITLE
Allow polar bear mount to swim

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#254]
### Feature description

Polar bears are amazing swimmers, being able to ride a polar bear across bodies of water without sinking would be a nice way to differentiate it more from the summoned horse mount.

### How it improves the player experience

I'm not sure how best to describe it, but it would be far more intuitive for a water/ice themed mount to be able to swim with the player on it!

**Comment by iron431** [comment]
i believe the polar bear can swim. if he cannot, that is a bug

**Comment by MarioSMB** [comment]
Polar bears cannot swim currently, they just sink to the bottom like a skeleton horse. Would you mind re-opening this issue?

**Comment by MarioSMB** [comment]
They also drown underwater - definitely no good for water traversal.
