### ISSUE TITLE
Reduce fire immunity ring power

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#259]
### Feature description

The ring of fire immunity is currently applying its effect far too broadly, making you immune to any fire-related damage sources.  
This completely trivializes the Nether as it allows you to swim in lava and walk across magma blocks.  

I believe this ring should only make you immune to being on fire, as that would keep it in line with the other rings (poison immunity making you immune to the poisoned status effect for example).

### How it improves the player experience

This change would offer more variation in playstyles, as the fire immunity ring would no longer be ***the*** ring to have above all others, while bringing back some challenge to the Nether.

**Comment by crushthatdwarf** [comment]
Agreeing with @MarioSMB that this ring is a bit out of whack, but the real effect of a straight-up nerf on the current ring would not be to offer more variation in playstyles -- the other playstyles already exist. The fundamental problem is that of the fire ring being too tempting in relation to the alternatives.

From that perspective, I suggest a couple of alternative approaches:

- Adjustable config file allowing different levels of resistance for the various rings -- this would allow players to tune their preferred experience without being strong-armed into a unilateral change.
- Split all protection rings into two tiers, one common form offering simple resistance, and one very rare form offering full immunity -- this would address the noted balance issue mentioned above.

Nerfing the ring as it exists now would be a shame. This would outlaw a currently valid (and very fun) playstyle that emerged as a result of this ring's existence. Building a Nether fortress with flowing lava elevators is a blast -- and for a fire mage, being able to walk across magma without harm seems reasonable, considering that any vanilla player can simply crouch on magma blocks to achieve the same effect.

**Comment by MarioSMB** [comment]
Complete immunity to all fire sources can already be achieved with alchemy (fire resistance potions).  

Not being able to burn would be a very strong effect on its own, anything more is extreme overkill for a ring.

**Comment by iron431** [comment]
I think the power level of this item is fine. As @crushthatdwarf said, it enables a very fun playstyle and significantly supports a pyromantic fantasy, and as @MarioSMB said, this effect is already achievable entirely through vanilla (and many other mods too). Furthermore, as @MarioSMB said, the primary consequence is only in the nether.

It is a powerful item, it is supposed to be. If the other rings aren't as powerful, that's more of an issue with them. If you don't like it,  you can always take it out of the loot pool. For all these reasons, this feature request will not be implemented.

**Comment by MarioSMB** [comment]
Potions are temporary and require brewing, this ring is very easily found and provides infinite immunity to basically every challenge in the Nether.

I'm sorry to hear that it won't be getting rebalanced. One doesn't need to play as a pyromancer for this ring to have a huge impact on gameplay.  
It is not powerful, it is extremely overpowered and I will indeed have to remove it from the loot tables.
