### ISSUE TITLE
After teleporting to another dimension, magic regeneration will immediately stop, regardless of whether it's to dimensions from other mods, the Nether or the End.[Bug] 

### ISSUE THREAD

**Issue by chunye-shanhui** [iron431/Irons-Spells-n-Spellbooks#26]
### Observed behaviour

Currently, regardless of whether it's in single-player or on a server, magic won't recover when teleporting to other dimensions. This has a severe impact as players can only play in the Overworld, and entering other dimensions prevents them from releasing magic (and therefore cannot continue magic recovery).

Oh, by the way, I play solo and also set up a LAN server to play.

### Expected behaviour

0

### Steps to reproduce

0

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.0.8

### Forge version

1.19.2 43.2.0

**Comment by chunye-shanhui** [comment]
This mod conflicts with "Blue Skies", causing magic to not regenerate when traveling to other dimensions.

**Comment by lab3** [comment]
@chunye-shanhui Thanks for the tip. I'll check it out

**Comment by lab3** [comment]
@chunye-shanhui I was able to replicate this with Blue Skies.  Also when Blue skies is installed mana regen in the overworld is happening at an accelerated rate.

**Comment by chunye-shanhui** [comment]
This mod conflicts with "collective", causing magic to not regenerate when traveling to other dimensions.
