### ISSUE TITLE
Metamorphosis Spells 

### ISSUE THREAD

**Issue by FilipKompaniets** [iron431/Irons-Spells-n-Spellbooks#260]
### Feature description

The player can turn himself into any mob and even from other mods for a certain time to disguise himself and receive their abilities; if the player encounters the same type of aggressive mob as the one he turned into, then that mob will be neutral towards him.

### How it improves the player experience

Disguise spells can be quite useful, but I can't describe how yet

**Comment by iron431** [comment]
this manner of spell is worth an entire mod on its own, and will not be worked on
