### ISSUE TITLE
[Bug] Spectral Hammer bypasses FTB Chunks Claims

### ISSUE THREAD

**Issue by RedAngel121** [iron431/Irons-Spells-n-Spellbooks#262]
### Observed behaviour

Spectral Hammer spell bypasses Claim restrictions when using FTB Chunks. I am playing on an ATM9 server hosted on my home PC, I have several friends and we all have claims so we dont accidentally break something while messing with each other. Spectral Hammer completely destroyed my floor and about 5 blocks beneath it, im glad there wasnt anything important under there. 

### Expected behaviour

obviously not bypass claim restrictions lol

### Steps to reproduce

Join an ATM9 public server, 
Find a claim that is not yours
Use the spectral hammer spell 
Observe

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-2.1.2

### Forge version

1.20.1-47.2.16

### Other mods

"Other Mods" > https://www.curseforge.com/minecraft/modpacks/all-the-mods-9

**Comment by iron431** [comment]
fixed in 2.2.2
