### ISSUE TITLE
Too strong arcane debris

### ISSUE THREAD

**Issue by MinecraftModderDailyDoseOfMods** [iron431/Irons-Spells-n-Spellbooks#264]
### Feature description

I just go mine with the alex's caves nuke and for a REASON the arcane debris is resist to 10 nukes explosion and I have to build up to mine them by hand

### How it improves the player experience

Better for players mine with nukes and more convinient.

**Comment by MarioSMB** [comment]
Ancient debris isn't destroyed by nukes either and arcane debris is even stronger. I don't think this is an issue.

**Comment by iron431** [comment]
> Ancient debris isn't destroyed by nukes either and arcane debris is even stronger. I don't think this is an issue.

i agree
