### ISSUE TITLE
Craft common ink with ink sacs and bottles

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#265]
### Feature description

I think it is reasonable to allow combining one ink sac with one bottle to craft a single common ink.  
This would provide an alternative (albeit slow) way to farm ink consistently without going through the lossy process of deconstructing old scrolls:

![common_ink](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/1998392/7f0fda20-268d-4bdf-86eb-47ad9dcb9092)

### How it improves the player experience

The mod's balance would not be upset while providing a more reliable renewable source of ink for spellcrafting. It is also rather intuitive with ink being a vanilla item!

**Comment by MarioSMB** [comment]
As an alternative using the mod's mechanics, perhaps putting an ink sac in an alchemical cauldron of water could create the common ink. I wasn't able to test that approach as it seems the alchemical cauldron isn't data-driven.

**Comment by iron431** [comment]
We're aware that common ink can be scarce and it largely dependent on randomness right now. We don't think recipes are the way to fix that though, as this detracts from the core fantasy of the mod. There are addons that enable this feature if the player is interested, so we have no plans to implement this

**Comment by JThomas7834** [comment]
I've been trying to find the add-ons you mentioned but can't. If you could link them I would appreciate it. I've been struggling to find ink recently as I've depleted most of it within a 1000-block radius of my base. I like exploring but anyway to reliably produce ink would be good.

**Comment by MarioSMB** [comment]
I do hope the ink situation is temporary; vanilla already adds a common ink in the form of Ink Sacs, and the cauldron alchemy thing is rather unintuitive.

Either way, here's one mod that might work (I personally used a data pack to fix this missing recipe):
https://legacy.curseforge.com/minecraft/mc-mods/irons-recipe-additions

**Comment by boywifejames** [comment]
> I do hope the ink situation is temporary; vanilla already adds a common ink in the form of Ink Sacs, and the cauldron alchemy thing is rather unintuitive.
> 
> Either way, here's one mod that might work (I personally used a data pack to fix this missing recipe): https://legacy.curseforge.com/minecraft/mc-mods/irons-recipe-additions

Hii I know this is a really old post but I'm having the same issue where I have the mod isntalled but the recipes are missing. Can you please help me with it? I'm currently playing ATM10 T~T
