### ISSUE TITLE
Remove arcane debris

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#266]
### Feature description

Given one must already have found ancient debris (for the pickaxe) to be able to gather arcane debris, and considering the item is a copy-paste of ancient debris with a single use, I believe it would be more sensible to simply use nether scraps in the recipe for upgrade orbs.

### How it improves the player experience

This would reduce the number of single-use duplicate items while providing another use to a vanilla end-game item serving the same purpose, while reducing the frustration and grindiness of finding these in the overworld and needing to come back with a netherite pickaxe.

**Comment by MarioSMB** [comment]
In my humble opinion I believe it takes away from the depth and quality of the mod to include items like this for the purpose of padding.

**Comment by iron431** [comment]
I agree that arcane debris is not in a good state right now. Originally, it had more uses and we had plans to expand its uses, but those other items ended up being scrapped and we haven't gotten around to the additional ideas yet. I don't think we are going to remove it until we finalize our plans for any future content that would rely on it, as it was supposed to be our post-netherite progression material, but unfortunately that has been limited to upgrade orbs as we've been developing other parts of the mod.

**Comment by MarioSMB** [comment]
That is understandable, and there’s nothing wrong with placeholder items - it’s just a bit of an enigma as a block in the overworld requiring netherite tools to mine.  
Either way I look forward to seeing what uses come for it with a future rework!

**Comment by iron431** [comment]
going to close this issue because its not something we plan on addressing for a while
