### ISSUE TITLE
Remove blaze rods from overworld loot tables

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#267]
### Feature description

Blaze rods act as a progression milestone and the primary reason for players to visit the Nether.  
Adding these to overworld chests (such as the mangrove huts) takes away that need allowing players to reach the End without ever having been to the Nether.

### How it improves the player experience

This would solve some sequence breaking issues and give more incentive to visit the Nether, especially as a fire mage.

**Comment by iron431** [comment]
For as long as the fire focus are blaze rods, this will not be worked on. We have noted that the fire focus may benefit from a rework, but there are no plans to deal with that any time soon

**Comment by MarioSMB** [comment]
I would argue that the fire focus *should* require going to the Nether (i.e. the "fire" dimension). Is there a reason you want to make sure the mod's progression is almost exclusively overworld-based?
