### ISSUE TITLE
More items should be able to be imbued with spells

### ISSUE THREAD

**Issue by Turnoverdisc** [iron431/Irons-Spells-n-Spellbooks#27]
### Feature description

I think all items that have a damage attribute should have the same functionality as swords when it comes to imbuement. If not in the anvil at least with commands.

### How it improves the player experience

This might be useful to modpack developers. Currently, only the vanilla swords are imbueable (that's not a real word). Modded swords and other weapons that modpack developers might want to include in loot tables cannot be imbued with spells.

### Iron's Spells N Spellbooks synergies

This feature can help the mod synergize with other mods, rather than itself.

**Comment by iron431** [comment]
This might be an interesting idea, especially with a similar config-based whitelist, like upgrades.

**Comment by bruglet** [comment]
This doesn't appear to work anymore, item's added to the `imbueWhitelist` still cannot be imbued.

``` 
["Imbue Overrides"]
  #Use these lists to change what items can interact with the Arcane Anvil's imbue system.
  #/!\ Unsupported item types are not guaranteed to work out of the box.
  #Imbue Whitelist. Use an item's id to allow it to be imbued, ex: "minecraft:iron_sword"
  imbueWhitelist = [
    "minecraft:trident",
    "minecraft:wooden_axe",
    "minecraft:stone_axe",
    "minecraft:iron_axe",
    "minecraft:gold_axe",
    "minecraft:diamond_axe",
    "minecraft:netherite:axe"
  ]
  #Imbue Blacklist. Use an item's id to prevent it from being imbued, ex: "minecraft:iron_sword"
  imbueBlacklist = []
```

I did this in the server configuration and it did nothing.

**Comment by iron431** [comment]
make sure you are editing the correct file (the defaultconfig file only affects new worlds, not existing ones), editing the file with the world closed, relaunching the world, and that there are no typos throughout the entire file. i can see one typo where you have "minecraft:netherite:axe"

**Comment by bruglet** [comment]
> make sure you are editing the correct file (the defaultconfig file only affects new worlds, not existing ones), editing the file with the world closed, relaunching the world, and that there are no typos throughout the entire file. i can see one typo where you have "minecraft:netherite:axe"

I have fixed the typo and it still does not appear to work, all other config is left untouched, and this is within the serverconfig of the world.

**Comment by iron431** [comment]
seems to be functioning as intended
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/34083081/35a8e8b7-223a-4f6c-bdec-0868abb71679)
