### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Divineaspect** [iron431/Irons-Spells-n-Spellbooks#271]
### Observed behaviour

Client crash on attempting to cast Blaze Storm 6 via the Blood Staff

### Expected behaviour

to cast blaze storm with a neat animation

### Steps to reproduce

acquire blood staff, use.

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Divineaspect/ea8db7c30c7c5af5b82e5bd9f1692006

### Iron's Spells N Spellbooks version

1.19.2-2.1.2

### Forge version

43.3.5

### Other mods

is in crash report

**Comment by lab3** [comment]
@Divineaspect  This doesn't appear to be related to us.  There are a bunch of mods that have mixed in to ClientLevelMixin. Here are the list.

pehkui.mixins.json:client.ClientWorldMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:accessors.client.multiplayer.ClientLevelAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:client.world.MixinClientLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.block_tint.MixinClientLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinClientLevel,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:blueprint.mixins.json:client.ClientLevelMixin,pl:mixin:A,pl:runtimedistcleaner:A}
