### ISSUE TITLE
[Bug] Spells partially reset when using End portal

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#275]
### Observed behaviour

Upon returning to the overworld via the portal in the End, I lose my Angel Wings buff. Despite visually still having a cooldown the spell can be recasted.

### Expected behaviour

For spell interactions to play nicely with the End portal? I don't know if losing the buff is a vanilla thing or the mod thinking I re-spawned and resetting my spells partially.

### Steps to reproduce

1. Enter the End post-dragon
2. Cast Angel Wings spell
3. Jump into the End portal back to the overworld
4. Try flying and look at the Angel Wings spell in your spellbook

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

2.1.2

### Forge version

47.2.17

**Comment by iron431** [comment]
Have confirmed and fixed the cooldown issue.

Due to how minecraft works, crossing through the final end portal is treated the same as death, and clears all mobeffects, including vanilla ones. Not sure if we should code a special case for our effects, or treat them the same as vanilla's.

**Comment by iron431** [comment]
Going to mark this as fixed for the aforementioned reason. If you think magic effects should persist, you can make a feature request

**Comment by MarioSMB** [comment]
Thanks for the heads up - I wasn't sure if vanilla effects were also cleared, but it's probably best to wait for Mojang to fix that rather than trying to hack around it for spells!
