### ISSUE TITLE
Empty Elixir into Alchemist Cauldron

### ISSUE THREAD

**Issue by 0dad0** [iron431/Irons-Spells-n-Spellbooks#277]
### Observed behaviour

i can't use Elixir on Alchemist Cauldron so can't make greater one. 
![2024-01-05_23 36 36](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/155748881/07f4d264-4be3-49d7-a586-1b0de7798e9a)

### Expected behaviour

using Elixir on Alchemist Cauldron 

### Steps to reproduce

1. use elixir on Alchemist Cauldron
2. it's not work and only drink

### Server Type

Single Player

### Iron's Spells N Spellbooks version

forge

### Forge version

1.20.1-2.2.0

### Other mods

no mod
![2024-01-05_23 49 37](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/155748881/0c6b8619-14eb-41d2-b9ef-440aeef6dcc7)

**Comment by 0dad0** [comment]
![2024-01-06_00 12 11](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/155748881/8382df56-806b-4f17-96f5-107c11eee276)
![2024-01-06_00 12 14](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/155748881/ed064614-b909-4c01-9e4c-55a8e397c179)
![2024-01-06_00 12 19](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/155748881/eb39dfbc-5185-4b9c-8548-ebbd5d4aacf5)
![2024-01-06_00 12 31](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/155748881/73c78380-5638-4235-8703-5ac1dfa5b65b)
 
all of them not work

**Comment by iron431** [comment]
changed to a feature request because this is intentional

**Comment by Szmaka** [comment]
> changed to a feature request because this is intentional

What do you mean intentional? How else are we supposed to make the potions higher level?

**Comment by iron431** [comment]
implemented in 3.4.0
