### ISSUE TITLE
Earthquake's moving blocks can be affected by Blackhole 

### ISSUE THREAD

**Issue by pvzfan1** [iron431/Irons-Spells-n-Spellbooks#281]
### Observed behaviour

earthquake's moving block effect can be sucked into the blackhole spell

### Expected behaviour

earthquake's effects usually cant be moved by anything

### Steps to reproduce

use earthquake near an active blackhole, or use one after the other

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 2.2.0

### Forge version

1.20.1 - 47.2.0

**Comment by iron431** [comment]
its intentional for black hole to affect non-living entities, such as projectiles, tnt, or falling blocks
