### ISSUE TITLE
[Bug] Cows travelers backpack breaks all spell effects

### ISSUE THREAD

**Issue by Alexsmobsenyojer** [iron431/Irons-Spells-n-Spellbooks#283]
### Observed behaviour

When casting spells it makes broken potion sound and doesn't apply any effects. Summoning works but it still makes the sound.

### Expected behaviour

It should eliminate only negative effects.

### Steps to reproduce

1. Equip cows traveler backpack 2. Cast spell

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.2.0

### Forge version

1.20.1-47.2.17

### Other mods

Travelers Backpack

**Comment by iron431** [comment]
I'm not familiar with this mods mechanics. Explain what is happening in greater detail, as well as what is supposed to happen in greater detail.
