### ISSUE TITLE
Redstone from Alchemist's Cauldron

### ISSUE THREAD

**Issue by OromisElf** [iron431/Irons-Spells-n-Spellbooks#285]
### Feature description

Have the cauldron output a redstone signal if something can be taken out of it.

### How it improves the player experience

Beside having the effect of letting redstone savy people automate some cauldron things, I was having trouble see the difference between a cauldron with water and a cauldron with water + 1 ink.

I had hoped I could put a comparator next to the cauldron so I could just read off of it, but at least in 1.19.2 that's not a thing :(

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
