### ISSUE TITLE
Config option to disable spawning with guidebook

### ISSUE THREAD

**Issue by MrFastZombie** [iron431/Irons-Spells-n-Spellbooks#286]
### Feature description

A boolean option in settings to set whether the player will spawn with a guidebook in their inventory.

### How it improves the player experience

I think this feature will benefit pack makers most. In my case, I want to give players an eccentric tome that includes all of the other guidebooks from other mods and this one, but I cannot find an option to disable spawning with this mod's guidebook.

**Comment by lab3** [comment]
In your datapack you can override the pools array to an empty array in this file
https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.19.2/src/main/resources/data/irons_spellbooks/loot_tables/patchouli_book.json
