### ISSUE TITLE
more like a general question 

### ISSUE THREAD

**Issue by Arekkusubillaga** [iron431/Irons-Spells-n-Spellbooks#287]
### Feature description

is there anyway to modify the values /damage of each spell ?

### How it improves the player experience

just a neat config to tweak to the like of the user and make it easy for modpack creators

**Comment by iron431** [comment]
yes in the server config

**Comment by Arekkusubillaga** [comment]
sorry so much for the annoyance, I'm new to this, so I should go to the server and go to the config directory and then see if there any file named iron spell common? ( btw I forgot to mention I'm using 1.19.2 )

**Comment by Arekkusubillaga** [comment]
I'm sorry it appears there is no file where i can config... well anything, no config file whatsoever
