### ISSUE TITLE
More Elemental Strengths/Weaknesses

### ISSUE THREAD

**Issue by LucioMagno** [iron431/Irons-Spells-n-Spellbooks#291]
### Feature description

 More non-rare mobs that have serious resistances/weaknesses to specific elemental damages. Maybe zombie/skeleton types for each element? maybe drowned could take more damage from ice and less from fire (because they are filled with water) ? Maybe these mobs could be new sources of elemental damage. resistances could go up to 90% damage reduction, there could be a new illager with complete immunity to elemental damage and would reflect elemental projectiles with a mirror shield? Bosses/enemies that can only be damaged by magic or a specific element? The possibilities are Numerous. It would also be wise to allow players to define the resistances for every mob, even modded ones, so players can add them to whatever mobs they feel like.

### How it improves the player experience

 It would add depth to the magic combat system and entice players to think ahead of confrontation, so that they get an edge or their spells arent nullified. It would enforce the usage of a variety of spells, because of the risk a mob could deactivate a element type entirelly or maybe even get stronger from that element. With a config, it would allow players and modpack makers to incorporate every modded mob into this system.

**Comment by LucioMagno** [comment]
keyword: entice, and not force. i dont think it would be fun for common mobs to force you to use something specific to defeat them, maybe specific bosses/stronger mobs could do that.

**Comment by iron431** [comment]
This is something we're already doing
