### ISSUE TITLE
[Bug]  Incompatibility with wildfyre gender mod

### ISSUE THREAD

**Issue by superRYANXD** [iron431/Irons-Spells-n-Spellbooks#292]
### Observed behaviour

The chest area shows default purple textures when equipping armor from Iron's spells mod, however, works fine with other mods.
Game version is 1.20.1 using CurseForge launcher

https://github.com/superRYANXD/Images/blob/main/Screenshot%20(8719).png

### Expected behaviour

Example of other mod armor which renders properly

https://github.com/superRYANXD/Images/blob/main/Screenshot%20(8716).png

### Steps to reproduce

The mod in question which does not render properly with the armors is https://www.curseforge.com/minecraft/mc-mods/female-gender

Version 3.0.1 1.20/1.20.1 

This bug also persists on all other compatible versions in which these two mods can be run together

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.2.1

### Forge version

1.20.1

### Other mods

The other mod used for example (which works properly) is the immersive armors mod for 1.20.1

Link to mod: https://www.curseforge.com/minecraft/mc-mods/immersive-armors

**Comment by lab3** [comment]
This is most likely an issue with geckolib.  @superRYANXD, do any mods that use geckolib armor work with it?

**Comment by superRYANXD** [comment]
Yes, I've tried out a few random armor mods with this mod (all with geckolib installed) and they seem to work just fine unless it's some really small obscure mod

**Comment by lab3** [comment]
Geckolib installed or they actually depend in geckolib?

**Comment by iron431** [comment]
Upon investigating, there is nothing we can do because they have a hardcoded texture guesser. Any fixes would have to be on their end (although for geckolib, such a fix would be incredibly easy)

**Comment by xinwolfthorn** [comment]
don't let them lie, they can make one texture for each armorset and fix all the problems..
