### ISSUE TITLE
4 Evoker Forts and None Have Wandering Traders? [Bug]

### ISSUE THREAD

**Issue by CheezBallzFTW** [iron431/Irons-Spells-n-Spellbooks#295]
### Observed behaviour

I've gone to 4 evoker forts and found 0 wandering traders, just one of them had 2 normal villagers in cages.

### Expected behaviour

I thought a wandering trader was supposed to be at some of the forts to translate the journal. Can they die as I'm getting to the fort? Or is it just that they're very rare to find at the forts?

### Steps to reproduce

I got a map from the priest villager, went to the evoker fort, cleared it out, and saw no wandering traders 4 times. I even tried checking my minimap to see if they were there at all, but I saw no dot labeled wandering trader, just 2 villagers in 1 of the 4 forts.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-2.2.1

### Forge version

1.19.2-43.3.7

### Other mods

All on newest 1.19.2 version:

[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Atmospheric (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/atmospheric)
[MrCrayfish's Gun Mod (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/mrcrayfishs-gun-mod)
[Exhausted Stamina (by Tage)](https://www.curseforge.com/minecraft/mc-mods/exhausted-stamina)
[Miner's Helmet (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/miners-helmet)
[MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Let Me Despawn (by frikinjay)](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Rotten Creatures (by fusionstudiomc)](https://www.curseforge.com/minecraft/mc-mods/rotten-creatures)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
[Max Health Fix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/max-health-fix)
[Bucolic Origins [FORGE/FABRIC] (by Tmanfoo)](https://www.curseforge.com/minecraft/mc-mods/bucolic-origins)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Auditory (by Sydokiddo)](https://www.curseforge.com/minecraft/mc-mods/auditory)
[Truly Treasures (by Ineffa)](https://www.curseforge.com/minecraft/mc-mods/truly-treasures)
[Integrated Dungeons and Structures (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/idas)
[XL Packets (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/xl-packets)
[Critters and Companions (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/critters-and-companions)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Shield Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/shield-expansion)
[Allurement (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/allurement)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Treasure2: Twilight Forest Loot Pack (by gottsch)](https://www.curseforge.com/minecraft/mc-mods/treasure2-twilight-forest-loot-pack)
[Chance Globe (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/chance-globe)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[GoProne (by Alpvax)](https://www.curseforge.com/minecraft/mc-mods/goprone)
[Canary (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/canary)
[Kobolds! (by Jusey1z)](https://www.curseforge.com/minecraft/mc-mods/kobolds)
[The Fletching Table Mod (by The_Hangel)](https://www.curseforge.com/minecraft/mc-mods/the-fletching-table-mod)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Dash (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/dash)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Treasure2 (by gottsch)](https://www.curseforge.com/minecraft/mc-mods/treasure2)
[Bosses of Mass Destruction [FORGE] (by CerbonXD)](https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction-forge)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Off Hand Combat [Forge] (by Awekyuwusu)](https://www.curseforge.com/minecraft/mc-mods/off-hand-combat)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Curios Quark Oddities Backpack (by 6LeoY)](https://www.curseforge.com/minecraft/mc-mods/curios-quark-oddities-backpack)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Sullys Mod (by GoesBySully)](https://www.curseforge.com/minecraft/mc-mods/sullys-mod)
[Quicksand (Forge) (by RaymondBlaze)](https://www.curseforge.com/minecraft/mc-mods/quicksand-forge)
[Tumbleweed (by bconv)](https://www.curseforge.com/minecraft/mc-mods/tumbleweed)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[YDM's MobHealthBar (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/ydms-mobhealthbar-mod)
[Randomium Ore (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/randomium-ore)
[Dramatic Doors (by FizzWare)](https://www.curseforge.com/minecraft/mc-mods/dramatic-doors)
[Blue Skies (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/blue-skies)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[CAS' Extra Potions (by CAS_ual_TY)](https://www.curseforge.com/minecraft/mc-mods/cas-extra-potions)
[Inventorio (Forge) (by Lizard_OfOz)](https://www.curseforge.com/minecraft/mc-mods/inventorio-forge)
[Ender Trigon (by nonamecrackers2)](https://www.curseforge.com/minecraft/mc-mods/ender-trigon)
[Dungeons Plus (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/dungeons-plus)
[Majrusz Library (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majrusz-library)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Step (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/step)
[Mutant More (by alexandersfunandgames)](https://www.curseforge.com/minecraft/mc-mods/new-mutant-more)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Creatures and Beasts (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creatures-and-beasts)
[Overflowing Bars [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/overflowing-bars)
[Upgrade Aquatic (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Tool Stats (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/tool-stats)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Jade 🔍 (by Snownee)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Majrusz's Enchantments (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments)
[Explorer's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/explorers-compass)
[Loot Integrations[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/loot-integrations)
[Presence Footsteps [Forge] (by Paint_Ninja)](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge)
[SecretRoomsMod (by AbrarSyed)](https://www.curseforge.com/minecraft/mc-mods/secretroomsmod)
[Golden Hopper (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/golden-hopper)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Useful Hats (by thecech12)](https://www.curseforge.com/minecraft/mc-mods/useful-hats)
[Click Machine (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/click-machine)
[YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples)
[Archaeology API (by min01)](https://www.curseforge.com/minecraft/mc-mods/archaeology-api)
[Better Tridents [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/better-tridents)
[Nyf's Spiders (by Nyfaria)](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[SwingThroughGrass (by exidex)](https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Create: Alloyed (by MythrilBagels)](https://www.curseforge.com/minecraft/mc-mods/create-alloyed)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Cursery[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cursery)
[Terralith (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/terralith)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[More Villager Trades (by TrueRealCursed_Warrior)](https://www.curseforge.com/minecraft/mc-mods/more-villager-trades)
[Polymorph (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Create Stuff & Additions (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions)
[Mutant Monsters [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/mutant-monsters)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Savage Ender Dragon[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon)
[Extra Mob Drops (by BowlOfHypocrisy)](https://www.curseforge.com/minecraft/mc-mods/extra-mob-drops)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Lightspeed - Launch optimizations (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/lightspeedmod)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Majrusz's Accessories (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories)
[Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
[GottschCore (by gottsch)](https://www.curseforge.com/minecraft/mc-mods/gottschcore)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
[The Floo (by CAS_ual_TY)](https://www.curseforge.com/minecraft/mc-mods/the-floo)
[Better Invisibility (by Purplicious_Cow_)](https://www.curseforge.com/minecraft/mc-mods/better-invisibility)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Completionist's Index [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/completionists-index)
[Music Maker Mod (by xerca0)](https://www.curseforge.com/minecraft/mc-mods/music-maker-mod)
[Actually Useful Smithing Table (by Rohzek)](https://www.curseforge.com/minecraft/mc-mods/actually-useful-smithing-table)
[LAN World Plug-n-Play (by Satxm)](https://www.curseforge.com/minecraft/mc-mods/mcwifipnp)
[Origins (Forge) (by EdwinMindcraft)](https://www.curseforge.com/minecraft/mc-mods/origins-forge)
[[FORGE/FABRIC] Armor Curve (by TheRealJackiecrazy)](https://www.curseforge.com/minecraft/mc-mods/armor-curve)
[Archer's Paradox (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/archers-paradox)
[Integrated API (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/integrated-api)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Joy of Painting (by xerca0)](https://www.curseforge.com/minecraft/mc-mods/joy-of-painting)
[Traverse Reforged (by Prospector)](https://www.curseforge.com/minecraft/mc-mods/traverse-reforged)
[Entity Collision FPS Fix (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix)
[Pluto (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/pluto)
[Neruina - Ticking Entity Fixer (by bawnorton)](https://www.curseforge.com/minecraft/mc-mods/neruina)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[Extra Trades (by CAS_ual_TY)](https://www.curseforge.com/minecraft/mc-mods/extra-trades)
[Damage Tilt (by Charles445)](https://www.curseforge.com/minecraft/mc-mods/damage-tilt)
[Auto Attack Rebirth (by segoitch)](https://www.curseforge.com/minecraft/mc-mods/auto-attack-rebirth)
[Realm RPG: Sea Dwellers (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/nocubes-sea-dwellers)
[Ensorcellation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/ensorcellation)
[Crafting Automat (by Fereydun)](https://www.curseforge.com/minecraft/mc-mods/crafting-automat)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Lootr (Forge & NeoForge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Regrowth (by MacTso)](https://www.curseforge.com/minecraft/mc-mods/regrowth)
[FramedBlocks (by XFactHD)](https://www.curseforge.com/minecraft/mc-mods/framedblocks)
[Xaero's Minimap & World Map - Waystones Compatibility [Forge] (by precisemodpacker)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap-world-map-waystones-compability)
[The Conjurer (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/the-conjurer)
[Xaero Arrow Fix (by Abbie34)](https://www.curseforge.com/minecraft/mc-mods/xaero-arrow-fix)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Enigmatic Legacy (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy)
[Automobility (by FoundationGames)](https://www.curseforge.com/minecraft/mc-mods/automobility)
[Better chunk loading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
[The Aether (by TheAetherTeam)](https://www.curseforge.com/minecraft/mc-mods/aether)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Majrusz's Progressive Difficulty (by Majrusz17)](https://www.curseforge.com/minecraft/mc-mods/majruszs-progressive-difficulty)
[NineZero's Gun Expansion (by zaeonNineZero)](https://www.curseforge.com/minecraft/mc-mods/ninezeros-gun-expansion)
[Meet Your Fight (by Lykrast)](https://www.curseforge.com/minecraft/mc-mods/meet-your-fight)
[Bag of Yurting (by Commoble)](https://www.curseforge.com/minecraft/mc-mods/bag-of-yurting)
[Farsighted Mobs (Forge & NeoForge) (by Sindarin27)](https://www.curseforge.com/minecraft/mc-mods/farsighted-mobs-forge)
[Vanilla Cookbook (by platinmoralle)](https://www.curseforge.com/minecraft/mc-mods/vanilla-cookbook)
[Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[Effortless Building (by Requioss)](https://www.curseforge.com/minecraft/mc-mods/effortless-building)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Embeddium (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Leap (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/leap)
[Biome Makeover (Forge) (by Lemonszz)](https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge)
[Drop the Meat (by platinmoralle)](https://www.curseforge.com/minecraft/mc-mods/drop-the-meat)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
[Waystone Towers (by ner07ca)](https://www.curseforge.com/minecraft/mc-mods/waystone-towers)
[Visual Workbench [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench)
[Enchantment Transfer (Fabric/Forge) (by treekicker4)](https://www.curseforge.com/minecraft/mc-mods/enchantment-transfer)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Relics (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/relics-mod)
[Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
[ImmediatelyFast (by RaphiMC)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Sky Villages [Forge] (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/sky-villages-forge)

**Comment by CheezBallzFTW** [comment]
If it's a mod compatibility issue that's changing the wandering trader into a normal villager, I'd like to request a config option to add a trade to normal wandering traders for translating the journal.

**Comment by iron431** [comment]
it's random. go to more than 4

**Comment by CheezBallzFTW** [comment]
Just to make sure I understand: the cages with the villagers are only in some evoker forts, and the ones that do have the villagers aren’t guaranteed to have a wandering trader right? What are the chances of finding the trader overall? Like 10%? I’ll keep looking. I guess I should’ve expected it’d take more than a simple quest to one fort if the reward is an epic spellbook. Now I should be able to get multiple as well.

**Comment by CheezBallzFTW** [comment]
I've now cleared 8 forts and still no wandering trader.

**Comment by iron431** [comment]
As of v2.2.1, there's about a 12% chance a fort has at least one wandering trader. This means there's a 50% chance to get one after 5.5 forts. You can edit the rates with a datapack.

**Comment by mycroftjr** [comment]
> As of v2.2.1, there's about a 12% chance a fort has at least one wandering trader. This means there's a 50% chance to get one after 5.5 forts. You can edit the rates with a datapack.

How exactly would one edit those rates? I've been to 5 forts now and found 0 hanging cages, 1 prisoner total who was just a plain villager. 1.19.2-3.1.7.

**Comment by iron431** [comment]
change the wandering trader spawn weight

**Comment by mycroftjr** [comment]
> change the wandering trader spawn weight

Any way to make the hanging cages more frequent? Because the wandering trader weight won't help if there's nowhere for them to spawn, right? Unless the spawns actually cause those structure features?
