### ISSUE TITLE
How do priests spawn

### ISSUE THREAD

**Issue by JalapenoGremlin** [iron431/Irons-Spells-n-Spellbooks#298]
### Feature description

I'm just trying to understand how priests spawn. And how to "create a priest". That is is there a "workstation block" for this mob? 

As I'm playing I encounter a village with priests and then they all die.

Do I need to cordon them into a "secure location" upon entering the village so that I can trade with them later when I actually have the items to make trades?

### How it improves the player experience

Knowing how/where to find priests is pretty important.

**Comment by iron431** [comment]
1 priest spawns per tower. There is no way to create one, its not a profession.

**Comment by JalapenoGremlin** [comment]
So once they die... That's it? 

Thanks for the quick response!
