### ISSUE TITLE
[Bug] void tentacle's, tentacles dont appear while using shaders 

### ISSUE THREAD

**Issue by kaairu** [iron431/Irons-Spells-n-Spellbooks#30]
### Observed behaviour

void tentacles didnt appear, only the black cloud part did

### Expected behaviour

void tentacles to appear

### Steps to reproduce

install oculus and rubidium
use shaders

the shaders im using are complementary reimagined shaders

### Server Type

Single Player

### Crashlog

n/a

### Iron's Spells N Spellbooks version

1.0.8

### Forge version

1.19.2 43.2.8

### Other mods

![image](https://user-images.githubusercontent.com/121336317/236715279-0a0a283d-b95f-42ad-9149-c722b849b452.png)
![image](https://user-images.githubusercontent.com/121336317/236715290-c3370dc5-260b-4de0-bea3-e8d59642a39c.png)

**Comment by iron431** [comment]
fixed in 1.1.1
