### ISSUE TITLE
[Bug] CTD when capturing a Priest Villager

### ISSUE THREAD

**Issue by kezmodius** [iron431/Irons-Spells-n-Spellbooks#302]
### Observed behaviour

A player on my server used a Portable Mobs cage to capture a Priest villager. CTD.
When he logged back in the Priest was in the cage and did not cause an issue when released.
Client log is attached below. Playing on my server but server was totally unaffected (nothing about it in the log).
I reported the issue to Portable Mobs github and the dev said it appears to be an error on Iron's Spells 'n' Spellbooks side and asked me to report to you.

### Expected behaviour

For the client not to crash

### Steps to reproduce

Click a Portable Mobs cage on an Iron's Spells Priest
Hard crash to desktop

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/kezmodius/305369e37c49da5cb2d613c2afd25717

### Iron's Spells N Spellbooks version

1.20.1-2.2.1.jar

### Forge version

1.20.1 - 47.2.20

### Other mods

Ars Ocultas ars_ocultas-1.20.1-1.1.0-all.jar
Artifacts artifacts-forge-9.2.0.jar
AzureLib azurelib-neo-1.20.1-2.0.19.jar
Biome Music[Forge/Fabric] biomemusic-1.20.1-2.2.jar
BlockUI blockui-1.20.1-1.0.135-BETA.jar
Citadel citadel-2.4.9-1.20.1.jar
Comforts (Fabric/Forge/Quilt) comforts-forge-6.3.4+1.20.1.jar
Cupboard cupboard-1.20.1-2.2.jar
Curios API (Forge/NeoForge) curios-forge-5.5.0+1.20.1.jar
Eidolon : Repraised eidolon_repraised-1.20.1-0.3.8.0.jar
Embeddium embeddium-0.2.18+mc1.20.1.jar
Epic Samurai's - Forge epicsamurai-0.0.33-1.20.1-neo.jar
Farmer's Delight FarmersDelight-1.20.1-1.2.3.jar
GeckoLib geckolib-forge-1.20.1-4.4.jar
Iron's Spells 'n Spellbooks irons_spellbooks-1.20.1-2.2.1.jar
L_Ender 's Cataclysm L_Enders_Cataclysm-1.89 -1.20.1.jar
Lootr (Forge & NeoForge) lootr-1.20-0.7.30.73.jar
MineColonies minecolonies-1.20.1-1.1.451-BETA.jar
Modonomicon modonomicon-1.20.1-forge-1.55.1.jar
Occultism occultism-1.20.1-1.109.0.jar
Simple Voice Chat voicechat-forge-1.20.1-2.4.32.jar
Simply Swords [Fabric & Forge] simplyswords-forge-1.51.5-1.20.1.jar
TerraBlender (Forge) TerraBlender-forge-1.20.1-3.0.1.2.jar

Additional Structures Rex's-AdditionalStructures-1.20.x-(v.4.2.1).jar
AppleSkin appleskin-forge-mc1.20.1-2.5.1.jar
Architectury API (Fabric/Forge/NeoForge) architectury-9.1.12-forge.jar
Armourer's Workshop armourersworkshop-forge-1.20.1-2.0.11.jar
Ars Artifice ars_artifice-1.20.1-2.0.4.jar
Ars Elemental ars_elemental-1.20.1-0.6.4.1.jar
Ars Nouveau ars_nouveau-1.20.1-4.9.0-all.jar
AttributeFix AttributeFix-Forge-1.20.1-21.0.4.jar
Awesome Dungeon - Forge awesomedungeon-forge-1.20.1-3.2.0.jar
Awesome Dungeon Nether edition - Forge awesomedungeonnether-forge-1.20.1-3.1.1.jar
Awesome Dungeon Ocean edition - Forge awesomedungeonocean-forge-1.20.1-3.3.0.jar
Awesome Dungeon The End edition - Forge awesomedungeonend-forge-1.20.1-3.1.1.jar
B.F. End Cities bfendcities-1.0.jar
bad packets badpackets-forge-0.4.3.jar
Balm (Forge Edition) balm-forge-1.20.1-7.2.1.jar
Better Copper / Armor and Tools BetterCopper 1.20.1 -1.1.jar
Better Fps - Render Distance[Forge] betterfpsdist-1.20.1-4.1.jar
Better Harvesting betterharvesting-1.20-forge-0.0.2.jar
Better Treasure Map treasuredistance-1.20-1.2.jar
Better Villages - Forge bettervillage-forge-1.20.1-3.2.0.jar
Biomes O' Plenty BiomesOPlenty-1.20.1-18.0.0.598.jar
Blood Magic bloodmagic-1.20.1-3.3.2-44.jar
Bookshelf Bookshelf-Forge-1.20.1-20.1.8.jar
Botany Pots BotanyPots-Forge-1.20.1-13.0.22.jar
Botany Trees BotanyTrees-Forge-1.20.1-9.0.7.jar
Caelus API (Forge/NeoForge) caelus-forge-3.1.0+1.20.jar
Charm of Undying (Fabric/Forge/Quilt) charmofundying-forge-6.4.5+1.20.1.jar
Chunk Sending[Forge/Fabric] chunksending-1.20.1-2.8.jar
Clean Swing Through Grass cleanswing-1.20-1.4.jar
Clickable advancements[Forge/Fabric] clickadv-1.20.1-3.7.jar
Cloth Config API (Fabric/Forge/NeoForge) cloth-config-11.1.118-forge.jar
Colorful Hearts colorfulhearts-forge-1.20.1-4.0.4.jar
Companion 🐕 (Forge) Companion-1.20.1-forge-5.0.1.jar
Connectivity[Forge/Fabric] connectivity-1.20.1-4.9.jar
Controlling Controlling-forge-1.20.1-12.0.2.jar
Cooking for Blockheads cookingforblockheads-forge-1.20-16.0.1.jar
Corail Woodcutter corail_woodcutter-1.20.1-3.0.4.jar
Corpse corpse-forge-1.20.1-1.0.10.jar
Cosmetic Armor Reworked cosmeticarmorreworked-1.20.1-v1a.jar
Creeper Overhaul creeperoverhaul-3.0.1-forge.jar
Cristel Lib cristellib-1.1.5-forge.jar
Croptopia Croptopia-1.20.1-FORGE-3.0.4.jar
Cucumber Library Cucumber-1.20.1-7.0.7.jar
Curious Armor Stands curious_armor_stands-1.20-5.0.1.jar
Cyclops Core CyclopsCore-1.20.1-1.18.14.jar
Distracting Trims DistractingTrims-Forge-1.20.1-2.0.3.jar
Domum Ornamentum domum_ornamentum-1.20-1.0.154-BETA-universal.jar
Dynamic View[Forge] dynview-1.20.1-3.9.jar
Elytra Slot (Fabric/Forge/Quilt) elytraslot-forge-6.3.0+1.20.1.jar
Enchantment Descriptions EnchantmentDescriptions-Forge-1.20.1-17.0.13.jar
End Remastered endrem_forge-5.2.3-R-1.20.X.jar
EpheroLib EpheroLib-1.20.1-FORGE-1.2.0.jar
Epic Knights: Shields, Armor and Weapons [Fabric & Forge] [1.20.1-forge]-Epic-Knights-8.11.jar
ExpandAbility expandability-9.0.0.jar
Explorer's Compass ExplorersCompass-1.20.1-1.3.3-forge.jar
Extreme sound muffler (Forge) extremesoundmuffler-3.41-forge-1.20.1.jar
Farsight [Forge] farsight-1.20.1-3.6.jar
FLIB flib-1.20.1-0.0.11.jar
Forgiving World - Dimension Stacking[Forge/Fabric] forgivingworld-1.20.1-4.2.jar
Framework framework-forge-1.20.1-0.6.16.jar
Friendly Fire FriendlyFire-Forge-1.20.1-18.0.5.jar
Functional Storage functionalstorage-1.20.1-1.2.8.jar
Goblin Traders goblintraders-forge-1.20.1-1.9.3.jar
Hostile Villages hostilevillages-1.20.1-5.3.jar
Hourglass hourglass-1.20-1.2.1.1.jar
HT's TreeChop TreeChop-1.20.1-forge-0.18.8.jar
Immersive Armors [Fabric/Forge] immersive_armors-1.6.1+1.20.1-forge.jar
Infused Foods infusedfoods-1.20.1-10.0.0.jar
Inventory Essentials inventoryessentials-forge-1.20.1-8.2.1.jar
Inventory Sorter inventorysorter-1.20.1-23.0.1.jar
Jade 🔍 Jade-1.20.1-forge-11.7.1.jar
Jade Addons (Forge) JadeAddons-1.20.1-forge-5.2.2.jar
JadeColonies JadeColonies-1.20.1-1.4.2.jar
JourneyMap journeymap-1.20.1-5.9.18-forge.jar
Just Enough Items (JEI) jei-1.20.1-forge-15.2.0.27.jar
L2 Library l2library-2.4.22.jar
Library Ferret - Forge libraryferret-forge-1.20.1-4.0.0.jar
Limited Chunkloading - Chunk cleanup[Forge/Fabric] limitedchunks-1.20.1-3.9.jar
Login Protection[Forge/Fabric] logprot-1.20.1-3.3.jar
Loot Beams: Relooted! lootbeams-1.20.1-1.2.3.jar
Loot Integrations[Forge/Fabric] lootintegrations-1.20.1-3.4.jar
Max Health Fix MaxHealthFix-Forge-1.20.1-12.0.2.jar
MC style paintings mc style paintings 1.20.1 v1.jar
Medieval Music[Forge/Fabric] zmedievalmusic-1.20.1-2.1.jar
MES - Moog's End Structures mes-1.3-1.20-forge.jar
Modular Golems modulargolems-2.4.27.jar
Mouse Tweaks MouseTweaks-forge-mc1.20-2.25.jar
Multi-Piston multipiston-1.20-1.2.31-ALPHA.ja
mutil mutil-1.20.1-6.1.1.jar
MVS - Moog's Voyager Structures mvs-4.1.1-1.20-forge.jar
Mystical Agradditions MysticalAgradditions-1.20.1-7.0.2.jar
Mystical Agriculture MysticalAgriculture-1.20.1-7.0.8.jar
Nameless Trinkets Nameless Trinkets-1.20.1-1.7.8.jar
Nature's Aura NaturesAura-39.4.jar
Nature's Compass NaturesCompass-1.20.1-1.11.2-forge.jar
Neat Neat-1.20-35-FORGE.jar
Oculus oculus-mc1.20.1-1.6.13.jar
Pam's HarvestCraft 2 - Crops pamhc2crops-1.20-1.0.3.jar
Pam's HarvestCraft 2 - Food Core pamhc2foodcore-1.20-1.0.3.jar
Pam's HarvestCraft 2 - Food Extended pamhc2foodextended-1.20-1.0.0.jar
Pam's HarvestCraft 2 - Trees pamhc2trees-1.20-1.0.2.jar
Patchouli Patchouli-1.20.1-84-FORGE.jar
Philip's Ruins Philips-Ruins1.20.1-3.0.1.jar
playerAnimator player-animation-lib-forge-1.0.2-rc1+1.20.jar
Polymorph (Fabric/Forge/Quilt) polymorph-forge-0.49.2+1.20.1.jar
Portable Mobs portablemobs-1.2.0-forge-mc1.20.jar
Repurposed Structures (Neoforge/Forge) repurposed_structures-7.1.11+1.20.1-forge.jar
Resourceful Config resourcefulconfig-forge-1.20.1-2.1.2.jar
Searchables Searchables-forge-1.20.1-1.0.2.jar
Server Performance - Smooth Chunk Save[Forge/Fabric] smoothchunk-1.20.1-3.5.jar
SmartBrainLib (Forge/Fabric/Quilt) SmartBrainLib-forge-1.20.1-1.13.jar
Sophisticated Backpacks sophisticatedbackpacks-1.20.1-3.19.5.988.jar
Sophisticated Core sophisticatedcore-1.20.1-0.5.113.524.jar
Sophisticated Storage sophisticatedstorage-1.20.1-0.8.65.680.jar
Sound Physics Remastered sound-physics-remastered-forge-1.20.1-1.3.1.jar
spark spark-1.10.53-forge.jar
Spice of Life: Apple Pie Edition solapplepie-1.20.1-2.3.0.jar
Storage Racks storageracks-1.20.1-1.7.jar
Structure Essentials[Forge/Fabric] structureessentials-1.20.1-3.2.jar
Structurize structurize-1.20.1-1.0.686-BETA.jar
Stylecolonies stylecolonies-1.3.1.jar
SuperMartijn642's Core Lib supermartijn642corelib-1.1.16-forge-mc1.20.1.jar
Tectonic tectonic-mod-1.19.3-v2.2.jar
Tetra tetra-1.20.1-6.1.0.jar
Tetra's Delight tetrasdelight-1.20.1-1.jar
The Lost Castle tlc_forge-1.0.3-R-1.20.X.jar
Tiny Coal TinyCoal-forge-1.20.1-1.1.4.jar
Titanium titanium-1.20.1-3.8.25.jar
Tom's Simple Storage Mod toms_storage-1.20-1.6.5.jar
Towns and Towers Towns-and-Towers-1.12-Fabric+Forge.jar
TownTalk towntalk-1.20.1-1.0.1.jar 
Transmog transmog-forge-1.2.4+1.20.jar
Vanilla Plus Tools vanillaplustools-1.20-1.0.jar
Waystones waystones-forge-1.20-14.1.3.jar

**Comment by kezmodius** [comment]
https://gist.github.com/kezmodius/fc5c943d75a421380a9dd6653c9ba234
Another player on my server tried to capture a Pyromancer with a Portable Mobs Master Capture Cell and had a hard CTD. As opposed to the above issue (crash when capturing with the cage) this time it's crashing when they try and release the mob from the cage.
If it's helpful, I caught and released a Necromancer they same way on the same server and had no issues.

**Comment by SiverDX** [comment]
> https://gist.github.com/kezmodius/fc5c943d75a421380a9dd6653c9ba234 Another player on my server tried to capture a Pyromancer with a Portable Mobs Master Capture Cell and had a hard CTD. As opposed to the above issue (crash when capturing with the cage) this time it's crashing when they try and release the mob from the cage. If it's helpful, I caught and released a Necromancer they same way on the same server and had no issues.

might have to ask farsight about that one

**Comment by iron431** [comment]
this should be fixed, if someone can confirm the issue can be closed sooner
