### ISSUE TITLE
Incompatibilty found with Dragon Mounts Legacy

### ISSUE THREAD

**Issue by danaorourke** [iron431/Irons-Spells-n-Spellbooks#304]
### Observed behaviour

There appears to be an incompatibility with Dragons Mount Legacy. Bug report suggests io.redspace.ironsspellbooks.player.ServerPlayerEvents.handleResistanceAttributesOnSpawn encounters null values it expects to exist.

### Expected behaviour

I expect to be able to spawn the mob from the other mod.

### Steps to reproduce

1. Get dragon spawn egg.
2. Try to use to summon.
3. Watch report log fill.

### Server Type

Single Player

### Crashlog

https://gist.github.com/danaorourke/8f0813bd4fed28a6ea6e5f0b869bef83

### Iron's Spells N Spellbooks version

1.20.1-2.2.2

### Forge version

1.20.1-47.2.0

### Other mods

Dragon Mounts Legacy (1.20.1) (link to mod - https://www.curseforge.com/minecraft/mc-mods/dragon-mounts-legacy)

**Comment by iron431** [comment]
This is an issue with Dragons Mount Legacy. Their dragon's fire immunity is based on a unsafe value https://github.com/Kay9Unit/Dragon-Mounts-Legacy/blob/fb5d068704e7651b61749926567ea85e3f52a1e0/src/main/java/com/github/kay9/dragonmounts/dragon/TameableDragon.java#L1062
