### ISSUE TITLE
[Bug] game crash when priest casts heal

### ISSUE THREAD

**Issue by guest-ujy** [iron431/Irons-Spells-n-Spellbooks#305]
### Observed behaviour

when the priest casts heal the game crashes (game version 1.20.1)
(HealSpell.java:80)

### Expected behaviour

the priest to cast heal 

### Steps to reproduce

*I made a custom mod pack using curse forge, i was able to dupe it in single player*
1: start a creative game sp or mp doesn't mater
2: spawn a bunch of villagers (5-15)
3: spawn a bunch of priests (10-20)
4: spawn a bunch of things for them to fight
5: wait 

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/guest-ujy/03f21f82349cf449671fe95738a218bc

### Iron's Spells N Spellbooks version

1.20.1-2.2.2 1/26/2024

### Forge version

47.2.20

### Other mods

*grabbed from crash log*

rsrequestify-1.20.1-2.3.3.jar                     |RSRequestify                  |rsrequestify                  |2.3.3               |DONE      |Manifest: NOSIGNATURE
		aether_enhanced_extinguishing-1.20.1-1.0.0-neoforg|Enhanced Extinguishing        |aether_enhanced_extinguishing |1.20.1-1.0.0-neoforg|DONE      |Manifest: NOSIGNATURE
		ftb-essentials-forge-2001.2.2.jar                 |FTB Essentials                |ftbessentials                 |2001.2.2            |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.2.jar                   |GeckoLib 4                    |geckolib                      |4.4.2               |DONE      |Manifest: NOSIGNATURE
		scena-forge-1.0.103.jar                           |Scena                         |scena                         |1.0.103             |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2-rc1+1.20.jar     |Player Animator               |playeranimator                |1.0.2-rc1+1.20      |DONE      |Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.3.2.jar                   |Botarium                      |botarium                      |2.3.2               |DONE      |Manifest: NOSIGNATURE
		aether-1.20.1-1.2.0-neoforge.jar                  |The Aether                    |aether                        |1.20.1-1.2.0-neoforg|DONE      |Manifest: NOSIGNATURE
		majruszs-difficulty-forge-1.20.1-1.9.7.jar        |Majrusz's Progressive Difficul|majruszsdifficulty            |1.9.7               |DONE      |Manifest: NOSIGNATURE
		connectivity-1.20.1-4.9.jar                       |Connectivity Mod              |connectivity                  |1.20.1-4.9          |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.2.1-mc1.20.1forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.20.1-12.0.2.jar               |Controlling                   |controlling                   |12.0.2              |DONE      |Manifest: NOSIGNATURE
		Placebo-1.20.1-8.6.0.jar                          |Placebo                       |placebo                       |8.6.0               |DONE      |Manifest: NOSIGNATURE
		citadel-2.5.2-1.20.1.jar                          |Citadel                       |citadel                       |2.5.2               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.7.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.7              |DONE      |Manifest: NOSIGNATURE
		IronsRecipeAdditions_1.20.1_modversion_1.5.jar    |Iron's Recipe Additions       |irons_recipe_additions        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.1-beta.2.jar                |MixinExtras                   |mixinextras                   |0.2.1-beta.2        |DONE      |Manifest: NOSIGNATURE
		lost_aether_content-1.20.1-1.2.3.jar              |Aether: Lost Content          |lost_aether_content           |1.2.3               |DONE      |Manifest: NOSIGNATURE
		ChanceCubes-1.20.1-5.0.2.489.jar                  |Chance Cubes                  |chancecubes                   |1.20.1-5.0.2.489    |DONE      |Manifest: NOSIGNATURE
		catacalysm delight 1.20.1 - 0.1.1.jar             |cataclysm delight             |cataclysm_delight             |1.0.0               |DONE      |Manifest: NOSIGNATURE
		quarry-1.20.1-1.6.5r.jar                          |Quarry                        |quarry                        |1.6.4r              |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |DONE      |Manifest: NOSIGNATURE
		dynview-1.20.1-3.9.jar                            |Dynamic view distance         |dynview                       |2.3                 |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.247.jar          |Just Enough Resources         |jeresources                   |1.4.0.247           |DONE      |Manifest: NOSIGNATURE
		dragonfight-1.20.1-4.2.jar                        |dragonfight mod               |dragonfight                   |1.20.1-4.2          |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.20.1-1.3.1.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.3.1        |DONE      |Manifest: NOSIGNATURE
		dummmmmmy-1.20-1.8.14.jar                         |MmmMmmMmmmmm                  |dummmmmmy                     |1.20-1.8.14         |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.1893-universal.jar      |The Twilight Forest           |twilightforest                |4.3.1893            |DONE      |Manifest: NOSIGNATURE
		mob_grinding_utils-1.20.1-1.0.3.jar               |Mob Grinding Utils            |mob_grinding_utils            |1.20.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.12.4.jar                         |Refined Storage               |refinedstorage                |1.12.4              |DONE      |Manifest: NOSIGNATURE
		durabilitytooltip-1.1.5-forge-mc1.20.jar          |Durability Tooltip            |durabilitytooltip             |1.1.5               |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.20.1-2.16.0.jar                   |Structure Gel API             |structure_gel                 |2.16.0              |DONE      |Manifest: NOSIGNATURE
		industrial-foregoing-1.20.1-3.5.14.jar            |Industrial Foregoing          |industrialforegoing           |3.5.14              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		ends_delight-1.20.1-1.0.1.jar                     |End's Delight                 |ends_delight                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		colorfulhearts-forge-1.20.1-4.0.4.jar             |Colorful Hearts               |colorfulhearts                |4.0.4               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.20.1.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.2.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.2               |DONE      |Manifest: NOSIGNATURE
		L_Enders_Cataclysm-1.90 -1.20.1.jar               |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.6.1+1.20.1.jar                     |Curios API                    |curios                        |5.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
		Searchables-forge-1.20.1-1.0.2.jar                |Searchables                   |searchables                   |1.0.2               |DONE      |Manifest: NOSIGNATURE
		advgenerators-1.6.0.6-mc1.20.1.jar                |Advanced Generators           |advgenerators                 |1.6.0.6             |DONE      |Manifest: NOSIGNATURE
		pmmo_farmers_compat-1.20.1-1.0.4.jar              |PMMO Farmers Delight Compat   |pmmo_farmers_compat           |1.20.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		elevatorid-1.20.1-lex-1.9.jar                     |Elevator Mod                  |elevatorid                    |1.20.1-lex-1.9      |DONE      |Manifest: NOSIGNATURE
		ftb-ultimine-forge-2001.1.4.jar                   |FTB Ultimine                  |ftbultimine                   |2001.1.4            |DONE      |Manifest: NOSIGNATURE
		Chunk Pregenerator-1.20-4.2.3.jar                 |Chunk Pregenerator            |chunkpregen                   |1.20-4.2.3          |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.20.jar            |Resourceful Lib               |resourcefullib                |2.1.20              |DONE      |Manifest: NOSIGNATURE
		ExtraStorage-1.20.1-4.0.5.jar                     |ExtraStorage                  |extrastorage                  |4.0.5               |DONE      |Manifest: NOSIGNATURE
		cumulus_menus-1.20.1-1.0.0-neoforge.jar           |Cumulus                       |cumulus_menus                 |1.20.1-1.0.0-neoforg|DONE      |Manifest: NOSIGNATURE
		twilightdelight-2.0.4.jar                         |Twilight's Flavor & Delight   |twilightdelight               |2.0.4               |DONE      |Manifest: NOSIGNATURE
		pmmo-1.20.1-1.2.16.jar                            |Project MMO                   |pmmo                          |1.2.16              |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		findme-3.2.0-forge.jar                            |FindMe                        |findme                        |3.2.0               |DONE      |Manifest: NOSIGNATURE
		squatgrow-forge-5.2.0+mc1.20.1.jar                |Squat Grow                    |squatgrow                     |5.2.0+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-2.3.jar                           |Cupboard utilities            |cupboard                      |1.20.1-2.3          |DONE      |Manifest: NOSIGNATURE
		light-overlay-8.0.0-forge.jar                     |Light Overlay                 |lightoverlay                  |8.0.0               |DONE      |Manifest: NOSIGNATURE
		flib-1.20.1-0.0.11.jar                            |flib                          |flib                          |0.0.11              |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		nitrogen_internals-1.20.1-1.0.2-neoforge.jar      |Nitrogen                      |nitrogen_internals            |1.20.1-1.0.2-neoforg|DONE      |Manifest: NOSIGNATURE
		l2library-2.4.16-slim.jar                         |L2 Library                    |l2library                     |2.4.16              |DONE      |Manifest: NOSIGNATURE
		pmmo_spellbooks_compat-1.20.1-1.0.2.jar           |PMMO Spells and Spellbooks Com|pmmo_spellbooks_compat        |1.20.1-1.0.2        |DONE      |Manifest: NOSIGNATURE
		polylib-forge-2000.0.3-build.97.jar               |PolyLib                       |polylib                       |2000.0.3-build.97   |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-31.jar                              |Fast Leaf Decay               |fastleafdecay                 |31                  |DONE      |Manifest: NOSIGNATURE
		majrusz-library-forge-1.20.1-7.0.4.jar            |Majrusz Library               |majruszlibrary                |7.0.4               |DONE      |Manifest: NOSIGNATURE
		Cyclic-1.20.1-1.12.6.jar                          |Cyclic                        |cyclic                        |1.12.6              |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		inventorysorter-1.20.1-23.0.1.jar                 |Simple Inventory Sorter       |inventorysorter               |23.0.1              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-2001.1.5.jar                    |FTB Library                   |ftblibrary                    |2001.1.5            |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-2001.1.4.jar                      |FTB Teams                     |ftbteams                      |2001.1.4            |DONE      |Manifest: NOSIGNATURE
		xlpackets-1.18.2-2.1.jar                          |XL Packets                    |xlpackets                     |1.18.2-2.1          |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		AttributeFix-Forge-1.20.1-21.0.4.jar              |AttributeFix                  |attributefix                  |21.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		tesseract-1.0.35a-forge-mc1.20.1.jar              |Tesseract                     |tesseract                     |1.0.35a             |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.20.1-10.4.5.19.jar                     |Mekanism                      |mekanism                      |10.4.5              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.20.1-10.4.5.19.jar           |Mekanism: Generators          |mekanismgenerators            |10.4.5              |DONE      |Manifest: NOSIGNATURE
		MekanismAdditions-1.20.1-10.4.5.19.jar            |Mekanism: Additions           |mekanismadditions             |10.4.5              |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.20.1-10.4.5.19.jar                |Mekanism: Tools               |mekanismtools                 |10.4.5              |DONE      |Manifest: NOSIGNATURE
		caelus-forge-3.1.0+1.20.jar                       |Caelus API                    |caelus                        |3.1.0+1.20          |DONE      |Manifest: NOSIGNATURE
		Kobolds-2.10.3.jar                                |Kobolds                       |kobolds                       |2.10.3              |DONE      |Manifest: NOSIGNATURE
		bdlib-1.27.0.8-mc1.20.1.jar                       |BdLib                         |bdlib                         |1.27.0.8            |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.3.jar                   |Waystones                     |waystones                     |14.1.3              |DONE      |Manifest: NOSIGNATURE
		FastSuite-1.20.1-5.0.1.jar                        |Fast Suite                    |fastsuite                     |5.0.1               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.9.18-forge.jar                |Journeymap                    |journeymap                    |5.9.18              |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.20.1-9.1.12.jar               |Traveler's Backpack           |travelersbackpack             |9.1.12              |DONE      |Manifest: NOSIGNATURE
		Dungeon Crawl-1.20.1-2.3.14.jar                   |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |DONE      |Manifest: NOSIGNATURE
		ftbbackups2-forge-1.20-1.0.23.jar                 |FTB Backups 2                 |ftbbackups2                   |1.0.23              |DONE      |Manifest: NOSIGNATURE
		roost_ultimate-1.20.1-2.1.3.jar                   |Roost Ultimate                |chicken_roost                 |2.1.3               |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.20-8.0.3.jar                           |McJtyLib                      |mcjtylib                      |1.20-8.0.3          |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.20-5.0.2.jar                        |RFToolsBase                   |rftoolsbase                   |1.20-5.0.2          |DONE      |Manifest: NOSIGNATURE
		rftoolscontrol-1.20-7.0.1.jar                     |RFToolsControl                |rftoolscontrol                |1.20-7.0.1          |DONE      |Manifest: NOSIGNATURE
		rftoolsdim-1.20-11.0.5.jar                        |RFToolsDimensions             |rftoolsdim                    |1.20-11.0.5         |DONE      |Manifest: NOSIGNATURE
		farsight-1.20.1-3.6.jar                           |Farsight mod                  |farsight_view                 |1.20.1-3.6          |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.20.1-4.9.0-all.jar                  |Ars Nouveau                   |ars_nouveau                   |4.9.0               |DONE      |Manifest: NOSIGNATURE
		rftoolspower-1.20-6.0.1.jar                       |RFToolsPower                  |rftoolspower                  |1.20-6.0.1          |DONE      |Manifest: NOSIGNATURE
		ExtraDisks-1.20.1-3.0.2.jar                       |Extra Disks                   |extradisks                    |1.20.1-3.0.2        |DONE      |Manifest: NOSIGNATURE
		EdivadLib-1.20.1-2.0.1.jar                        |EdivadLib                     |edivadlib                     |2.0.1               |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-2001.2.5.jar                     |FTB Chunks                    |ftbchunks                     |2001.2.5            |DONE      |Manifest: NOSIGNATURE
		toofast-1.20-0.4.3.5.jar                          |Too Fast                      |toofast                       |0.4.3.5             |DONE      |Manifest: NOSIGNATURE
		FasterLadderClimbing-1.20.1-0.2.10.jar            |Faster Ladder Climbing        |fasterladderclimbing          |0.2.10              |DONE      |Manifest: NOSIGNATURE
		infernalmobs-1.20.1.1.jar                         |Infernal Mobs                 |infernalmobs                  |1.20.1.1            |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.20.x-2.1.58-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.58-1.20.x       |DONE      |Manifest: NOSIGNATURE
		craftingtweaks-forge-1.20-18.2.2.jar              |CraftingTweaks                |craftingtweaks                |18.2.2              |DONE      |Manifest: NOSIGNATURE
		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		toomanyglyphs-1.20.1-2.3.2.12345.jar              |Too Many Glyphs               |toomanyglyphs                 |2.3.2.12345         |DONE      |Manifest: NOSIGNATURE
		smoothchunk-1.20.1-3.5.jar                        |Smoothchunk mod               |smoothchunk                   |1.20.1-3.5          |DONE      |Manifest: NOSIGNATURE
		rftoolsutility-1.20-6.0.5.jar                     |RFToolsUtility                |rftoolsutility                |1.20-6.0.5          |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.20.1-10.0.1.jar                     |The One Probe                 |theoneprobe                   |1.20.1-10.0.1       |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.1.4.jar             |TerraBlender                  |terrablender                  |3.0.1.4             |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.592.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.592          |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.9.7-forge.jar                    |Moonlight Library             |moonlight                     |1.20-2.9.7          |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.20-2.25.jar                 |Mouse Tweaks                  |mousetweaks                   |2.25                |DONE      |Manifest: NOSIGNATURE
		ToolBelt-1.20-1.20.0.jar                          |Tool Belt                     |toolbelt                      |1.20.0              |DONE      |Manifest: NOSIGNATURE
		titanium-1.20.1-3.8.25.jar                        |Titanium                      |titanium                      |3.8.25              |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.13.14+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.14+1.20.1      |DONE      |Manifest: NOSIGNATURE
		nethersdelight-1.20.1-4.0.jar                     |Nether's Delight              |nethersdelight                |1.20.1-4.0          |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.20.1-4.1.jar                      |betterfpsdist mod             |betterfpsdist                 |1.20.1-4.1          |DONE      |Manifest: NOSIGNATURE
		rftoolsbuilder-1.20-6.0.4.jar                     |RFToolsBuilder                |rftoolsbuilder                |1.20-6.0.4          |DONE      |Manifest: NOSIGNATURE
		dimdungeons-180-forge-1.20.0.jar                  |Dimensional Dungeons          |dimdungeons                   |180                 |DONE      |Manifest: NOSIGNATURE
		brutalbosses-1.20.1-6.6.jar                       |brutalbosses mod              |brutalbosses                  |1.20.1-6.6          |DONE      |Manifest: NOSIGNATURE
		Rats-1.20.1-8.1.2.jar                             |Rats                          |rats                          |1.20.1-8.1.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.20-universal.jar                |Forge                         |forge                         |47.2.20             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		gravestone-1.20.1-1.0.10.jar                      |Gravestone Mod                |gravestone                    |1.20.1-1.0.10       |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.49.2+1.20.1.jar                 |Polymorph                     |polymorph                     |0.49.2+1.20.1       |DONE      |Manifest: NOSIGNATURE
		JustEnoughProfessions-forge-1.20.1-3.0.1.jar      |Just Enough Professions (JEP) |justenoughprofessions         |3.0.1               |DONE      |Manifest: NOSIGNATURE
		storagedrawers-1.20.1-12.0.2.jar                  |Storage Drawers               |storagedrawers                |12.0.2              |DONE      |Manifest: NOSIGNATURE
		irons_spellbooks-1.20.1-2.2.2.jar                 |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.20.1-2.2.2        |DONE      |Manifest: NOSIGNATURE
		buildinggadgets2-1.0.6.jar                        |Building Gadgets 2            |buildinggadgets2              |1.0.6               |DONE      |Manifest: NOSIGNATURE
		oceansdelight-1.0.2-1.20.jar                      |Ocean's Delight               |oceansdelight                 |1.0.2-1.20          |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		lootr-1.20-0.7.31.76.jar                          |Lootr                         |lootr                         |0.7.30.75           |DONE      |Manifest: NOSIGNATURE
		solcarrot-1.20.1-1.15.1.jar                       |Spice of Life: Carrot Edition |solcarrot                     |1.15.1              |DONE      |Manifest: NOSIGNATURE
		chunksending-1.20.1-2.8.jar                       |chunksending mod              |chunksending                  |1.20.1-2.8          |DONE      |Manifest: NOSIGNATURE
		chisels-and-bits-forge-1.4.145.jar                |chisels-and-bits              |chiselsandbits                |1.4.145             |DONE      |Manifest: NOSIGNATURE
		cristellib-1.1.5-forge.jar                        |Cristel Lib                   |cristellib                    |1.1.5               |DONE      |Manifest: NOSIGNATURE
		ad_astra-forge-1.20.1-1.15.5.jar                  |Ad Astra                      |ad_astra                      |1.15.5              |DONE      |Manifest: NOSIGNATURE

**Comment by iron431** [comment]
> at net.silvertide.pmmo_spellbooks_compat.events.EventHandler.entityHealedEvent(EventHandler.java:33) ~[pmmo_spellbooks_compat-1.20.1-1.0.2.jar%23320!/:1.20.1-1.0.2] {re:classloading}

this is an issue with pmmo compat
