### ISSUE TITLE
Decrepit Flamberge crashes the server [Bug] 

### ISSUE THREAD

**Issue by Valacchia** [iron431/Irons-Spells-n-Spellbooks#306]
### Observed behaviour

The use of the Decrepit Flamberge can make the server crash, not just the game, not just for the player holding the Flamberge, but the entire server. 
Basically it happens sometimes when interacting with an hostile entity, whether attacking them or using the spell associated with the weapon.
After the crash of the server, the player that made the server crash in this way, whenever tries to re-enter the server, make the server crash again immediatly.

### Expected behaviour

Being able to use the Decrepit Flamberge without the risk of randomly obliterating the server

### Steps to reproduce

1. Wield Decrepit Flamberge
2. Eventually reproduce the setup: Mending Enchantment + Bloodstep Lv2 Spell infused
3. Play with the weapon

N.B. It may be of use knowing that I was wearing Scarecrow Coat + Scarecrow Leggings + Scarecrow Boots + Tarnished Crown

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

1.20.1

### Other mods

Artifacts (9.2.0)- https://www.curseforge.com/minecraft/mc-mods/artifacts
Realm RPG: Creep & Crop (1.0.2) - https://www.curseforge.com/minecraft/mc-mods/realm-rpg-creep-crop      <----- A couple of times attacking creeplings, one time attacking a halloweed
Realm RPG: Imps & Demons (0.9.0) - https://www.curseforge.com/minecraft/mc-mods/realm-rpg-imps-demons      <------ One time attacking an imp
The Graveyard (2.6.1) - https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge      <----- One time attacking a lesser ghoul
Better Combat (1.8.1) - https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus
Sophisticated Backpacks (3.18.66.941) - https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

**Comment by lab3** [comment]
@Valacchia we need a crashlog or full server log to look into this

**Comment by Valacchia** [comment]
I didn't have crashlogs, but after lots of raw testing I managed to find the problem, and it wasn't anything related your awesome mod which reaffirms itself as one of the best mods around.

I made this bug report too soon, but I was genuinely convinced that was a problem of the sword 'cause the issue appeared on 2 people that are the only 2 in the server that have just started using that sword (and due to an unfortunate coincidence, both of them had just activated a perk from another mod at the same time that none had even considered, and that perk turned out to be the actual cause of the crash).

So yeah, problem solved, I hope you didn't waste any time 'cause of me, I am really sorry

**Comment by lab3** [comment]
No worries. Thanks for the follow up.
