### ISSUE TITLE
Mana Bar Mover?

### ISSUE THREAD

**Issue by Merancapeman** [iron431/Irons-Spells-n-Spellbooks#308]
### Feature description

I'm baffled this isn't an option.

### How it improves the player experience

By not being annoyingly in a weird or unmanageable spot?!

**Comment by kaairu** [comment]
look at the configs lil bro

**Comment by Merancapeman** [comment]
> look at the configs lil bro

If that's true then f*** me for real, I've been coding all day getting frustrated and if I missed something as simple as that I'm truly a moron. Sorry.
