### ISSUE TITLE
Armor dyeing

### ISSUE THREAD

**Issue by BobtheBromosapien** [iron431/Irons-Spells-n-Spellbooks#309]
### Feature description

Allow for many of the sets like the Wandering Magician and the Elemental Mancer sets (Pyromancer, Cryomancer, ect.) and others to be dyed.

### How it improves the player experience

This will allow for color coordination between various armor pieces from this pack and other mod packs too. Lets say I wanted to wear the hat from Electromancer, the chest and legs from pyromancer and the boots from the priest leggings. The outfit looks horrible. It is blue, copper, red, black, white and gold. If we were able to dye the gear, you could make the outfit look great, and even work with other mod armor too!

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
