### ISSUE TITLE
[Bug] Tooltip not displaying with Mindful Darkness

### ISSUE THREAD

**Issue by WenXin20** [iron431/Irons-Spells-n-Spellbooks#311]
### Observed behaviour

The error tooltip appears to be broken, possibly an incompatibility with [Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips).

![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/12000593/8b5f47ae-9433-40a1-aec5-6bd3a9e3a302)

Scroll used:
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/12000593/cf258e72-64c1-4301-96b6-39c31a65802b)

### Expected behaviour

The error tooltip should render.

### Steps to reproduce

1. Install [Legendary Tooltips](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)
2. Attempt to apply a scroll that won't work

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.2.2

### Forge version

1.20.1-47.2.20

### Other mods

Legendary Tooltips v1.4.5

**Comment by iron431** [comment]
if legendary tooltips bricks all other mods' tooltips, that's an issue with them. you also seem to be using a wealth of other gui-changing addons, which we do not support

**Comment by lab3** [comment]
@WenXin20 i think you should report this to them.

**Comment by WenXin20** [comment]
This is the only mod I've seen Legendary Tooltips not work with. It does not break most mod tooltips. But I'll try reporting it to them. 
The other two mods, one just makes a trash slot, and when disabled from that gui, makes no changes. The other one at the top adds a dark mode to guis, which also makes no difference when disabled.

**Comment by WenXin20** [comment]
Hmm, now I am not sure what might be causing this, but it is unrelated to Legendary Tooltips, here it is removed. 

![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/12000593/bb43d9e6-1daa-4a8b-b0bc-ca45575926e9)

**Comment by WenXin20** [comment]
Looks like it was caused by Mindful Darkness, I had forgotten that it changes font brightness. I'll report it there.
