### ISSUE TITLE
[Bug] Apotheosis spellbook modifiers do not work when the book is held in offhand

### ISSUE THREAD

**Issue by aallfik11** [iron431/Irons-Spells-n-Spellbooks#313]
### Observed behaviour

When putting a spellbook into the offhand, all the buffs from apotheosis like cast time reduction, bonus mana etc. no longer apply

### Expected behaviour

When putting a spellbook into the offhand, their additional stats and modifiers should apply
(I'm on a version 1 older than newest but I haven't noticed this problem being mentioned in the changelog)

### Steps to reproduce

1. Have iron's spellbooks and apotheosis installed (I'm doing it on ATM9 with Unobtainium Spellbook if that matters)
2. Reforge the spellbook to have some observable, high bonuses (like 70% cast time reduction/cooldown reduction)
3. Try casting a spell in the main and offhand, observing that their cast time and cooldown differ

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-2.2.1

### Forge version

1.20.1 - 47.2.19

### Other mods

Playing on Allthemods 9 version 0.2.39

**Comment by SiverDX** [comment]
could add `EquipmentSlot.OFFHAND` in the array here, should apply then

https://github.com/iron431/irons-spells-n-spellbooks/blob/b5e838866fffe7bcec582225ad0b4b8e9c5b87d2/src/main/java/io/redspace/ironsspellbooks/compat/apotheosis/ApotheosisHandler.java#L10

**Comment by iron431** [comment]
@aallfik11 do other items, such as bows, give their attribute bonus while in the offhand?

**Comment by SiverDX** [comment]
> @aallfik11 do other items, such as bows, give their attribute bonus while in the offhand?

see

https://github.com/Shadows-of-Fire/Apotheosis/blob/c311d7004bb78ac39cb5fd5a2b59e50c5c346192/src/main/java/dev/shadowsoffire/apotheosis/adventure/loot/LootCategory.java#L48-L61

for reference

**Comment by aallfik11** [comment]
> @aallfik11 do other items, such as bows, give their attribute bonus while in the offhand?

I must admit I haven't tested it, but I imagine that would be the case, given that apotheosis supports shields as well.

**Comment by iron431** [comment]
fixed in 3.0.0
