### ISSUE TITLE
Strange Tetra arcane Ingot Shield mana buff not interacting with main hand arcane ingot weapon [Bug] 

### ISSUE THREAD

**Issue by CannerCrebes** [iron431/Irons-Spells-n-Spellbooks#314]
### Observed behaviour

When having the shield equipped that boosts maximum mana and switching to a weapon that increases your mana even further the two values are not added and are instead replaced. Once you un-equip the weapon with the mana buff your max mana will then be reduced to the amount you had before the shield is equipped even though you are still wearing it.

### Expected behaviour

The two mana buffs would stack and your mana buff from your shield would be kept when un-equipping a mana buffing item from your main hand

### Steps to reproduce

1. Create arcane shield in tetra
2. create arcane sword with tetra
3. equip shield (+50mana)
4. equip sword (no change)
5. un-equip sword (...)
6. where did the buff go?
<img width="1440" alt="Screenshot 2024-02-11 at 8 25 44 AM" src="https://github.com/iron431/irons-spells-n-spellbooks/assets/149726528/211df752-946a-409a-8ee5-5959e80cae9a">
<img width="1440" alt="Screenshot 2024-02-11 at 8 25 53 AM" src="https://github.com/iron431/irons-spells-n-spellbooks/assets/149726528/17ed912e-3ffa-4745-b04e-5f9f5e50d197">
<img width="1440" alt="Screenshot 2024-02-11 at 8 25 56 AM" src="https://github.com/iron431/irons-spells-n-spellbooks/assets/149726528/4db2df7b-7dc1-4284-b7fc-0c17b1ff13fd">
<img width="1440" alt="Screenshot 2024-02-11 at 8 26 11 AM" src="https://github.com/iron431/irons-spells-n-spellbooks/assets/149726528/27a0c975-40dd-4fda-9cc6-e2448adf8dfd">
<img width="1440" alt="Screenshot 2024-02-11 at 8 26 16 AM" src="https://github.com/iron431/irons-spells-n-spellbooks/assets/149726528/37970961-80a9-461a-a57b-fda12d76c66e">
<img width="1440" alt="Screenshot 2024-02-11 at 8 26 22 AM" src="https://github.com/iron431/irons-spells-n-spellbooks/assets/149726528/e1d76a31-2934-4ef3-b8a3-f7b9e9b8a485">

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

Most likely a test version

### Forge version

47.2.19

### Other mods

Modding Magic Server

**Comment by iron431** [comment]
This seems to be an issue on Tetra's end, specifically with duplicate attribute UUIDs. Being that tetra's latest versions are closed source, I cannot investigate this further
