### ISSUE TITLE
Epic fight compatibility

### ISSUE THREAD

**Issue by Bodex111** [iron431/Irons-Spells-n-Spellbooks#315]
### Feature description

When using Epic fight along with irons spells and spellbooks, casting in first preson is bugged. When you cast a spell until the end of casting your pov is locked in player's head, preventing from seeing anything except for head's insides. Please release a fix.

### How it improves the player experience

Being able  to see when casting in first person

**Comment by anthraxJM** [comment]
I just had the same problem and solved it by turning on "filter animations" in the epic fights GUI. What a shame I didn't see your message months ago :c

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
