### ISSUE TITLE
[Sinytra Connector] "Can't find attribute irons_spellbooks:lightning_magic_resist" Crash (Better Nether)

### ISSUE THREAD

**Issue by KszKszXDD** [iron431/Irons-Spells-n-Spellbooks#316]
### Observed behaviour

Got the "java.lang.IllegalArgumentException: Can't find attribute irons_spellbooks:lightning_magic_resist", and the game crashed.
It happened when tried to cast a lightning lance spell on a mob from "Better Nether". Now the Better Nether is a fabric mod, and it only works because of a "Sinytra Connector". I know it's prob a issue of using forge and fabric mods together, but is there a way we could get a work-around?

### Expected behaviour

Not crashing i think, tho not really

### Steps to reproduce

Already explained

### Server Type

Single Player

### Crashlog

https://gist.github.com/KszKszXDD/88bfca0a27fc580cfb01726f36bf72ad

### Iron's Spells N Spellbooks version

1.20.1-2.2.2

### Forge version

1.20.1 forge47.2.20

### Other mods

In crash-log

**Comment by iron431** [comment]
That must mean they are not firing the forge attribute event, or that it does not include fabric mobs. We do not support the use of connector
