### ISSUE TITLE
[Bug] Earthquake spell underground crashes modpack server

### ISSUE THREAD

**Issue by Mercylayne** [iron431/Irons-Spells-n-Spellbooks#317]
### Observed behaviour

After player casted Earthquake spell in the 2x1 tunnel underground server starts to ticking too high, fps dropped low, ram usage goes high with everyone who stands close to epicenter, chunks stopped generating.

I used to reproduce same thing in singleplayer - same issue.

### Expected behaviour

Earthquake spell will casts with the same effect like on surface, and does not crash server when used underground

### Steps to reproduce

1. Dig staircase-like tunnel 2x1 straight under the ground to the y coord below 30 or even under 0
2. Turn around facing to the place where are you come from
3. Turn your vision up while beign under the ground in the tunnel
3. Cast spell Earthquake 3+ level on the blocks that in your sight
4. Do it 1-2 times and wait until spell time goes off
5. Check your FPS rate and RAM usage

I've done it in singleplayer and on the server, crash happened in both cases

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Mercylayne/e61a6c933e13f8282d7875b48545c765

### Iron's Spells N Spellbooks version

1.20.1-2.2.2

### Forge version

1.20.1. - 47.2.20

### Other mods

![explorer_eG6T83IdzC](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/318d84d8-5b0b-4123-b6b1-98dcbdd20a15)
![explorer_9cGQuUo4Pc](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/6dc282c8-7fcd-4a0e-a836-39ae1f5e4795)
![explorer_ml1dP2nuy0](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/06f28b15-cf8f-4b6a-b238-beeadd58bac9)
![explorer_xlOwdWb8U8](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/7a4c3bf7-c845-4b78-bef2-840d91e56d82)
![explorer_VB4KZb585M](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/18a25240-6481-4082-aa90-881784546901)
![explorer_5oUGfXpq2B](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/4f30187b-2e47-4247-96dd-155f0e6b3023)
![explorer_67QTRKXK9L](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/ac6ea503-90c4-4830-8782-66178998039c)
![explorer_CS5hLWUSS5](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/ef24ce18-e9ca-4a03-9161-5591d3e0eddb)
![explorer_D7iDvU0WM5](https://github.com/iron431/irons-spells-n-spellbooks/assets/71908193/be980fea-f82a-45f0-ac62-0ec960cc674f)

**Comment by SiverDX** [comment]
https://github.com/iron431/irons-spells-n-spellbooks/blob/b5e838866fffe7bcec582225ad0b4b8e9c5b87d2/src/main/java/io/redspace/ironsspellbooks/entity/spells/EarthquakeAoe.java#L140-L147

shouldn't there be a cap on how many recursive calls this can make (in addition to the air check)?
like a max. height (from the origin)

**Comment by iron431** [comment]
> shouldn't there be a cap on how many recursive calls this can make (in addition to the air check)?

yeah i already fixed it on curio casting

**Comment by iron431** [comment]
fixed in 3.0.0
