### ISSUE TITLE
[Bug] Problem with apotheosis reforging affixes

### ISSUE THREAD

**Issue by car45167** [iron431/Irons-Spells-n-Spellbooks#319]
### Observed behaviour

I built the latest curio 1.20.1 from github and noticed that reforging a spellbook and equipping it in the curio slot just don't give the bonuses from the affixes. The bonuses are correctly applied when the book is helded in hand.

### Expected behaviour

I expected that the increased stats from the reforged book would be added to the character

### Steps to reproduce

1) Reforge a book( preferably with mana bonus)
2) Equip in the curio slot)
3) Hold it in hand to observe the difference in mana

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 curio

### Forge version

43.2.0

**Comment by SiverDX** [comment]
apotheosis does not support curios
you will need to use https://www.curseforge.com/minecraft/mc-mods/apothic-curios and configure it yourself
