### ISSUE TITLE
[Bug] When using shaders in first person mage armor is rendered at a distance of 100 blocks next to the crosshair

### ISSUE THREAD

**Issue by John1740** [iron431/Irons-Spells-n-Spellbooks#32]
### Observed behaviour

When using a shader with rubidium and oculus worn mage armor gets rendered at a distance of exaclty 100 block in the direction of the crosshair when in first person. 
![normal](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/133345888/f2e7414f-48ff-4414-90b1-6ad6fddad856)

Much easier to see when using a spy glass
![spyglass](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/133345888/5414b373-6972-4fda-a2b1-c71177f304ec)

The rendered armor mimics the movement of the player(walking, crouching, jumping) and when ever it leaves the small box around the crosshair it gets teleported in the center agian. This only happens with the armor added by this mod. I tested it with multiple shaders for example BSL and complementary reimagined. The only mods I used are the required mods and oculus and rubidium.

I tested alot of other mods that add new armor and almost no other mod had this issue. The only mod I found that had the same issue is Ars Nouveau. This might be an issue with Oculus but it would be nice if armors of this mod were compatible with Oculus. 

### Expected behaviour

Armor should not get rendered

### Steps to reproduce

Install required mods + oculus and rubidum + use a shader for forge 1.19.2 -43.2.3.
Then look in a direction that is unblocked for at least 100 blocks for example the sky.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

v1.0.8 for 1.19.2

### Forge version

1.19.2 - 43.2.3

### Other mods

requried mods + oculus and rubidum

**Comment by iron431** [comment]
I noticed this when making the trailer, and it seems to be GeckoLib /Oculus issue. The only other reports of this I can find are the one you commented on Oculus https://github.com/Asek3/Oculus/issues/360 and https://github.com/baileyholl/Ars-Nouveau/issues/962. I'm sure it happens with other mods that use GeckoLib for custom armor models, but maybe there aren't many. Considering it's an issue with libraries and not this mod itself, I'm just gonna close this for now. Feel free to reply or add additional information.

**Comment by John1740** [comment]
While GeckoLib is listed as a required mod on the modpage, for [version 1.19.2 of Ars Nouveau](https://legacy.curseforge.com/minecraft/mc-mods/ars-nouveau/files/4512859) GeckoLib is not listed as a required dependency anymore and it works for me without installing GeckoLib. And this issue happens for Ars Nouveau even if i dont have GeckoLib istalled.

I tested a few armor mods that require GeckoLib and at least the mod [Knight Quest](https://legacy.curseforge.com/minecraft/mc-mods/knight-quest) seemed to add some custom models however i could not reproduce this issue with any other mod than Ars Nouveau.

**Comment by iron431** [comment]
> I tested a few armor mods that require GeckoLib and at least the mod [Knight Quest](https://legacy.curseforge.com/minecraft/mc-mods/knight-quest) seemed to add some custom models however i could not reproduce this issue with any other mod than Ars Nouveau.

I was also playing around with Knight Quest last night while posting this. While Knight Quest makes custom armor models, the only thing they use GeckoLib for is the mobs. I'm not sure what to make of the Ars Nouveau still breaking without geckolib however.
