### ISSUE TITLE
Allying Others

### ISSUE THREAD

**Issue by CuddleCurmet** [iron431/Irons-Spells-n-Spellbooks#320]
### Observed behaviour

This isnt really a bug report but my friend and i need help, we cant find anywhere how to ally eachother we just need to know what to do

### Expected behaviour

same as above?

### Steps to reproduce

.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1 2.2.2

### Forge version

1.20.1

**Comment by kaairu** [comment]
create a team
https://minecraft.wiki/w/Commands/team

**Comment by iron431** [comment]
team, or turn off server pvp if you do not want pvp

**Comment by CuddleCurmet** [comment]
> team, or turn off server pvp if you do not want pvp

we just tried the teams, it didnt work, the problem is that healing circle doesnt seem to work on him but it works on me?

**Comment by iron431** [comment]
> we just tried the teams, it didnt work, the problem is that healing circle doesnt seem to work on him but it works on me?

That would imply you're on different teams. Join the same team and disable the team's friendly fire
