### ISSUE TITLE
[Bug] Make Iron Spells Monsters not spawn in forge:no_default_monsters biome tag 

### ISSUE THREAD

**Issue by TelepathicGrunt** [iron431/Irons-Spells-n-Spellbooks#321]
### Observed behaviour

Some mods like Terralith or Alex's Caves are tagging their biomes as `forge:no_default_monsters` in an attempt to help show other mods that their biomes should not have monsters. Iron Spells is spawning Necromancers in these biomes still
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/40846040/4ac7353c-c1d0-4f8f-a341-dfc34823353a)

### Expected behaviour

Monsters should not be added to Mushroom Biome, not added to Deep Dark, and not to `forge:no_default_monsters` tagged biomes. 

In 1.21, this `forge:no_default_monsters` is going to become `c:no_default_monsters` tag and added to NeoForge and Fabric modloaders themselves as a default tag. For now, mods are defining the tag themselves in forge so best to add and check it now so things work better now and better prepared for future.

### Steps to reproduce

Added TACT mod, Alex's Caves mod, and Iron Spells mod. Go locate Primordial Cave by locate command and go to it. See Necromancers spawning

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.2.2

### Forge version

1.20.1-47.2.20

### Other mods

TACT
Alex's Caves
Terralith (They use `forge:no_default_monsters` for some of their biomes. I don't remember which)

**Comment by iron431** [comment]
will definitely do this. how long has forge:no_default_monsters been a thing? Last time I asked in the forge discord, there didn't seem to be a universal tag

**Comment by TelepathicGrunt** [comment]
It started in my unify tag pr for 1.21 here: https://github.com/neoforged/NeoForge/pull/135

Then I PRed the 1.20.1 `forge:no_default_monsters` tag to Alex's Mobs and Alex's Caves to resolve the issue between those two mods when i tag Alex's Cave biome properly as overworld biomes.
https://github.com/AlexModGuy/AlexsMobs/pull/1896
https://github.com/AlexModGuy/AlexsCaves/pull/710

So concept started September 2023 and started being backported and implemented into mods in December 2023. And then adopted by Terralith. Other mod biome mods had picked this too that i don't know about. More mob mods are going to make use of this tag too as I have been contacting people that were spawning monsters in Alex's Caves Primordial Biome. It is not in Forge itself but defined by mods themselves.

So we should be seeing better compat as the tag picks up usage. Then 1.21 will make it even more visible as it gets added to modloaders themselves and that's when it'll get used even more heavily.

**Comment by iron431** [comment]
added in 3.0.0
