### ISSUE TITLE
[Bug] Inscription table is missing

### ISSUE THREAD

**Issue by Kaejuka** [iron431/Irons-Spells-n-Spellbooks#322]
### Observed behaviour

The Inscription table appears to be missing from version 1.20.1-2.2.2. It's not in JEI or the creative inventory

### Expected behaviour

the table should be available

### Steps to reproduce

install version 2.2.2

look for the item in creative

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-2.2.2

### Forge version

47.2.19

**Comment by iron431** [comment]
going to need more information 
<img width="883" alt="image" src="https://github.com/iron431/irons-spells-n-spellbooks/assets/34083081/a8c043b2-8cd0-4ac1-9e6c-cba28424d128">
