### ISSUE TITLE
[Bug] The Dead King bossbar stuck

### ISSUE THREAD

**Issue by funnycubeguy** [iron431/Irons-Spells-n-Spellbooks#326]
### Observed behaviour

The dead king bossbar is stuck at the top and the fog in the area stays. It has been a month of this and has happened twice. There is no dead king in sight.

### Expected behaviour

To go away. Add the ability to clear dead kings and bossbars/fog in the area?

### Steps to reproduce

No idea happens randomly to players on the server

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-2.2.2.jar

### Forge version

1.20.1 -  47.2.20

### Other mods

All the mods 9

**Comment by iron431** [comment]
In all liklihood, there is a Dead King entity in the area.
Run the command `/kill @e[type=irons_spellbooks:dead_king,distance=..100]` and see if that fixes it

**Comment by funnycubeguy** [comment]
Sadly this did not work. I tried it on a spawned one too and it didn't remove it

**Comment by iron431** [comment]
If the boss bar goes away when you walk away, there is still a Dead King somewhere. If this is actually a bug, it is an issue with vanilla's boss tracking and will not be worked on
