### ISSUE TITLE
[Bug] Spell Selection Wheel Not Working as Expected

### ISSUE THREAD

**Issue by lexchxn** [iron431/Irons-Spells-n-Spellbooks#328]
### Observed behaviour

In prior mod versions to 3.0.0, the Spell Selection Wheel would come up immediately when holding the button and remain open for only as long as the button was held. Releasing the button would then immediately select the hovered spell.

In mod version 3.0.0, the Spell Selection Wheel only opens immediately while not pressing any other buttons, and will remain open even if the button is not held. To select a spell in this mode, a left click is required. 
While pressing any other buttons, the menu opens anywhere from immediately to ~2 seconds after pressing the selection button down, and closes anywhere from immediately to ~2 seconds after releasing the selection button, staying open only if the selection button is held down.

### Expected behaviour

I expected the Spell Selection Wheel to come up immediately when holding the button and remain open for only as long as the button was held, selecting the hovered spell when the button is released; this was its functionality prior to 3.0.0, up to and including 2.2.2.

### Steps to reproduce

A. Version 2.2.2 or prior:
   1. Hold the Spell Selection Wheel button down while moving (or holding down any other button), then release the button. The spell wheel will open and the hovered spell will be selected instantly.

B. Version 3.0.0:
   1. Hold the Spell Selection Wheel button down while moving (or holding down any other button). Through brief repetition, there should be a noticable delay.
   2. Release the Spell Selection Wheel button while moving (or holding down any other button). There should be a noticable delay.
   3. While pressing no other buttons, press and release the Spell Selection Wheel button. The Spell Selection Wheel should remain open, and require a left click to select a spell from the menu.

Special Note: The bug report requires me to select whether this occurs in Single Player or Multiplayer. I have tested this bug on both and it occurs on both modes of play.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.0.0

### Forge version

47.2.0

### Other mods

caelus-forge-3.1.0+1.20
curios-forge-5.7.0+1.20.1
geckolib-forge-1.20.1-4.4.2
player-animation-lib-forge-1.0.2-rc1+1.20

**Comment by iron431** [comment]
I cannot reproduce this. In fact, left clicking does nothing - not select a spell, not close the wheel. No matter how many other keys  I have held or how I'm moving, the spell wheel immediately opens and closes.

**Comment by lab3** [comment]
I also tried and was unable to replicate this.  Are you using any keyboard/macro apps?

**Comment by lab3** [comment]
Can you run a /modlist and upload the results

**Comment by iron431** [comment]
> Can you run a /modlist and upload the results

@lab3 
>caelus-forge-3.1.0+1.20
curios-forge-5.7.0+1.20.1
geckolib-forge-1.20.1-4.4.2
player-animation-lib-forge-1.0.2-rc1+1.20

**Comment by lexchxn** [comment]
I am using no keyboard or macro apps, however I have narrowed the issue. It only occurs when utilizing a non-keyboard button for the Spell Selection Wheel. Any mouse button (originally tested mouse4, but confirmed that middle mouse, etc, all function this way) experiences the bug.

I can confirm from prior experience (and testing I just did to be sure) that this was not an issue prior to 3.0.0.
