### ISSUE TITLE
[Bug] Structures Not Spawning

### ISSUE THREAD

**Issue by eLmOxy** [iron431/Irons-Spells-n-Spellbooks#330]
### Observed behaviour

Me and some of my friends started to play on a LAN hosted server a while ago and I was instantly stunned by the mod. Sadly, while I was playing the mod, I noticed that non of the buildings spawn that are showcased in some youtube videos and websites. I also tried to go to the nether, using the Wayward Compass, but it did not seem to work as well. Mobs, besides the Dead King and the Necromancer, non of the mobs spawn. Because of this, it is nearly impossible to progress with the mod.

### Expected behaviour

Well, structures and mons should spawn?

### Steps to reproduce

Try to play with the SteamPunk modpack.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-2.2.1

### Forge version

1.19.2

### Other mods

SteamPunk modpack(1.19.2)

**Comment by iron431** [comment]
look harder
<img width="486" alt="image" src="https://github.com/iron431/irons-spells-n-spellbooks/assets/34083081/ca067fc4-97a0-4eda-8cc3-5dc73cdaf797">

**Comment by eLmOxy** [comment]
Shouldn't the Compass lead me there if I use it in the nether? Or do I have to be in a certain range?

**Comment by iron431** [comment]
No, the compass is for an overworld structure
