### ISSUE TITLE
[Bug] Damage source problem of a few spells

### ISSUE THREAD

**Issue by Jesse1079** [iron431/Irons-Spells-n-Spellbooks#332]
### Observed behaviour

The projectile damage from Arrow Volley and kinetic damage from Telekinesis and Gust won't count as damage dealt by a player when the spells are casted by a player.This will cause some mobs (for example, the Blaze) to not drop the items they're supposed to.

### Expected behaviour

The aforementioned spells (or at least Arrow Volley projectiles) should give the credit of dealing damage to their casters.

### Steps to reproduce

1.Kill a blaze with Arrow Volley, Gust or Telekinesis
2.There will be no item or exp drops

### Server Type

Single Player

### Crashlog

This is not a Crash-related problem

### Iron's Spells N Spellbooks version

1.20.1 - 3.0.0

### Forge version

NeoForge 47.1.100

### Other mods

MmmMmmMmmmmm (the testing dummy mod) 1.20-1.8.14
I noticed the bug when I hit a dummy with Arrow Volley and no damage numbers were displayed.

**Comment by iron431** [comment]
For arrow volley, this is a bug. For the other spells mentioned, they don't directly do damage and so there is no way around that.

**Comment by Jesse1079** [comment]
> For arrow volley, this is a bug. For the other spells mentioned, they don't directly do damage and so there is no way around that.

Thank you!

**Comment by Jesse1079** [comment]
Unfortunately, the bug seems to be more persistent than expected. I tested version 3.0.1 snd Arrow Volley kills still won't count as player kills.

**Comment by iron431** [comment]
actually fixed in 3.1.0
