### ISSUE TITLE
[Bug] Spellbar Y offset can't be modified on 1.20.1

### ISSUE THREAD

**Issue by AnasterianSunstrider** [iron431/Irons-Spells-n-Spellbooks#333]
### Observed behaviour

No matter what I type into the Y offset the spellbar doesn't move. It only works with X and even with that it moves diagonally instead of up and down.

### Expected behaviour

I expected the spellbar to move accordingly on the Y axis.

### Steps to reproduce

Edit the configuration with a config mod,or edit it manually and restart the game.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.0.1

### Forge version

47.2.19

### Other mods

Tried it with no other mods but i still had the same issue.

**Comment by iron431** [comment]
A typo lead to it using the Y config for both offsets

**Comment by giova-01** [comment]
Hello, this is happening to me in 1.19.2, but with the X offset

**Comment by iron431** [comment]
fixed in 3.1.0
