### ISSUE TITLE
[Bug] inscription table can CTD and eat spell book when looking at jei recipe with book in curios

### ISSUE THREAD

**Issue by hpf3** [iron431/Irons-Spells-n-Spellbooks#337]
### Observed behaviour

if the spell book is in the curios slot and a spell is selected in the inscription table, the client will crash and the book will be deleted (happens in both singleplayer and dedicated server, but on dedicated the server keeps running like nothing happened, asside from the book being gone on re-connect)

### Expected behaviour

client not crashing, or at the very least, the book not being destroyed

### Steps to reproduce

0. have jei & curios installed
1. get any spellbook with any spell in it
2. put spell book in curios slot
3. open inscription table and select a spell
4. press 'R' (jei view recipe keybind) on book or spell, then press esc
5. CTD, opening world/server again will have missing book

video: https://youtu.be/Wv5y43yKpwY

### Server Type

Single Player

### Crashlog

https://gist.github.com/hpf3/fc62e8835f4f08c983db4fc1d6551a69

### Iron's Spells N Spellbooks version

1.20.1-3.0.1

### Forge version

47.2.0

### Other mods

Caelus API 3.1.0+1.20
Curios API 5.7.0+1.20.1
GeckoLib 4 4.4.2
Just Enough Items 15.3.0.4
Player Animator 1.0.2-rc1+1.20

**Comment by iron431** [comment]
This is actually a few issue wrapped together.

The book not showing back up is client side and visual only, you can actually click the slot and take the book out

The crash is due to the client trying to render the book when its missing, and is an easy fix.

And the item disappearing is because the menu isn't properly clearing itself due to crashing, which may just be a vanilla bug, but I need to look into it more.

**Comment by Cinderheart** [comment]
Have a similar issue. Book is gone after using JEI while at an inscription table, also with a Crash to Desktop. Does not appear to be visual only, even breaking the table wont get it back.

**Comment by iron431** [comment]
Right, crashing is not visual only. The base bug is visual only, the crash is an unrelated issue

**Comment by Cinderheart** [comment]
I meant the book disappearing wasn't visual only.

**Comment by iron431** [comment]
fixed in 3.1.0
