### ISSUE TITLE
Add Gamepad Compatibity

### ISSUE THREAD

**Issue by chosti-factor** [iron431/Irons-Spells-n-Spellbooks#339]
### Feature description

Hi. Any chance you'd consider adding a keybind for scrolling through the spells? It would make gamepad compatibility much easier. The default could remain the same (mouse wheel). Thanks.

### How it improves the player experience

While in combat, you could use multiple spells without switching from controller to keyboard.

**Comment by CallyKoh** [comment]
This keybind exists afaik, it is set to shift by default.

**Comment by iron431** [comment]
I think keybinds to move forward/backward were what was meant. However, considering I can't tell, definitely not going to work on this

**Comment by chosti-factor** [comment]
Yes, the keybind to move forward/backward between spells is what I meant. However, I understand if you don't want to work on any additional features.
