### ISSUE TITLE
[Bug] Crash when seeing recipes with JEI

### ISSUE THREAD

**Issue by LeKripiY** [iron431/Irons-Spells-n-Spellbooks#34]
### Observed behaviour

Pressed [U] to see what could be done using the amethyst anvil, game crashed.

### Expected behaviour

Seeing what I can make using the amethyst anvil.

### Steps to reproduce

1. have JEI and Iron's Spells 'n Spellbooks installed
2. clicking on "view reciped" a.k.a the big arrow inside of the amethyst anvil GUI
3. crash

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.0.9

### Forge version

1.19.2 43.2.8

### Other mods

Just enough items

**Comment by iron431** [comment]
Can you please attach a crashlog?

**Comment by lab3** [comment]
@LeKripiY are you able to get us the crash log?

**Comment by LeKripiY** [comment]
Sorry for the wait, here's a new crash report with the latest version of the mod: 
[crash-2023-05-20_11.12.51-client.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/11521953/crash-2023-05-20_11.12.51-client.txt)

**Comment by lab3** [comment]
Hey @LeKripiY, our mod is integrated with JEI version 11.6.0.1013 and should work with anything newer than that. It looks like you are using 11.4.0.286 which is a much earlier version of JEI.  I think our mod might work with some earlier versions of JEI but not 2 major versions back.
