### ISSUE TITLE
[Suggestion] Disable guide book in inventory by default

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#340]
### Feature description

In-game documentation is important, but spawning with an inventory full of guide books from random mods is an overwhelming first impression.
Therefore, I would like to suggest that you consider disabling giving the book by default and instead provide it in some other manner - for example, as loot in villages or as an easy crafting recipe.

Yes, I am aware it can be turned off, but I would encourage you to find more intuitive ways to teach players how to use your mod than with book items dumped into the inventory on spawn.

### How it improves the player experience

Guide books only add to early game confusion and clutter while taking away from the immersion.

**Comment by MarioSMB** [comment]
To be clear, I am very well aware that this book can be disabled with a datapack and I have already done so.  
I am making this suggestion to benefit the base mod so that others can have a better experience in the future.

**Comment by iron431** [comment]
There are a couple of scenarios involving the guidebook that illustrate how this feature is not needed:
1. You're doing a playthrough primarily or singularly with this mod, so there is no guidebook clutter and the guidebook will be useful
2. You're playing in a modpack and do not know what this mod is, so the guidebook will be useful because it introduces you into the mod 
3. You're playing in a modpack and the modpack creator doesn't want guidebook clutter, in which case they can turn it off
4. You didn't install patchouli because you want to preserve "immersion", so there is no guidebook

This will not be worked on

**Comment by MarioSMB** [comment]
I am sorry to hear that yet another mod will be leaving these annoying books on by default - they are such a poor way to engage the player with the world you're trying to build.  

At least a hotbar full of random books the average player will never read isn't as bad as the old days when your entire inventory was packed full of "helpful" items when loading in. Baby steps...  

EDIT: Apologies if that comes off as rude, it's just that Patchouli is a hard dependency in some mods and whenever I create a new world my *entire* hotbar is taken by random flashy guide books that require digging around in datapacks to disable. It's completely unnecessary and the mod is no less intuitive for not including them.

**Comment by pa267** [comment]
> To be clear, I am very well aware that this book can be disabled with a datapack and I have already done so. I am making this suggestion to benefit the base mod so that others can have a better experience in the future.

Can you share this datapack? I can't seem to figure out how to set it up.

**Comment by MarioSMB** [comment]
Yeah... it's a terrible system currently, forcing users to learn how to work with datapacks just to get rid of random starting books - something that shouldn't even need to exist with an intuitive design.  

Regardless, this should do the trick: 
[disable_irons_spellbook_guide.zip](https://github.com/user-attachments/files/18462812/disable_irons_spellbook_guide.zip)

**Comment by iron431** [comment]
i'm waiting for the pr

**Comment by MarioSMB** [comment]
Are you genuinely interested in finding a better way to provide documentation than dumping a guide book in players' inventories on spawn?  
If that isn't just a way of trying to make me put in the time and effort to submit some solution so you can shoot it down (like the rest of my feedback), then I don't mind discussing alternatives.  

I've written a rather lengthy post on the topic to the Simply Swords developers who also give players guide books [here](https://github.com/Sweenus/SimplySwords/issues/154#issuecomment-2051079603).  
The TL;DR of it is that there are a few ways to do it without starting item spam:  
- Put the guide book in the starting (bonus) chest loot pool, accessible to those who want starting gear and easy access to guides
- Emphasize intuitivity and learning by playing, this is already done fairly well in Iron's Spells & Spellbooks
- Make the guide easily craftable or accessed by early-game means (village loot tables, recipe book visibility)

There's nothing wrong with providing in-game documentation, and for the record this is mostly Patchouli's fault for not providing an interface to access guides from a single GUI (the only attempt at such being from someone who decided belligerently to make it a Fabric-only extension).  
But I believe it is very conceded and short-sighted to make players spawn with these guide books - when several mods do this and the only way to remove them is via custom datapacks it becomes an incredibly tedious and frustating issue that just gives a poor first impression of your mod.
