### ISSUE TITLE
quick cast spell keybind

### ISSUE THREAD

**Issue by Hello-Liar** [iron431/Irons-Spells-n-Spellbooks#344]
### Observed behaviour

Imbued items like chest plates, or the tarnished crown don't have a quick cast key bind option at least from my knowledge.

### Expected behaviour

I was hoping for a special section just for quick casting armor imbuement.

### Steps to reproduce

check controls

### Server Type

Single Player

### Crashlog

none

### Iron's Spells N Spellbooks version

1.20.1 v3.0.1 

### Forge version

1.20.1

**Comment by Hello-Liar** [comment]
pls help

**Comment by iron431** [comment]
they use the same keybinds as other quick casts
