### ISSUE TITLE
Setting to remove Guidebook on initial spawn

### ISSUE THREAD

**Issue by Avanstarwa** [iron431/Irons-Spells-n-Spellbooks#346]
### Feature description

Id like a server setting to not be given the guidebook when joining a world the first time.

### How it improves the player experience

Many players dont like being given dozens of guidebooks on startup. When you have a mod pack your inventory is normally already quite small for the many items and blocks added by many mods.

**Comment by kaairu** [comment]
just remove it via datapack

**Comment by iron431** [comment]
^
