### ISSUE TITLE
Portal Spell QoL Update

### ISSUE THREAD

**Issue by Silvertide7** [iron431/Irons-Spells-n-Spellbooks#347]
### Feature description

The portal is awesome, except when it isn't. Currently the spell has issues when placed on a block that is 1 layer. When you teleport to that portal it clips you through that 1 block layer and you fall through. This is common in multi story houses.

Also I think there should be a minimum distance that two portals can placed next to each other. I accidentally double clicked and created two portals on top of each other. These teleported me back and forth like a ping pong ball many times a second and did damage to me every time, I think simulating impact or fall damage. Aside from dying it was a great time.

Also when falling onto a portal from above I take fall damage before or as the portal triggers the teleport. So I can't jump down onto a portal and not take fall damage.

### How it improves the player experience

It makes the portals much easier to use.

**Comment by LostGameDev** [comment]
Also would be nice if portals teleported items as well currently if you through an item at them it doesn't teleport

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
