### ISSUE TITLE
[Bug] i cant see particular spells like Fireflys

### ISSUE THREAD

**Issue by CodyBullmorr** [iron431/Irons-Spells-n-Spellbooks#348]
### Observed behaviour

i cant see particular spells like Fireflys 

so my friend and i  started playing on my minecraft server with my own modpack 
i just sendet my mods folder to him and he Copyed it 

I noticed that my friend can see the Fireflies but I can't

It's not the texture pack and optifine isn't installed either

What can i do to fix it 

### Expected behaviour

When i cast the Firefly spell i don't see the Fireflys, you can only hear them

### Steps to reproduce

idk how to reproduce 

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.0.1

### Forge version

1.20.1 -47.2.18

### Other mods

ALL Mods 

1. ctov-irons-add-on-v1-2
2. [Forge]ctov-3.4.2
3. AI-Improvements-1.20-0.5.2
4. appleskin-forge-mc1.20.1-2.5.1
5. architectury-9.2.14-forge
6. ava-1.20.1-2.5.9
7. balm-forge-1.20.1-7.2.2
8. betterarcheology-1.1.7-1.20.1
9. BetterF3-7.0.2-Forge-1.20.1
10. BetterThirdPerson-Forge-1.20-1.9.0
11. bocchium-1.20.1-0.0.3
12. Bookshelf-Forge-1.20.1-20.1.9
13. buildersaddition-1.20.1-20230928a
14. caelus-forge-3.1.0+1.20
15. canary-mc1.20.1-0.3.3
16. capybaramod-1.0.0
17. charmofundying-forge-6.5.0+1.20.1
18. citadel-2.5.4-1.20.1
19. cloth-config-11.1.118-forge
20. Clumps-forge-1.20.1-12.0.0.3
21. collective-1.20.1-7.36
22. Controlling-forge-1.20.1-12.0.2
23. cristellib-1.1.5-forge
24. CullLessLeaves-Reforged-1.20.1-1.0.5
25. curios-forge-5.7.0+1.20.1
26. curious_armor_stands-1.20-5.0.1
27. deeperdarker-forge-1.20.1-1.2.1
28. DoggyTalentsNext-1.20.1-1.18.8
29. dungeons-and-taverns-3.0.3 [Forge]
30. DungeonsArise-1.20.x-2.1.58-release
31. dynview-1.20.1-3.9
32. EasierSleeping-1.20.1-2.1.3
33. EasyAnvils-v8.0.1-1.20.1-Forge
34. EasyEmerald-Forge-1.20.1-1.5.3
35. EasyMagic-v8.0.1-1.20.1-Forge
36. elytraslot-forge-6.3.0+1.20.1
37. EnchantmentDescriptions-Forge-1.20.1-17.0.14
38. entityculling-forge-1.6.2-mc1.20
39. Fallingleaves-1.20.1-2.1.0
40. FallingTree-1.20.1-4.3.4
41. fantasyfurniture-1.20.1-9.0.0
42. FastFurnace-1.20.1-8.0.1
43. Fastload-Reforged-mc1.20.1-3.4.0
44. FastWorkbench-1.20.1-8.0.4
45. ferritecore-6.0.1-forge
46. flib-1.20.1-0.0.11
47. FpsReducer2-forge-1.20-2.5
48. geckolib-forge-1.20.1-4.4.2
49. guardvillagers-1.20.1-1.6.4
50. iceandfire-2.1.13-1.20.1-beta-4
51. ImmediatelyFast-Forge-1.2.10+1.20.4
52. immersive_aircraft-0.7.1+1.20.1-forge
53. inventorysorter-1.20.1-23.0.1
54. ironchest-1.20.1-14.4.4
55. irons_spellbooks-1.20.1-3.0.1
56. jei-1.20.1-forge-15.3.0.4
57. L_Enders_Cataclysm-1.90 -1.20.1
58. LibX-1.20.1-5.0.12
59. modernfix-forge-5.14.0+mc1.20.1
60. MouseTweaks-forge-mc1.20-2.25
61. mythicmounts-20.1-7.4.2-forge
62. naturalist-forge-4.0.3-1.20.1
63. Patchouli-1.20.1-84-FORGE
64. PickUpNotifier-v8.0.0-1.20.1-Forge
65. Placebo-1.20.1-8.6.1
66. player-animation-lib-forge-1.0.2-rc1+1.20
67. PuzzlesLib-v8.1.17-1.20.1-Forge
68. Quark-4.0-438
69. Rex's-AdditionalStructures-1.20.x-(v.4.2.1)
70. rubidium-mc1.20.1-0.7.1a
71. saturn-mc1.20.1-0.1.3
72. Searchables-forge-1.20.1-1.0.2
73. simpleplanes-1.20.1-5.2.7
74. simpletomb-1.20.1-1.3.0
75. sit-1.20.1-1.3.4
76. SkyVillages-1.0.3-1.19.2-1.20.x-forge-release
77. smallships-forge-1.20.1-2.0.0-b1.1
78. smoothboot(reloaded)-mc1.20.1-0.0.4
79. starlight-1.1.2+forge.1cda73c
80. storagedrawers-1.20.1-12.0.3
81. the_bumblezone-7.2.16+1.20.1-forge
82. trashslot-forge-1.20-15.1.0
83. TravelersBackpack-1.20.1-9.1.12
84. valhelsia_core-forge-1.20.1-1.1.1
85. valhelsia_furniture-forge-1.20.1-1.1.2
86. valhelsia_structures-forge-1.20.1-1.1.1
87. villagernames-1.20.1-7.3
88. VisualWorkbench-v8.0.0-1.20.1-Forge
89. voicechat-forge-1.20.1-2.5.8
90. waystones-forge-1.20-14.1.3
91. worldedit-mod-7.2.15
92. Xaeros_Minimap_23.9.7_Forge_1.20
93. XaerosWorldMap_1.37.8_Forge_1.20
94. YungsApi-1.20-Forge-4.0.4
95. YungsBetterNetherFortresses-1.20-Forge-2.0.5
96. YungsBetterOceanMonuments-1.20-Forge-3.0.4
97. Zeta-1.0-14

**Comment by iron431** [comment]
do you have your particles turned off

**Comment by CodyBullmorr** [comment]
Nope Sir ^^  

thanks, it's working now
