### ISSUE TITLE
Some opinions about summoning spells.

### ISSUE THREAD

**Issue by chunye-shanhui** [iron431/Irons-Spells-n-Spellbooks#35]
### Feature description

Currently, there are some issues with summoning Wraiths and Undead Zombies. For example, they only attack me if I provoke them, which I find quite underwhelming. It would be better if the summoned creatures could automatically attack any hostile entities targeting me. They shouldn't attack neutral entities but should actively defend and engage any threats to me. This approach might improve the gameplay experience. Of course, it would be even better if players could choose the preferred attack behavior themselves.

### How it improves the player experience

If these suggestions are taken into consideration, the "Summoning Spells" would become much more interesting and significant. I hope you can take these opinions into account. Thank you.

**Comment by iron431** [comment]
They currently behave as vanilla wolves do as far as aggression. I would still like the expand the concept of summons, so maybe this can be considered next time summons get updated.

**Comment by chunye-shanhui** [comment]
You're right, the current behavior is similar to wolves, but it presents a problem. My summoned creatures need me to be attacked before they can attack. In other words, I have to intentionally let them attack me first for them to engage in combat. However, if I can kill the enemy before they have a chance to damage me, the summoned creatures become less effective. (I would prefer them to be active spells rather than "passive support spells").

If it's possible to update with a similar mechanism, I have a few suggestions. For example, using the player as the center to determine hostile entities. Before using the summoning spell, the player can use Shift+Right Click to set the attack behavior of the summoned creatures (Patrol, Stay, Follow, or Passive). Patrol, Stay, and Follow would be active attack modes, while Passive would mean they don't attack unless provoked.

The above features were actually inspired by the "Domestication Innovation" mod. Just thinking about it feels cool, but I understand that it might involve a lot of work. Regardless of whether this suggestion is accepted or not, I want to express my gratitude for creating such an excellent mod. Thank you.

**Comment by chunye-shanhui** [comment]
> They currently behave as vanilla wolves do as far as aggression. I would still like the expand the concept of summons, so maybe this can be considered next time summons get updated.

You're right, the current behavior is similar to wolves, but it presents a problem. My summoned creatures need me to be attacked before they can attack. In other words, I have to intentionally let them attack me first for them to engage in combat. However, if I can kill the enemy before they have a chance to damage me, the summoned creatures become less effective. (I would prefer them to be active spells rather than "passive support spells").

If it's possible to update with a similar mechanism, I have a few suggestions. For example, using the player as the center to determine hostile entities. Before using the summoning spell, the player can use Shift+Right Click to set the attack behavior of the summoned creatures (Patrol, Stay, Follow, or Passive). Patrol, Stay, and Follow would be active attack modes, while Passive would mean they don't attack unless provoked.

The above features were actually inspired by the "Domestication Innovation" mod. Just thinking about it feels cool, but I understand that it might involve a lot of work. Regardless of whether this suggestion is accepted or not, I want to express my gratitude for creating such an excellent mod. Thank you.
