### ISSUE TITLE
[Bug] Issue #332 is not yet fixed for who knows what reason

### ISSUE THREAD

**Issue by Jesse1079** [iron431/Irons-Spells-n-Spellbooks#350]
### Observed behaviour

In version 3.0.1,  Arrow volley's damage source issue is still present. Damage dealt by the arrow entities won't give credit to the caster.
I even created a new instance to test again, just to make sure it's not just some file corruption problem on my client.
Unfortunately, Issue #332 is more persistent than what we thought it will be... (; _ ;)
(I tried to add a reply on the old page but nothing happened. I think a "closed" page just won't send notifications anymore so I created this new page to let the devs know)

### Expected behaviour

Arrow volley's damage should count as dealt by the caster.

### Steps to reproduce

1.Install the mod
2.kill a blaze with Arrow Volley
3.Nothing will drop from that flying hot stick thing

### Server Type

Single Player

### Crashlog

This is not a Crash-related problem

### Iron's Spells N Spellbooks version

1.20.1 - 3.0.1

### Forge version

NeoForge 47.1.101 - Minecraft 1.20.1

### Other mods

Only Iron's Spells N Spellbooks and its dependencies

**Comment by lab3** [comment]
Bug #332 has not been fixed yet. Please stop opening duplicates.

**Comment by Jesse1079** [comment]
Successful fix confirmed in version 3.1.0. I tested Arrow Volley again and mobs are dropping loot and adding to the kill count as intended.
