### ISSUE TITLE
[Bug] Connector crash

### ISSUE THREAD

**Issue by Qee1y** [iron431/Irons-Spells-n-Spellbooks#351]
### Observed behaviour

geckolib-fabric-1.20.1-4.4.2.jar
Why use fabric? Because a mod requires a fabric version

### Expected behaviour

Not doing anything, loading blocks, occasionally crashing

### Steps to reproduce

Not doing anything, loading blocks, occasionally crashing

### Server Type

Single Player

### Crashlog

https://github.com/bernie-g/geckolib/files/14605263/latest.log

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.0.1.jar

### Forge version

47.2.20

**Comment by iron431** [comment]
we dont support fabric (connector)
