### ISSUE TITLE
[Bug] Mana Regeneration Attribute

### ISSUE THREAD

**Issue by TietAsnee** [iron431/Irons-Spells-n-Spellbooks#352]
### Observed behaviour

when i try to set "mana_regen" in the attributes to zero or a negative integer, the mana count still increases and doesn't stop

### Expected behaviour

well uh i expected it to stop ticking and increasing the mana count

### Steps to reproduce

/attribute @s iron_spellbooks:mana_regen base set 0

or 

/attribute @s iron_spellbooks:mana_regen base set -1

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-3.0.1

### Forge version

1.19.2-forge-43.3.5

**Comment by iron431** [comment]
The range of the mana regen attribute has been expanded in 3.1.2
