### ISSUE TITLE
[Bug] School specific scroll texture not displayed with stacked scrolls

### ISSUE THREAD

**Issue by SiverDX** [iron431/Irons-Spells-n-Spellbooks#355]
### Observed behaviour

`isSpellContainer` checks for a stack size of 1
Things like [Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks) allow you to stack items with the same NBT though

NBT itself is valid:
```
{
    ISB_Spells: {
        data: [
            {
                id: "irons_spellbooks:oakskin",index: 0,level: 2,locked: 1b
            }
        ],
        maxSpells: 1,
        mustEquip: 0b,
        spellWheel: 0b
    }
}
```

![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/22003703/e3bae858-3c05-4b8d-a3d4-a45d964b52b9)

![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/22003703/9abba816-d59b-4c4c-b5d0-bbe2e69bb7c3)

### Expected behaviour

N/A

### Steps to reproduce

N/A

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2 - 3.0.1

### Forge version

1.19.2 - 4.3.0

**Comment by iron431** [comment]
fixed in 3.1.0
