### ISSUE TITLE
[Bug] Crash With Apotheosis Gems And Unique Spellbooks

### ISSUE THREAD

**Issue by Chreal** [iron431/Irons-Spells-n-Spellbooks#356]
### Observed behaviour

When I tried to smith a Necromancy Gem onto the Necronomicon, I crashed when I hovered over the output slot.

### Expected behaviour

The Necronomicon with a Necromancy Gem in the output slot without crashing.

### Steps to reproduce

1. Reforge a unique Spellbook 2. Put the reforged unique spellbook and a spellbook-compatible gem into a smithing table 3. Hover over the output slot

### Server Type

Single Player

### Crashlog

https://gist.github.com/Chreal/2af907ac710450021892ddb09425f16c

### Iron's Spells N Spellbooks version

1.19.2 - 3.1.0

### Forge version

1.19.2 - 43.3.8

### Other mods

Iron's Spells n' Spellbooks 1.19.2 - 3.1.0
Apotheosis 1.19.2 - 6.5.0
Apothic Curios 1.19.2 - 1.0.3b
Apotheotic Additions 1.0.4

**Comment by iron431** [comment]
it looks like apothic curios is not compatible with the latest apotheosis update. try downgrading apotheosis and see if the crash persists

**Comment by Chreal** [comment]
yeah that worked, thanks
