### ISSUE TITLE
[CRASH] Crash upon checking JEI recipe of a spellbook.

### ISSUE THREAD

**Issue by posral** [iron431/Irons-Spells-n-Spellbooks#358]
### Observed behaviour

So, basically, my friend on the server tried to check blaze instruction manual recipe in JEI, when the game crashed and the spellbook that he had at that moment, disappeared. The funny thing is that I can't really see any ways to get this spellbook using JEI.

### Expected behaviour

See the book recipe or ways of acquisation.

### Steps to reproduce

Something may have influenced that, because when I try to check the recipe, everything's normal.

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/posral/b46f03ed8dbb228bf36a4364620d3dd5

### Iron's Spells N Spellbooks version

1.19.2-3.0.1

### Forge version

1.19.2 - 43.3.9

### Other mods

You can check them in crashlog.

**Comment by iron431** [comment]
use the latest version of the mod
