### ISSUE TITLE
[Suggestion] New Elements

### ISSUE THREAD

**Issue by pen9go** [iron431/Irons-Spells-n-Spellbooks#360]
### Feature description

I found it odd that you have a bunck of assorted elements but not ones like water, wind, or earth. Adding basic elements like this might make players feel like they have a bit more variation.

Here are some example spells 9just me freeballing)

Water
-Torrent: Similar to Burning Dash or a Riptide Trident, it allows players to fly forward using the power of water
-Bubble: Creates a bubble of air that allows the caster to breath onderwater for a period of time, and could also protect from one attack before pooping
-Tidal Wave: send a tidal wave forward, pushing back enemies
-Douse: puts out fire on caster and prevents fire damage for a small period of time
-Drown: make a targetted enemy take drowning damage for a period of time
-Surf: move on a wave in the direction you are facing, whle being able to aim yourself during the duration

Earth
-Move Earthquake and Stomp from nature to here
-Plateau: a pillar of stone forms underneath you and sends you up into the air, giving you the high ground for a while (pillar dissapears after a set mount of time)
-Earthen Cover: similar to the evocation spell sheild, creates an impermeable barrier that can block from attacks 
-Petrify: makes a target freeze in place, unnable to move or attack, but also take lower damage
-Harden: similar to petrify, but for yourself, and doesnt completely freeze, only slows you
-Tunnel: dig into the ground, moving at a fast speed, then resurfacing after some time

Wind
-Move Gust from Evocation to here
-Tornado: create a gust of wind forward that pulls enemies in 
-Updraft: similar to ascension from electricity, sends you upwards, maybe more quickly
-Draft: Fly forward, sending enemies away from you
-Wind Barrier: create a dome around you that protects from arrows

As for the material associate with the runes, water could be prismarine crystals, wind could be the new breeaze rods from 1.21 (im not entirely sure what you could do for earlier versions), and earth could be a new type of mineable material (maybe one randomly dropped from all vanilla ore types)

As for any extra spells you would need for each element, you can reuse ones from other elements like the arrows or bolts, most players wouldnt mind a copy paste version of a spell, especially when that spells matched the armor they chose.

### How it improves the player experience

I know this is a lot, but please consider it. I really enjoy this mod and would like to see a lot more from it.

**Comment by iron431** [comment]
more spells are always planned but take time to get into the game. to this extent, we do not have plans to add any additional schools for a while, especially nature and wind which can already most spell ideas into existing schools, so this will not be worked on
