### ISSUE TITLE
Magic bypass_armor

### ISSUE THREAD

**Issue by jpaulo-rb** [iron431/Irons-Spells-n-Spellbooks#364]
### Feature description

-Detailed description of feature
So, instead of magic damage being reduce though `generic.armor`, it could uses `spell_resist`

### How it improves the player experience

-How this improves the mod
Magic damage is reduced by `generic.armor`, and I think it would be better if magic spells had the `bypass_armor` tag. And the way to reduce damage was through attribute  `spell_resist` in armors, artifacts or spells magics that increase the attribute.

-Why this improves the mod
Donest make much sense magic damage being reduce by `generic.armor`

**Comment by iron431** [comment]
this will not be done because the magic is designed and balanced to scale with armor. likewise, spell resistance is designed and balanced to be a special buff
