### ISSUE TITLE
broken hostage nitwit trade

### ISSUE THREAD

**Issue by GreenForzeGaming** [iron431/Irons-Spells-n-Spellbooks#366]
### Observed behaviour

having the Recruits mod cancels out the nitwit in the archevokers castles making the bible trade item unobtaiable.
the recruits mod turns all nitwits into recruitable npc that you can have fight for you. so only thing i could see solve then is a specal npc from the iron spells or make use of another npc.

### Expected behaviour

be able to do the 64 emerald trade with hostage nitwit

### Steps to reproduce

have recruits mod and iron spell.... installed
find hostage nitwit

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1 3.1.0

### Forge version

forge 1.20.1 47.2.0

### Other mods

Villager Recruits 1.20.1-1.10.15

**Comment by iron431** [comment]
Nitwits no longer spawn in evoker forts. check the wiki for the updated way to obtain the villager bible

**Comment by GreenForzeGaming** [comment]
then its the trader that gets removed by recruits the same way.

> Nitwits no longer spawn in evoker forts. check the wiki for the updated way to obtain the villager bible
