### ISSUE TITLE
[Bug] priest bug

### ISSUE THREAD

**Issue by AciDawarudo** [iron431/Irons-Spells-n-Spellbooks#368]
### Observed behaviour

priest made the game crash and corrupt the world
![Capture d'écran 2024-03-27 220217](https://github.com/iron431/irons-spells-n-spellbooks/assets/165215786/f8343200-fd97-4819-9007-0f280302a506)

### Expected behaviour

it wil be crash when priest kill someone

### Steps to reproduce

go in a village,
priest agro a monster
he kill the monster and kaboom

### Server Type

Single Player

### Iron's Spells N Spellbooks version

all 1.20.1

### Forge version

1.20.1

### Other mods

ask me later

**Comment by lab3** [comment]
Please upload your actual crashlog or we can't really help. Unfortunately, that screenshot doesn't tell us much.
