### ISSUE TITLE
Store spellbooks in chiseled bookshelf

### ISSUE THREAD

**Issue by pumkinisawesome** [iron431/Irons-Spells-n-Spellbooks#369]
### Feature description

I think it would be really cool to be able to store your spellbooks in the chiseled bookshelf blocks. Is that something that would be possible? I would understand if not, as they're not technically openable books, but if it happens to be possible, I think that would be a cool way of storing your spells!

### How it improves the player experience

It allows your spellbooks to be stored in an aesthetic way, and integrates with a vanilla block in a logical way.

**Comment by Spider2200** [comment]
True, I want that too

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
