### ISSUE TITLE
[Bug] Upgrade Orbs no longer work in recent update

### ISSUE THREAD

**Issue by cnlaw99** [iron431/Irons-Spells-n-Spellbooks#370]
### Observed behaviour

With the most recent update, you now equip the spellbook in a curios slot and use a casting hotkey rather than the right click while holding the item. This stops the Upgrade Orbs from working, meaning you need to hold an upgraded book in your hand with upgrades while casting spells from a non upgraded book in your curios slot. Need to find a way to apply your upgrade orbs to the player even while the book is in the curios slot.

### Expected behaviour

I expect that with an upgrade orb applied to my ancient codex, I would have 150 max mana to use. 

### Steps to reproduce

1. apply mana upgrade orb to spellbook
2. equip spellbook by right clicking or placing in a curios slot
3. watch as your max mana drops from 150 back to 100 when you try to cast spells.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2-3.1.1

### Forge version

1.19.2

**Comment by iron431** [comment]
This is an issue with spellbooks that already had upgrade nbt before the update. You can use a shriving stone to reset them. Upgrades applied after the update work
