### ISSUE TITLE
[Bug] Villager Bible obtention unkown

### ISSUE THREAD

**Issue by Hugoswnw** [iron431/Irons-Spells-n-Spellbooks#371]
### Observed behaviour

No informations in the wiki about captive wandering traders.

### Expected behaviour

According to the wiki, in order to obtain the villager bible : "The written book must be translated by a captive wandering trader from the Evoker Fort first."

According to the changelog "Reworked the “questline” to obtain the Villager Bible - Nitwits no longer spawn in Evoker Forts, nor have trades - The final trade is done with the Priest"

### Steps to reproduce

1. The priest trades the bible for a translated journal and sells a map to a fort.
2. The journal obtained in the fort is untranslated.
3. Captive wandering traders are nowhere to be found.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-2.1.13

### Forge version

1.20.1-47.2.21

**Comment by iron431** [comment]
the spawn in random and rare.
