### ISSUE TITLE
[Bug] Quick cast keybinds dont affect imbued items

### ISSUE THREAD

**Issue by TomatoSoupter** [iron431/Irons-Spells-n-Spellbooks#372]
### Observed behaviour

When binding any keys to Quick Cast 13-15, nothing happens when pressing the key bound. It works perfectly fine with Quick Cast 1-12

### Expected behaviour

Quick cast should function normally with slots 13-15

### Steps to reproduce

Have a book with 12 spell slots full of spells
Imbue a weapon with a spell
Bind a key to "Quck Cast Slot 13"
Attempt to Quick Cast imbued weapon's spell

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.1.0

### Forge version

1.20.1-47.2.0

**Comment by iron431** [comment]
the keybinds work fine, they just only affect the spell book

**Comment by TomatoSoupter** [comment]
How are you even supposed to get 15 slots in a spellbook? The max is 12 normally. So there doesn't seem to be a point of having keybinds for spells 13-15. It would be useful to use an imbue'd weapons ability with a simple bind instead of selecting the spell manually then casting it with the casting key.

Edit: It'd also make the usage of spells imbued into chestplates easier too.

**Comment by iron431** [comment]
fixed in 3.1.2
