### ISSUE TITLE
 player model covers the screen when you cast a spell

### ISSUE THREAD

**Issue by dh2577** [iron431/Irons-Spells-n-Spellbooks#373]
### Observed behaviour

whenever i use a spell in first person it shows the inside of my player models head
![Skjermbilde (32)](https://github.com/iron431/irons-spells-n-spellbooks/assets/165426691/453cac36-f868-4281-b60a-019808be3e72)

### Expected behaviour

its not suposed to show the inside of my player model

### Steps to reproduce

1. go in first person
2. cast a spell
3. only see the inside of your player model while your casting the spell

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

1.20.1 - 47.2.20

### Other mods

i added irons' spells and spellbooks to (Chosen's Modded Adventure modpack) version  0.8.0

**Comment by Entity-808** [comment]
Hey, Im also experiencing the same problem right now and would like to know how you fixed it if you did, since it's really annoying for me

**Comment by BBTezooka** [comment]
did someone find the solution?

**Comment by iron431** [comment]
turn off first person animations in client config

**Comment by BBTezooka** [comment]
> turn off first person animations in client config

i did, but is there another “animation-on” way, this bug is really strange and i didn’t get it before on forge 1.20.1, but after one month it got me, sad :(
thx for the reply
