### ISSUE TITLE
Dead King cannot be Set on Fire

### ISSUE THREAD

**Issue by TheGreatMagispeller** [iron431/Irons-Spells-n-Spellbooks#374]
### Feature description

The Dead King is Now Fully Resistance to Lava Damage, but He can Still be Set on Fire While Being a Wither Skeleton, Which doesn't Make any Sense Because Vanilla Wither Skeletons and the Wither cannot be Set on Fire

### How it improves the player experience

Making Sense with Vanilla Wither Skeletons and the Wither, so You won't be Tricked by His Black, Withered Bones

**Comment by iron431** [comment]
The dead king being immune to lava is for mitigating cheese strategies, not because he is thematically immune to fire, so this will not be implemented
