### ISSUE TITLE
Wimpy Spell Books Have No 3D Model

### ISSUE THREAD

**Issue by TheGreatMagispeller** [iron431/Irons-Spells-n-Spellbooks#375]
### Observed behaviour

The New Update Adds Beautiful 3D Models For Almost Every Spell Book, Expect for the Wimpy Spell Book created by /createSpellBook command, Because Unlike Every other Spell Book, Wimpy Spell Books Still Shows their 2D Sprites while being Hold in Hand/Put in Spell Book Slot

### Expected behaviour

Wimpy Spellbooks have a 3D Model and a Related Texture

### Steps to reproduce

/createSpellBook (number between 1-15)
Hold It in Hand/Put it in Spell Book Slot
The 2D Sprite Still Appears in Your Hand/At the Side of Your Legs

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2 3.1.1

### Forge version

43.2.8

**Comment by iron431** [comment]
this is a debug item and will not be receiving additional art

**Comment by TheGreatMagispeller** [comment]
@iron431
Am I Allowed to Post a Texture Pack Somewhere to Fix this Problem?
