### ISSUE TITLE
The Dead King's Torso and Head isn't Moving When Doing Melee Attacks

### ISSUE THREAD

**Issue by TheGreatMagispeller** [iron431/Irons-Spells-n-Spellbooks#376]
### Observed behaviour

In the Video Showcasing the Dead King's New Music and Animations, the Dead King is shown that He will Move His Torso and Head when Doing the Double Swipe Melee Attack as Well as His Arms, but this Doesn't Happen in Game, Leaving the Dead King's Arms and Head Moving into Cursed Places
Video Link: [https://www.youtube.com/watch?v=Hm9kJFDJkaA]
![2024-03-30_19 42 37](https://github.com/iron431/irons-spells-n-spellbooks/assets/146729015/89ed4518-88d9-4acd-b6ab-419c209dc077)
![2024-03-30_19 48 21](https://github.com/iron431/irons-spells-n-spellbooks/assets/146729015/dab09ccb-ac80-43f2-bec9-6f3e62488ab2)
![2024-03-30_19 50 39](https://github.com/iron431/irons-spells-n-spellbooks/assets/146729015/434f1952-48a2-452f-9cbb-bd500d3e9571)

### Expected behaviour

The Dead King Moves His Torso and Head when Doing the Double-Swipe Melee Attack, Just like in the Video

### Steps to reproduce

Wake the Dead King Up
Be Near Him to Let Him to do Melee Attacks
Watch the Arms(phase 1)/Rest of the Body(phase 2) Moving into Cursed Places Because of the Torso(phase 1)/Head(phase 2) didn't Move

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2 3.1.1

### Forge version

43.2.8

**Comment by iron431** [comment]
fixed in 3.1.2
