### ISSUE TITLE
Flaming Strike Classified as Holy Spell

### ISSUE THREAD

**Issue by TheGreatMagispeller** [iron431/Irons-Spells-n-Spellbooks#377]
### Observed behaviour

Flaming Strike is a Spell that Makes You Attack Nearby Enemies with a Flaming Swipe, Dealing Damage and Burning to Them, but for Some Reason it is Classified as a Holy Spell while None of any other Holy Spells Burns Targets

### Expected behaviour

Flaming Strike Classified as a Fire Spell

### Steps to reproduce

/createScroll flaming_strike 1
See the Flaming Strike being Classified as a Holy Spell by the Scroll's Texture

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2 3.1.1

### Forge version

43.2.8

**Comment by Anifelus** [comment]
Delete your ISS config (inside world folder) and join the world again.

**Comment by iron431** [comment]
^
