### ISSUE TITLE
Visual bug [Bug] 

### ISSUE THREAD

**Issue by ZerausDG** [iron431/Irons-Spells-n-Spellbooks#378]
### Observed behaviour

I have two worlds in a single player, in the first world, I was in creative mode, and I had a spell book with several spells, in the second world I started a game in survival, what happens is that the spells of the first world appear to me.

-----------
first world with the book of spells
![imagen](https://github.com/iron431/irons-spells-n-spellbooks/assets/106796155/ad36f449-9c38-44ed-b2c6-b056656281ff)

----------
second world
![imagen](https://github.com/iron431/irons-spells-n-spellbooks/assets/106796155/d6179ec9-b733-4895-8f25-126904acaf22)

### Expected behaviour

I don't think that should happen.

### Steps to reproduce

.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.1

### Forge version

1.20.1-47.2.19

**Comment by iron431** [comment]
fixed in 3.1.2
