### ISSUE TITLE
[Bug] spawners in structures are set too 0 spawn delay

### ISSUE THREAD

**Issue by GreenForzeGaming** [iron431/Irons-Spells-n-Spellbooks#379]
### Observed behaviour

spawners in structures is set on a 0 spawn delay standard is 200

### Expected behaviour

not to be gang banged by vex

### Steps to reproduce

walk in cellar in evoker tower or bridge area in dead king crypt

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1 3.1.0

### Forge version

forge 1.20.1 47.2.0

**Comment by iron431** [comment]
this is intentional
