### ISSUE TITLE
All spells respecting PVP off

### ISSUE THREAD

**Issue by KamiSami** [iron431/Irons-Spells-n-Spellbooks#38]
### Feature description

Basically all spells that would do some form of harm (not directly, such as root or black hole affecting other players) would be not affecting others in non-pvp enviroment.

### How it improves the player experience

No more for example all team mates being dragged into black hole and falling to death...

**Comment by iron431** [comment]
You have to turn friendly fire off on the team in question (/team modify yourTeam friendlyFire false), and then spells will not do damage and black hole with stop affecting teammates.

**Comment by KamiSami** [comment]
Sorry about late reply, and... Um... That is really poor way of management, since only OP can manage teams, so that makes no sense why not consider that... Regular players in my server have literally no way of joining my team since command for team is OP only, unless there is mod that makes it available for regular players only, which, am not aware of right now. I guess it's too much work to make mod respect PvP false...

**Comment by milkembers** [comment]
false, friendly fire is off for the team and certain spells are still hitting friends, making team play impossible with this mod unless we restrict ourselves to certain spells.
