### ISSUE TITLE
[Bug] Wizards won't be revenging after being attacked by other mobs

### ISSUE THREAD

**Issue by 5A93** [iron431/Irons-Spells-n-Spellbooks#380]
### Observed behaviour

After Pyromancer/Cryomancer being attacked by other mobs, they're just drinking their healing potion and do not respond even until the very moment they're killed. Test subject includes zombies, pillagers, mobs from other mods. They still can attack any mobs they want normally. I didn't test other spellcasters.

### Expected behaviour

Revenging seems to work just fine until the lastest big update.

### Steps to reproduce

1. Somehow make mobs target pyromancer/cryomancer
2. They will be just hanging there, drinking potions, until the inevitable death came by.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-3.1.1

### Forge version

1.19.2

**Comment by 5A93** [comment]
Hold on. It seems to works just fine on my other PC with a few other mods. Maybe some conflicts happened.

**Comment by 5A93** [comment]
Dungeons Libraries caused it.

**Comment by iron431** [comment]
@5A93 is this isolated as a bug with Dungeons Libraries?

**Comment by 5A93** [comment]
> @5A93 is this isolated as a bug with Dungeons Libraries?

I surpose so. Problem completely solved by removing it. Sorry for not replying so long, I summitted an issue to dungeon crew and expect them to solved this but nothing happens since then.
