### ISSUE TITLE
[Bug] Unable to choose spells

### ISSUE THREAD

**Issue by WhimsicTinkerer** [iron431/Irons-Spells-n-Spellbooks#381]
### Observed behaviour

Spell Selection Failed, happens constantly.

I am on a mac, which may be the problem.

https://github.com/iron431/irons-spells-n-spellbooks/assets/153570446/390d175c-19a4-4478-b3a8-ced51de57972

### Expected behaviour

The mouse position is most likely reset due to something having a higher priority, although I have no idea what.

### Steps to reproduce

Holding R, move mouse to a new spell, on click resets mouse position and chosen spell to the previously chosen one

After mouse pos resets, if you move your camera to where the mouse pos was supposed to go, it changes the spell to what you click on, this only applies after you close the menu though...

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-3.1.1

### Forge version

1.19.2-43.3.0

### Other mods

![Screen Shot 2024-04-04 at 5 33 57 pm](https://github.com/iron431/irons-spells-n-spellbooks/assets/153570446/305a0c1d-50f8-4e70-ae5e-ad0a85a5f95a)
![Screen Shot 2024-04-04 at 5 34 16 pm](https://github.com/iron431/irons-spells-n-spellbooks/assets/153570446/4a4cb183-33cb-434e-b1b8-43e32c5c46d3)

**Comment by WhimsicTinkerer** [comment]
Happens on both server and singleplayer

**Comment by iron431** [comment]
TIhis is because you do not click to choose a spell, you release your wheel button. However, its not supposed to grab the mouse back, so this will be improved in the next update

**Comment by WhimsicTinkerer** [comment]
Iron, i was clicking in that video, when the mouse stops showing is when i clicked.

**Comment by iron431** [comment]
Right. You are not supposed to click.

**Comment by WhimsicTinkerer** [comment]
Ah, that makes a lot more sense, thanks for the help. Its quite unintuitive when moving from old spell system to the new one.
