### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by CannerCrebes** [iron431/Irons-Spells-n-Spellbooks#383]
### Observed behaviour

disconnecting mid-cast locks you into a mid-cast state when you re-connect and does not end until you cast another spell

### Expected behaviour

disconnecting mid-cast not locking you in a mid-cast state when you re-connect 

### Steps to reproduce

cast spell with a cast time, disconnect before the casting is complete, reconnect
achieved on Modding magic ISS server

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.1.1

### Forge version

47.2.19

### Other mods

check the ISS server modpack with quark update

**Comment by iron431** [comment]
fixed in 3.1.2
