### ISSUE TITLE
[Bug] tetra compat issues

### ISSUE THREAD

**Issue by aycfes** [iron431/Irons-Spells-n-Spellbooks#384]
### Observed behaviour

only shields apply the arcane ingot's effects in the offhand, and other such tools held in the main hand overwrite it.
the shield needs to be unequipped and re-equipped to start working again
arcane cloth wraps on tool handles also seem to trigger this

### Expected behaviour

holding tetra tools containing arcane ingot parts in either hand increases mana capacity equally, and holding one in each hand stacks their effects

### Steps to reproduce

make n tools containing the compat materials
switch them around in the main and offhand
observe the mana meter

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.1.

### Forge version

1.20.1 - 47.2.0

### Other mods

	- advancementframes 1.20-2.2.6
	- advancementplaques 1.5.1
	- aeroblender 1.20.1-1.0.1-neoforge
	- aether 1.20.1-1.3.1-neoforge
	- aether_redux 2.0.7d
	- aetheric_tetranomicon 1.1.0-1.20.1
	- alexscaves 1.1.4
	- alexsmobs 1.22.8
	- alexsmobsinteraction 2.0
	- allthetrims 3.4.2
	- ambientenvironment 11.0.0.1
	- ambientsounds 5.3.9
	- amendments 1.20-1.1.11
	- ancient_aether 0.8.9
	- appleskin 2.5.1+mc1.20.1
	- aquaculture 2.5.1
	- archers_paradox 5.0.0
	- architectury 9.2.14
	- armorpointspp 1.20-3.1.1
	- artifacts 9.3.0
	- balm 7.2.2
	- bettercombat 1.8.4+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterjungletemples 1.20-Forge-2.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- bettersmithingtable 1.1.0
	- bettertridents 8.0.1
	- betterwitchhuts 1.20-Forge-3.0.3
	- bookshelf 20.1.9
	- caelus 3.1.0+1.20
	- carryon 2.1.2.7
	- cataclysm 1.0
	- charmofundying 6.5.0+1.20.1
	- cherishedworlds 6.1.6+1.20.1
	- chimes 2.0.1
	- chunky 1.3.136
	- citadel 2.5.4
	- cloth_config 11.1.118
	- clumps 12.0.0.3
	- cofh_core 11.0.0
	- collective 7.40
	- comforts 6.3.5+1.20.1
	- conduitspreventdrowned 3.6
	- conjurer_illager 1.1.6
	- controlling 12.0.2
	- convenientcurioscontainer 1.13-forge-1.20.1
	- cosmeticarmorreworked 1.20.1-v1a
	- creativecore 2.11.25
	- ctov 3.4.2
	- culllessleaves 1.20.1-1.0.5
	- cumulus_menus 1.20.1-1.0.0-neoforge
	- curios 5.7.2+1.20.1
	- curious_armor_stands 1.20-5.0.1
	- deep_aether 1.20.1-1.0.2
	- diagonalblocks 8.0.2
	- diagonalfences 8.1.3
	- distanthorizons 2.0.1-a
	- doapi 1.2.9
	- domesticationinnovation 1.7.1
	- dummmmmmy 1.20-1.8.14
	- dynamic_fps 3.4.2
	- enchdesc 17.0.14
	- endrem 5.2.3-R-1.20.1
	- enigmaticlegacy 2.29.0
	- entityculling 1.6.2
	- equipmentcompare 1.3.7
	- everycomp 1.20-2.6.40
	- excavar 1.20.1-3.1.0
	- expandability 9.0.0
	- explorerscompass 1.20.1-1.3.3-forge
	- extremesoundmuffler 3.41-forge-1.20
	- fastload 3.4.0
	- fastpaintings 1.20-1.2.5
	- ferritecore 6.0.1
	- forge 47.2.0
	- friendsandfoes 2.0.10
	- galosphere 1.20.1-1.4.1
	- geckoanimfix 1.0.0
	- geckolib 4.4.4
	- gpumemleakfix 1.20.1-1.8
	- gravestone 1.20.1-1.0.15
	- guardvillagers 1.20.1-1.6.4
	- hardcorerevival 12.0.2
	- highlight 2.0.1
	- hopo 1.1.8
	- hoporp 1.3.7
	- hopour 1.1.4
	- ice_and_fire_spellbooks 2.2.0-1.20.1
	- iceandfire 2.1.13-1.20.1-beta-4
	- iceberg 1.1.21
	- imst 2.1.0
	- incendium 5.3.4
	- irons_spellbooks 1.20.1-3.1.1
	- jade 11.7.1
	- jadeaddons 5.2.2
	- jei 15.3.0.4
	- labels 1.20-1.20.1
	- leavesbegone 8.0.0
	- legendarytooltips 1.4.5
	- letmedespawn 1.2.0
	- lithostitched 1.1.5
	- lootr 0.7.32.80
	- lost_aether_content 1.2.3
	- mcwroofs 2.3.0
	- meadow 1.3.7
	- mindfuldarkness 8.0.3
	- minecraft 1.20.1
	- mixinextras 0.2.0
	- mixinsquared 0.1.1
	- modernfix 5.15.0+mc1.20.1
	- moonlight 1.20-2.11.9
	- mr_dungeons_andtaverns 3.0.3.f
	- mutantmonsters 8.0.7
	- mutil 6.1.1
	- naturescompass 1.20.1-1.11.2-forge
	- nerb 0.3
	- nethers_exoticism 1.2.7
	- nitrogen_internals 1.20.1-1.0.7-neoforge
	- nullscape 1.2.4
	- oculus 1.6.15a
	- openpartiesandclaims 0.20.4
	- packetfixer 1.2.8
	- patchouli 1.20.1-84-FORGE
	- playeranimator 1.0.2-rc1+1.20
	- polymorph 0.49.2+1.20.1
	- prism 1.0.5
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.18
	- quark 4.0-439
	- quarkoddities 1.20.1
	- radium 0.12.2+git.5f80f74
	- realisticbees 3.8
	- regions_unexplored 0.5.5
	- resourcefullib 2.0.7
	- saturn 0.1.3
	- sawmill 1.20-1.3.11
	- searchables 1.0.2
	- shouldersurfing 1.20.1-2.9.6
	- simpleradio 2.2.4
	- smoothboot 0.0.4
	- sophisticatedbackpacks 3.20.3.1034
	- sophisticatedcore 0.6.12.589
	- sophisticatedstorage 0.10.12.768
	- sound_physics_remastered 1.20.1-1.3.1
	- spectrelib 0.13.15+1.20.1
	- stalwart_dungeons 1.2.8
	- starlight 1.1.2+forge.1cda73c
	- step 1.2.2
	- structure_gel 2.16.1
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.7
	- suppsquared 1.20-1.1.14
	- tectonic 2.2.1
	- terrablender 3.0.1.4
	- terraform 7.0.1
	- terralith 2.4.11
	- tetra 6.2.0
	- tetracelium 1.1.1
	- tetraextras 0.1.4-1.20.1
	- tetranomicon 1.5.3-1.20.1
	- tetratic_combat_expanded 2.7.1
	- toms_storage 1.6.6
	- toolbelt 1.20.0
	- torchmaster 20.1.5
	- totemofreviving 1.20.1-2.0.0
	- treechop 0.18.8
	- valhelsia_core 1.1.2
	- valhelsia_furniture 1.1.3
	- valhelsia_structures 1.20.1-1.1.2
	- voicechat 1.20.1-2.5.10
	- w2pets 1.0
	- walljump 1.20.1-1.1.5-forge
	- wandering_bags 2.0.7
	- waystones 14.1.3
	- xaerominimap 24.0.3
	- xaeroworldmap 1.38.1
	- xaerozoomout 1.1.0
	- yungsapi 1.20-Forge-4.0.4
	- zeta 1.0-14

**Comment by iron431** [comment]
this is a known issue with tetra, not the arcane material
