### ISSUE TITLE
Teleporting in place when using the Teleport Scroll

### ISSUE THREAD

**Issue by Toska0** [iron431/Irons-Spells-n-Spellbooks#385]
### Observed behaviour

No matter what I use (weapon, staff, hand, single use scroll) I just stay in the same position as before and won't budge. I spam the spell and go upwards. Log doesn't show anything. It happens both in a server and singleplayer.

### Expected behaviour

.

### Steps to reproduce

.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.7

### Forge version

47.2.32

**Comment by iron431** [comment]
fixed in 3.1.3
