### ISSUE TITLE
[Bug] Haste have a bug

### ISSUE THREAD

**Issue by Lando77777** [iron431/Irons-Spells-n-Spellbooks#386]
### Observed behaviour

Since the latest update, i've put a Haste level 3 (rare) made in a scroll forge into an ironbound tome and when i activate him the duration is 25 sec instead of 46 sec and the value indicate when i open the inventory and paste my cursor on the screen of the spell is : 

--0% mana regenaration
--0%rapidity
--0% attack speed
--0% cast time reduction.

### Expected behaviour

the true duration and the true value 

### Steps to reproduce

Do a haste lvl 3 in scroll forge , put him into an ironbound tome and activate the spell and look the effect in the inventory.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

the latest

### Forge version

the latest

### Other mods

jade, jei and many others but i' just come to try with only ISS and that doing the same thing.

**Comment by iron431** [comment]
fixed in 3.1.3
