### ISSUE TITLE
Broken Spells

### ISSUE THREAD

**Issue by TheGreatMagispeller** [iron431/Irons-Spells-n-Spellbooks#387]
### Observed behaviour

Most Spells are Having Their Level 1 Stat, Even if They are Level 10 Spells
Example: A Level 1 Cone of Cold Deals 1 Damage per Hit, But a Level 10 Cone of Cold Spell Still Does 1 Damage per Hit
Casting a Raise Dead or Summon Vex Spell Results Nothing Summoned
Eldritch Blast Have Only 2 Shots, Even if the Desc Says It has 3 Shots or More
Casting a Telport Spell only Results You to Telport about 1 Block Higher than Your Current Location, No Matter Which Way You are Seeing
I Tried to Reset Server Config, But It Didn't Fix the Problem

### Expected behaviour

Fix the Spell Stats Back to the Value They are Supposed to be
Fix Raise Dead and Summon Vex Spell

### Steps to reproduce

Grab a Level 1 and Level Max Spell Scroll in Creative Inventory, Example: Level 1 and 10 Cone of Cold
Grab a Raise Dead and a Summon Vex Scroll
Grab a Teleport Scroll
Cast the Spell Without any Additional Spell Power Upgrade
If the Spell is a Damaging Spell, Cast It on a Mob(mobs with no resistance like creepers will be the best)(will be easier to see damage value with tslat entity status)
Notice the Spells Having Zero Diffrence
Notice Raise Dead and Summon Vex Spell Spawns Nothing
Notice You only Teleport to about 1 Block Higher than Your Current Location with Teleport Spell

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2 3.1.2

### Forge version

43.2.8

### Other mods

Tslat Entity Status 1.2.1

**Comment by iron431** [comment]
fixed in 3.1.3
