### ISSUE TITLE
Event should be not cancellable

### ISSUE THREAD

**Issue by pietro-lopes** [iron431/Irons-Spells-n-Spellbooks#388]
https://github.com/iron431/irons-spells-n-spellbooks/blob/adde21d345428f5c1c1201b671589e45b23dcf56/src/main/java/io/redspace/ironsspellbooks/api/events/SpellOnCastEvent.java#L14

https://github.com/iron431/irons-spells-n-spellbooks/blob/adde21d345428f5c1c1201b671589e45b23dcf56/src/main/java/io/redspace/ironsspellbooks/api/events/SpellOnCastEvent.java#L42-L44

While cancelling still does nothing, this was left behind to be changed.

**Comment by iron431** [comment]
This has been fixed
