### ISSUE TITLE
[Bug] Infinite usage of scrolls

### ISSUE THREAD

**Issue by Arthurszzz** [iron431/Irons-Spells-n-Spellbooks#389]
### Observed behaviour

Whenever you cast a continuous cast, you can drop or pickup item from inventory to circumvent the call of `Scroll.attemptRemoveScrollAfterCast(serverPlayer);`.

### Expected behaviour

There should be checks for item tossing and picking up scrolls from the inventory and deleting them, or maybe delete scrolls instantly on usage?

### Steps to reproduce

https://github.com/iron431/irons-spells-n-spellbooks/assets/67706547/05d2600d-fac8-4b9f-95e2-19da6f65df97

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.2 and 1.19.2-3.1.2

### Forge version

47.2.20

**Comment by iron431** [comment]
fixed in 3.1.7
