### ISSUE TITLE
Mana regen in the config file

### ISSUE THREAD

**Issue by Lucas-Carrarini** [iron431/Irons-Spells-n-Spellbooks#391]
### Feature description

I checked that already have an attribute and a command for mana regen
In the changelogs we have: Mana regen can now be 0, but not negative
My suggestion and request (please) is to add in config file an option to set the mana regen for all players to a specific value, and capable of disabling completely the automatic mana regen

### How it improves the player experience

You can diverse the gameplay experience, and balance some spell usage. Avoiding spell spam for those who dont want it.
Will be more immersive and generate more exclusive experiences that will be more challenging
Thats my idea for a feature, i see myself needing that and I think will be an excellent adittion make that in config files
Its already in the game, just need to put the set value in config file

**Comment by iron431** [comment]
this is exactly what this new change enables. use a mod that lets you configure default attributes.

**Comment by Lucas-Carrarini** [comment]
> this is exactly what this new change enables. use a mod that lets you configure default attributes.

Oh nice! I didnt know that have mods for this, any suggestion that works well with your mod?
Great work btw!!

EDIT: For anyone needing, AttributeFix solve my problem, so highly recommended

**Comment by UmbralCosmos** [comment]
@DevLucasTavares Might I ask how you did it?
I am unable to effectively set mana regen to anything lower than 1.
Any lower value is ignored for some reason.

Edit: The value 1 seems to be 1% of the max mana so I am unable to go below 1% mana regen per regen (mana regen seems to trigger 2-3 times per second, wonder if there's any way to change this?)
