### ISSUE TITLE
[Bug] Spell Wheel stays after death

### ISSUE THREAD

**Issue by TheKillager** [iron431/Irons-Spells-n-Spellbooks#394]
### Observed behaviour

Spellwheel stays after death, and sometimes even allows you to cast from the nonexistent spellbook

### Expected behaviour

The spellwheel _should_ disappear when the book drops on death

### Steps to reproduce

Get book
Put in spell slot
Die
Respawn
It's really simple

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1 v1.20.1-3.1.3

### Forge version

1.20.1 - Autocompiled by Modrinth

### Other mods

Not applicable, happens no matter what the other mods. This _may_ be influenced by toggling on and back off KeepInventory, as I have only seen it in places where this is the case.

**Comment by lab3** [comment]
@TheKillager do you need to die with the wheel open?

**Comment by TheKillager** [comment]
@lab3 Sorry for my mis-wording, I mean the spell list in the bottom left. You can open and close the wheel as normal.

**Comment by iron431** [comment]
I cannot reproduce this
