### ISSUE TITLE
Number of slots in the spell book 🙏

### ISSUE THREAD

**Issue by LehaKat** [iron431/Irons-Spells-n-Spellbooks#395]
### Feature description

Please give the opportunity to increase the number of slots in the spell book 🙏
You can do this with enhancement spheres or something else, but please, I would really like to carry more spells with me

### How it improves the player experience

Players will not have to choose between a move spell, a bounce spell, or a defense spell, but rather take all 3.
This will make people happy)

**Comment by iron431** [comment]
something to this degree is planned. for the time being, look into imbued items, which are intended to give players this strategic ability in their spell choice.
