### ISSUE TITLE
How yo get " Iron's crown "

### ISSUE THREAD

**Issue by LovenKyuu** [iron431/Irons-Spells-n-Spellbooks#396]
### Feature description

Hi !

I search many way to find "Iron's crown" but I don't know how we can loot her.
She is not mentionned in the wiki, 
Could you tell me how we can loot her ?

**Comment by pvzfan1** [comment]
its creative-only

**Comment by Crillax1** [comment]
still no legit way to get the crown? or anything similar to it? and i dont mean the tarnished crown that shit takes away 15% damage.
