### ISSUE TITLE
Raise Dead Spell [Bug] 

### ISSUE THREAD

**Issue by ghost** [iron431/Irons-Spells-n-Spellbooks#398]
### Observed behaviour

When using the raise dead spell, no friendly mobs appear, however if equipped with the Necronomicon only 1 mob spawns.

### Expected behaviour

the spell should summon the number of mobs it indicates will be spawned

### Steps to reproduce

1. Get any Raise Dead Spell
2. Use it
3. No mobs spawn

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 3.1.2

### Forge version

1.20.1

### Other mods

![Screenshot 2024-04-16 125453](https://github.com/iron431/irons-spells-n-spellbooks/assets/167238678/6340e708-a2ba-4cc6-bef7-196f91f19416)

**Comment by iron431** [comment]
use the lastest version
