### ISSUE TITLE
Jenkins

### ISSUE THREAD

**Issue by SamuelM28** [iron431/Irons-Spells-n-Spellbooks#399]
### Observed behaviour

The Game crashes in the world creation screen, deleting the mod fix the issue  

### Expected behaviour

Create a new world?

### Steps to reproduce

Open the Game 
Select world creation 

### Server Type

Single Player

### Crashlog

https://gist.github.com/SamuelM28/2c4a81463f9789f2fe59a0ef36bd2c22

### Iron's Spells N Spellbooks version

1.20.1-3.1.3

### Forge version

1.20.1 47.2.23

**Comment by iron431** [comment]
> Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: io.redspace.ironsspellbooks.capabilities.spellbook.SpellBookData

It looks like you are using an outdated addon. ~~@SamuelM28 Can you confirm?~~ Yes, All the Wizard Gear 1.0.9 is incompatible with 3.0.0+. Update it to fix.

**Comment by SamuelM28** [comment]
> > Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: io.redspace.ironsspellbooks.capabilities.spellbook.SpellBookData
> 
> It looks like you are using an outdated addon. ~@SamuelM28 Can you confirm?~ Yes, All the Wizard Gear 1.0.9 is incompatible with 3.0.0+. Update it to fix.

**Comment by SamuelM28** [comment]
Thanks bro
