### ISSUE TITLE
[Bug] The Dead King teleports into walls

### ISSUE THREAD

**Issue by Korumaku** [iron431/Irons-Spells-n-Spellbooks#40]
### Observed behaviour

The Dead King has a habit of teleporting into the walls in his arena and thus slowly killing himself. At first I thought this was rare or simply an issue with him recognizing the edge of blocks, since he teleported into the first layer of blocks in his arena, but once I dug him out, he teleported again, but this time *much* further into the wall, several blocks deep.

P.S. Beautiful work on this mod, looking forward to watching it gain a large following :)

### Expected behaviour

Can't really say I expected him to teleport into a wall, but I guess it helped me finish the fight pretty quickly.

### Steps to reproduce

Not sure if it had to do with me hanging out behind the pillars on the lower floor of the arena while healing while he's near his throne, but that's where I was when it happened

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.1.1

### Forge version

1.19.2 - 43.2.11

### Other mods

Not sure if this is relevant to this report, but here:

[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
    [OpenBlocks Trophies (by GizmoTheMoonPig)](https://www.curseforge.com/minecraft/mc-mods/openblocks-trophies)
    [Piglin Proliferation (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/piglin-proliferation)
    [Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
    [Neko's Enchanted Books (by Nekomaster1000)](https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books)
    [Domestication Innovation (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/domestication-innovation)
    [Create: Steam 'n' Rails (by mattentosh)](https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails)
    [AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
    [Alex's Delight (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/alexs-delight)
    [Dragon Mounts: Legacy (by UnitKay9)](https://www.curseforge.com/minecraft/mc-mods/dragon-mounts-legacy)
    [Brewin' And Chewin' (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin)
    [Better Third Person (by Socolio)](https://www.curseforge.com/minecraft/mc-mods/better-third-person)
    [Tetranomicon (by syrikalis)](https://www.curseforge.com/minecraft/mc-mods/tetranomicon)
    [Farmer's Respite (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite)
    [AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
    [Dynamic Crosshair (by Crendgrim)](https://www.curseforge.com/minecraft/mc-mods/dynamic-crosshair)
    [Storage Drawers (by Texelsaur)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers)
    [Chalk (by mortuus_art)](https://www.curseforge.com/minecraft/mc-mods/chalk)
    [[SBM] Jukebox (by StrikerRocker)](https://www.curseforge.com/minecraft/mc-mods/sbm-jukebox)
    [Create Central Kitchen (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-central-kitchen)
    [Oreganized (by xaidee)](https://www.curseforge.com/minecraft/mc-mods/oreganized)
    [Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
    [Compat Makeover (by phoenixknight___)](https://www.curseforge.com/minecraft/mc-mods/compat-makeover)
    [Modular Golems (by lcy0x1)](https://www.curseforge.com/minecraft/mc-mods/modulargolems)
    [Band of Gigantism (by textstack)](https://www.curseforge.com/minecraft/mc-mods/band-of-gigantism)
    [Extended Mushrooms (by thecech12)](https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms)
    [Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
    [Infinity Buttons (by LarsMans)](https://www.curseforge.com/minecraft/mc-mods/infinity-buttons)
    [Mutant More (by alexandersfunandgames)](https://www.curseforge.com/minecraft/mc-mods/new-mutant-more)
    [I Know What I'm Doing (IKWID) (by HeckinChloe)](https://www.curseforge.com/minecraft/mc-mods/i-know-what-im-doing)
    [Heartstone (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/heartstone)
    [Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
    [Kiwi 🥝 (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/kiwi)
    [Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
    [More Dragon Eggs (by Darkere)](https://www.curseforge.com/minecraft/mc-mods/more-dragon-eggs)
    [BiomeTweaker (by superckl)](https://www.curseforge.com/minecraft/mc-mods/biometweaker)
    [Delightful (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/delightful)
    [Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
    [Art of Forging: A Tetra Addon (by Eldritch_King24)](https://www.curseforge.com/minecraft/mc-mods/art-of-forging-a-tetra-addon)
    [CoFH Core (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/cofh-core)
    [Snow! Real Magic! ⛄ (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/snow-real-magic)
    [More Frogs - Fabric/Quilt/Forge (by frikinjay)](https://www.curseforge.com/minecraft/mc-mods/more-frogs-fabric)
    [YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
    [Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
    [YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
    [Dyenamics and Friends (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/dyenamicsandfriends)
    [Dynamic Surroundings Resurrected (by theNyfaria)](https://www.curseforge.com/minecraft/mc-mods/dynamic-surrounding-resurrected)
    [Global Packs (by JTK222)](https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack)
    [YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
    [Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
    [Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
    [Desolation (Forge) (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/desolation-forge)
    [Tetra Toolbooster (by syrikalis)](https://www.curseforge.com/minecraft/mc-mods/tetra-toolbooster)
    [Tetra (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/tetra)
    [End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
    [YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
    [Sculked (by Ethan_4d)](https://www.curseforge.com/minecraft/mc-mods/sculked)
    [Withering Boon: A Tetra Material Addon (by faerminded)](https://www.curseforge.com/minecraft/mc-mods/tetra-booster-pack)
    [Quark Oddities (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark-oddities)
    [Respiteful (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/respiteful)
    [Boatload (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/boatload)
    [Tetra's Delight (by hyperlynx01)](https://www.curseforge.com/minecraft/mc-mods/tetras-delight)
    [Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
    [Overweight Farming (by agentmhkskg)](https://www.curseforge.com/minecraft/mc-mods/overweight-farming)
    [YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
    [Wither Skeleton Totem (by Barribob)](https://www.curseforge.com/minecraft/mc-mods/wither-totem)
    [Abnormals Delight (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/abnormals-delight)
    [Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
    [Dramatic Doors (by FizzWare)](https://www.curseforge.com/minecraft/mc-mods/dramatic-doors)
    [Upgrade Aquatic (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
    [Jade Addons (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
    [HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
    [Repurposed Structures (Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
    [Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
    [Tetra Materials (by PthaloTheSimp)](https://www.curseforge.com/minecraft/mc-mods/tetra-materials)
    [Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
    [Neapolitan (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/neapolitan)
    [Ensorcellation (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/ensorcellation)
    [Spelunkery (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/spelunkery)
    [Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
    [Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
    [Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed)
    [Enchant With Mob (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/enchant-with-mob)
    [Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
    [Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
    [Cyclops Core (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
    [More Axolotl Variants API (by AkashiiKun69)](https://www.curseforge.com/minecraft/mc-mods/mavapi)
    [Shutup Experimental Settings! (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/shutup-experimental-settings)
    [Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
    [MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
    [Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
    [NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
    [Personality (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/personality)
    [Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
    [Smarter Farmers (farmers replant) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant)
    [TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
    [Stalwart Dungeons (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons)
    [Supplementaries Squared (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/supplementaries-squared)
    [The Magic Mirror (by tboshoven)](https://www.curseforge.com/minecraft/mc-mods/the-magic-mirror)
    [Dragon Enchants (by FavouriteDragon)](https://www.curseforge.com/minecraft/mc-mods/dragon-enchants)
    [Collector's Reap (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/collectors-reap)
    [Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
    [Lucent (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/lucent)
    [Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
    [Archer's Paradox (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/archers-paradox)
    [Caupona (by khjxiaogu)](https://www.curseforge.com/minecraft/mc-mods/caupona)
    [JER Integration (by AlasDiablo)](https://www.curseforge.com/minecraft/mc-mods/jer-integration)
    [Fog Looks Good Now (by CAPPIN1)](https://www.curseforge.com/minecraft/mc-mods/fog-looks-good-now)
    [Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
    [Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
    [Environmental (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/environmental)
    [Thatched (by lilypuree)](https://www.curseforge.com/minecraft/mc-mods/thatched)
    [Axolotl Bucket Fix (Forge) (by RaymondBlaze)](https://www.curseforge.com/minecraft/mc-mods/axolotl-bucket-fix-forge)
    [Create: Ender Transmission (by Forsteri123)](https://www.curseforge.com/minecraft/mc-mods/create-ender-transmission)
    [L2 Library (by lcy0x1)](https://www.curseforge.com/minecraft/mc-mods/l2library)
    [More Axolotl Variants Mod (by AkashiiKun69)](https://www.curseforge.com/minecraft/mc-mods/mavm)
    [EffectsLeft (by CoolSimulations)](https://www.curseforge.com/minecraft/mc-mods/effectsleft)
    [Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
    [Create Enchantment Industry (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/create-enchantment-industry)
    [Portable Jukebox (by the_will_bl)](https://www.curseforge.com/minecraft/mc-mods/portable-jukebox)
    [Cave Enhancements (by exdrill_10)](https://www.curseforge.com/minecraft/mc-mods/cave-enhancements)
    [playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
    [Knight Quest (by count_grimhart)](https://www.curseforge.com/minecraft/mc-mods/knight-quest)
    [Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
    [GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
    [Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
    [Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
    [Create Encased (by iglee42)](https://www.curseforge.com/minecraft/mc-mods/create-encased)
    [Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
    [Dyenamics (by TeamCoFH)](https://www.curseforge.com/minecraft/mc-mods/dyenamics)
    [Tetratic Combat (by Eldritch_King24)](https://www.curseforge.com/minecraft/mc-mods/tetratic-combat)
    [Carry On (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/carry-on)
    [Create Deco (by talrey)](https://www.curseforge.com/minecraft/mc-mods/create-deco)
    [JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
    [Biome Makeover (Forge) (by Lemonszz)](https://www.curseforge.com/minecraft/mc-mods/biome-makeover-forge)
    [YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
    [Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
    [Productive Bees (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/productivebees)
    [Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
    [Nether Depths Upgrade (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/nether-depths-upgrade)
    [mutil (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/mutil)
    [Curios Quark Oddities Backpack (by 6LeoY)](https://www.curseforge.com/minecraft/mc-mods/curios-quark-oddities-backpack)
    [Elytra Slot (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot)

**Comment by iron431** [comment]
It appears with his custom boss AI, he was skipping the collision check before teleporting. The check is now in place so all issues should be fixed, but I had trouble getting him to get stuck to begin with, so feel free to reply if this continues
