### ISSUE TITLE
Crash during Dead King bossfight

### ISSUE THREAD

**Issue by Maxim-Loginov** [iron431/Irons-Spells-n-Spellbooks#401]
### Observed behaviour

I've gotten through the first stage of the bossfight but then game crashes (even after a restart)

### Expected behaviour

Game not crashing^)

### Steps to reproduce

Fight the Dead King

### Server Type

Single Player

### Crashlog

https://gist.github.com/Maxim-Loginov/323188bcdf5230b2199500a6a0da1d18

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.4

### Forge version

1.18.2-40.2.10

### Other mods

See crash report

**Comment by iron431** [comment]
this is an old bug that has been patched in later versions. the fix will be backported.

**Comment by Maxim-Loginov** [comment]
Thanks a lot! Love the mod, hope to see more.
