### ISSUE TITLE
[Bug] wayward compass issue

### ISSUE THREAD

**Issue by Irfanejat** [iron431/Irons-Spells-n-Spellbooks#403]
### Observed behaviour

I had a Wayward Compass in my hand and it didn't point to the Catacombs even when I located it and was in it. It did thething compasses do when they can't find anything (like Nature's Compass mod for example). Also the compass of the mod Explorer's Compass pointed to a false Catacombs and the wasn't anthing around. Maybe the two are related.

### Expected behaviour

For the compass to point in the direction of the Catacombs.

### Steps to reproduce

Get a Wayward Compass.
See it not working as it shows in every direction.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.4

### Forge version

40.2.18

### Other mods

There are a couple of worldgen mods, but I don't think they are relevant. Nevertheless, here are all the mods in my server:
[modlist.txt](https://github.com/iron431/irons-spells-n-spellbooks/files/15031819/modlist.txt)

**Comment by iron431** [comment]
Please actually explain the issue and how to reproduce it. There is no actionable information in this report. Also refer to the wiki for how the compass is intended to work https://iron.wiki/items/#irons_spellbooks:wayward_compass

**Comment by Irfanejat** [comment]
First of all, I was dumb. Everything is working just fine and I missed the Catacombs in the Spectator Mode. However, as it is, the Compass is a one time craft (as vaguely implied in iron.wiki) and doesn't update as you travel. I suggest that it updates every time you right click for example, just like how it is with Nature's or Explorer's Compass. In my case, When I crafted it wasn't pointing into anything because there wasn't any Catacombs in my area, which led me to post this issue. I would recommend to at least make it clearer that it won't update to the player.
With that stated, I will close this issue. Thanks for your reply and sorry for wasting your time.
