### ISSUE TITLE
[Bug] Cauldron broken with carry on mod

### ISSUE THREAD

**Issue by GauntAndreX8** [iron431/Irons-Spells-n-Spellbooks#406]
### Observed behaviour

With the carry on mod, when i picked up the cauldron(from your mod) and place it down, it creates a bug that doesn't make you drop the cauldron and duplicates when you keep trying to place it

### Expected behaviour

Suppose to pick up then place it down normally with the carry on mod

### Steps to reproduce

Have carry on mod install with this mod
place cauldron down, then shift right click to pick it up
place down cauldron by right clicking and bug starts to appear

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.3

### Forge version

1.20.1-47.2.0

### Other mods

Carry on mod interfere iron spell mod when carrying cauldron

**Comment by iron431** [comment]
This is a known carry on issue and should be reported to them
