### ISSUE TITLE
[Bug] Rendering Issue with Armor

### ISSUE THREAD

**Issue by Exokyhh** [iron431/Irons-Spells-n-Spellbooks#407]
### Observed behaviour

When looking far away from the player (like the sky), if any armor from this mod is equipped, a small player will be seen near the crosshair, repeating your moves (it will have your armor).

https://github.com/iron431/irons-spells-n-spellbooks/assets/90096585/99c9d71d-9f2a-4b7d-86d4-bddbe3c4d3c3

### Expected behaviour

Not any of what I've said, this visual bug shouldn't exist.

### Steps to reproduce

1. Enable Shaders
2. Wear any armor from this mod
3. Look at the sky or far away and focus on your crosshair (the mini player will appear)

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-3.1.3

### Forge version

1.19.2 - 43.3.0

### Other mods

-Embeddium (embeddium-0.3.14+mc1.19.2)
- oculus-mc1.19.2-1.6.9.jar (with ComplementaryReimagined_r5.1.1)

**Comment by kaairu** [comment]
this is an issue with geckolib armors

**Comment by Exokyhh** [comment]
So should I open a new issue on the Geckolib github?

**Comment by Exokyhh** [comment]
Also, I just wanted to point this out, a few days ago I found a very similar issue with the Gliders mod (https://github.com/Jeryn99/MC-Gliders/issues/62), but the mod doesn't require Geckolib as a dependency. Don't get me wrong, I'm not doubting you ahaha
I'm not into modding so idk what could cause this, but it's very strange. I guess I'll wait for a fix

**Comment by iron431** [comment]
geckolib no longer supports 1.19.2. they are already aware of the issue, it is fixed 1.20+
