### ISSUE TITLE
Option to hide mana number

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#41]
### Feature description

The mana bar has a beautiful visual to it that is tainted by oddly floating numbers ontop of it!  
I'd like to suggest adding an option to hide the numbers so that one can just have the mana bar, thanks!

### How it improves the player experience

I believe hiding the mana number would make for a cleaner and more polished UI matching most games and would love to see an option to do so in this amazingly well designed mod.

**Comment by lab3** [comment]
I like this idea. We will add a config option for it

**Comment by iron431** [comment]
released in 1.1.2
