### ISSUE TITLE
Compatible with Epic Fight please 🥺

### ISSUE THREAD

**Issue by Pokecraft1234** [iron431/Irons-Spells-n-Spellbooks#412]
### Feature description

Hello, you must have surely heard the incompatibility of your iron's spell'n'spellbook mode with Epic Fight. Epic Fight is a mode that enhances the combat experience that would go well with your mode. In fact this one does not work because when we use a spell we do not see in front of us but in the head of our character. Surprisingly due to change in head position. The hand animations don't take place either, but please fix the camera problem already.

### How it improves the player experience

this will allow you to have incredible fights with incredible spells

**Comment by maximogta** [comment]
In Epic Fight Discord Server you can find a mod for forge 1.20.1 to add casting animations for epic fight when casting spells from irons spells.

**Comment by Pokecraft1234** [comment]
Thank you and it’s work for the caméra ?

**Comment by maxhightower** [comment]
Was there a fix for this? I'm also encountering the issue

**Comment by Pokecraft1234** [comment]
yes you just have to change true to false in the animations in the iron’s spell mode configuration exemple
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/162625097/91fdb58a-02c4-4f47-9d1a-2bf62ab89a31)
the animations will be deactivated but a mode in the epic fight server puts them back 
Sorry for m’y bad english

**Comment by iron431** [comment]
with the config and various addons/resourcepacks there should be plenty to resolve any conflicts. otherwise, this will not directly be worked on
