### ISSUE TITLE
[Bug] Theres name above Sculk Tentacles

### ISSUE THREAD

**Issue by ar4ik313** [iron431/Irons-Spells-n-Spellbooks#413]
### Observed behaviour

![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/81323811/708672ce-bf90-4a34-967b-42f667a71fde)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/81323811/652f02af-ad68-4b2e-9aeb-76b99a254107)

### Expected behaviour

I excepted Sculk Tentacles without they're names above them

### Steps to reproduce

When i used Sculk Tentacles, they're names appeared above them, i dont use other modes beside Iron Spells and spellbooks

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.3

### Forge version

1.20.1-47.2.30

### Other mods

caelus api-3.2.0-1.20.1
curios-forge-5.8.1-1.20.1
geckolib-forge-1.20.1-4.4.4
player-animation-lib-forge-1.0.2-rc1+1.20

**Comment by iron431** [comment]
? 
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/34083081/a988a756-179d-45e0-815d-230ee50cb65c)

**Comment by bruglet** [comment]
Can't isolate the problem since I have way too many mods, but can confirm that I have name tags above my sculk tentacles. I'm running 1.20.1-3.1.4

**Comment by Cyolence** [comment]
This seems to be a problem with Geckolib. I just tested a couple version of it with the newest Release of SnS and from what I can tell, 4.4 - 4.4.5 have this problem. 4.3.1 works fine

4.3.1 Geckolib
![without name](https://github.com/iron431/irons-spells-n-spellbooks/assets/161567834/f34162a0-7221-4870-98a2-b6760ff119ae)

4.4 - 4.4.5 Geckolib
![with name](https://github.com/iron431/irons-spells-n-spellbooks/assets/161567834/18097c6e-c390-482d-88a8-088b94fbf959)

**Comment by iron431** [comment]
fixed in 3.2.0
