### ISSUE TITLE
[Bug] What should I do if there is no alchemical cauldron?

### ISSUE THREAD

**Issue by Hirotochka** [iron431/Irons-Spells-n-Spellbooks#414]
### Observed behaviour

The problem is that there is no alchemy cauldron in fashion. What should I do, is there an alternative?

### Expected behaviour

The problem is that there is no alchemy cauldron in fashion. What should I do, is there an alternative?

### Steps to reproduce

3.The problem is that there is no alchemy cauldron in fashion. What should I do, is there an alternative?

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.18.2-1.1.4.3

### Forge version

1.18.2

**Comment by kaairu** [comment]
1.18.2 has been discontinued in terms of content updates, the alchemist cauldron is only in the 1.19 and 1.20 versions

**Comment by Hirotochka** [comment]
oh(
