### ISSUE TITLE
Config option to disable "Iron's Guidebook" item being given to new players

### ISSUE THREAD

**Issue by The-Goat-HUN** [iron431/Irons-Spells-n-Spellbooks#415]
### Feature description

A config option to turn off the Patchouli guidebook from being given to new players.

### How it improves the player experience

This would help clean up the player's starting inventory in modpacks.

**Comment by kaairu** [comment]
just make a datapack or use https://www.curseforge.com/minecraft/texture-packs/iron-spellbooks-patchouli-book-removal
