### ISSUE TITLE
[Bug] Issue with the effect of aspect of the spider spell

### ISSUE THREAD

**Issue by Lando77777** [iron431/Irons-Spells-n-Spellbooks#416]
### Observed behaviour

the spell aspect of the spider created on a scroll forge and put in an ancient codex doesn't work and the duration and it's value effect or not those registered.

and the spell doesn't functionnate at all when you use it by his different way of proc.

### Expected behaviour

true value and the spell activating

### Steps to reproduce

cf description

### Server Type

Single Player

### Iron's Spells N Spellbooks version

the latest

### Forge version

the latest

### Other mods

many of mods but no terraforma or things weird..

**Comment by iron431** [comment]
if there is an issue, create a proper report. there its zero information to glean from this post.
