### ISSUE TITLE
apotheosis spawner NoAi does not work on the dead corpse king

### ISSUE THREAD

**Issue by sadan4** [iron431/Irons-Spells-n-Spellbooks#419]
### Observed behaviour

when the dead corpse king is in the mob spawner with NoAi, it **does have** ai

### Expected behaviour

when the dead corpse king is in the mob spawner with NoAi, it does not have ai

### Steps to reproduce

- get dead corpse king spawn egg
- put it in a spawner with NoAi
- see that it has Ai

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.1.1

### Forge version

1.20.1-47.2.20

### Other mods

the atm9 modpack

**Comment by iron431** [comment]
The dead king corpse doesn't have AI at all. What are you saying the expected behavior of setting no ai is supposed to be?

**Comment by sadan4** [comment]
I don't know the name for it, but with the no AI modification on the apotheosis spawner, the boss that comes from the dead corpse king has ai

**Comment by iron431** [comment]
what is he doing that you expect him to not do while under no ai?

**Comment by sadan4** [comment]
summoning mobs, attacking the player, etc. 

if you want, i can attach a video by the end of the day

**Comment by iron431** [comment]
that is not the corpse entity, that is the summoned dead king. they are completely separate entities
