### ISSUE TITLE
Game Crash when hovering over [Bug] 

### ISSUE THREAD

**Issue by A4AAAAAA** [iron431/Irons-Spells-n-Spellbooks#42]
### Observed behaviour

I went to the Equipment Tab to look at the armors but when I hovered over over the armor the game crashed but only while hovering over armor the first row of items was fine.

### Expected behaviour

I expceted it to show me the name of the item.

### Steps to reproduce

1.Open a world in creative
2.Go to the Iron's Spellbook Equipment tab
3.Hover with your cursor over any armor

### Server Type

Single Player

### Crashlog

https://gist.github.com/A4AAAAAA/05d51a1a673755d03e22e8ab1654bd98

### Iron's Spells N Spellbooks version

1.1.1

### Forge version

1.19.2 Forge 43.2.11

### Other mods

Ad Astra
Adaptive Performance Tweaks: Core
Akashic Tome
Alex's Armoury
Alex's Mobs
AmbientSounds 5
Architect's Palette
Borderless Window
Climb Ladders Fast
Clumps
Controlling
Create
Dimensional Dungeons
Droplight
Dungeon Crawl
Dungeons Gear
Enchantment Descriptions
End Remastered
Ensorcellation
Entity Culling Fabric/Forge
Epic Knights: Shields, Armor   and Weapons
ESSENTIAL Mod
Falling Leaves
Farmer's Delight
Fast Leaf Decay
FPS Reducer
Handcrafted
Harvest with ease
Hex Casting
Immersive Aircraft
Inventory Essentials
Inventory Sorter
Item Borders
ItemPhysic Full
Jade 🔍
Just Another Rotten Flesh to   Leather Mod
Just Enough Items (JEI)
Knight Quest
L_Ender 's Cataclysm
Large Ore Deposits
Legendary Tooltips
Let Me Despawn
Looot
Lootr
MineColonies
Mod Name Tooltip
Mouse Tweaks
Multi Mine
Oculus
Ore Excavation
Pick Up Notifier
Pumpkillager's Quest
Quark
Radon
Regions Unexplored
River Redux
Rubidium
Saturn
Shield Expansion
Sophisticated Backpacks
spark
Stack Refill
Tectonic
Terralith
The Lost Castle
Tom's Simple Storage Mod
Towns and Towers
TrashSlot
Traveler's Titles (Forge)
Visual Workbench
William Wythers' Overhauled   Overworld

**Comment by kaairu** [comment]
this is a crash relating to the latest quark update and equipment compare. report it to them

**Comment by A4AAAAAA** [comment]
ok but still thanks.

**Comment by iron431** [comment]
Quark already fixed this, update Quark
