### ISSUE TITLE
[Bug] Clear command cannot clear magic book.

### ISSUE THREAD

**Issue by ghost** [iron431/Irons-Spells-n-Spellbooks#422]
### Observed behaviour

"/clear" command cannot clear on bauble's magic book

### Expected behaviour

"/clear" command cannot clear on bauble's magic book

### Steps to reproduce

1.Equip a magic book on Curio's bauble slot
2.run /clear command
3.Others Equipment and bauble has cleared,only left the magic book.

### Server Type

Single Player

### Crashlog

NONE

### Iron's Spells N Spellbooks version

1.20.1-3.1.4

### Forge version

1.20.1-47.2.30

### Other mods

Curios-5.8.1

**Comment by iron431** [comment]
that is an issue with curios, the mod that adds the extra slots.
