### ISSUE TITLE
[Bug] Mana regen attribute cannot be set lower than 1

### ISSUE THREAD

**Issue by UmbralCosmos** [iron431/Irons-Spells-n-Spellbooks#423]
### Observed behaviour

[Bug] Setting the mana regen attribute to anything between 0 and 1 doesn't work.
Setting the value between 1 and 0 (0.X) acts as if it has been set to 0 (same goes for the negatives, as those act as 0 too)

### Expected behaviour

For the mana regen attribute to be settable below 1.

### Steps to reproduce

/attribute @s irons_spellbooks:mana_regen base set 0.X
or
/attribute @s irons_spellbooks:mana_regen base set -X

/attribute @s irons_spellbooks:mana_regen get to check

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 3.1.4

### Forge version

1.20.1 - 47.2.17

### Other mods

Alone and with AttributeFix

**Comment by iron431** [comment]
will be fixed in the next update

**Comment by iron431** [comment]
fixed in 3.1.5
