### ISSUE TITLE
[Bug]  When visible, the spellbooks in the spellbook curio slot cause outer layers of the player model to stop abiding by the fresh moves resource pack when the 3D Skin Layers mod is installed.

### ISSUE THREAD

**Issue by UmbralCosmos** [iron431/Irons-Spells-n-Spellbooks#424]
### Observed behaviour

No other curio item causes this.
When the spellbook is equipped in the curio slot, the outer layers of the player model follow their default parentage without fresh moves.

I have observed that unlike all other curios at my disposal, the spellbooks do not follow the fresh moves parentage.
With my limited knowledge I assume they are not parented to an individual body part but to an object higher in the hierarchy.  

### Expected behaviour

For the 3d outer layers of the player to follow the right parent.

### Steps to reproduce

Install Fresh Moves resource pack, 3d skin layers mod and all their dependencies.
Equip any spellbook in spellbook curio slot.
Observe.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 3.1.4

### Forge version

1.20.1 - 47.2.17

**Comment by iron431** [comment]
fixed in 3.1.5
