### ISSUE TITLE
[Bug] summoned_zombie and summoned_skeleton incompatibility with resource packs that alter the model of the default zombie and skeletons.

### ISSUE THREAD

**Issue by UmbralCosmos** [iron431/Irons-Spells-n-Spellbooks#428]
### Observed behaviour

Using creepermax123's Better Zombies and Better Skeletons, (which require optifine or EMF and ETF in my case) I have observed that the textures for the summoned_zombie and summoned_skeleton were bugged. 
Makes sense, their model was taken from the default zombie (which had its model changed) but their textures were the same, as they have their own textures.

This can be fixed with a simple resource pack, giving the summoned_zombie and summoned_skeletons model-appropriate textures.
That's when a problem I don't know how to fix myself appears:
The rising dead animation only works with default model textures. 

The simplest way I can imagine to solve this would be to give the summoned_zombie and summoned_skeleton their own model, effectively resolving incompatibility with packs that alter the models of zombies and skeletons. 

### Expected behaviour

For the textures to work I guess. 
I get the feeling making it so the rising animations can work with altered models is probably way too much to ask.

### Steps to reproduce

1. Download Iron's Spellbooks and all its dependencies.
2. Download Entity Model Features and Entity Textures Features
3. Download Creepermax123's Better Zombies and/or Better Skeletons
4. With the resource pack enabled, summon your undead.
5. Observe.

To see how the zombies work with the right textures:
You can either make your own resource pack with the textures from Better Zombies applied to summoned_zombie.
Or you can download the pack I'm providing here.
[Better Zombies - Iron's Patch.zip](https://github.com/iron431/irons-spells-n-spellbooks/files/15287454/Better.Zombies.-.Iron.s.Patch.zip)

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 3.1.4

### Forge version

1.20.1 - 47.2.17

### Other mods

Caelus API
Curios API 
Geckolib
playerAnimator

EMF
ETF

**Comment by iron431** [comment]
We plan to overhaul summons eventually™, and in the meantime do not plan to add compat to every texture pack that changes vanilla models. 

If you want to release that patch as a compat resourcepack, feel free.
