### ISSUE TITLE
[Bug] Crash on Startup

### ISSUE THREAD

**Issue by ToastiMan** [iron431/Irons-Spells-n-Spellbooks#43]
### Observed behaviour

Game crashes with this mod installed. Tried both Versions 1.1.1 and 1.1.0, same message 
"Error loading class: dev/kosmx/playerAnim/minecraftApi/PlayerAnimationAccess (java.lang.ClassNotFoundException: dev.kosmx.playerAnim.minecraftApi.PlayerAnimationAccess)"

Disabling this mod makes Minecraft start just fine.

### Expected behaviour

The game to start

### Steps to reproduce

1. Have the same mods
2. Start the game

### Server Type

Single Player

### Crashlog

https://gist.github.com/ToastiMan/db96d62f802130abeb1b561d4468792d

### Iron's Spells N Spellbooks version

1.1.1 1.1.0

### Forge version

1.19.2-43.2.11

### Other mods

Mod List: 
		saturn-mc1.19.2-0.0.1.jar                         |Saturn                        |saturn                        |0.0.1               |DONE      |Manifest: NOSIGNATURE
		TreeChop-1.19.2-forge-0.17.8a.jar                 |HT's TreeChop                 |treechop                      |0.17.8a             |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.19.2-Forge-3.2.1.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.2-Forge-3.2.1  |DONE      |Manifest: NOSIGNATURE
		UnionLib-1.19.2-9.0.2.1-Forge.jar                 |UnionLib                      |unionlib                      |9.0.2.1             |DONE      |Manifest: NOSIGNATURE
		Piglin-Expansion-1.2.2-1.19.2.jar                 |Piglin Expansion              |piglin_expansion              |1.1.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.19.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		beautify-1.4.3.jar                                |Beautify                      |beautify                      |1.4.3               |DONE      |Manifest: NOSIGNATURE
		UndergroundVillages-1.19.2-1.2.0.jar              |Underground Villages Mod      |underground_villages          |1.2.0               |DONE      |Manifest: NOSIGNATURE
		naturalist-forge-3.0.3a-1.19.2.jar                |Naturalist                    |naturalist                    |3.0.3a              |DONE      |Manifest: NOSIGNATURE
		incontrol-1.19-7.1.7.jar                          |InControl                     |incontrol                     |1.19-7.1.7          |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.19.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		Entity_Collision_FPS_Fix-forge-1.18.2-1.0.0.jar   |Entity Collision FPS Fix      |entitycollisionfpsfix         |1.0.0               |DONE      |Manifest: NOSIGNATURE
		rubidium-0.6.2a.jar                               |Rubidium                      |rubidium                      |0.6.2a              |DONE      |Manifest: NOSIGNATURE
		gildedarmor-forge-1.19.2-1.4.1.jar                |Gilded Armor                  |gildedarmor                   |1.4.1               |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.19.2-10.0.6.0-build.0865.jar     |ForgeEndertech                |forgeendertech                |10.0.6.0            |DONE      |Manifest: NOSIGNATURE
		piglinproliferation-1.19.2-1.0.3.jar              |Piglin Proliferation          |piglinproliferation           |1.19.2-1.0.3        |DONE      |Manifest: NOSIGNATURE
		MoreMobGriefingOptions-1.19.2-2.0.3.jar           |More MobGriefing Options      |moremobgriefingoptions        |2.0.3               |DONE      |Manifest: NOSIGNATURE
		CTM-1.19.2-1.1.6+8.jar                            |ConnectedTexturesMod          |ctm                           |1.19.2-1.1.6+8      |DONE      |Manifest: NOSIGNATURE
		Placebo-1.19.2-7.1.2.jar                          |Placebo                       |placebo                       |7.1.2               |DONE      |Manifest: NOSIGNATURE
		citadel-2.1.3-1.19.jar                            |Citadel                       |citadel                       |2.1.3               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.6.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.6  |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.5.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.5        |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.2.18.jar                |Bookshelf                     |bookshelf                     |16.2.18             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.19.2-1.5.5.jar                   |Guard Villagers               |guardvillagers                |1.19.2-1.5.5        |DONE      |Manifest: NOSIGNATURE
		bygonenether-1.2.2-1.19.2.jar                     |Bygone Nether                 |bygonenether                  |1.2.2               |DONE      |Manifest: NOSIGNATURE
		SimplyHouses-1.1.3-1.19-forge.jar                 |Simply Houses                 |simply_houses                 |1.1.3.1-1.19        |DONE      |Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		paladin-furniture-mod-1.1.1-forge-mc1.19.jar      |Paladin's Furniture           |pfm                           |1.1.1               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.19.2-4.2.1518-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1518            |DONE      |Manifest: NOSIGNATURE
		upgradednetherite-1.19.2-5.1.0.9-release.jar      |Upgraded Netherite            |upgradednetherite             |1.19.2-5.1.0.9-relea|DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.19.2-1.4.7.jar               |Advancement Plaques           |advancementplaques            |1.4.7               |DONE      |Manifest: NOSIGNATURE
		chipped-forge-1.19.2-2.1.4.jar                    |Chipped                       |chipped                       |2.1.4               |DONE      |Manifest: NOSIGNATURE
		out_of_sight-1.19.2-1.0.2.jar                     |Out of Sight                  |out_of_sight                  |1.19.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		tenshilib-1.19.2-1.6.15-forge.jar                 |TenshiLib                     |tenshilib                     |1.19.2-1.6.15       |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.1.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.1          |DONE      |Manifest: NOSIGNATURE
		torchmaster-19.2.0.jar                            |Torchmaster                   |torchmaster                   |19.2.0              |DONE      |Manifest: NOSIGNATURE
		morevillagers-forge-1.19-4.0.3.jar                |More Villagers                |morevillagers                 |4.0.3               |DONE      |Manifest: NOSIGNATURE
		Ping-1.19-1.9.1.jar                               |Ping                          |ping                          |1.19-1.9.1          |DONE      |Manifest: NOSIGNATURE
		simpleshops-1.2.1.jar                             |Simple Shops                  |simpleshops                   |1.1.4               |DONE      |Manifest: NOSIGNATURE
		endrem_forge-5.2.1-R-1.19.X.jar                   |End Remastered                |endrem                        |5.2.1-R-1.19.2      |DONE      |Manifest: NOSIGNATURE
		drawerfps-1.19.2-1.8.jar                          |Example Mod                   |drawerfps                     |1.19.2-1.8          |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.19.2-Forge-3.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.19.2-Forge-3.1.0  |DONE      |Manifest: NOSIGNATURE
		simplefarming-1.19.2-2.0.4.jar                    |Simple Farming                |simplefarming                 |1.19.2-2.0.4        |DONE      |Manifest: NOSIGNATURE
		Immunity+Enchantments+1.0.0+-+1.19.2.jar          |Immunity Enchantments         |immunity_enchantments         |1.0.0               |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.19.2-1.0.20.jar         |Resourcefulconfig             |resourcefulconfig             |1.0.20              |DONE      |Manifest: NOSIGNATURE
		cloudstorage-1.3.4-1.19.2.jar                     |Cloud Storage                 |cloudstorage                  |1.3.4               |DONE      |Manifest: NOSIGNATURE
		wthit-forge-5.16.1.jar                            |wthit                         |wthit                         |5.16.1              |DONE      |Manifest: NOSIGNATURE
		spark-1.10.37-forge.jar                           |spark                         |spark                         |1.10.37             |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |DONE      |Manifest: NOSIGNATURE
		blockui-1.19-0.0.64-ALPHA.jar                     |UI Library Mod                |blockui                       |1.19-0.0.64-ALPHA   |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.19.2-1.2.8a.jar                        |Oculus                        |oculus                        |1.2.8a              |DONE      |Manifest: NOSIGNATURE
		collective-1.19.2-6.53.jar                        |Collective                    |collective                    |6.53                |DONE      |Manifest: NOSIGNATURE
		Explosiont-1.19.2-2.4.7.jar                       |Explosion't                   |explosiont                    |1.19.2-2.4.7        |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.19.2-Forge-3.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.19.2-Forge-3.1.0  |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		overweightfarming-1.19.2-2.0.1-forge.jar          |Overweight Farming            |overweight_farming            |1.19.2-2.0.0-forge  |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.19.2-1.1.24.jar            |Resourceful Lib               |resourcefullib                |1.1.24              |DONE      |Manifest: NOSIGNATURE
		eatinganimation-1.19-3.2.0.jar                    |Eating Animation              |eatinganimation               |3.0.0               |DONE      |Manifest: NOSIGNATURE
		architectury-6.5.82-forge.jar                     |Architectury                  |architectury                  |6.5.82              |DONE      |Manifest: NOSIGNATURE
		Ottercraft-forge-1.19.2-1.1.13.jar                |Ottercraft                    |ottercraft                    |1.1.13              |DONE      |Manifest: NOSIGNATURE
		AI-Improvements-1.19.2-0.5.2.jar                  |AI-Improvements               |aiimprovements                |0.5.2               |DONE      |Manifest: NOSIGNATURE
		glowinc-1.19.2_1.3.3.jar                          |Glow Inc.                     |glowinc                       |1.19.2_1.3.3        |DONE      |Manifest: NOSIGNATURE
		AdChimneys-1.19.2-9.1.10.0-build.0865.jar         |Advanced Chimneys             |adchimneys                    |9.1.10.0            |DONE      |Manifest: NOSIGNATURE
		the_bumblezone_forge-6.7.19+1.19.2.jar            |The Bumblezone                |the_bumblezone                |6.7.19+1.19.2       |DONE      |Manifest: NOSIGNATURE
		HigherWorldDeeperOceans-1.19.x.jar                |Higher World Deeper Oceans    |higherworlddeeperocean        |0.0.2               |DONE      |Manifest: NOSIGNATURE
		Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar        |Towns and Towers              |t_and_t                       |1.10                |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.39.jar                    |GeckoLib                      |geckolib3                     |3.1.39              |DONE      |Manifest: NOSIGNATURE
		sliceanddice-forge-2.2.0.jar                      |Create Slice & Dice           |sliceanddice                  |0.0.0-dev           |DONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.19.2-0.3.0.148.jar           |Better Advancements           |betteradvancements            |0.3.0.148           |DONE      |Manifest: NOSIGNATURE
		Kiwi-1.19.1-forge-8.3.4.jar                       |Kiwi                          |kiwi                          |8.3.4               |DONE      |Manifest: NOSIGNATURE
		cozy-1.1.0-forge.jar                              |Cozy                          |cozy                          |1.1.0               |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.19.2-6.0.6.jar                         |Cucumber Library              |cucumber                      |6.0.6               |DONE      |Manifest: NOSIGNATURE
		toasticraft-1.19.2-0.1.0b.jar                     |ToastiCraft                   |toasticraft                   |1.19.2-0.1.0b       |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1015.jar                  |Just Enough Items             |jei                           |11.6.0.1015         |DONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v4.2.4-1.19.2-Forge.jar           |Visual Workbench              |visualworkbench               |4.2.4               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		waystones-forge-1.19-11.1.0.jar                   |Waystones                     |waystones                     |11.1.0              |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.19.1-1.3.1.jar                    |Falling Leaves                |fallingleaves                 |1.3.1               |DONE      |Manifest: NOSIGNATURE
		Structory_1.19.3_v1.3.1a.jar                      |Structory                     |structory                     |1.3.1a              |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |DONE      |Manifest: NOSIGNATURE
		integrated_api_forge-1.2.7+1.19.2.jar             |Integrated API                |integrated_api                |1.2.7+1.19.2        |DONE      |Manifest: NOSIGNATURE
		comforts-forge-6.0.5+1.19.2.jar                   |Comforts                      |comforts                      |6.0.5+1.19.2        |DONE      |Manifest: NOSIGNATURE
		ColorfulAzaleas-forge-1.19.2-2.3.1.jar            |ColorfulAzaleas               |colorfulazaleas               |2.3.1               |DONE      |Manifest: NOSIGNATURE
		artifacts-1.19.2-5.0.2.jar                        |Artifacts                     |artifacts                     |1.19.2-5.0.2        |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.19.2-8.1.0.24.jar                 |Serene Seasons                |sereneseasons                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		dbExtended-1.19-5.1.jar                           |Dave's Building Extended      |davebuildingmod               |5.1                 |DONE      |Manifest: NOSIGNATURE
		configured-2.1.1-1.19.2.jar                       |Configured                    |configured                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		badpackets-forge-0.2.1.jar                        |Bad Packets                   |badpackets                    |0.2.1               |DONE      |Manifest: NOSIGNATURE
		Decorative+Blocks-forge-1.19.2-3.0.0.jar          |Decorative Blocks             |decorative_blocks             |3.0.0               |DONE      |Manifest: NOSIGNATURE
		starlight-1.1.1+forge.cf5b10b.jar                 |Starlight                     |starlight                     |1.1.1+forge.a3aea74 |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.19.2-Forge-2.2.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.19.2-Forge-2.2.1  |DONE      |Manifest: NOSIGNATURE
		catalogue-1.7.0-1.19.2.jar                        |Catalogue                     |catalogue                     |1.7.0               |DONE      |Manifest: NOSIGNATURE
		blueprint-1.19.2-6.1.2.jar                        |Blueprint                     |blueprint                     |6.1.2               |DONE      |Manifest: NOSIGNATURE
		boatload-1.19.2-4.2.1.jar                         |Boatload                      |boatload                      |4.2.1               |DONE      |Manifest: NOSIGNATURE
		savage_and_ravage-1.19.2-5.0.4.jar                |Savage & Ravage               |savage_and_ravage             |5.0.4               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.19-5.0.1.jar                       |Buzzier Bees                  |buzzier_bees                  |5.0.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.11-universal.jar                |Forge                         |forge                         |43.2.11             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		VanillaTweaks-forge-1.19.2-1.5.65.jar             |VanillaTweaks                 |vanillatweaks                 |1.5.65              |DONE      |Manifest: NOSIGNATURE
		TravelersTitles-1.19.2-Forge-3.1.2.jar            |Traveler's Titles             |travelerstitles               |1.19.2-Forge-3.1.2  |DONE      |Manifest: NOSIGNATURE
		rlp-1.4.0-1.19.2.jar                              |Redstone Lamps Plus           |rslamps_plus                  |1.4.0               |DONE      |Manifest: NOSIGNATURE
		friendsandfoes-forge-mc1.19.2-1.8.2.jar           |Friends&Foes                  |friendsandfoes                |1.8.2               |DONE      |Manifest: NOSIGNATURE
		idas_forge-1.7.3+1.19.2.jar                       |Integrated Dungeons and Struct|idas                          |1.7.3+1.19.2        |DONE      |Manifest: NOSIGNATURE
		MysticalAgriculture-1.19.2-6.0.8.jar              |Mystical Agriculture          |mysticalagriculture           |6.0.8               |DONE      |Manifest: NOSIGNATURE
		LootBag-1.19.2-1.2.2.jar                          |Loot Bag                      |lootbag                       |1.19.2-1.2.2        |DONE      |Manifest: NOSIGNATURE
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		radon-0.8.2.jar                                   |Radon                         |radon                         |0.8.2               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.2-17.1.2.544.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.2.544          |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.34-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.34       |DONE      |Manifest: NOSIGNATURE
		commonality-1.19.2-4.2.1.jar                      |Commonality                   |commonality                   |4.2.1               |DONE      |Manifest: NOSIGNATURE
		NoChatReports-FORGE-1.19.2-v1.5.1.jar             |No Chat Reports               |nochatreports                 |1.19.2-v1.5.1       |DONE      |Manifest: NOSIGNATURE
		HopoBetterRuinedPortals-[1.19-1.19.3]-1.3.3.jar   |HopoBetterRuinedPortals       |hoporp                        |1.3.3               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.12.4+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.4+1.19.2       |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.19-1.0.83-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.19-1.0.83-ALPHA   |DONE      |Manifest: NOSIGNATURE
		kffmod-3.9.1.jar                                  |Kotlin For Forge              |kotlinforforge                |3.9.1               |DONE      |Manifest: NOSIGNATURE
		rottencreatures-forge-1.19.2-1.0.1.jar            |Rotten Creatures              |rottencreatures               |1.0.1               |DONE      |Manifest: NOSIGNATURE
		BrewinAndChewin-1.19-2.0.jar                      |Brewin' and Chewin'           |brewinandchewin               |1.19-2.0            |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.19.2-forge-1.1.4.jar                    |Iceberg                       |iceberg                       |1.1.4               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a-14.jar              |Flywheel                      |flywheel                      |0.6.8.a-14          |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.1.b.jar                         |Create                        |create                        |0.5.1.b             |DONE      |Manifest: NOSIGNATURE
		create_crystal_clear-0.2.1-1.19.2.jar             |Create: Crystal Clear         |create_crystal_clear          |1.19.2-0.2.a        |DONE      |Manifest: NOSIGNATURE
		gravestone-1.19.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.19.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		create-stuff-additions1.19.2_v2.0.3a.jar          |Create Stuff & Additions      |create_sa                     |2.0.3.              |DONE      |Manifest: NOSIGNATURE
		performant-1.19.2-8.3.jar                         |Performant                    |perf                          |5.8                 |DONE      |Manifest: NOSIGNATURE
		FastWorkbench-1.19.2-7.1.2.jar                    |Fast Workbench                |fastbench                     |7.1.2               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |DONE      |Manifest: NOSIGNATURE
		Quark-3.4-402.jar                                 |Quark                         |quark                         |3.4-402             |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.3.14.jar                 |Supplementaries               |supplementaries               |1.19.2-2.3.14       |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.19.2-4.0.2.jar                |Abnormals Delight             |abnormals_delight             |4.0.2               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.19-11.1.2.jar                    |Storage Drawers               |storagedrawers                |11.1.2              |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.6.1-mc1.19.2.jar            |EntityCulling                 |entityculling                 |1.6.1               |DONE      |Manifest: NOSIGNATURE
		backpacked-2.1.12-1.19.2.jar                      |Backpacked                    |backpacked                    |2.1.12              |DONE      |Manifest: NOSIGNATURE
		effective_fg-1.3.4.jar                            |Effective (Forge)             |effective_fg                  |1.3.4               |DONE      |Manifest: NOSIGNATURE
		structurize-1.19.2-1.0.472-BETA.jar               |Structurize                   |structurize                   |1.19.2-1.0.472-BETA |DONE      |Manifest: NOSIGNATURE
		multipiston-1.19.2-1.2.21-ALPHA.jar               |Multi-Piston                  |multipiston                   |1.19.2-1.2.21-ALPHA |DONE      |Manifest: NOSIGNATURE
		upgradedcore-1.19.2-4.1.0.1-release.jar           |Upgraded Core                 |upgradedcore                  |1.19.2-4.1.0.1-relea|DONE      |Manifest: NOSIGNATURE
		FastFurnace-1.19.2-7.0.0.jar                      |FastFurnace                   |fastfurnace                   |7.0.0               |DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-2.0.9-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |2.0.9               |DONE      |Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		apexcore-1.19.2-7.3.1.jar                         |ApexCore                      |apexcore                      |7.3.1               |DONE      |Manifest: NOSIGNATURE
		fantasyfurniture-1.19.2-6.7.0.jar                 |Fantasy's Furniture           |fantasyfurniture              |6.7.0               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v4.4.0-1.19.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |4.4.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Aquaculture-1.19.2-2.4.8.jar                      |Aquaculture 2                 |aquaculture                   |1.19.2-2.4.8        |DONE      |Manifest: NOSIGNATURE
		layered_snowfall-1.0.0+-+1.18.2.jar               |Deeper Snow                   |layered_snowfall              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		improvedmobs-1.19-1.11.0-forge.jar                |Improved Mobs Mod             |improvedmobs                  |1.19-1.11.0         |DONE      |Manifest: NOSIGNATURE
		expandability-forge-7.0.0.jar                     |ExpandAbility                 |expandability                 |7.0.0               |DONE      |Manifest: NOSIGNATURE
		valhelsia_core-forge-1.19.2-0.5.0.jar             |Valhelsia Core                |valhelsia_core                |1.19.2-0.5.0        |DONE      |Manifest: NOSIGNATURE
		domesticationinnovation-1.6.1-1.19.2.jar          |Domestication Innovation      |domesticationinnovation       |1.6.1               |DONE      |Manifest: NOSIGNATURE
		xptome-1.19-2.1.7.jar                             |XP Tome                       |xpbook                        |2.1.7               |DONE      |Manifest: NOSIGNATURE

**Comment by kaairu** [comment]
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/121336317/657c4289-83d6-42f5-8555-e3b63104eac5)
seems like ur missing player animator and caelus API. dependencies for mods can be found here https://legacy.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks/relations/dependencies?filter-related-dependencies=3

**Comment by ToastiMan** [comment]
Well, that's on me, but sure would be nice to have this information somewhere on the mods Description page

**Comment by iron431** [comment]
> player

it is https://legacy.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks/relations/dependencies

**Comment by ToastiMan** [comment]
Well, i meant this page: 
https://legacy.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

For example right under or above "It is recommended to play with [JEI and [Configured]"
