### ISSUE TITLE
pyromancer tower doesn't have pyromancer or basement 

### ISSUE THREAD

**Issue by giuseppothegreat** [iron431/Irons-Spells-n-Spellbooks#437]
### Observed behaviour

I created several different worlds and the result is the same: all pyromancer towers (7 across 4 seeds for now) I find don't have the pyromancer and the basement in them. 

### Expected behaviour

I expect the tower to have at leasst the pyromancer because if not it turns into an utterly useless cool looking build

### Steps to reproduce

fix the tower so that it has the features it used to have 

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-3.1.5

### Forge version

1.19.2

**Comment by iron431** [comment]
fixed in 3.1.6
