### ISSUE TITLE
[Bug] Yes Steve Mod Render Issue

### ISSUE THREAD

**Issue by lab3** [iron431/Irons-Spells-n-Spellbooks#44]
### Observed behaviour

Reporting on behalf of:  meowtionsworld / https://legacy.curseforge.com/members/meowtionsworld

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/1099358/a7ea8e70-fb3e-43f1-9447-1c9852d4f43b)

### Expected behaviour

No render interference

### Steps to reproduce

- Install https://legacy.curseforge.com/minecraft/mc-mods/yes-steve-model
- Cast a Spell

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.1.2

### Forge version

1.19.2-43.2.3

**Comment by lab3** [comment]
Added a change that will disable the first person rendering when all config options are off.  This is a workaround for now. Not sure if the issue is in our mod or thier mod yet.

**Comment by DeshiDesu** [comment]
I'm also having this issue but with Epic Fight in 1.18.2. The custom player model by Epic Fight completely blocks the view in first person when using spells. Disabling the first person rendering options do not work as it is already not rendered, possibly replaced by Epic Fight.

Mods that I used:
>EpicFight-18.3.8.jar
irons_spellbooks-1.18.2-1.0.1.jar
