### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Bobololo08** [iron431/Irons-Spells-n-Spellbooks#440]
### Observed behaviour

When the player gets near a priest it crashed.

### Expected behaviour

It isn't suppose to crash

### Steps to reproduce

I had 
[Bobololo8's Magic.zip](https://github.com/iron431/irons-spells-n-spellbooks/files/15396171/Bobololo8.s.Magic.zip) Mod. Just go near a village and it will crash.

### Server Type

Single Player

### Crashlog

https://gist.github.com/Bobololo08/334e9f3ed80757890931fcc8676a1e1b#file-gistfile1-txt

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

1.20.1

**Comment by iron431** [comment]
this is an issue with pmmo_spellbooks_compat, and should be reported to them

**Comment by Bobololo08** [comment]
Ok thx
