### ISSUE TITLE
[Bug] Black Hole scrolls in the incorrect place in the creative menu

### ISSUE THREAD

**Issue by TomatoSoupter** [iron431/Irons-Spells-n-Spellbooks#441]
### Observed behaviour

Black Hole scrolls are placed amongst eldritch spells in the "Iron's Spellbooks Scrolls" tab 
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/136109129/9037ab27-b8d0-4f89-aba9-1b4e6a42d5f0)

### Expected behaviour

Black Hole scrolls should be placed amongst other ender school spells.

### Steps to reproduce

1. Open the creative menu
2. Locate the "Iron's Spellbooks Scrolls" tab
3. Scroll down until you reach the eldritch school spells
4. The Black Hole scrolls come after "Abyssal Shroud"

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.1.5

### Forge version

Forge 1.20.1-47.2.17

**Comment by iron431** [comment]
fixed in 3.1.7
