### ISSUE TITLE
Arcane Anvil undo

### ISSUE THREAD

**Issue by exefer** [iron431/Irons-Spells-n-Spellbooks#444]
### Feature description

I would suggest adding a way to remove imbued spells from an item, as of a new player i try adding one to my strongest sword which had an ability bound to the right button just as the imbued spell. And just like that i lost part of the utility of that item.
Also documentation should be more exhaustive, and not only feature recipes of the items. Or either add a config for key binding if someone wants to change the imbued spell's key. Could any of these be implemented as an hotfix?

### How it improves the player experience

Prevent mistakes that destroy items

**Comment by iron431** [comment]
both these requests already exist
