### ISSUE TITLE
[Bug] Spells not showing up in creative

### ISSUE THREAD

**Issue by SAGA23456** [iron431/Irons-Spells-n-Spellbooks#447]
### Observed behaviour

![スクリーンショット 2024-05-24 204440](https://github.com/iron431/irons-spells-n-spellbooks/assets/131721194/7e833628-302c-44e1-bc70-b7ca4298dac0)

### Expected behaviour

Spells are displayed in the creative column

### Steps to reproduce

Spells are not displayed in the creative column

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2 3.16

### Forge version

43.3.0

**Comment by iron431** [comment]
they show up in the search menu. the scroll tab is 1.20.1 only
