### ISSUE TITLE
What about of give this mod short name?

### ISSUE THREAD

**Issue by ghost** [iron431/Irons-Spells-n-Spellbooks#448]
### Feature description

Such as _IC2(Industrial Craft 2)_,_TC(ThaumCraft)_,_MA(Mana and Artifice)_.
Give this mod the short name to let players can speak this mod more easier.
Example:**ISS**

### How it improves the player experience

Let players can more easier to speak this mod.

**Comment by kaairu** [comment]
most of the community calls it ISS, also this isn't even a feature

**Comment by ghost** [comment]
> most of the community calls it ISS, also this isn't even a feature

Sorry,But I haven't found **Discussions** on this repositorie :(
So I just ask author on issue.

**Comment by kaairu** [comment]
there is a discord https://discord.com/invite/TRzEdrndM2

**Comment by ghost** [comment]
> there is a discord https://discord.com/invite/TRzEdrndM2

Thanks!
And I'm sorry to bother you:(
