### ISSUE TITLE
[Bug] Flimsy book say 4 slots but there's only 3

### ISSUE THREAD

**Issue by SelnerenX** [iron431/Irons-Spells-n-Spellbooks#45]
### Observed behaviour

I got the flimsy book up and it apparently say 4 spell slot but there's only 3 

### Expected behaviour

Well i expected 4 slots as the book say.

### Steps to reproduce

!. Grab the flimsy book
2. See the slots while seeing the description on on that flimsy book

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.1.2

### Forge version

1.19.2 - 43.2.8

**Comment by lab3** [comment]
@SelnerenX That spell book originally had 3 slots but was changed to 4 slots starting in the v1.1.0 release.  Any books that existed in the world before upgrading to that version or a newer version would not be changed to have the 4th slot.

**Comment by lab3** [comment]
If you pull a new book out of the creative inventory or get one in a newly generated world I would expect it to have the 4 slots.  Can you confirm?
