### ISSUE TITLE
[Bug] Huge performance hit when looking at recipe usage with JEI

### ISSUE THREAD

**Issue by ChrisJacobs2** [iron431/Irons-Spells-n-Spellbooks#450]
### Observed behaviour

I got extreme lag from checking usage recipe for some scrolls. In one case it made the program stop responding. Kicking myself from the server using the console allowed me to escape without killing the java process.

### Expected behaviour

The usage recipes to appear, which should be using an arcane anvil to combine the scrolls.

### Steps to reproduce

In inventory, with JEI installed, press U on a high level spell scroll. For example level 9 firebolt.

Some scrolls appear to have a higher performance hit from viewing usage recipes.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.1.4

### Forge version

1.20.1-47.2.0

### Other mods

Just Enough Items 15.3.0.4
Just Enough Resources 1.4.0.247
Just Enough Professions 3.0.1

**Comment by iron431** [comment]
fixed in 3.2.1
