### ISSUE TITLE
[Bug] Hold melee weapons is strange

### ISSUE THREAD

**Issue by ghost** [iron431/Irons-Spells-n-Spellbooks#452]
### Observed behaviour

I update mod to 3.1.7,And I found the Magehunter and Keeper Flamberge's hold is weird.
When I downgrade to 3.1.4,this problem haven't appeared.

### Expected behaviour

The Magehunter and Keeper Flamberge's hold is weird.
![1](https://github.com/iron431/irons-spells-n-spellbooks/assets/115908948/624170f7-1549-42ca-876c-c9eb99047d6f)
![QQ截图20240529105220](https://github.com/iron431/irons-spells-n-spellbooks/assets/115908948/9161cdd7-5bd5-4c85-b021-16efb608e583)

### Steps to reproduce

1.Update mod to 3.1.6+
2.Get Magehunter and Keeper Flamberge and hold them
3.These's hold is weird

### Server Type

Single Player

### Crashlog

NONE

### Iron's Spells N Spellbooks version

1.20.1-3.1.7

### Forge version

1.20.1-47.2.32

### Other mods

![QQ截图20240529105402](https://github.com/iron431/irons-spells-n-spellbooks/assets/115908948/1611feb4-3c65-4e93-b012-413575348f9e)
![QQ截图20240529105417](https://github.com/iron431/irons-spells-n-spellbooks/assets/115908948/7548540a-9737-4697-ac3b-97044e1e23e2)

**Comment by iron431** [comment]
this does not happen with just the base mod. are you using any texture packs?
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/34083081/638219a3-ad6d-4cd8-80b7-0c5e0819ee9a)

**Comment by TskimiSeiran** [comment]
> this does not happen with just the base mod. are you using any texture packs? ![image](https://private-user-images.githubusercontent.com/34083081/335016482-638219a3-ad6d-4cd8-80b7-0c5e0819ee9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzYxNjcsIm5iZiI6MTcxNzAzNTg2NywicGF0aCI6Ii8zNDA4MzA4MS8zMzUwMTY0ODItNjM4MjE5YTMtYWQ2ZC00Y2Q4LTgwYjctMGM1ZTA4MTllZTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAyMjQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZDUwMjY3OGQ2ODQwYTc1Yzk4ZGIyMzM2ODQ0M2U2MWQ4Y2UxMmQ1YmIwNzZjY2FjNGMzMjdiOThhOWI0NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGJb3IjeFB0aIGcBkfg_nR-f6yuZV9P1lqvY2L9BrgQ)

I'm using tetra gui and my personal language lack,I'm sure haven't any modify to item,only ui and language.

**Comment by TskimiSeiran** [comment]
> this does not happen with just the base mod. are you using any texture packs? ![image](https://private-user-images.githubusercontent.com/34083081/335016482-638219a3-ad6d-4cd8-80b7-0c5e0819ee9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNDI3NDgsIm5iZiI6MTcxNzA0MjQ0OCwicGF0aCI6Ii8zNDA4MzA4MS8zMzUwMTY0ODItNjM4MjE5YTMtYWQ2ZC00Y2Q4LTgwYjctMGM1ZTA4MTllZTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDA0MTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzY2FhMmE5YzEyNDNiOTllOGMyZjExYTJhMWE5NjM1OTg2MGQ4NmMzOWY4YTZlZDA4NGNlN2JmZmRiNzVlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f5WPp-LUgTEK8MmZzLvvxygIbFLOt_d1cNCs6_tgDJQ)

It's still strangely hold when i disable all resourcepacks.

**Comment by ghost** [comment]
> this does not happen with just the base mod. are you using any texture packs? ![image](https://private-user-images.githubusercontent.com/34083081/335016482-638219a3-ad6d-4cd8-80b7-0c5e0819ee9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjE1MjAsIm5iZiI6MTcxODYyMTIyMCwicGF0aCI6Ii8zNDA4MzA4MS8zMzUwMTY0ODItNjM4MjE5YTMtYWQ2ZC00Y2Q4LTgwYjctMGM1ZTA4MTllZTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDEwNDcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMmNkNTJjNjQ3YjRmMjI1ZGZiMDI2NGY4NjQ1ZTYzMzczNjU0MWViOTdkOWRhNjBjNGYwNTJjNGQ5MTUxNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3cC4FlqO1tKDFLYWTrW4FHJDYaS2Ggk-CtXG0V4zDYM)

At 3.1.7.1,It's still holding strangely when i disable all resourcepacks.
But on 3.1.4,i use resourcepack or not,this issue haven't appeared.

**Comment by Hulinyi01** [comment]
删除 一起火锅 模组即可修复此问题
delete EveryXhotpot mod so that u can fix this bug

**Comment by ghost** [comment]
> 删除 一起火锅 模组即可修复此问题 delete EveryXhotpot mod 以便您可以修复此错误

谢谢，删除一起火锅模组后，问题已解决。
Thank you,I deleted EveryXHotpot mod,this problem haven't appear again.
