### ISSUE TITLE
[Bug] FFapi + Methane + Sinytra Connector crush

### ISSUE THREAD

**Issue by chmonyasik** [iron431/Irons-Spells-n-Spellbooks#458]
### Observed behaviour

After adding Methane, the game stops starting.

### Expected behaviour

Start the game.

### Steps to reproduce

1. Make a modpack with:
caelus-forge-3.2.0+1.20.1
cloth-config-11.1.118-forge
Connector-1.0.0-beta.43+1.20.1
ConnectorExtras-1.10.1+1.20.1
curios-forge-5.9.1+1.20.1
fabric-api-0.92.2+1.11.8+1.20.1 (FFAPI / Forgified Fabric API)
geckolib-forge-1.20.1-4.4.5
Methane 2.5.0
player-animation-lib-forge-1.0.2-rc1+1.20

2. Add Methane.

3. Try to start the game.

### Server Type

Single Player

### Crashlog

https://gist.github.com/ElenaNya/4ca126d216fa139f8001863fb0b20b7b

### Iron's Spells N Spellbooks version

1.20.1-3.1.4

### Forge version

1.20.1-47.2.30

### Other mods

caelus-forge-3.2.0+1.20.1
cloth-config-11.1.118-forge
Connector-1.0.0-beta.43+1.20.1
ConnectorExtras-1.10.1+1.20.1
curios-forge-5.9.1+1.20.1
fabric-api-0.92.2+1.11.8+1.20.1 (FFAPI / Forgified Fabric API)
geckolib-forge-1.20.1-4.4.5
Methane 2.5.0
player-animation-lib-forge-1.0.2-rc1+1.20

**Comment by iron431** [comment]
Sinytra Connector is not supported, especially not with use of fabric optimization mods
