### ISSUE TITLE
[Bug] Server doesn't refuse connection when mod versions are mismatched

### ISSUE THREAD

**Issue by TheLastFriendly** [iron431/Irons-Spells-n-Spellbooks#461]
### Observed behaviour

Upon joining a forge server with the player running the newest version (1.20.1 - 3.1.7), servers running (1.20.1 - 3.1.4) will allow the player to join. This can cause crashes.

### Expected behaviour

Server should refuse connection due to a version mismatch error

### Steps to reproduce

1.  Start Server with version 3.1.4 installed
2.  Start Client with version 3.1.7 installed
3.  Join Server with Client, and cast for example Devour to cause client side crash. Server log will simply report a disconnect.

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/TheLastFriendly/345dc750873b6255a4aa13965b131f64

### Iron's Spells N Spellbooks version

1.20.1-3.1.7

### Forge version

1.20.1 - 47.2.17

**Comment by meeprdib** [comment]
What's stopping you from updating the server?

**Comment by TheLastFriendly** [comment]
it's not my server, I recreated the crash on a clean version and a self hosted server to make sure the issue isn't with a different mod from the modpack that the server runs

**Comment by iron431** [comment]
this isn't something forge servers do anymore. use the correct mod versions.
