### ISSUE TITLE
[Bug] Inscription Table and Scroll Forge.

### ISSUE THREAD

**Issue by Umbra09** [iron431/Irons-Spells-n-Spellbooks#462]
### Observed behaviour

Both the Inscription Table and the Scroll forge are not appearing in Creative mod.
![imagen_2024-06-05_161639383](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/84af51b6-44a4-4d2d-8739-072a9e0cdb94)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/f38bb150-0cda-4842-86ba-4b600b600234)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/f2f15928-0050-4c92-ba51-00032dcda626)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/ca5ecb43-34c4-438e-88ed-7951332cc4e0)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/35ab670f-14ba-4715-a228-20a31af11e37)

### Expected behaviour

I was in creative mode and went to the Iron's Spells menus in search for those items and they are not appearing. I also have JEI installed and they are not appearing either. I can still craft them, but apparently they are appearing as if they weren't part of the mod.

### Steps to reproduce

I simply updated the mod. I have the v 3.1.7.1

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.7.1

### Forge version

47.2

### Other mods

I don't think this will be necesary, It worked fine before.

**Comment by iron431** [comment]
they appear in functional blocks tab

**Comment by Umbra09** [comment]
Nope, Checked 5 times. Here is the entire Tab (Didn't want to put everything so I cut out 4 screenshots (materials of different colors))
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/0fdca072-9bea-439f-9548-1601da2c0fd6)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/b7a1da05-7283-4ae4-b64e-5a61c67e4656)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/d4139b07-6d7c-48e1-b9bc-956bc6aa2602)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/d8df15ce-6414-4fa6-88a6-d9d06f39ab96)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/c1031a01-bbb5-461e-922b-4f28612730ab)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/d0d6ddb4-33f0-4153-8010-6d0be1a31a84)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/1134d722-5b0f-4815-8236-acde887009a7)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/1299e2c9-431d-413d-89ee-10d2d25db170)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/244d8cca-c523-4944-8b83-340f7159e116)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/63ad9440-5951-4852-b946-0f2bdd7f20b0)
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/171612942/8eff42ad-4108-4d23-a6d7-7ef8fd7510b1)
