### ISSUE TITLE
Angel Wings & Cape [Bug] 

### ISSUE THREAD

**Issue by Jar420** [iron431/Irons-Spells-n-Spellbooks#463]
### Observed behaviour

When activating Angel Wings my cape continues to render with the wings.
![2024-06-05_17 54 41](https://github.com/iron431/irons-spells-n-spellbooks/assets/102393475/d4369c5d-cad6-4456-b961-4ad7010f6e5a)
![2024-06-05_17 54 34](https://github.com/iron431/irons-spells-n-spellbooks/assets/102393475/8335f0d7-9b29-4321-8e35-16eb5ec37581)

### Expected behaviour

When activating Angel Wings the cape would disappear like vanilla elytra.

### Steps to reproduce

Equip any cape. Activate Angel Wings. 

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 3.1.7.1

### Forge version

1.20.1 - 47.2.0

**Comment by iron431** [comment]
fixed in 3.2.0
