### ISSUE TITLE
Animation incompatibility with Mowzie's Mobs (1.20.1)[Bug] 

### ISSUE THREAD

**Issue by vukkax** [iron431/Irons-Spells-n-Spellbooks#464]
### Observed behaviour

When using Mowzie's Mobs Ice Crystal and wearing any Spells and Spellbooks armor, the armor layer detaches from the player. 

Log:
[latest.log](https://github.com/user-attachments/files/15629901/latest.log)

Images: 
![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/108903683/ddc3ca6e-f4d4-4565-aabf-2f4c9b79ed44)

### Expected behaviour

Armor layer rendering correctly

### Steps to reproduce

1. Wear Iron's Spells & Spellbooks armor.
2. Use Mowzie's Mobs 
3. Armor layer renders incorrectly

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 3.1.7

### Forge version

1.20.1 - 47.3.1

### Other mods

Mowzie's Mobs: 1.20.1 - 1.6.5

**Comment by iron431** [comment]
this is an incompatibilty with mowzies mobs and geckolib, the library we use for armor.
this issue can be tracked on their page https://github.com/BobMowzie/MowziesMobs/issues/769
