### ISSUE TITLE
About possible improvement of balance

### ISSUE THREAD

**Issue by uhloin** [iron431/Irons-Spells-n-Spellbooks#466]
### Feature description

The complexity of retrieving spells should be balanced with power of effects, especially balance with usual weapon.

### How it improves the player experience

Such spells as teleport are very useful, but it's hard to say about balance for them because of there are nothing to compare. But damaging spells may be compared with usual weapon like enchanted sword and bow. 

For first glance magic is similar to bow because makes range damage from safety (if enemy is melee fighter). It's ultra-easy to get bow without enchantment and make random damage 6-7-8-9-10 per second. But when we view some let's play we'll find that players very rare use bows because of problem with arrows. And even if they can make a farm for arrows or have Infinite enchantment, they normally use sword instead. So, may be comparison with bow DPM is not so good idea. Or else your magic will not interesting like a bow. So Firebolt level 1 with damage 6.6 and cooldown 1s is nothing.

What about sword? It's relatively easy to craft diamond sword, you need mine only 2 diamonds. The level of damage 7 with speed 1.6, so 11.2 is minimal DPM for a magic. But even legendary tier of Firebolt gives only 10.5. What is a sense of all grinding if I can hit harder with my sword and without spend mana?

Also if we use your mod, then you should expect there are other mods. And for example Silent Gear allows relatively easy (similar to make a spell of Rare tier) and without go to End create a sword with damage 23 and speed 1.7. Or a bow with similar or more damage. And this is not overpower, because in the modded Minecraft we usually have tough modded bosses like those from your mod and worse. So we need power.

Possible Solution: 
- Lightweight spells like Firebolt should start from damage like 11-12 on level 1 with cooldown 1s and near to 0 mana per cast. 
- Other slow spells should be one-hit kill for standard 20 HP mobs or better.
- High-level spells should gain MUCH MORE power and make splendid BIG BOOMS or... see alternative solution below about grinding.

Your mod requires hard grinding to get max power. Sorry, but... it's a bit boring to kill archevoker, archevoker, archevoker... until get enough inks to upgrade to legendary tier. I was too bored to make my spell collection and power of most top-tier spells was disappointing. I finished 4 schools and I surrender on attempt to maximize Eldritch spells, I have not such patience. May be it's too hard just for me, I know. But I think I am a person who like some grinding in other games, so, probably it's not only me. 

But sometimes we can find random loot in chests with legendary spell without fighting. It's too easy, except dangerous looting in Deep Dark Towns. It's about balance too. Also there are spells like Lightning Bolt with Legendary levels 7,8,9,10 so you need 8 legendary or 32 epic inks to maximize it. 

Possible Solution: 
- No Epic/Legendary spells in chests except dark towns.
- There should be only one (top) Legendary level and only one (second from top) Epic level for any spell
- Bosses MUST always drop at least one (or may be exactly one) legendary ink or spell of maximum level from his school.
- Chests defended by bosses (like Apothecary) may contain Epic inks/scrolls (so you can get it and flee).
- For case if you already have dropped spell, Legendary/Epic scroll must have chance 100% of conversion to Legendary/Epic ink, but scrolls of lower tiers may have poor chances like 50% for Rare, 33% for Uncommon and 25% for Common. They may be easy found in chests, so reward should be lesser.
- Think about possibility to craft higher level ink from 2 inks instead of 4. But it's just my subjective sense, may be it's too good.

**Comment by uhloin** [comment]
Here is example of possible balance (see attached file). I tested in in real game in hard mode. So the magic was powered, but not overpowered. Config is changed for spells Blood Needles, Magic Missile, Ray of Frost, Heat Surge, Wisp, Fang Strike. If you interested, then after some game time, I can give full server config file with other spells modified with the same manner.

I used this common rules for changes:

1. 100% chance of scroll to ink conversion

2. Minimum rarity is always Common to avoid 2 or more levels with Legendary rarity,

3. There is random spread with damage grow from min to max level from x1.6 to x2.8 and mana from x1.9 to x3.4. So it's impossible to make some equality. The mana overhead may be roleplay thing like some "mana loss" from higher concentration of Mage. But different power grow is not so good, making some spells preferred and moving other to trash can.
So common rule is:
On the legendary level 
Usual ranged spell must have damage 20 to kill usual legacy mob with one hit, but more hits if it has armor.
Ranged spell with non-zero cast time may be interrupted, so as compensation for risk damage may be grown to 30-40.
Closer combat spell has maximum risk, so damage is 40-60.
But if coefficient of damage grow kD is less than 2.0 then such spells becomes too powerful on level 1. So for them I make Cooldown increase by 2.0/kD. They will like spells for newbies with lower efficiency on legendary level. 
Not sure about Eldritch spells, may be they should be more empowered to 60 and usual to 20-30-40.

4. For mana I targeted to balance on mid-level (6th for 10 levels)
Mostly spells become cheaper to make them useful for novice mage
So common rule is:
On the mid level
Non-damager, like Heat Surge: cost 10 mana
Usual damager (like magic missile): 20 mana
Damager with very useful effect like AoE damage (fire ball) or damage through walls (fangs): 40 mana
Damager for Holy school: 60 mana, as punishment for cleric to use use destructive magic

5. The main empowering is drastically decrease cooldown. This is essential change to make magic really useful and valid alternative to mere swordplay. And I repeat, I tested this, and it's not overpowered, small carelessness and mobs killed me in diamond armor (several times, yeah)
So common rule is:
For usual spell Cooldown + Cast time = 1 sec 
For spell with effects like freeze/poison: 2 sec 
For spells with very long effects like Heat Surge: 10 sec
For "newbie" spells with kD < 2: multiply by 2/kD

[irons_spellbooks-server_toml.txt](https://github.com/user-attachments/files/15915402/irons_spellbooks-server_toml.txt)

**Comment by uhloin** [comment]
One more thing about balance, but balance between popular magic mods.

Your natural rival is Ars Nouveau. It has no noticeable cast cooldown or cast time, but limited mana bar, so it's impossible to spam casting too long. Your mod has both cast cooldown+cast time AND limited mana bar, therefore becomes too weak. Ars Nouveau IS overpowered in farming, but is not in terms of PvE combat. So my point is to save cooldown as your feature, but not make it too long, keep it a bit longer than for a sword, but allow to make more damage per cast.

Also there is Elemental Craft as potential rival in the future, because it's unbalanced and unusable for PvE combat in current version.

**Comment by uhloin** [comment]
Here is result file for all spell schools. 
All spells were tested and adjusted on Hard level of solo-play mode, except Eldrich (they are kept as is)

[irons_spellbooks-server.toml.txt](https://github.com/user-attachments/files/16041146/irons_spellbooks-server.toml.txt)

Here is a table of all spells after changes

[iron_spells_balanced.txt](https://github.com/user-attachments/files/16041153/iron_spells_balanced.txt)

I suggest this file as alternative server config or you can use it as default settings if you like it

**Comment by Alebentod** [comment]
I just want to say thank you to Uhloin for the config file. It helped my build a lot.

With regard to fashion, yes, a rebalancing of magic and equipment is needed. Even for vanilla, the spells are too weak and demanding.

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
