### ISSUE TITLE
[Bug] Spellbook with some chance disappears on death

### ISSUE THREAD

**Issue by uhloin** [iron431/Irons-Spells-n-Spellbooks#467]
### Observed behaviour

Spellbook sometimes is lost on death 

### Expected behaviour

Book should be saved

### Steps to reproduce

1. Install Gravestone mod (not sure about behavior without it) but do not set option to keep items on death during world creation
2. Craft a spellbook (Ancient Codex)
3. Put some spells into it and put it to "Spell Book" slot of Curious
4. Put some rings from mod to "Ring" slots of Curious
5. Be killed by End Dragon
6. Rings are saved in the grave and any other item from other mods too, bit Codex disappears
7. If Codex DOES NOT disappear, then repeat step 5 (it happens with some chance)

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.7.1

### Forge version

1.20.1-47.1.100

### Other mods

gravestone-forge-1.20.1-1.0.15.jar 
curios-forge-5.9.1+1.20.1.jar

**Comment by iron431** [comment]
this sounds like an issue between curios and gravestone. we don't control how curios handles the slots nor how gravestone saves items, this should be reported to them.

**Comment by uhloin** [comment]
Rings from your mod have not such a problem, so this is some difference between rings and codex

**Comment by uhloin** [comment]
You was right it's not your problem
