### ISSUE TITLE
[Bug] Ring of Expediency

### ISSUE THREAD

**Issue by uhloin** [iron431/Irons-Spells-n-Spellbooks#469]
### Observed behaviour

Ring of Expediency has a description: "+15% Cast Time **Reduction**"
But in fact it is +15% Cast Time **Expanding** for Blaze Storm and Fire Breath. Probably, because such behavior will increase the sum of total damage.

### Expected behaviour

It would be more clear and convenient, if cast time, as written, is decreased, but also add +15% DPM to inflict the same total damage.

### Steps to reproduce

-

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.7.1

### Forge version

1.20.1-47.1.100

**Comment by iron431** [comment]
this is the intended behavior of the attribute, labelled under the most concise and intuitive name
