### ISSUE TITLE
'this caster' is null [Bug] 

### ISSUE THREAD

**Issue by Mijio** [iron431/Irons-Spells-n-Spellbooks#470]
### Observed behaviour

Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_7307_(net.minecraft.world.entity.Entity)" because "this.caster" is null
	at com.github.L_Ender.cataclysm.entity.AnimationMonster.BossMonsters.The_Leviathan.Abyss_Mine_Entity.m_8119_(Abyss_Mine_Entity.java:130) ~[L_Enders_Cataclysm-1.99.3%20-1.20.1.jar%23494!/:1.99.3 -1.20.1] {re:classloading}

### Expected behaviour

not crash :)

### Steps to reproduce

1) find Leviathan (Cataclysm)

### Server Type

Single Player

### Iron's Spells N Spellbooks version

3.1.7.1

### Forge version

47.2.0

### Other mods

Ender Cataclysm

**Comment by iron431** [comment]
attach a crash log

**Comment by iron431** [comment]
this is solely caused by cataclysm's casting mechanics, not ours.
