### ISSUE TITLE
About Fabric version

### ISSUE THREAD

**Issue by Sam-Chai** [iron431/Irons-Spells-n-Spellbooks#471]
### Feature description

Is it any possible to support fabric version?

### How it improves the player experience

In fact, more and more modpacks using fabric but not forge. Fabric (Also Quilt) need more high-quality mods.

**Comment by kaairu** [comment]
nah 
port it urself or smth

**Comment by iron431** [comment]
> Fabric (Also Quilt) need more high-quality mods.

sounds like a great opportunity to make your own mod
