### ISSUE TITLE
Mana Crystals?

### ISSUE THREAD

**Issue by salsacodes** [iron431/Irons-Spells-n-Spellbooks#472]
### Feature description

A way to reach "full mana capacity" (500 mana) without needing to wear the armor provided in this mod. Maybe something similar to Terraria where you can craft Mana Crystals to increase your "base mana" (100 mana). 

### How it improves the player experience

 In modpacks or even vanilla, players won't be forced to craft/wear the armor of this mod to use the magic system. Keep the buffs on the armors for the different schools of magic but remove the dependency on the armors to cast spells.

**Comment by iron431** [comment]
mana upgrades can be used on any mod's armor, and the config can be used to adjust mana cost for modpack balance. with these existing tools, a concept that upheaves the default balance shouldnt be added

**Comment by salsacodes** [comment]
Ahhh I see
