### ISSUE TITLE
[Bug] Server config option "Min Rarity" doesn't work

### ISSUE THREAD

**Issue by uhloin** [iron431/Irons-Spells-n-Spellbooks#475]
### Observed behaviour

Min Rarity server config option doesn't work
In fact, the goal was to make for Blood Needles legendary only level 10 (instead of 9 and 10) by change of min level from uncommon to common.

### Expected behaviour

Minimal rarity for level 1 scroll should be changed in the game, and upper levels should change

### Steps to reproduce

In the server config file irons_spellbooks-server.toml 
In the section [Spells."irons_spellbooks:blood_needles"]
Change value MinRarity from "UNCOMMON" to "COMMON"
Start a game, use JEI to list scrolls of Blood Needles, minimal rarity is still "UNCOMMON"

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.1.7.1

### Forge version

1.20.1-47.1.100

**Comment by iron431** [comment]
I cannot reproduce this. Server Configs can be messy. Make sure to edit the file with the world closed, make sure you have the correct spell id, make sure you are editing the correct file, and make sure there are no other typos in the file, to start. Try those and see if it fixes it.

![image](https://github.com/iron431/irons-spells-n-spellbooks/assets/34083081/991adf4f-465e-4259-af89-7a221c8aa0cf)

**Comment by uhloin** [comment]
Tried all you said.
1. Other values change OK (for example Cooldown)
2. If I edit file without quit game with this mod:
https://www.curseforge.com/minecraft/mc-mods/config-menus-forge
- file changed, but scroll in JEI is still old
3. If press "Save and Quit to TItle", change the file with text editor, reload world
- file changed, but scroll in JEI is still old
4. If close and RESTART Minecraft - scroll in JEI changed!

**Comment by uhloin** [comment]
Now I have additional issue:
JEI shows that:
Eldritch Blast 5 Legendary + Eldritch Blast 5 Legendary = Eldritch Blast 6 Common(!)
But there are no such scroll of level 6

Server config for this spell:
		Enabled = true
		School = "irons_spellbooks:eldritch"
		MaxLevel = 5
		#Allowed Values: COMMON, UNCOMMON, RARE, EPIC, LEGENDARY
		MinRarity = "RARE"
		ManaCostMultiplier = 1.0
		SpellPowerMultiplier = 1.0
		CooldownInSeconds = 15.0
		AllowCrafting = true

**Comment by iron431** [comment]
this is an unrelated issued caused by a mistake in 3.2.1, and will be fixed

**Comment by uhloin** [comment]
ok, thank you
