### ISSUE TITLE
[Bug] this.caster

### ISSUE THREAD

**Issue by Scykrai** [iron431/Irons-Spells-n-Spellbooks#479]
### Observed behaviour

Killed by "Catackysm Leviathan" then teleported back to death location but after doing so ran into a server crash

### Expected behaviour

Running stable

### Steps to reproduce

1. Encounter Cataclysm Leviathan 
2. Die to it
3. Attempt to teleport back to location

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Scykrai/fe8889516427679d8691742524a2db15

### Iron's Spells N Spellbooks version

1.19.2 (Ciscos Fantasy Medieval RPG [Ultimate])

### Forge version

43.3.5

### Other mods

L_Ender's' Cataclysm 1.19.2

**Comment by iron431** [comment]
this is solely caused by cataclysm's casting mechanics, not ours.

**Comment by Scykrai** [comment]
Do you have any idea how i might be able to fix it?  or atleast make the server operable for the meantime

**Comment by meeprdib** [comment]
Go to the cataclysm discord and ask

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/neruina should make it playable again (it will disable / delete the problematic mines)
