### ISSUE TITLE
[Bug] Void Tentacles and Fang Ward don't spawn at y<0

### ISSUE THREAD

**Issue by ghost** [iron431/Irons-Spells-n-Spellbooks#48]
### Observed behaviour

When casting Fang ward or void tentacles with no fluids nearby, nothing will get summoned, but if there is some, it will spawn inside the fluid.

### Expected behaviour

Summoned Fang ward and void tentacles spawned near the player no matter the terrain.

### Steps to reproduce

1. Go near a fluid lake
2. Use either spell

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.1.3

### Forge version

1.19.2 - 43.2.13

### Other mods

None

**Comment by lab3** [comment]
@SalmonSmacker , can you run the /modlist command and upload the modlist.txt that is put into the minecraft folder

**Comment by lab3** [comment]
I'm not able to reproduce this.  This is likely a mod compatibility issue with your modpack.  If you upload the modlist.txt we can look at.

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/1099358/25366592-1ab4-466a-8db3-8b1c373bc039)
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/1099358/8916ded4-6cf1-45d1-979f-7f4c4da2b526)

**Comment by ghost** [comment]
The spawning seems to be tied to depth, going below y0 doesn't allow the tentacles to spawn
[modlist.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/11641783/modlist.txt)

**Comment by lab3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Void Tentacle below Y:0 doesn't spawn.](https://trello.com/c/GRKMfoqp/628-void-tentacle-below-y0-doesnt-spawn)
