### ISSUE TITLE
[Bug] Cast command resets client use progress

### ISSUE THREAD

**Issue by Vic-PT** [iron431/Irons-Spells-n-Spellbooks#480]
### Observed behaviour

every time a command block uses a /cast command, even if the command doesn't target the player, actions like holding up a shield or charging a bow get interrupted. although the charging progress with the bow is not lost, if you try to shoot the arrow the moment the spell is cast it simply doesn't shoot. this is anoying when fighting custom bosses made with commands and command blocks that use the /cast command. this behaviour might extend to other right click actions

### Expected behaviour

for the /cast command to not interrupt the player's right click actions when the player isn't the target for the command

### Steps to reproduce

1. make a command block
2. give it a /cast command that doesn't target the player (example: /cast @e[type=minecraft:zombie,limit=1,sort=nearest] ascension)
3. hook the command block to a redstone loop
4. hold up a shield or charge up a bow

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2-3.2.0

### Forge version

43.3.0

**Comment by iron431** [comment]
fixed in 3.2.1
