### ISSUE TITLE
[Bug] Registry Object not present: irons_spellbooks:shriving_stone

### ISSUE THREAD

**Issue by TheIon2** [iron431/Irons-Spells-n-Spellbooks#482]
### Observed behaviour

Hello. Today i try to uprgade backpack from travalers backpack mod in smithing table, i put backpack and i got crashed, next i test with others items - same crash. i try without this mod and everythings normal.

### Expected behaviour

i expected that i just upgrade my backpack

### Steps to reproduce

1. Grab smithing table 2. Put something inside 3. Crash

### Server Type

Dedicated Server

### Crashlog

https://bytebin.lucko.me/P07B9w1R5O

### Iron's Spells N Spellbooks version

1.18.2 - 1.1.4.5

### Forge version

1.18.2 - 40.2.21

### Other mods

![изображение_2024-06-29_143631492](https://github.com/iron431/irons-spells-n-spellbooks/assets/89282232/aa6ab729-ce3a-465b-89b9-554f602f3a88)

**Comment by iron431** [comment]
are you using the same version of the mod as the server?
