### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by cheduude** [iron431/Irons-Spells-n-Spellbooks#483]
### Feature description

How can i make a localization for your mod?
Guide books needs localization

### How it improves the player experience

This will allow players from certain countries to get up to speed on fashion and have fun!

**Comment by iron431** [comment]
This is the patchouli wiki, which can guide you through creating localizations. Create a fork of the repository, and make a pull request with any additions you make to be approved: https://vazkiimods.github.io/Patchouli/docs/intro

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
