### ISSUE TITLE
[Bug] enchanted spellbook cant be crafted 

### ISSUE THREAD

**Issue by XKingCreeper85X** [iron431/Irons-Spells-n-Spellbooks#484]
### Observed behaviour

the enchanted spell book cant be crafted this might be an issue with one of the other mods im using though.

### Expected behaviour

i believe this is caused by the fact that the code for the recipe doesn't use a tag/the tag is broken. this is probably a super easy fix if this is actualy the issue. 

### Steps to reproduce

its simple just try and craft it with any enchanted book it wont work

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2

### Forge version

1.19.2

### Other mods

lots of other mods where on but i believe apotheosis (latest 1.19.2 version) may be a culprit if the base mod fails to reproduce it. JEI can also be used to see the issue more clearly, as it shows and unenchanted enchanted book (dont ask how that makes sense) instead of a tag being used as required for the recipe.

**Comment by iron431** [comment]
JEI cannot match the NBT of the recipe and gets confused. Place the book manually and it works.
