### ISSUE TITLE
[Suggestion] Add the remaining Spanish variants

### ISSUE THREAD

**Issue by LioxAcc** [iron431/Irons-Spells-n-Spellbooks#486]
### Feature description

Mod version:  v1.20.1-3.2.0

I have checked in the assets folder "lang" and I have seen that they have a .json file that contains the translation of this mod to mexican spanish.
However, there are no spanish translations for the rest of the south american countries (Chile, Uruguay or in my case, Argentina).
The work would be quite simple (it would only be copy and paste the file changing the name) since the mexican spanish is practically identical to the rest of south american countries.

### How it improves the player experience

Most players set the language of the game only once, when they open it for the first time.
In my case I thought that maybe the mod had a spanish translation in another variant. And so it was
But most Spanish-speaking players who are not from Mexico would think that this mod is simply not translated into spanish.
So adding the remaining variants would allow them to know and make use of the translation made for this amazing mod.

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
