### ISSUE TITLE
[Bug] 1.18.2 Missing fire bomb icon texture

### ISSUE THREAD

**Issue by Sketano** [iron431/Irons-Spells-n-Spellbooks#49]
### Observed behaviour

Equipped the scroll, No Texture/Icon

### Expected behaviour

Texture/Icon

### Steps to reproduce

(Required to be able to post) 1. Equip Fire Bomb Scroll.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.0.1

### Forge version

40.2.9

### Other mods

About 60 mods, Extremely unlikely to be the reason

**Comment by iron431** [comment]
This icon and 2 others seemed to have been left out of the 1.18.2 port. Working on it now
