### ISSUE TITLE
Inscription table dupe[Bug]

### ISSUE THREAD

**Issue by FaroTheEye** [iron431/Irons-Spells-n-Spellbooks#490]
### Observed behaviour

Recently I found some funny bug when creeper explodes next to it and game thinks that it's gone, but you still can see the table's second part hit box, so if you break it you not only get dropped item after explosion, but also one that you obtained after breaking remaining hit box

### Expected behaviour

I was expecting to see block dropping without any "ghost blocks" 👻

### Steps to reproduce

1. Lead creeper next to Inscription table block;
2. Wait till it makes kabooom;
3. See that there is no block on place but it's hit box;
4. Harvest two blocks

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

1.20.1 – 47.3.0

**Comment by iron431** [comment]
this was fixed in 3.4.0
