### ISSUE TITLE
Mine and Slash Compatibility

### ISSUE THREAD

**Issue by AstarothZven** [iron431/Irons-Spells-n-Spellbooks#491]
### Observed behaviour

As many players like to use, rpg mods always go well together, but seems like one of the lastest updates from Mine and slash, leaves Iron's Spellbooks without any sort of damage, the overal utility and projectiles still appear, but no damage is done to any mob

### Expected behaviour

It should be doing some sort of damage to mobs and entities

### Steps to reproduce

just grab any scroll and try out while using mod mine and slash

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.2.0

### Forge version

1.20.1 47.3.0

### Other mods

Mine and Slash

**Comment by iron431** [comment]
Mine and Slash overrides all damage mechanics and has built in methods to restore compatibility https://github.com/RobertSkalko/Mine-and-Slash/wiki/Compatibility-FAQ

**Comment by Bohemiangrove666** [comment]
I can't find the way to restore compatibility. Could you please show us how? I'm very confused.
