### ISSUE TITLE
Adding Support to ProjectMMO

### ISSUE THREAD

**Issue by SomewhatDamaged** [iron431/Irons-Spells-n-Spellbooks#492]
As the titles says, I'm in the process of adding support directly to ProjectMMO. 

I have already added support for gaining "magic" experience by casting spells that do damage, but have come up short on applying benefits for having the skill leveled up.

Are there any attributes Iron's Spells 'n Spellbooks implements to increase spell damage, increase maximum mana, and/or increase mana regeneration?

Tracking feature adding over here:
https://github.com/Caltinor/Project-MMO-2.0/issues/570

**Comment by meeprdib** [comment]
There are spell power and maximum mana attributes, and mana regeneration is based off of maximum mana. You can see all available attributes in game by running `/attribute @s`.

**Comment by SomewhatDamaged** [comment]
Ah! Cheers.
