### ISSUE TITLE
pedestal crafting recipe?

### ISSUE THREAD

**Issue by superblast1** [iron431/Irons-Spells-n-Spellbooks#496]
### Feature description

is it possible to make a pedestal crafting recipe my personnel suggestion would be:
 
[smooth stone slab] [smooth stone slab] [smooth stone slab]
[air/nothing]             [arcane ingot]          [air/nothing]
[air/nothing]             [smooth stone]        [air/nothing]

### How it improves the player experience

it would allow the crafting of pedestals which could be used to show off items.

**Comment by nul666lun** [comment]
+1 (i came here to see why nothing happened when i clicked on that in Jei....) thank you for an answer

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
