### ISSUE TITLE
[Bug] [1.18.2] You cannot wear rings via curio slot.

### ISSUE THREAD

**Issue by Cixon** [iron431/Irons-Spells-n-Spellbooks#50]
### Observed behaviour

Title.

### Expected behaviour

To wear rings.

### Steps to reproduce

Download latest Iron Spell for 1.18.2 [1.1.4]
and Dependencies.

see results.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

tested on 1.18.2 using v1.1.4

### Forge version

40.2.1

### Other mods

none. only iron's spells and dep.

**Comment by iron431** [comment]
Will be fixed shorty

**Comment by Cixon** [comment]
thank you can't wait for this fix!
