### ISSUE TITLE
Visual Bug in Curios

### ISSUE THREAD

**Issue by Brimstone287** [iron431/Irons-Spells-n-Spellbooks#502]
In the latest update, the books in the Spell Book slot bug and appear upside down inside your neck instead of on your belt area.

**Comment by iron431** [comment]
@Brimstone287 provide more information (game version, forge version, mod version, screenshots, etc) or this will not be looked into

**Comment by Brimstone287** [comment]
Haha that would be helpful:

Game version: 1.20.1 Forge
Forge version: 47.2.32
Mod version: 3.3.0

Working on the screenshot right now

**Comment by Brimstone287** [comment]
Well it looks like it fixed itself because I rebooted the world again to get the screenshot and now its working totally fine. I rebooted it a couple of times last night and it didnt fix so if it happens again ill post it.
