### ISSUE TITLE
Options for Adjusting Equipment Attributes

### ISSUE THREAD

**Issue by DeliciousTea** [iron431/Irons-Spells-n-Spellbooks#503]
### Feature description

Config options (or some kind of datapack) for changing the attributes of equipment (armor, weapons, curios). Additionally, being able to set a maximum for potion effects applied by spells would be helpful.

### How it improves the player experience

**Equipment Attributes:** When balancing a heavy RPG modpack, access to these types of things can be extremely useful. For instance, the latest update added a bunch of extra spell power to all the gear and totally threw off the balance I'd been working with. I'd like to be able to update the mod and still have the ability to balance the entire pack.

**Potion Effects::** Certain effects can become absolutely insanely overpowered quite easily. By wearing full Plagued armor and wielding a Druid's spellbook, spells that apply poison now apply Poison 5-6 which absolutely shreds every mob. Having either an option to set these effects or, even better, set a maximum level for the effect helps pack makers substantially.

**Comment by iron431** [comment]
In the context of a modpack, there are several mods that can help you customize attributes.
Amplifier caps or otherwise limiting spell power for certain spells is something we are looking into, especially around teleport spells

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
