### ISSUE TITLE
Allow the Wayward Compass to be used in other dimensions when Catacombs are present

### ISSUE THREAD

**Issue by Dweblenod** [iron431/Irons-Spells-n-Spellbooks#504]
### Feature description

Through a datapack it is possible to change which biomes, and therefore which dimensions, the Catacombs generate in. Right clicking the compass in another dimension that has been changed to contain the Catacombs will cause it to successfully write CatacombsPos to the ItemStack but on the client side it will continue to point in random directions.

The early return in the method getCatacombsLocation() makes it seem like this is intentional. I suggest it be opened up! I havent tested it in an environment but I imagine you could find which biomes are present in the current dimension from ServerLevel and check that against the tag #irons_spellbooks:wayward_compass_locator for the early return.

### How it improves the player experience

This does not change base gameplay, however it would be valuable for addons or standalone datapacks. It allows creators to take full advantage of the infrastructure that is otherwise already built (generation that is otherwise fully data-driven).

Otherwise just want to note how much the mod is appreciated! Seems to have come very far even within the last few months I last used it for a server.

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
