### ISSUE TITLE
Postmortal spells

### ISSUE THREAD

**Issue by Flysuperda** [iron431/Irons-Spells-n-Spellbooks#505]
### Feature description

Legendary spells (possibly created from a special item). on use kill user, but makes something overpowered (powerful mob for blood school, buff nearby players for holy school, 30 seconds of immortality but then player die for eldritch school and more). also you can craft artifact to put this spell in so it is used automatically at death. It's has to be very powerful spell for best magicians. 

### How it improves the player experience

This spell will help the friends of the deceased magician to survive, defeat the boss or get out of another difficult situation

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
