### ISSUE TITLE
[Bug] Iron's Guidebook and Spellbook's

### ISSUE THREAD

**Issue by LiluMortem** [iron431/Irons-Spells-n-Spellbooks#506]
### Observed behaviour

I died with the Guidbook and tought it just spawns with me again or i can craft it but no i cant craft it and i dont spawn with it .so what can i do now to have it? And when i use the spellbooks they go back to the Inscription Table but if i die they are gone too even if they are in the inscription table.

### Expected behaviour

that i can craft it or spawn with it

### Steps to reproduce

1. in die
2. i cant craft it
3. its not spawning with me
4. its gone

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.3.0.jar

### Forge version

47.3.0

**Comment by iron431** [comment]
this is because when you die in minecraft, you drop your items

**Comment by meeprdib** [comment]
The guide is craftable with a book and arcane essence btw
