### ISSUE TITLE
Items without any recipes or usages causes compability crashes with just enough items.

### ISSUE THREAD

**Issue by Oscar3e** [iron431/Irons-Spells-n-Spellbooks#510]
### Observed behaviour

(These are default keybinds) When pressing R for recipes or U for usages, some items will cause an instant crash. This prominently occurs with the some of the spellbooks. This specific crash was caused by interacting this way with the "Ruined Book."

### Expected behaviour

Well in a perfect world I would assume the game wouldn't crash. However considering it's a compability issue I'm not complaining, I just wanted to bring attention to the issue.

### Steps to reproduce

1. Grab or find a Ruined Book
2. Press R or U (default keybinds) on the Ruined Book with Just Enough Items installed
3. Observe your game die.

### Server Type

Single Player

### Crashlog

https://gist.github.com/Oscar3e/feef24286cd6b49f2b873efb8d8d39ef

### Iron's Spells N Spellbooks version

1.20.1-3.3.0

### Forge version

1.20.1-47.3.0

### Other mods

Just Enough Items 1.20.1-15.8.2.23

**Comment by iron431** [comment]
This is not an issue with Spells n Spellbooks, this is an issue with Mechanism using an outdated version of JEI's api.
