### ISSUE TITLE
Smarter/Controllable Summons

### ISSUE THREAD

**Issue by Raegier** [iron431/Irons-Spells-n-Spellbooks#511]
### Feature description

I feel like player summons should automatically attack nearby hostile mobs or you should have some kind of wand or spell that allows you to command your summons to attack any hostile mobs within a radius around where you click or around yourself.

### How it improves the player experience

I find that when fighting multiple mobs the summons either just stand around and do very little to nothing or chase after a single nonimportant mob leaving you to deal with the threats, having a way to command them or the summons being more aggressive would not only make them more reliable but also aid in the "fantasy" (for lack of a better word) of having a powerful horde of summoned beasts destroying everything in your path, while the "powerful horde" is implemented very well, the "destroying everything in your path" part could use a bit of refinement.

**Comment by Oidon21** [comment]
I have to agree here. They feel rather useless standing around until I get hit

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
