### ISSUE TITLE
"ironsspellbooks" not properly using GeckoLib

### ISSUE THREAD

**Issue by Starsseeker2078** [iron431/Irons-Spells-n-Spellbooks#512]
### Observed behaviour

"Caused by: java.lang.AbstractMethodError: Receiver class io.redspace.ironsspellbooks.item.armor.TarnishedCrownArmorItem does not define or inherit an implementation of the resolved method 'java.util.function.Supplier getRenderProvider()' of interface software.bernie.geckolib.animatable.GeoItem."

### Expected behaviour

Game crashed due to the reason above

### Steps to reproduce

1.Download Fabric-> Forge Connector
2. Download Ironspell mod
3. Download fabric Geckolib in a forge server

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Starsseeker2078/62114dba4a713f77faac15f7a68f65b1

### Iron's Spells N Spellbooks version

Latest version

### Forge version

43.2

### Other mods

Geckolib

**Comment by iron431** [comment]
this is because you are using fabric. we do not support fabric
