### ISSUE TITLE
[Bug] right click scrolls no mana / cooldown is required

### ISSUE THREAD

**Issue by 2929762171** [iron431/Irons-Spells-n-Spellbooks#513]
### Observed behaviour

*

### Expected behaviour

consume mana and needs cooldown

### Steps to reproduce

 use scroll

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.19.2-3.3.0

### Forge version

forge 43.3.7

**Comment by iron431** [comment]
thats how scrolls work
