### ISSUE TITLE
Unable to craft guidebook

### ISSUE THREAD

**Issue by OgunSyntax** [iron431/Irons-Spells-n-Spellbooks#516]
### Observed behaviour

Using the recipe for the iron's guidebook results in nothing appearing.
![Screenshot 2024-08-05 122732](https://github.com/user-attachments/assets/1183a3dd-129e-4491-97c0-265291c24675)

### Expected behaviour

result iron's guidebook

### Steps to reproduce

1.place the book and arcane essence in crafting table

### Server Type

Single Player

### Iron's Spells N Spellbooks version

v1.20.1-3.3.0

### Forge version

1.20.1

**Comment by iron431** [comment]
install patchouli
