### ISSUE TITLE
Raise dead crashes players [Bug] 

### ISSUE THREAD

**Issue by Arutaa** [iron431/Irons-Spells-n-Spellbooks#519]
### Observed behaviour

Whenever using raise dead, any player nearby crashes. In the crash logs it says that the suspected mods causing it are irons spells itself, epic fight, geckolib, and oculus

### Expected behaviour

use raise dead and not crash

### Steps to reproduce

1. get raise dead scroll
2. use it
3. crash

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Arutaa/8e73eeae317695fae08c4db72ae3e9df

### Iron's Spells N Spellbooks version

1.20.1-3.3.0

### Forge version

47.3.1

### Other mods

The mods that were suspected are:
Iron's Spells & Spellbooks 3.3.0
Epic Fight 20.8.7
GeckoLib 4.4.7
Oculus 1.7.0

The rest of the mods are listed in the crashlog

**Comment by iron431** [comment]
This is an issue due to unsafe code in Epic Fight attempting to cast a geckolib renderer to a vanilla renderer. This should be reported to them.
