### ISSUE TITLE
[Bug] Epic Fight Player Model obstructs first person view when using spells

### ISSUE THREAD

**Issue by DeshiDesu** [iron431/Irons-Spells-n-Spellbooks#52]
### Observed behaviour

![2023-06-10_17 35 03](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/120287925/0abe94a8-8276-485e-98a9-e97ce689edd7)

When casting spells in first person, the player model is rendered. Completing the spell will no longer render the model. I have turned off both render options in the config, but it does not change anything.

### Expected behaviour

Casting spells will not render the player model

### Steps to reproduce

1. Install Epic Fight alongside Iron's Spells 'n Spellbooks
2. Obtain the spellbook
3. Use spells

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.18.2-1.1.4.1.jar

### Forge version

40.2.9

### Other mods

[EpicFight-18.3.8.jar](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/4447075)

**Comment by lab3** [comment]
It looks like the is a compatibility issue between playeranimator which we use and epic flight mods.  I'm not sure what we can do on this one.

**Comment by lab3** [comment]
I posted on their issue tracker to see if they can add any context

https://github.com/Yesssssman/epicfightmod/issues/1331

**Comment by DeshiDesu** [comment]
If it is an incompatibility with playeranimator maybe you could list it as an optional dependency since it would not be needed at all if there is already a mod installed that changes the player model.

**Comment by HarlamovLive** [comment]
Hello, sorry to barge into this thread, but there is another bug with EpicFight, when in combat mode you hit a magic shield or a magic pyromancer the game crashes.

**Comment by DeshiDesu** [comment]
> Hello, sorry to barge into this thread, but there is another bug with EpicFight, when in combat mode you hit a magic shield or a magic pyromancer the game crashes.

You should submit your report in this issue I made for you https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/55

**Comment by lab3** [comment]
> If it is an incompatibility with playeranimator maybe you could list it as an optional dependency since it would not be needed at all if there is already a mod installed that changes the player model.

All our casting animations for players rely on this.

**Comment by iron431** [comment]
Playeranimtor does not give us the tools to deal with Epic Fight's complete character model replacement. You can still cast spells just fine if you are not in combat mode. This would need to be fixed on Epic Fight's side

**Comment by DeshiDesu** [comment]
@lab3 I meant your mod doesnt need playeranimator to be a hard dependency in the jar file. You can still list it as a required dependency on curseforge when players need it for animations. It's true that this is not the best fix, but if it works then why not?
