### ISSUE TITLE
A command that can give a affinity ring with a affinity

### ISSUE THREAD

**Issue by Acat1234** [iron431/Irons-Spells-n-Spellbooks#520]
### Feature description

The fact that I cant use /give to get a affinity ring that works (also can there be a everything affinity ring that just works for all of the spells)

### How it improves the player experience

Because a creative player that wants one of the rings wont want to keep spawning loot chests until they get it

**Comment by kaairu** [comment]
u can js do 
/give @s irons_spellbooks:affinity_ring{"ISBEnhance":"irons_spellbooks:magic_missile"}

**Comment by Acat1234** [comment]
I am not good enough at commands for that

**Comment by kaairu** [comment]
boohoo

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
