### ISSUE TITLE
[Bug] [1.21] [neoforge] Missing item tags and other things

### ISSUE THREAD

**Issue by ffuentesm** [iron431/Irons-Spells-n-Spellbooks#521]
### Observed behaviour

Mostly how raw Mithril is missing the `c:raw_materials/mithril` tag and the mithril ores are missing the `c:ores/mithril`, `c:ores_in_ground/stone`, and `c:ores_in_ground/deepslate` tags

Also, the spellbook curio slots are missing from my menu. 

Also, the new tags is `c:glass_block` not `c:glass`
![image](https://github.com/user-attachments/assets/586823e2-d1f5-4cc8-9f07-65292e34de17)
![image](https://github.com/user-attachments/assets/dc2c7fc4-13a9-4f2c-af84-851a8ac09d26)
![image](https://github.com/user-attachments/assets/914166bc-d279-4478-b0ce-85dfbefa93c3)

### Expected behaviour

mithril material should have the missing tags, firefly jar should have the correct glass tag, and the path for the curio slots should be checked. 

### Steps to reproduce

launch the game. 

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.4.0

### Forge version

21.1.1

**Comment by iron431** [comment]
fixed in 3.4.1
