### ISSUE TITLE
[Bug] Bruh

### ISSUE THREAD

**Issue by davethemodderguy** [iron431/Irons-Spells-n-Spellbooks#522]
### Observed behaviour

It doesn't load

### Expected behaviour

I want to play

### Steps to reproduce

Just run the game with JEI, Curios API continuation, and the reqired mod it just said this
![image](https://github.com/user-attachments/assets/fd3b45bb-a5ba-4e79-bfa8-e5d02c0c1864)

### Server Type

Single Player

### Crashlog

https://gist.github.com/davethemodderguy/9a67653312c5f46d5abda795091c56fb

### Iron's Spells N Spellbooks version

Lasted 1.21 version

### Forge version

Newest neforge

### Other mods

[mod list.txt](https://github.com/user-attachments/files/16568264/mod.list.txt)

**Comment by iron431** [comment]
you are using the wrong version of curios, use adorned
