### ISSUE TITLE
[Bug] Game crashes when opening inventory while wearing an enchanted piece of the mods armor

### ISSUE THREAD

**Issue by TomatoSoupter** [iron431/Irons-Spells-n-Spellbooks#524]
### Observed behaviour

Opening the inventory while wearing an enchanted piece of armor from the mod crashes the game. The offending armor piece is shown for a split second before crashing

### Expected behaviour

Opening the inventory without it crashing.

### Steps to reproduce

1. Wear a piece of enchanted armor from the mod.
2. Open the inventory

### Server Type

Single Player

### Crashlog

https://gist.github.com/TomatoSoupter/049d5565843d2d5c1bfe9f28d9eab039

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.4.0-all

### Forge version

Neoforge - 21.0.163

### Other mods

AI-Improvements-1.21-0.5.3
architectury-13.0.6
artifacts-neoforge-12.0.4
athena-neoforge-1.21-4.0.0
BiomesOPlenty-neoforge-1.21-21.0.0.11
caelus-neoforge-7.0.0+1.21
chipped-neoforge-1.21+4.0.0
Chunky-1.4.16
cloth-config-15.0.128
curios-neoforge-9.0.5+1.21.0
curios-neoforge-9.0.5+1.21
FastWorkbench-1.21-9.1.1
ferritecore-7.0.0-neoforge
geckolib-neoforge-1.21-4.5.8
GlitchCore-neoforge-1.21-2.0.0.2
jei-1.21-neoforge-19.7.0.87
lootr-neoforge-1.21-0.9.32.76
modernfix-neoforge-5.19.0+mc1.21
MouseTweaks-neoforge-mc1.21-2.26
nerb-1.21-0.4-NEOFORGE
NoChatReports-NEOFORGE-1.21-v2.8.0
open-parties-and-claims-neoforge-1.21-0.23.2
OreExcavation-NeoForge-1.21-1.16.14
Placebo-1.21-9.3.5
resourcefullib-neoforge-1.21-3.0.9
spark-1.10.73-neoforge
TerraBlender-neoforge-1.21-4.0.0.1
Terralith_1.21_v2.5.4
worldedit-mod-7.3.5

**Comment by TomatoSoupter** [comment]
It also appears to crash when you try to apply a trim in a smithing table

**Comment by iron431** [comment]
this seems to be a geckolib issue https://github.com/bernie-g/geckolib/issues/616

**Comment by iron431** [comment]
actually a misuse of geckolib, fix pending release

**Comment by iron431** [comment]
fixed in 3.4.2
