### ISSUE TITLE
[Bug] Weapons are not imbued when combined with Scrolls in the Arcane Table

### ISSUE THREAD

**Issue by twohundredangels** [iron431/Irons-Spells-n-Spellbooks#525]
### Observed behaviour

Items do not imbue when combined with scrolls in the Arcane Anvil Menu. It does not deny combining items with scrolls, but instead results in an unchanged item.
No errors in log.

### Expected behaviour

In previous versions of ISS (such as version 1.20.1), combining an Imbueable Item and a Scroll in the Arcane Anvil GUI would result in an Imbued Item.
The comments in the Arcane Anvil Menu suggest that this behaviour is not intentional in 1.21.

### Steps to reproduce

1. Interact with Arcane Anvil to open the Arcane Anvil Menu
2. Place an imbueable item in first slot (for demonstration, an iron sword)
3. Place a scroll in the second slot (for demonstration, a level 1 acupuncture scroll)
4. Hover over the resulting item within the third slot.
![image](https://github.com/user-attachments/assets/4eeba5f5-3f5f-4177-8e9a-d6645c39fcec)
 

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.4.1

### Forge version

Neoforge 21.0.167

### Other mods

(The dependencies of ISS)

- Adorned API 9.0.5+1.21.0
- Caelus API 7.0.0+1.21
- Geckolib 4 4.5.8

**Comment by iron431** [comment]
fixed in 3.4.2
