### ISSUE TITLE
[Bug] [1.21] Irons Spell crash with latest version

### ISSUE THREAD

**Issue by Periam** [iron431/Irons-Spells-n-Spellbooks#526]
### Observed behaviour

Installing the latest version made the game crash

### Expected behaviour

To run after installing

### Steps to reproduce

1-Install Mod and depencies
2-Launch the Game

### Server Type

Single Player

### Crashlog

https://gist.github.com/Periam/878c7ee55305783bd32111b42d00f442

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.4.1-all

### Forge version

Neoforge-21.0.164

### Other mods

Jei-1.21-neoforge-19.8.2.99
curios-neoforge-9.0.5+1.21
geckolib-neoforge-1.21-4.5.8
caelus-neoforge-7.0.0+1.21

**Comment by iron431** [comment]
you are using the wrong curios. use adorned
