### ISSUE TITLE
[Bug] 1.21.1 NeoForge Error while dispatching events. 

### ISSUE THREAD

**Issue by Zelioth** [iron431/Irons-Spells-n-Spellbooks#528]
### Observed behaviour

Error on start up 

### Expected behaviour

start up

### Steps to reproduce

add to 1.21.1 NeoForge

### Server Type

Single Player

### Iron's Spells N Spellbooks version

3.4.3

### Forge version

NeoForge 21.1.4

### Other mods

![image](https://github.com/user-attachments/assets/7dde4005-a8db-42a1-ab09-59b80e106f73)
[latest.log](https://github.com/user-attachments/files/16571800/latest.log)

https://www.curseforge.com/minecraft/modpacks/friends-united-2-1

**Comment by iron431** [comment]
youre using the wrong curios port, use adorned

**Comment by Zelioth** [comment]
![image](https://github.com/user-attachments/assets/9b2fd08a-a35e-42a5-8656-1ea0e9f2d453)


am I missing something?
