### ISSUE TITLE
[Bug] ATM10 0.33 crash when rings and necklace in curio slot and I open backpack

### ISSUE THREAD

**Issue by seals55** [iron431/Irons-Spells-n-Spellbooks#537]
### Observed behaviour

Upgraded ATM10 server to 0.33 today. Made a Sophisticated backpack, put it in curio back slot. After 1 or 2 openings, the client crashes. If I remove backpack from curios slot it works fine. If I remove all iron rings and necklace from curios backpack works fine from curios slot.

`Client disconnected with reason: Failed to open a screen with advanced data: java.lang.ClassCastException: class io.redspace.ironsspellbooks.item.curios.CurioBaseItem cannot be cast to class net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem (io.redspace.ironsspellbooks.item.curios.CurioBaseItem is in module irons_spellbooks@1.21-3.4.4 of loader 'TRANSFORMER' @3be3e76c; net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem is in module sophisticatedbackpacks@3.20.6 of loader 'TRANSFORMER' @3be3e76c)`

### Expected behaviour

I can open backpack without crashing

### Steps to reproduce

ATM10 0.33 server
1. Have iron poison and fire ring, and a necklace in curios. 
2. Put sophisticated netherite backpack in curios. 
3. open backpack with hotkey, crash

### Server Type

Dedicated Server

### Crashlog

https://mclo.gs/Apdosfv

### Iron's Spells N Spellbooks version

1.21-3.4.4

### Forge version

Neoforge 21.1.8

### Other mods

ATM10 - 0.33, no manually added mods

https://www.curseforge.com/minecraft/modpacks/all-the-mods-10/relations/dependencies

**Comment by iron431** [comment]
This is an issue with sophisticated backpacks and should be reported to them. there is nothing i can do on my end
