### ISSUE TITLE
[Bug] The Necromancer Skeleton crashes the game whenever it summons its undead minions

### ISSUE THREAD

**Issue by Orm4tt** [iron431/Irons-Spells-n-Spellbooks#539]
### Observed behaviour

1.- Whenever a Skeleton Necromancer summons his undead minions in the vicinity of a player it crashes the game.
2.- If the player is far away enough from the Necromancer when it summons its minios the game will not crash. (Distance not tested but it has to be somewhat far) (This point was proven by the third point)
3.- If playing singleplayer LAN with another player and only one player is close to the Necromancer when it summons its minions, it will only crash the game of the player that is close to it. But if it is the player that opened the world to LAN it will Crash all the players games.

### Expected behaviour

The game not crashing when the necromancer summons its minions.

### Steps to reproduce

1. Approach a Necromancer that spawned naturally or that was spawned by command or spawn egg. (This can be done in survival and creative. i have not tested the other game modes.)
2. Wait for the Necromancer to summon its undead minions.
3. Game Crashes. 

### Server Type

Single Player

### Crashlog

https://gist.github.com/Orm4tt/8365f5ac044a9ba52c38d8151a700ba1

### Iron's Spells N Spellbooks version

1.20.1 - 3.3.0

### Forge version

1.20.1 - 47.3.0

### Other mods

We are using a list of 66 mods including Iron's spells. Game version 1.20.1
Im sorry for the long mod list.
1. [1.20.1-forge]-Epic-Knights-9.8
2. Alex Caves 1.1.4
3. Alex Mobs 1.22.8
4. Aquamirae-6API15
5. Architectury-9.2.14
6. artifacts-forge-9.5.11
7. bendy-lib-forge-4.0.0
8. BOMD-Forge-1.20.1-1.1.2
9. Bonfires-1.20.1-1.2.18-43da133
10. born_in_chaos_[Forge]1.20.1_1.3.1
11. caelus-forge-3.2.0+1.20.1
12. canary-mc1.20.1-0.3.3
13. CerbonsAPI-Forge-1.20.1-1.1.0
14. citadel-2.5.6-1.20.1
15. cloth-config-11.1.118-forge
16. Clumps-forge-1.20.1-12.0.0.4
17. creeperoverhaul-3.0.2-forge
18. curios-forge-5.9.1+1.20.1
19. curiouslanterns-1.20.1-1.3.2
20. dungeons_enhanced-1.20.1-5.2.2
21. dungeons-and-taverns-3.0.3.f
22. dynamiclightsreforged-1.20.1_v1.6.0
23. EFMCompat 2.0
24. embeddium-0.3.18+mc1.20.1-all
25. endermanoverhaul-forge-1.20.1-1.0.4
26. entityculling-forge-1.6.2-mc1.20.1
27. epic_stats_mod_remastered-1.1.4-forge-1.20.1
28. epicfight-forge-20.8.7-1.20.1
29. fantasyfurniture-1.20.1-9.0.0
30. geckolib-forge-1.20.1-4.4.7
31. iceandfire-2.1.13-1.20.1-beta-4
32. irons_spellbooks-1.20.1-3.3.0
33. iter_rpg-0.7.0b-forge-1.20.1
34. jei-1.20.1-forge-15.3.0.4
35. L_Enders_Cataclysm-1.99.6-1.20.1
36. lionfishapi-1.9
37. mobsunscreen-forge-1.20.1-3.1.1
38. mowziesmobs-1.6.5
39. obscure_api-15
40. oculus-mc1.20.1-1.7.0
41. player-animation-lib-forge-1.0.2-rc1+1.20
42. radiantgear-forge-2.1.5+1.20.1
43. resourcefulconfig-forge-1.20.1-2.1.2
44. Ribbits-1.20.1-Forge-3.0.0
45. rubidium-extra-0.5.4.3+mc1.20.1-build.121
46. saturn-mc1.20.1-0.1.3
47. ShoulderSurfing-Forge-1.20.1-4.2.1
48. smallships-forge-1.20.1-2.0.0-b1.2
49. sophisticatedbackpacks-1.20.1-3.20.5.1044
50. sophisticatedcore-1.20.1-0.6.22.611
51. starlight-1.1.2+forge.1cda73c
52. structure_gel-1.20.1-2.16.2
53. TreeChop-1.20.1-forge-0.19.0
54. weaponmaster_ydm-forge-1.20.1-4.2.3
55. WeaponsOfMiracles-20.1.8.5
56. Xaeros_Minimap_24.1.1_Forge_1.20
57. XaerosWorldMap_1.38.4_Forge_1.20
58. YungsApi-1.20-Forge-4.0.5
59. YungsBetterDesertTemples-1.20-Forge-3.0.3
60. YungsBetterDungeons-1.20-Forge-4.0.4
61. YungsBetterJungleTemples-1.20-Forge-2.0.5
62. YungsBetterMineshafts-1.20-Forge-4.0.4
63. YungsBetterNetherFortresses-1.20-Forge-2.0.6
64. YungsBetterOceanMonuments-1.20-Forge-3.0.4
65. YungsBetterStrongholds-1.20-Forge-4.0.3
66. YungsExtras-1.20-Forge-4.0.3

**Comment by iron431** [comment]
This is an epic fight issue and should be reported to them

**Comment by Orm4tt** [comment]
Okay, Thank you Iron!
