### ISSUE TITLE
[Bug] Crash Report

### ISSUE THREAD

**Issue by ClockyVaudeville** [iron431/Irons-Spells-n-Spellbooks#540]
### Observed behaviour

Crash on Startup, have dependencies, getting exit code -1
[crash-2024-08-16_13.59.35-client.txt](https://github.com/user-attachments/files/16640218/crash-2024-08-16_13.59.35-client.txt)

### Expected behaviour

Game to start up

### Steps to reproduce

Literally just play the game

### Server Type

Single Player

### Crashlog

https://gist.github.com/ClockyVaudeville/6cd914b5d70815a379bfcd021b5a2099

### Iron's Spells N Spellbooks version

v1.19.2-3.4.0

### Forge version

1.19.2

### Other mods

I was playing Luvstar's Fairycore so there's about 104 other mods involved in this modpack.

**Comment by iron431** [comment]
this has nothing to do with spells n spellbooks
