### ISSUE TITLE
[Bug] Capturing a mob while it's spellcasting crashes the game.

### ISSUE THREAD

**Issue by wasabiwhisper** [iron431/Irons-Spells-n-Spellbooks#541]
### Observed behaviour

I'm playing the Craftoria mod pack. Where I used a mob catcher from JustDireThings to capture an Archevoker. When trying to capture it when it is not casting any spell everything is fine. However, when it is casting a spell, when I capture it the game crashes. Next time the game starts and the world loads I have it in my inventory. When it's in when I open my inventory it would crash the game (because the catcher tries to display the mob).

It seems like it's loading serverside code on my client when hovering. From what I see in the log it tries to initiate the spell.

[Crash log](https://github.com/user-attachments/files/16641335/message.txt)

### Expected behaviour

When I capture the mob it should go into a default "idle" state. Thus preventing any client bound packets to be sent when it's in my inventory. I think some other mods do a similar thing. 

### Steps to reproduce

1. Spawn an Archevoker.
2. Use a Creature Catcher from JustDireThings while it's casting a spell.
3. Crash.

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/wasabiwhisper/efe3f5cd2af03529c72eed1260dca9de

### Iron's Spells N Spellbooks version

1.21-3.4.4

### Forge version

NeoForge 21.1.8

### Other mods

For testing purposes only **JustDireThings** would be needed.

For all the other mods check out [Craftoria 0.8.0 - Mod list](https://github.com/TeamAOF/Craftoria/blob/main/changelogs/modlist_0.8.0.md)

**Comment by iron431** [comment]
This is an issue with JustDireThings using a server method on the client and should be reported to them
