### ISSUE TITLE
[Bug]  Render crash for summoned zombies and skeletons

### ISSUE THREAD

**Issue by Codemancrazyguy** [iron431/Irons-Spells-n-Spellbooks#542]
### Observed behaviour

Currently, anytime the "Raise Undead" spell is used, the instant the cast is complete and creates the entities, it crashes anyone close enough to render them. Does not close the server, nor does it crash those that are further away. However, logging back in, I still see all three summons walking around.

### Expected behaviour

Use Raise Dead, and summons spawn without crashing my game. Fight a necromancer without crashing.

### Steps to reproduce

1. Use Raise Dead
2. Crash
3. Log back in and summons are there

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.4.0

### Forge version

1.20.1-47.3.1

### Other mods

![Screenshot 2024-08-16 151536](https://github.com/user-attachments/assets/9f2c3d3d-b1da-435e-b7f6-35239d251633)

**Comment by iron431** [comment]
This is an epic fight issue
