### ISSUE TITLE
[Bug] Necromancer Crash Epicfight

### ISSUE THREAD

**Issue by Archongaming** [iron431/Irons-Spells-n-Spellbooks#543]
### Observed behaviour

The summoning animation from the necromancer causes a crash ... This has been reported before, but I dont think epic fight team will fix this. Is it possible to use configs or really do anything to fix this issue while we wait to see if it gets fixed. for example removing necromancers ability to summon, config option for simple necromancer summon which uses a simpler summon command.

### Expected behaviour

Summon, no crash

### Steps to reproduce

Have epicfight summon necromancer, engage necromancer in combat

### Server Type

Single Player

### Iron's Spells N Spellbooks version

2.2.0

### Forge version

1.20,1

### Other mods

I know epic fight causes the crash

**Comment by lab3** [comment]
There are no issues in the epic fight bug tracker for this (open or closed).  You should enter one. We are not going to nerf our mobs or spend time coding workarounds because of bugs in epic fight.

https://github.com/Yesssssman/epicfightmod/issues?q=necromancer
