### ISSUE TITLE
Animationless Summoning

### ISSUE THREAD

**Issue by Archongaming** [iron431/Irons-Spells-n-Spellbooks#544]
### Feature description

I love the current summoning animation for necromancers, we should have an config toggle to remove animations from summoned zombies and skeletons (config option called something like simple necromancer summons)

### How it improves the player experience

animation mods like epic fight are awesome but directly conflict with irons spells. when both are installed and summoned zombies and skeletons have epic fight animations it causes a game crash as the animation they use when being summoned conflicts with epic fights animations and causes a crash. if we had the ability to turn the summon animations off as a toggle this would allow mod pack creators to more freely use irons spellbooks in their modpacks without having to disable necromancers or have default animations on the summoned zombies and skeletons (this would mean that this could potentially mesh alot better with animation mods)

**Comment by Archongaming** [comment]
to be more specific I dont think this is something that epic fight team would be able to fix because of how it functions, I cant see this being possible without a complete rewrite of how the mod calls animations. from your end this could be an optional toggle which simply removes the animations of zombies crawling out and has them simply spawn in instead (the rest of the spawning code doesnt seem to cause issues) this wont nerf or water down your mobs at all and instead will just help with current and future compatibility

**Comment by Archongaming** [comment]
alternatively this could also be fixed by being able to add a config which allows us to choose what the necromancer summons, and then adding the summoned dead effect tag to it separately, this would allow even greater versatility as we would be able to add mobs from other mods such as the mutant zombie from mutants or the even allow us to customize them to be more thematic (for example husks or drowned) this could possibly allow us to also bypass the animations used when they are summoned allowing us to replace the summoned mobs variants with vanilla mobs with the summoned dead effect

**Comment by iron431** [comment]
epic fight crashing the game is explicitly and singlehandedly an epic fight issue
