### ISSUE TITLE
[Bug] rendering Iron's Spells entity with glowing crashes the game

### ISSUE THREAD

**Issue by LzModding** [iron431/Irons-Spells-n-Spellbooks#547]
### Observed behaviour

Whenever I make Iron's Spells entities glow the game crashes.

### Expected behaviour

Making the entities glow.

### Steps to reproduce

mack a  Iron's Spells entitie glow 

### Server Type

Single Player

### Crashlog

https://gist.github.com/Lucaszwarthoed/f9818b7717f05ac0e511abd6df901101

### Iron's Spells N Spellbooks version

v1.21-3.4.4

### Forge version

Neoforge - 21.1.22

### Other mods

adorned(curios)
Caelus API
GeckoLib

**Comment by iron431** [comment]
this is a geckolib issue
