### ISSUE TITLE
Balance Change: Amethyst Rapier & Spellbreaker

### ISSUE THREAD

**Issue by Feyreth** [iron431/Irons-Spells-n-Spellbooks#548]
### Feature description

Loving the new weapons, but I think the Amethyst Rapier and Spellbreaker weapons might be a touch too powerful. They both boast an insane attack speed with good damage and high reach, while being particularly easy to make even early game. Amethyst Rapier also has its special imbued spell that allows it to hit in a radius around the struck mob, and the mob itself.
This is what I'd personally suggest for them:
**Spellbreaker**
Damage: 10 ~ 10
Attack speed: 2 > 1.5
Range: 3.25 > 3
**Amethyst Rapier**
Damage: 8 > 7
Attack Speed: 2.5 > 2
Range: 4 > 2.75

I worked out these changes from the weapon mod Simply Swords since it has a pretty good baseline for each weapon type, katana and longsword (assuming Spellbreaker is meant to be one, correct me if I'm wrong).

### How it improves the player experience

Generally makes these more balanced for the ease of availability of these weapons.

**Comment by Razor235T** [comment]
Or config to change that. Please

**Comment by iron431** [comment]
These weapons are intended to be very powerful. They are admittedly much easier to get on older versions of the mod, but that is due to restrictions on the unsupported version and is very unlikely to change.

Any personal tweaks or configuration can be done with any mod that lets you change item attributes, so this will not be worked on

**Comment by Feyreth** [comment]
> These weapons are intended to be very powerful. They are admittedly much easier to get on older versions of the mod, but that is due to restrictions on the unsupported version and is very unlikely to change.
> 
> Any personal tweaks or configuration can be done with any mod that lets you change item attributes, so this will not be worked on

That's entirely fair. I do still think the range should be nerfed at the very least but if you think it's fine then I'll take your word for it and look up how to change them for my own use. Ta

**Comment by Razor235T** [comment]
> > These weapons are intended to be very powerful. They are admittedly much easier to get on older versions of the mod, but that is due to restrictions on the unsupported version and is very unlikely to change.
> > Any personal tweaks or configuration can be done with any mod that lets you change item attributes, so this will not be worked on
> 
> That's entirely fair. I do still think the range should be nerfed at the very least but if you think it's fine then I'll take your word for it and look up how to change them for my own use. Ta

I just deleted recipe, where you get arcane salvage from melting rings (to make gear truly high end), and mod called property modifier (1.20.1 forge) let me decrease damage and attack speed for the weapons. But it seems that there is no range stat change supported, though.
