### ISSUE TITLE
[Bug] Memory Leak of Client Player

### ISSUE THREAD

**Issue by pietro-lopes** [iron431/Irons-Spells-n-Spellbooks#549]
### Observed behaviour

Client Player is leaked to Main Menu

### Expected behaviour

No leak

### Steps to reproduce

Join game, exit game to Main menu and Client Player is leaked.

SpellBarOverlay holds an instance of:
SpellSelectionManager which holds a player

![image](https://github.com/user-attachments/assets/99522fc1-8812-4caa-84d6-fe3d454e43ab)

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.4.4

### Forge version

1.21.1 - 21.1.12

**Comment by lab3** [comment]
@pietro-lopes Is this creating an actual issue or just something that can be cleaned up?

**Comment by pietro-lopes** [comment]
This is the kind of leak that does not grow, but it is nice to be cleaned in case the player joins a new world.
With this leak, the player when joining a new world will have at some point 2 instances, instead of trying to spin the new one only.
This is negligible on vanilla mc, but in modded and packs like ATM, Client Level can be huge

**Comment by iron431** [comment]
fixed in 3.4.5
