### ISSUE TITLE
Bug with EpicFight, when in combat mode you hit a magic shield or a magic pyromancer the game crashes.

### ISSUE THREAD

**Issue by DeshiDesu** [iron431/Irons-Spells-n-Spellbooks#55]
Hello, sorry to barge into this thread, but there is another bug with EpicFight, when in combat mode you hit a magic shield or a magic pyromancer the game crashes.

_Originally posted by @HarlamovLive in https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/52#issuecomment-1589894941_

**Comment by lab3** [comment]
@DeshiDesu Please post the logs

**Comment by DeshiDesu** [comment]
I tried it myself and it does indeed crash when hitting a pyromancer using epic fight battle mode
[crash-2023-06-14_01.07.16-server.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/11741830/crash-2023-06-14_01.07.16-server.txt)
Pardon the large file, I haven't tested in with only those 2 mods installed.

**Comment by DeshiDesu** [comment]
It seems the crash is caused by Epic Fight. They explicitly said that it is recommended to use Forge 40.1.80 or it likely wont be compatible with some mods.

**Comment by DeshiDesu** [comment]
Error persisted even when downgrading to Forge 40.1.80. I'll leave this here in chance the cause was ISNS

**Comment by DeshiDesu** [comment]
[crash-2023-06-15_00.22.51-server.txt](https://github.com/iron431/Irons-Spells-n-Spellbooks/files/11752805/crash-2023-06-15_00.22.51-server.txt)
heres the crash report for the magic shield

**Comment by iron431** [comment]
I've looked into it and it is an Epic Fight issue. They have a nullable method but do not check if it is null, resulting the null pointer crash. https://github.com/Yesssssman/epicfightmod/blob/8c47302aa24f6a0259e071ee72a4ce5ee8c15c7b/src/main/java/yesman/epicfight/api/animation/types/AttackAnimation.java#LL203C4-L203C6
Closing as wontfix

**Comment by DeshiDesu** [comment]
Fixed using mod https://www.curseforge.com/minecraft/mc-mods/mod-compat-fixes

**Comment by HarlamovLive** [comment]
> Fixed using mod https://www.curseforge.com/minecraft/mc-mods/mod-compat-fixes

Thank you so much!

**Comment by DeshiDesu** [comment]
> > Fixed using mod https://www.curseforge.com/minecraft/mc-mods/mod-compat-fixes
> 
> Thank you so much!

Np
