### ISSUE TITLE
[Bug] Crash in 1.21.1 when equipping two of the same curio

### ISSUE THREAD

**Issue by pyrige** [iron431/Irons-Spells-n-Spellbooks#550]
### Observed behaviour

When equipping two of the same curio (e.g. Rings of Expediency) at the same time, the server crashes.

I raised the same issue with **Curios API Continuation** (SSKirillSS/Curios#8) and as I understand it, attribute processing in 1.21 has changed in such a way that `addModifier()` throws `IllegalArgumentException: Modifier is already applied on this attribute!` when the same `ResourceLocation` is used multiple times.

With **Adorned (Curios)** no crash is exhibited, but the `AttributeModifier` is applied only once instead of the expected two times.

### Expected behaviour

Equipping multiple of the same curio in different curio slots applies their effect multiple times.

### Steps to reproduce

1. Equip Ring of Expediency in Ring slot 0
2. Equip another Ring of Expediency in Ring slot 1

### Server Type

Dedicated Server

### Crashlog

https://hastebin.com/share/gitatijecu.bash

### Iron's Spells N Spellbooks version

1.21-3.4.4

### Forge version

21.1.19

**Comment by iron431** [comment]
fixed in 3.4.5
