### ISSUE TITLE
[Bug] Mobs drop broken scrolls

### ISSUE THREAD

**Issue by element-aMge** [iron431/Irons-Spells-n-Spellbooks#554]
### Observed behaviour

Mobs from the mod dropped broken scrolls that crashed my game when I opened my inventory

### Expected behaviour

I expected mobs to drop normal scrolls.
https://imgur.com/a/vw678rR

### Steps to reproduce

1. Kill mob
2. Pick up drops
3. Open inventory
4. Crash

### Server Type

Single Player

### Iron's Spells N Spellbooks version

v1.21-3.4.4

### Forge version

neoforge-21.0.167

### Other mods

A lot

**Comment by iron431** [comment]
please fill out the rest of the bug report

**Comment by ExiledMiner04** [comment]
It causes the game to hang or run out of memory and you have to force close it, so it can't generate a proper crash report. You can't even hover the cursor over the bugged scroll.

See my report for more details. https://github.com/iron431/irons-spells-n-spellbooks/issues/563

**Comment by iron431** [comment]
closing for duplicate of #563
