### ISSUE TITLE
Suggestions on the block radius and block range of spells

### ISSUE THREAD

**Issue by Mnibr** [iron431/Irons-Spells-n-Spellbooks#558]
### How it improves the player experience

When the player's spell power is too high, the block radius and block range values of some spells affected by the spell power will become very large, which makes them unable to be used properly (such as the spectrol-hammer destruction range being very large, causing the server to not respond, using teleport will transmit thousands of coordinates, etc.). I hope to allow upper limits to be set in the mod's config to ensure that this part of the spell can be used properly. Therefore, I have customized an open source mod to handle this issue and hope that you can add its functionality to your mods

**Comment by iron431** [comment]
please dont leave links to code anywhere. we are aware of these balance concerns and are working on them

**Comment by Mnibr** [comment]
If you have a good idea, is it convenient to adjust the relevant parameters to allow the use of event changes?

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
