### ISSUE TITLE
[Bug] Walk on powder snow causes fps drops

### ISSUE THREAD

**Issue by DankestO** [iron431/Irons-Spells-n-Spellbooks#559]
### Observed behaviour

I don't know exactly why this happens, but if you walk in powder snow, while falling the fps drops incredibly the more Curios slots you have equipped with Iron's Spellbook gear.
I've been checking with a few other mods, but it only seems to happen with Curios Iron's Spellbooks gears.

### Expected behaviour

No fps drops

### Steps to reproduce

1. Equip myself with 4 rings from Iron's Spellbook: 1 cooldown ring 3 mana rings
2. Falling in powder snow
3. Enjoy the view

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1 - 3.4.0

### Forge version

1.20.1 - 47.2.00

### Other mods

The list of mods along with statistics of what happens can be seen in Spark:
https://spark.lucko.me/OH1RA2fCvB

**Comment by iron431** [comment]
The profiler shows that parcool is causing the resource consumption.

**Comment by iron431** [comment]
parcool is using 70% of the tick's resources
![image](https://github.com/user-attachments/assets/7f2c34f8-a737-4a65-8009-c8780e661be1)
