### ISSUE TITLE
[Bug] Right click to use spells spells will override other interactions with weapons

### ISSUE THREAD

**Issue by XiFengXF** [iron431/Irons-Spells-n-Spellbooks#56]
### Observed behaviour

When a spell is installed, and using a weapon with other right-click interactions, such as tetra's block, the use of the spell overrides the other interactions, making it impossible to block.

### Expected behaviour

I want to be able to use spells by binding other keys.

### Steps to reproduce

1. Install spells on weapons that have other right-click interactions.
2. Right click to use.
3. Spell usage and cooldowns override other interactions with weapons.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.19.2-1.1.4

### Forge version

1.19.2 - 43. 2.9

**Comment by Darkmega18** [comment]
This is somewhat problematic on my end as I have Project War dance and it allows dualwielding and shield bashing with rightclick when available, but the spell equipped to the weapon overrides/gets used first, sometimes wasting it/misfiring.

I'd appreciate a key or a "modifier" binding that allows the spell to be used also or even the ability to shift+mousewheel select the weapon's spell as a "spell book" to an "empty spell" that appears on it's bar that basically does no interaction when selected meaning it can be returned to it's original state unless you scroll back onto the right to activate it.
Another way could be requiring the spell to be primed with a quick keybind or action which you can then just hold onto and use when you next rightclick, which then toggles itself back off again.

**Comment by Darkmega18** [comment]
:V

**Comment by Darkmega18** [comment]
rawr

**Comment by Darkmega18** [comment]
:V :V :V :V :V

**Comment by zireaelqqq** [comment]
Same problem, but with Epic Fight. I would like this fix sooner

**Comment by Darkmega18** [comment]
Gah. how do we re-open this...
