### ISSUE TITLE
[Bug] Server latency allows users to gain permanent Buffs/Debuffs

### ISSUE THREAD

**Issue by TomatoSoupter** [iron431/Irons-Spells-n-Spellbooks#560]
### Observed behaviour

When dying, there is a short time frame where the player can use spells due to latency. Using a spell that buffs the player, will cause that buff to be permanently applied to the user until the buff is used again. Counterspell cannot remove the buff, nor can milk.

### Expected behaviour

Spells should be cleared from the player after death/respawning, like other effects do.

### Steps to reproduce

1: Die and use a spell before the client realizes the player is dead (Timing is easier with higher latency)
2: Respawn
3: You now have a permanent buff

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1,21-3.4.4

### Forge version

Neoforge - 21.0.163

### Other mods

The mods currently in the Modding Magic Playtest pack.

**Comment by Neko-a-b** [comment]
Main discoverer here, as far as we know, only Abyssal Shroud or Evasion could theoretically be abused. You can also remove the effect by using the spell again, whilst alive. 
Here's a list of spells and their effects during the bug:
Abyssal Shroud lasts permanently, and you cannot take damage from sources like other players or environmental, such as lava and fire. Fall damage still persists.
Evasion works exactly like Abyssal Shroud, except now you have teleportation added on top of it.
Charged only shows a visual indication you're "charged". Any buffs from it aren't included.
Angel Wings and Oakskin do not have any effect.
Any other buff/debuff spells are either too difficult to test or haven't been tested yet.

**Comment by iron431** [comment]
this is a bug due to dying with any effect, and is fixed in 3.4.5
