### ISSUE TITLE
[Bug] IronEnderChests Crash on JEI/EMI/Creative Menu load. 

### ISSUE THREAD

**Issue by Zelioth** [iron431/Irons-Spells-n-Spellbooks#561]
### Observed behaviour

Crash when loaded through any recipe viewer 

### Expected behaviour

to not crash

### Steps to reproduce

yes

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Zelioth/13d8fa09ad9ee934aa9244322dc7a376

### Iron's Spells N Spellbooks version

Iron Ender Chests 1.0.3

### Forge version

NeoForge 21.1.31 / Minecraft 1.21.1

### Other mods

Friends United 2.1
https://www.curseforge.com/minecraft/modpacks/friends-united-2-1

**Comment by iron431** [comment]
Iron Ender Chests does not support 1.21.1 yet
