### ISSUE TITLE
Toggleable Curios Spell book slot

### ISSUE THREAD

**Issue by Banditial** [iron431/Irons-Spells-n-Spellbooks#562]
### Feature description

There should be a way to toggle the spell book curios slot on and off in either the configs or as a new command.

### How it improves the player experience

With Curios, you can use your spell menu at any point, which kind of defeats the purpose of imbuing your weapons. I like using Curios with ISS but I find it a bit boring that the spell book can be used without physically holding it. So having it be toggleable would be the best choice since there are probably people that like having it as a curios slot, while others would prefer having to physically hold the book.

**Comment by iron431** [comment]
no
