### ISSUE TITLE
[Bug] I'm Picking up a bugged looted Scroll form a dead priest game just hangs indefinately. Must end task.

### ISSUE THREAD

**Issue by ExiledMiner04** [iron431/Irons-Spells-n-Spellbooks#563]
### Observed behaviour

I found a priest village to have died fighting a mob when it wandered over water. It dropped a lot of stuff including some scrolls, ink of various rarities and even holy runes. It dropped an inscribed spell scroll and a blank one probably one that is Null that I seen back in 1.20.1. I checked the bugged scroll and the game will freeze to a halt and become unresponsive, no crash report can be generated though I had one occur during looting said item or related to something else on the mod? I can post it here.

### Expected behaviour

The scroll when looted should not cause the game to hang when hovered over in inventory or just not exist if its a null scroll.

### Steps to reproduce

1. Kill a priest or let it die to something it was fighting.
2. loot the stuff it dropped. It may drop a bugged Null scroll.
3. Open inventory and try to look at it.

### Server Type

Single Player

### Crashlog

https://gist.github.com/ExiledMiner04/fdf611b8f13da53650f8780dae13c32d

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.4.5-all

### Forge version

Neoforge 1.21.1 - 21.1.31 

### Other mods

Jade-1.21.1-NeoForge-15.1.8
geckolib-neoforge-1.21.1-4.6.2
jei-1.21-neoforge-19.8.2.99
alllootdrops-1.21.1-3.4
collective-1.21.1-7.84
justmobheads-1.21.1-8.3

**Comment by ExiledMiner04** [comment]
I tried to delete the item by jumping in lava added with a bucket from creative mode, and it survived being immolated and destroyed, looking at it with jade doesn't crash the game luckily. Maybe its a conflict with Jade?

![image](https://github.com/user-attachments/assets/98a0a333-36a4-44a7-89f4-5a209211c15c)

**Comment by ExiledMiner04** [comment]
[crash-2024-09-01_16.25.56-client.txt](https://github.com/user-attachments/files/16830404/crash-2024-09-01_16.25.56-client.txt)
I was able to get a crash report finally.

**Comment by iron431** [comment]
crashbug fixed in 3.5.0
