### ISSUE TITLE
"/give" command giving filled spellbook

### ISSUE THREAD

**Issue by otaldojonis** [iron431/Irons-Spells-n-Spellbooks#565]
### Feature description

I don't know if is already possible, but I believe is not: giving a player a specific spellbook with a specific set of spells already registered on it, via command.

### How it improves the player experience

This would be very useful especially when you are trying to make starter items for a mage class. Modpack devs could choose exactly how strong the mage should be from start.
(Yes I'm trying to do this ;¬;)

**Comment by iron431** [comment]
spellbooks are based on nbt/componets and work with the give command
