### ISSUE TITLE
Why don't we have a discord channel? 

### ISSUE THREAD

**Issue by otaldojonis** [iron431/Irons-Spells-n-Spellbooks#566]
### Feature description

This mod is big complex and amazing, I think it deserves a dedicate server even if it's simple. 

### How it improves the player experience

Sometimes wikis aren't enough and many people, me included, feels bad having to bother devs everytime we have a doubt. I wish there is a way for the community help and interact with each other, since comments section at curseforge is more likely a joke.

**Comment by MHImoment** [comment]
Buddy, they have discord channel

**Comment by meeprdib** [comment]
The server link is on the curseforge page
https://discord.com/invite/ANKfpYu6
