### ISSUE TITLE
[Bug] Game crash when right click blood-filled cauldron with empty hand

### ISSUE THREAD

**Issue by TomTheThuan** [iron431/Irons-Spells-n-Spellbooks#567]
### Observed behaviour

Game crash when right click blood-filled cauldron with empty hand

### Expected behaviour

- Nothing happens when I right click blood-filled cauldron with hand
- Fill the bucket when I interact cauldron with empty bucket
- Not make the game crash

### Steps to reproduce

1. Place the cauldron on a camp fire
2. player stand in the cauldron to produce blood
3. interact the cauldron with empty hand

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.4.5

### Forge version

neoforge 21.0.167

### Other mods

appleskin-neoforge-mc1.21-3.0.5.jar
caelus-neoforge-7.0.0+1.21.jar
curios-neoforge-9.0.7+1.21.jar
CustomSkinLoader_ForgeV3-14.20.jar
geckolib-neoforge-1.21-4.5.8.jar
irons_spellbooks-1.21-3.4.5-all.jar
Jade-1.21-NeoForge-15.1.6.jar
jei-1.21-neoforge-19.8.2.99.jar
MouseTweaks-neoforge-mc1.21-2.26.1.jar
open-parties-and-claims-neoforge-1.21-0.23.2.jar
Terralith_1.21_v2.5.4.jar
Xaeros_Minimap_24.3.0_NeoForge_1.21.jar
XaerosWorldMap_1.39.0_NeoForge_1.21.jar

**Comment by iron431** [comment]
@TomTheThuan please attach a crash log so this can be looked into
