### ISSUE TITLE
Options to change Mana Bar Appearance.

### ISSUE THREAD

**Issue by Mqony** [iron431/Irons-Spells-n-Spellbooks#568]
### Feature description

Imo right now the current Mana Bar doesn't fit in the best with the base game. It's wider than the vanilla health/hunger bars, taller, and generally looks out of place. It would be cool if it was adjusted to replicate the base game, possibly using the 10 icon appearance that all other bars in vanilla do. Or maybe you could give a config option to adjust the size of the current mana bar, so people can make it fit in. Also, an option to hide it in Creative would be nice.

### How it improves the player experience

Allows players and modpack developers to adjust the mana bar and make it fit in with the game

**Comment by iron431** [comment]
there are extensive client config options already. if you do not think it fits vanilla, you can make a texture pack. otherwise, this will not be worked on
