### ISSUE TITLE
[Bug] Bounding spells to a spell book makes the game crash

### ISSUE THREAD

**Issue by BersisSe** [iron431/Irons-Spells-n-Spellbooks#569]
### Observed behaviour

My game Crashed when I tried to bound a spell to a spellbook that has a "i" in the name like magic missile for example. There the Exception:
 `net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: irons_spellbooks:textures/gui/spell_icons/magıc_mıssıle.png
`
Also here is the whole crash report:
https://mclo.gs/k696pCD

### Expected behaviour

Also most of the spells textures are not avaliable like magic missile it's a problem with "i" & "ı" character
what I expected to happen is all of the spells to work as expected

### Steps to reproduce

1.On a Dawncraft Dedicated Server 2.Both Server and Client Is on turkish 3.Try to bound a spell to a spell book preferably something that has a "I" or "i" in it

### Server Type

Dedicated Server

### Crashlog

https://mclo.gs/k696pCD

### Iron's Spells N Spellbooks version

 1.18.2 1.1.4.5

### Forge version

1.18.2 40.2.17

### Other mods

The dawncraft mod pack this happens on dawncraft modpack

**Comment by SiverDX** [comment]
https://github.com/iron431/irons-spells-n-spellbooks/blob/944e4f5010d2d1d1a1caa749e29ea9e9c1483c0c/src/main/java/io/redspace/ironsspellbooks/spells/SpellType.java#L339

would need `Locale.ENGLISH` as parameter for the lower case call
ran into the same problem with some other mod

**Comment by BersisSe** [comment]
Ok I get that but, What should I now?

**Comment by BersisSe** [comment]
I cloned the repo did what you said, and it works! 
Thank you for your help but I think someone has to make a new version or something(I am pretty new with git)
