### ISSUE TITLE
[Bug] Spell "Abyssal Shroud" sometimes teleports you into blocks, leading to no-clipping and possibly suffocation damage.

### ISSUE THREAD

**Issue by Bork6996** [iron431/Irons-Spells-n-Spellbooks#571]
### Observed behaviour

Basically, I was defending a village from an illager raid and used Abyssal Shroud in a panic, but the amount of entities attacking me at once made me teleport rapidly, and eventually I found myself in the ground dead from suffocation damage. It was too fast to properly process what made me lose so much health so fast(I was almost full health before entering the ground then died within 2 seconds), but being teleported into the ground isn't new. It also happened while fighting the "Ignis" boss from the mod "L_Ender's Cataclysm". Sometimes it'd teleport me 1 block into the ground, which forced me to either jump to get out or teleport away.

### Expected behaviour

It should check for clear space nearby to teleport you to in order to avoid no-clipping. If there is none and you're in a 1x1 hole, it should just play the sound without actually teleporting you anywhere.

### Steps to reproduce

1. Summon a large amount of slightly taller entities, or one very tall entity.
2. Cast "Abyssal Shroud"
3. Get hit with "Abyssal Shroud" active. You will sometimes be teleported into the ground.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.2.1

### Forge version

1.20.1 - 47.2.0

### Other mods

[Beyond the Overworld-1.0.2.zip](https://github.com/user-attachments/files/16913446/Beyond.the.Overworld-1.0.2.zip)

**Comment by iron431** [comment]
dog, you using 3.2.1. you are 12 updates behind. this was fixed 7 updates ago
