### ISSUE TITLE
[Bug] Game Crashes when trying to open configs

### ISSUE THREAD

**Issue by ffuentesm** [iron431/Irons-Spells-n-Spellbooks#573]
### Observed behaviour

The game crashes 

### Expected behaviour

It should open the game configs

### Steps to reproduce

Try to open the Iron's Mod Config when in-game

### Server Type

Single Player

### Crashlog

https://pastebin.com/fWn8qBNE

### Iron's Spells N Spellbooks version

1.21-3.5.0

### Forge version

21.1.39

**Comment by meeprdib** [comment]
I'm assuming this means that ISS' way of doing configs is not supported by the "Configured" mod. Try changing the configs through the config file in your modpack instance folder.
Edit: This is misinformation.

**Comment by iron431** [comment]
this appears to be an issue between catalogue and jab125's config screens. it is not clear what, if anything, this has to do with spellbooks
