### ISSUE TITLE
zh_cn Update

### ISSUE THREAD

**Issue by GuKaaaa** [iron431/Irons-Spells-n-Spellbooks#574]
### Feature description

I've heard it that Chinese translators aren't able to work on the new versions currently. So I tried to update it.
Link: [https://paste.ubuntu.com/p/DNXPGvH6Mh/](https://paste.ubuntu.com/p/DNXPGvH6Mh/)
I hope it will do.

### How it improves the player experience

Update Chinese Translate

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
