### ISSUE TITLE
[Suggestion] Fix the Missing components that do not show up on JER/EMI

### ISSUE THREAD

**Issue by ffuentesm** [iron431/Irons-Spells-n-Spellbooks#576]
### Feature description

Let's start with the problem. 
due to how things are implemented, JER and EMI Loot do not recognize the irons drops for the vanilla mobs (Stray, Dragon, Blaze, Hoglin, Evolker). The way the mod circumvents that is by adding an INFO tab on those drops. The problem is that some of those items do not have an INFO tab. 

Mainly the Blaze Spellbook and Prist Spellbook (Since for some reason the Iron NPC trades do not show up on JEI/EMI). 
In comparison, all other spellbooks have an INFO tab or a JER entry. 
![image](https://github.com/user-attachments/assets/4fb0971a-8393-447d-93ef-04ecf45add2d)
![image](https://github.com/user-attachments/assets/fa83b72d-890f-443c-be15-7ab6c89a1a48)
![image](https://github.com/user-attachments/assets/16884209-2fa3-4389-a1e8-e127cb1dbdae)
![image](https://github.com/user-attachments/assets/1e880cf4-90be-4186-8c03-cd7f6f5c928f)

I was able to add it to the Mob Drop tab, but I had to copy the vanilla loot table and add the new section to it. Otherwise, the mod loot table fully overwrites the vanilla drops. 
![image](https://github.com/user-attachments/assets/63630ef6-c406-47c3-880e-7cc3db113ea7)

### How it improves the player experience

The solution is to either add an INFO tab to the missing items. Or add the new item drops onto the mob vanilla loot table so they show up on JER/EMI tabs.

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
