### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Ashayi-pi** [iron431/Irons-Spells-n-Spellbooks#578]
### Observed behaviour

i use Iron's Spells 'n Spellbooks 1.19.2-3.4.0,i try to change the thunderstorm's damage so i change the spellpowermultiplier of this spell from 1.0 to 15.0,but i found it seems to not work on it,it still cause damage like spellpowermultiplier 1.0
![微信图片_20240914215005](https://github.com/user-attachments/assets/b2e5508f-2d1a-438c-873b-0158b929ba1f)
![微信图片_20240914215122](https://github.com/user-attachments/assets/c3f82d3c-d72c-4a9f-9089-7b9ba91b56f7)

### Expected behaviour

the damage of thunderstorm should be change by modify the spellpower

### Steps to reproduce

1.modify the spellpower
2.open the game 
3.find out no different between the after

### Server Type

Single Player

### Iron's Spells N Spellbooks version

Iron's Spells 'n Spellbooks 1.19.2-3.4.0

### Forge version

forge 43.2.11

**Comment by iron431** [comment]
~~the inscription table does not show an entity's spell power, only the base stats of the spell. hover over a scroll or spellbook to see the effective stats~~
nvm there is a different issue at play

**Comment by Ashayi-pi** [comment]
I have actually tried using this spell after modifying it，it still doesn't work properly，also i tried to modify other spell like thunderclap,and he work

**Comment by iron431** [comment]
fixed in 3.6.0/3.4.0.1

**Comment by qxZap** [comment]
Hi @iron431 
Me and my team we are working on a modpack and we are in a big struggle to balance the spells (spellpowermultiplier does not work properly for us). 
Some work but most of them are cooked, oakskin, earthquake, lightning, frost step, all step actually, fortify, haste and many others. 

I changed the defcofnig place it in serverconfig of the world but nothing happens. Is there an exta step required?

fml 47.2.20 isb 3.4.0.1 mcv 1.20.1

**Comment by iron431** [comment]
some parameters are based strictly on the level, so a player's power would not affect it
