### ISSUE TITLE
Fire Dash I-frames

### ISSUE THREAD

**Issue by Darkmega18** [iron431/Irons-Spells-n-Spellbooks#58]
### Feature description

A lot of mods which try to do dash attacks don't consider the instantaneousness of attacks of enemies like a zombie when they come within range to hit you. 
Please consider putting some form of temporary i-frames and hit negation (no flinching) during the dash period of flame dash (extended to the end of the animation) so you can dash through enemies without immediately being slapped. Otherwise the ability is just glorified mobility and can't safely be used offensively in combat without likely suffering equal or worse damage depending on the modpack from taking a hit while trying to use your attack.

### How it improves the player experience

yes. No more frustration of the dash being bad.

**Comment by Darkmega18** [comment]
:V

**Comment by Darkmega18** [comment]
rawr.

**Comment by Darkmega18** [comment]
aaaaaaah

**Comment by iron431** [comment]
added in 3.0.0

**Comment by Darkmega18** [comment]
noice. that aughtta be helpful when I next play.
