### ISSUE TITLE
[Missing Tags] Autoloading  Crossbow missing tags

### ISSUE THREAD

**Issue by ffuentesm** [iron431/Irons-Spells-n-Spellbooks#581]
### Feature description

If you compare the weapon to the base crossbow tags, you can see a few missing. Adding them would improve compatibility to other features
![image](https://github.com/user-attachments/assets/5ffb2456-5821-4416-a27e-178b71e6b03c)
![image](https://github.com/user-attachments/assets/60897440-e36f-4775-8bf6-148e64243d21)

### How it improves the player experience

Add the missing tags to the item 
`c:tools/crossbow`
`c:tools/ranged_weapons`
`minecraft:enchantable/durability`

**Comment by iron431** [comment]
what mod adds the tags to the tooltip?

**Comment by ffuentesm** [comment]
Currently, for Neoforge, I could only find that Occultism has the tooltip option. 
For fabric there is https://modrinth.com/mod/component-viewer

**Comment by iron431** [comment]
tags added in 3.6.0
