### ISSUE TITLE
[Bug] Fireward Ring not working with Tough as Nails (NeoForge 1.21.1)

### ISSUE THREAD

**Issue by gamerpotion** [iron431/Irons-Spells-n-Spellbooks#583]
### Observed behaviour

Hi, the Frostward ring works fine with tough as nails and stops any freezing damage however the fireward ring does not protect against heat. Is there a possibility that this could be looked into please?

### Expected behaviour

Fireward Ring to protect against heat damage from Tough as Nails mod.

### Steps to reproduce

1. Install Irons Spells and Tough as Nails mod
2. Equip Fireward Ring
3. Go to Nether and test
4. Do the same with Frostward ring and snowy biome and that works fine

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.21-3.6.1 (NeoForge)

### Forge version

NeoForge 1.21.1 (21.1.51)

### Other mods

tested on Vagrant Saga modpack - https://legacy.curseforge.com/minecraft/modpacks/vagrant-saga

**Comment by Quarkrus** [comment]
most likely because tough as nails uses vanilla freezing mechanics and therefore the ring works great, but it already provides its own heating mechanics, with which the fireward ring does not work.

**Comment by iron431** [comment]
this is correct and as such requires a compatibility patch, making this less of a bug and more of a feature request. i am not interesting in implementing this, although an addon could do so easily
