### ISSUE TITLE
[Bug] Wall of Fire obstructs player movement at rather awkward locations

### ISSUE THREAD

**Issue by amzelee** [iron431/Irons-Spells-n-Spellbooks#586]
### Observed behaviour

Setting up Wall of Fire would randomly generate invisible obstructions near or outside the location where the spell is cast.

### Expected behaviour

I believe the obstructions are meant to be what shields against projectiles like arrows. My expected behavior for Wall of Fire is that it should generate obstructions inside the line it is casted at, and not random areas around it.

### Steps to reproduce

1. Cast Wall of Fire
2. Walk towards, then through the spell.
3. If walking towards it doesn't work, then jump towards it at different angles.

### Server Type

Single Player

### Crashlog

None. However, here's the [latest](https://gist.github.com/amzelee/20456e52355acb261f19942daa3a5178) log instead in-case it helps.

### Iron's Spells N Spellbooks version

3.6.2

### Forge version

NeoForge 21.1.54

### Other mods

[Adorned API](https://www.curseforge.com/projects/1036809) [9.1.3+1.21.0]
[AppleSkin](https://modrinth.com/mod/EsAfCjCV) [3.0.5+mc1.21 ]
[BadOptimizations](https://modrinth.com/mod/g96Z4WVZ) [2.1.4]
[Balm](https://modrinth.com/mod/MBAkmtvl) [21.0.19]
[Better Combat](https://www.curseforge.com/projects/639842) [2.0.3+1.21.1]
[Caelus API](https://modrinth.com/mod/40FYwb4z) [7.0.1+1.21.1]
[Catalogue](https://www.curseforge.com/projects/459701) [1.10.2]
[Cloth Config v15 API](https://www.curseforge.com/projects/348521) [15.0.140]
[Clumps](https://modrinth.com/mod/Wnxd13zP) [19.0.0.1]
[Concurrent Chunk Management Engine](https://modrinth.com/mod/VSNURh3q) [0.3.0+alpha.0.206+1.21.1]
[Configuration](https://modrinth.com/mod/3WjjSM5O) [3.0.0]
[Connectivity Mod](https://www.curseforge.com/projects/470193) [5.8]
[Connector Extras](https://modrinth.com/mod/FYpiwiBR) [1.12.1+1.21.1 ]
[Controlling](https://modrinth.com/mod/xv94TkTM) [19.0.2]
[Cristel Lib](https://modrinth.com/mod/cl223EMc) [1.2.8]
[CullLeaves](https://modrinth.com/mod/GNxdLCoP) [3.4.0]
[Cupboard mod](https://www.curseforge.com/projects/326652) [2.8]
[Dungeons and Taverns](https://modrinth.com/mod/tpehi7ww) [4.4]
[Embeddium](https://modrinth.com/mod/sk9rgfiA) [1.0.11+mc1.21.1]
[Embeddium Extra](https://modrinth.com/mod/oY2B1pjg) [0.5.7e+mc1.21-build.129]
[Enhanced Block Entities](https://modrinth.com/mod/OVuFYfre) [0.10.1+1.21]
[EntityCulling](https://modrinth.com/mod/NNAgCjsB) [1.7.0]
[Euphonium](https://modrinth.com/mod/XH8cnjHW) [1.0.3+1.21]
[Explorify](https://modrinth.com/mod/HSfsxuTo) [1.6.2]
[FastQuit](https://modrinth.com/mod/x1hIzbuY) [3.0.0+1.20.6]
[Ferrite Core](https://modrinth.com/mod/uXXizFIs) [7.0.0 ]
[Forgified Fabric API](https://modrinth.com/mod/Aqlf1Shp) [0.102.0+2.0.12+1.21.1 ]
[GeckoLib 4](https://modrinth.com/mod/8BmcQJ2H) [4.6.5]
[Geophilic](https://modrinth.com/mod/hl5OLM95) [3.1.1]
[Gpu memory leak fix](https://www.curseforge.com/projects/882495) [1.8]
[ImmediatelyFast](https://modrinth.com/mod/5ZwdcRci) [1.2.21+1.21.1]
[Iron's Spells 'n Spellbooks](https://www.curseforge.com/projects/855414) [1.21-3.6.2]
[Lootintegrations mod](https://www.curseforge.com/projects/580689) [3.7]
[MidnightLib](https://modrinth.com/mod/codAaoxh) [1.6.3]
[Mineblock's Repeated Utilities](https://modrinth.com/mod/SNVQ2c0g) [1.0.2+1.21+neoforge]
[Model Gap Fix](https://modrinth.com/mod/QdG47OkI) [1.21-1.10]
[ModernFix](https://modrinth.com/mod/nmDcB62a) [5.19.3+mc1.21.1]
[Mouse Tweaks](https://modrinth.com/mod/aC3cM3Vq) [2.26.1]
[NetherPortalFix](https://modrinth.com/mod/nPZr02ET) [21.1.1]
[Noisium](https://modrinth.com/mod/KuNKN7d2) [2.3.0+mc1.21-1.21.1]
[Player Animator](https://www.curseforge.com/projects/658587) [2.0.0-alpha1+1.21]
[Presence Footsteps](https://modrinth.com/mod/rcTfTZr3) [1.10.0+1.21]
[Radium](https://modrinth.com/mod/2gvRmQXx) [0.13.0b+git.9938f59]
[Searchables](https://modrinth.com/mod/fuuu3xnx) [1.0.1]
[Sinytra Connector](https://modrinth.com/mod/u58R1TMW) [WFiIDhbD]
[Sounds](https://modrinth.com/mod/ZouiUX7t) [2.0.4+1.21+neoforge]
[Stony Cliffs Are Cool](https://modrinth.com/mod/boFjx9eY) [1.1.2]
[Towns and Towers](https://modrinth.com/mod/DjLobEOy) [1.13.2]
[chunksending mod](https://www.curseforge.com/projects/831663) [2.8]
[clientcrafting mod](https://www.curseforge.com/projects/888790) [1.8]

**Comment by amzelee** [comment]
https://github.com/user-attachments/assets/5177213f-fe70-4d52-992c-27b76fff6980

**Comment by iron431** [comment]
i cannot reproduce this. it seems like a mod you are using is giving all entity hitboxes collision. do any mods sound like they would do that? i would also try reproducing without connector.
