### ISSUE TITLE
[Bug] Spellbook duplicates when you get kicked

### ISSUE THREAD

**Issue by ZackenbarschLP** [iron431/Irons-Spells-n-Spellbooks#587]
### Observed behaviour

I disconnected from the game while i had my spellbook in the inscription table, and when i came back i had one in my curious slot, and one in my inventory.

### Expected behaviour

I was expecting it to either go in my inventory or in my curious slot, but not both

### Steps to reproduce

Go into a server, put a spellbook into an inscription table, and disconnect somehow. After you log back in you should have two spellbooks in your invetory, one of them in the curious slot.(and yes, all item data is duped, so all the spells are included aswell)

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.5.0.all.jar

### Forge version

1.21.1, Neoforge

### Other mods

Curious API continuation, version: curious-neoforge-9.0.9+1.21.jar

**Comment by Spider2200** [comment]
Pls don't fix that, it's op

**Comment by iron431** [comment]
duplication was fixed in 3.7.0, although a bug related to that fix will be released with the next update
