### ISSUE TITLE
[Bug] Cauldron crash

### ISSUE THREAD

**Issue by RyozuK** [iron431/Irons-Spells-n-Spellbooks#589]
### Observed behaviour

Attempted to place myself in a normal, empty, minecraft cauldron that was heated by a soul campfire to produce blood to put in a bottle. As soon as I took damage, some blood appeared in the cauldron, and the game crashed.  Subsequent attempts to load the game also crashed.  Deleting the cauldron via a world editor (Amulet) allowed me to load the save once again.
[debug_cauldron_crash.log](https://github.com/user-attachments/files/17089945/debug_cauldron_crash.log)

### Expected behaviour

Expected: Not to crash.

### Steps to reproduce

Place Soul campfire, place cauldron above it, jump into cauldron.

### Server Type

Single Player

### Crashlog

https://gist.github.com/RyozuK/b3594264cc54f3d6443812646241c58d

### Iron's Spells N Spellbooks version

1.21-3.6.2

### Forge version

NeoForge 21.1.43

### Other mods

[modlist.txt](https://github.com/user-attachments/files/17089968/modlist.txt)

**Comment by iron431** [comment]
@RyozuK please attach the crashlog, not the debug log

**Comment by RyozuK** [comment]
Sorry, was dead tired and didn't pay enough attention.
[crash-2024-09-22_09.05.31-server.txt](https://github.com/user-attachments/files/17091490/crash-2024-09-22_09.05.31-server.txt)
https://gist.github.com/RyozuK/3d5554eda6d2e48555d33aa50aed9d89
Having gotten some sleep, and looking at this log however, I'm suspecting it's actually an issue with Ars Nouveau instead.
