### ISSUE TITLE
[Bug] My game crashed due to the issue that irons and pmmo caused

### ISSUE THREAD

**Issue by NeoStarWonV** [iron431/Irons-Spells-n-Spellbooks#592]
### Observed behaviour

hanging around the village

### Expected behaviour

no

### Steps to reproduce

1.go to the village
2.pillage resources
3.crash

### Server Type

Single Player

### Crashlog

https://gist.github.com/NeoStarWonV/04d8f8fd44c57b4a84c0d20d7a266143

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.4.0.1

### Forge version

1.20.1-47.3.1

### Other mods

Pmmo
pmmo_spellbooks_compat

**Comment by iron431** [comment]
this is strictly a pmmo_spellbooks_compat issue and needs to be dealt with by them

**Comment by NeoStarWonV** [comment]
ok
