### ISSUE TITLE
[Bug] PlayerAnimator - Required Dependency not compatible with mod version 1.21.1

### ISSUE THREAD

**Issue by Azzazza101** [iron431/Irons-Spells-n-Spellbooks#593]
### Observed behaviour

upon trying to launch the game with with this new "Required Dependency" the game fails to load as the mod loader curseforge will not allow mods with different game versions to load, e.g. Iron's Spells 'n Spellbooks 1.21.1 and PlayerAnimator 1.21

![Screenshot 2024-09-24 185311](https://github.com/user-attachments/assets/db23e9f2-63d0-4019-9fea-6b1318b38cba)
![Screenshot 2024-09-24 185443](https://github.com/user-attachments/assets/3d98354b-c35c-4224-a579-eb6e62505cfe)
![Screenshot 2024-09-24 185513](https://github.com/user-attachments/assets/64b9a620-c7bc-4ef6-a062-172ce029e857)

### Expected behaviour

I expect the modpack to run without having a "Required Dependency" for a mod that doesnt even have a up to date mod to use with this modpack like it used to prior to this last update

### Steps to reproduce

download modpack v1.21-3.6.2 and required dependency's (that actually exist in the required version), launch mod pack encounter error screen.

### Server Type

Single Player

### Crashlog

https://gist.github.com/Azzazza101/265067820f660ea9f0cf031032d01ba0

### Iron's Spells N Spellbooks version

v1.21-3.6.2

### Forge version

v1.261.0.20372

**Comment by iron431** [comment]
while the file is not marked for 1.21.1 on curseforge, it works. install it manually
