### ISSUE TITLE
[Bug] Interaction with blood filled cauldron with empty hand causes crash

### ISSUE THREAD

**Issue by RyozuK** [iron431/Irons-Spells-n-Spellbooks#595]
### Observed behaviour

When a vanilla cauldron has blood in it, right clicking with empty hand will cause a crash

### Expected behaviour

No crash should occur

### Steps to reproduce

1. Place vanilla cauldron over a campfire (Soul fire used for me)
2. get some blood in the cauldron (I stood in it for my repro)
3. with both hands empty, right click cauldron

### Server Type

Single Player

### Crashlog

https://gist.github.com/RyozuK/527ff46afe224e58b3b1bb5c3ad92367

### Iron's Spells N Spellbooks version

1.21-3.6.2

### Forge version

NeoForge 21.1.43

### Other mods

Only the bare minimum to run Iron's Spells for this reproduction:
caelus-neoforge-7.0.1+1.21.1.jar
curios-neoforge-9.1.4+1.21.0.jar
geckolib-neoforge-1.21.1-4.6.5.jar
irons_spellbooks-1.21-3.6.2.jar
player-animation-lib-forge-2.0.0-alpha1+1.21.jar

**Comment by iron431** [comment]
fixed in 3.7.0
