### ISSUE TITLE
[Bug] blaze instruction Manual

### ISSUE THREAD

**Issue by Supertankkillz** [iron431/Irons-Spells-n-Spellbooks#596]
### Observed behaviour

Emi not showing how to obtain, and when killing a blaze its not droping

### Expected behaviour

when i kill blaze i should get the blaze instruction manual after killing 100

### Steps to reproduce

1. kill blaze 100 times
2. no blaze instruction manual will drop

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.6.2

### Forge version

1.21.1 NEO

**Comment by iron431** [comment]
emi doesnt have forge loot modifier support, and thats not how probability works
