### ISSUE TITLE
[Bug] Bug with twilight forest installed

### ISSUE THREAD

**Issue by SaphiraxYtb** [iron431/Irons-Spells-n-Spellbooks#597]
### Observed behaviour

Each time I cast a spell, my view switches to inside the player (I see myself from inside for the duration of the cast).
Update : I saw that this only happens with twilight forest installed

![image](https://github.com/user-attachments/assets/6f78324f-932f-444f-accb-2aafcc067b51)

### Expected behaviour

Not to see myself for 1-6 seconds while casting

### Steps to reproduce

0.Have Twilight Forest installed
1.Choose a spell
2.Cast the spell

### Server Type

Single Player

### Iron's Spells N Spellbooks version

v1.21-3.6.2

### Forge version

1.21 Neoforge v21.1.61

**Comment by iron431** [comment]
this is a twilight forest issues https://github.com/TeamTwilight/twilightforest/issues/2257
disable first person animation in the config as a workaround
