### ISSUE TITLE
[Bug] Can't use Arcane Anvil to merge two same 

### ISSUE THREAD

**Issue by Lunatunny** [iron431/Irons-Spells-n-Spellbooks#599]
### Observed behaviour

![image](https://github.com/user-attachments/assets/fa44e7b7-9f76-4053-95c5-0ed03b58a483)
![image](https://github.com/user-attachments/assets/ef92594d-69e2-43d2-ac04-63871f891d79)

### Expected behaviour

Expecting the scrolls to merge into a scroll of +1 level

### Steps to reproduce

1. Put two scrolls of the same level in an arcane anvil

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.1

### Forge version

1.20.1-47.2.19

### Other mods

aether-1.20.1-1.4.2-neoforge
amendments-1.20-1.1.1
architectury-9.1.12-forge
architectury-9.2.14-forge
balm-forge-1.20.1-7.2.1
bendy-lib-forge-4.0.0
Better+Cave+Dweller-1.20.1
bettervillage-forge-1.20.1-3.2.0
BiomesOPlenty-1.20.1-18.0.0.598
caelus-forge-3.2.0+1.20.1
collective-1.20.1-7.84
comforts-forge-6.4.0+1.20.1
curios-forge-5.10.0+1.20.1
deeperdarker-forge-1.20.1-1.2.1
doapi-1.2.8-forge
dungeons-and-taverns-3.0.3.f[Forge]
dungeons_plus-1.20.1-1.5.0
eureka-1201-1.5.1-beta.3
FarmersDelight-1.20.1-1.2.3
Female-Gender-Mod-forge-1.20.1-3.1
flying_castles_1.20.1_knight,village,empty_7.2
From-The-Fog-1.20-v1.9.2-Forge-Fabric
geckolib-forge-1.20.1-4.4.9
geckolib-neoforge-1.20.1-4.3.1
HammerLib-1.20.1-20.1.33
handoveryouritems-1.20.1-3.5
ImmersiveUI-FORGE-0.2.2
ImprovableSkills-1.20.1-20.1.11
InventoryProfilesNext-forge-1.20-1.10.9
irons_spellbooks-1.20.1-3.4.0.1
jei-1.20.1-forge-15.19.5.99
jei-1.20.1-forge-15.2.0.27
kotlinforforge-4.10.0-all
kotlinforforge-4.11.0-all
letsdo-bakery-forge-1.1.3b
letsdo-vinery-1.4.7-forge
libIPN-forge-1.20-4.0.1
libraryferret-forge-1.20.1-4.0.0
majrusz-library-forge-1.20.1-7.0.8
majruszs-enchantments-forge-1.20.1-1.10.8
mcdw-9.0.4
moonlight-1.20-2.10.10-forge
MRU-1.0.2+1.20.1+forge
OctoLib-FORGE-0.4.2+1.20.1
Patchouli-1.20.1-84-FORGE
player-animation-lib-forge-1.0.2-rc1+1.20
Siren_head v1.1.4-1.20.1
sophisticatedbackpacks-1.20.1-3.20.7.1094 (1)
sophisticatedcore-1.20.1-0.6.27.687
structure_gel-1.20.1-2.16.0
TerraBlender-forge-1.20.1-3.0.0.169
treeharvester-1.20.1-9.1
twilightforest-1.20.1-4.3.2508-universal
valkyrienskies-120-2.3.0-beta.5 (1)
waystones-forge-1.20-14.1.3
Wesley's Roguelike Dungeons 1.20.1-2.3.2
whisperwoods-1.20.1-2.1.2-forge
Xaeros_Minimap_24.4.0_Forge_1.20
xptome-1.20.1-2.2.1
yesstevemodel-forge-1.20-2.2.2
YungsApi-1.20-Forge-4.0.2
YungsBetterMineshafts-1.20-Forge-4.0.4
[1.20.1]illusion_onslaught-1.1.0

**Comment by iron431** [comment]
this is not how spells are upgraded anymore, check jei

**Comment by Lunatunny** [comment]
Thank you so much! Sorry for the trouble.
