### ISSUE TITLE
[Bug] Timed out waiting for world statistics

### ISSUE THREAD

**Issue by zEpiixz** [iron431/Irons-Spells-n-Spellbooks#60]
### Observed behaviour

So, its hard to say exactly when and/or where it happens but after updating to the latest version of Irons SnS the singleplayerworld i created started to just stop ticking. So i started to remove the mods that i added/ updated and sadly it was SnS that made the world stop working. I couldnt create new worlds any more it would stuck at some %., the world I play in new or old just stop working after entering the inventory or after a very short time walking around the world. No crash reports, i just have the latest log message that was "Timed out waiting for world statistics". One other world i created without it, added it back. Went exploring found a little Wizard pillage fort and shortly after the world stopped responding again. You also always have to close the game with task manager after it happens. If there is anything I can provide that would help let me know.

### Expected behaviour

To not time out.

### Steps to reproduce

Put the mod into the modpack.
Fly around.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.19.2 1.1.4

### Forge version

1.19.2 43.2.11

### Other mods

https://pastebin.com/6sWG38Q3

**Comment by lab3** [comment]
@zEpiixz Can you upload the logs as well including a the crash log if the game crashed

**Comment by iron431** [comment]
@zEpiixz are you using the fabric version of Better Statistics Screen?

**Comment by zEpiixz** [comment]
> @zEpiixz are you using the fabric version of Better Statistics Screen?

No, its the forge version 2.2.2 name is just Fabric because of the project page but i even removed it to test.



> @zEpiixz Can you upload the logs as well including a the crash log if the game crashed
No crash happening but i can provide a log: 
https://gist.githubusercontent.com/zEpiixz/b8eaa7788abf7c42f1066ae23e295679/raw/4407fcf67d26716ed52cfc4675093df90a1a1311/Timed%2520out

**Comment by iron431** [comment]
@zEpiixz I'm trying a bunch of things but I cannot replicate it. Our mod doesn't do anything related to the statistics screen. Are you sure it isn't another mod in your large modpack that is the root problem, even if it only seems to affect our mod?

**Comment by iron431** [comment]
@zEpiixz It may be a broken version of moonlight lib/supplementaries. Are you using the up to date version of these mods, and does that fix the issue?

**Comment by zEpiixz** [comment]
> @zEpiixz It may be a broken version of moonlight lib/supplementaries. Are you using the up to date version of these mods, and does that fix the issue?

Sadly, it didn't fix it. But I got closer to the root problem. I tested now with 4 newly created worlds and teleported to all over world available structures. All the structures go completely fine except the catacombs, they are the issue. Every time I teleport to them or encounter them nearby in a world while exploring, the client gets stuck in ghost mode.  I will try to test as much as i can by turning mods off and see what may cause this interaction to happen. Maybe that alone helps you.

**Comment by zEpiixz** [comment]
I found the mod conflict that causes the problem. After some hours of testing now its : https://www.curseforge.com/minecraft/mc-mods/proficiency-honest-work

I have no clue why these two mods interact that way at the catacombs, I'm not technical enough to figure that out. But with either one removed, the whole thing works. Maybe you can figure something with the dev out. Thanks

**Comment by iron431** [comment]
i appreciate your help with working through this issue and i will definitely check them out
