### ISSUE TITLE
[Bug] These modded blocks cannot be waterlogged

### ISSUE THREAD

**Issue by lzm11111111** [iron431/Irons-Spells-n-Spellbooks#600]
### Observed behaviour

These new blocks create air pockets when placed underwater instead of waterlogged
firefly jar, inscription table, scroll forge, pedestal, arcane anvil
![2024-09-28_17 07 50](https://github.com/user-attachments/assets/628b28ca-4300-4da9-a0c0-711008c8ae68)

### Expected behaviour

These blocks should be waterlogged when placed underwater

### Steps to reproduce

Place a firefly jar underwater

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.4.0

### Forge version

1.20.1

**Comment by iron431** [comment]
added in 3.7.0
