### ISSUE TITLE
[Request] Config option to disable upgrading Scrolls and Ink

### ISSUE THREAD

**Issue by Cephelo** [iron431/Irons-Spells-n-Spellbooks#603]
### Feature description

As the title says: a config option to disable upgrading/improving Scrolls in the Arcane Anvil, and perhaps upgrading/enhancing ink in the Alchemist Cauldron.  Obviously would allow upgrading by default.  An alternate way of doing this would be to make the arcane anvil partially data-driven, but I know that's probably more work than it's worth.

### How it improves the player experience

I know this would essentially undermine a big part of the mod, but it would allow for modpack creators or server admins more freedom to create new ways for scrolls and inks to be upgraded or discovered.  One example would be a modpack creator implementing their own scroll upgrade system using custom ink items or nbt.

It would also be greatly appreciated if this were to be backported to 1.20.1 as well.
Thoughts?  If I find the time I may be able to create a pull request and save you the trouble, though I doubt I'd be as fast as y'all.

**Comment by iron431** [comment]
It is very unlikely something like this would get backported, but if you are interested in making a pull request to 1.21 i would encourage it. It wouldnt be a hugely prioritized task for us and you indeed could do it faster.

**Comment by Cephelo** [comment]
Finally got around to making the pull requests.  Thank you!
1.21.1: #628 
1.20.1: #627
