### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HalvBlood555** [iron431/Irons-Spells-n-Spellbooks#604]
### Observed behaviour

I tried to use a normal as well as an alchemical cauldren to upgrade ink by filling the cauldron with water and then the ink. But the ink item doesn‘t interact with either cauldrons. Even though JEI shows that that is still the way to optain the higher ink.
![image](https://github.com/user-attachments/assets/eac8e211-e317-4212-88d8-a6ff2fe7c910)

### Expected behaviour

I expected the water to get tinted into the colour of the ink and for me to recieve empty glass bottles in return. 4 at maximum in one cauldron.

### Steps to reproduce

1) version 1.20.1
2) forge 47.3.7
3) alchemical cauldren on sand next to water
4) waterbucket into cauldron
5) right click on the hitbox of the cauldron
6) nothing happens

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 3.4.0.2

### Forge version

1.20.1 - 47.3.7.

### Other mods

Iron's Recipe Additions 1.0.0.
JEI 15.20.0.101.

**Comment by iron431** [comment]
that is because the cauldron is full of water, remove it to fit the ink
