### ISSUE TITLE
[Request/Bug] Echoing Strikes spell does not work with "Bullet Damage" from TaCZ

### ISSUE THREAD

**Issue by ACE1337x** [iron431/Irons-Spells-n-Spellbooks#606]
### Feature/Bug description

Echoing Strikes spell does not work with "Bullet Damage" from TaCZ

### How it improves the player experience

The spell works with arrow and melee damage, and would be awesome if it worked with bullet damage as well.

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
