### ISSUE TITLE
Make Fire Ring, Poison Ring & Ice Ring Configurable 

### ISSUE THREAD

**Issue by ZzamZ** [iron431/Irons-Spells-n-Spellbooks#607]
### Feature description

I would love if you could add a config to the fire, poison and ice rings so that they're not as strong as they currently are. This would fix them being so op and allow the other rings to shine more. The effect would work as follows: Once you take damage from that specific source, you're immune for a certain amount of time (configurable). After it then goes on cooldown for a period of time. (also configurable).

### How it improves the player experience

This would give players and mod pack developers (Like myself) the opportunity to configure and balance out the rings more efficiently and power them the way they want. This also give players a bigger reason to maybe look at some of the other not as powerful rings! I've also seen requests for something like this before from others, so allowing this and implementing this would be so greatly appreciated!

**Comment by iron431** [comment]
The rings being too powerful is definitely a sentiment that has been expressed before, but it is just not at the top of our list to look at right now,  especially since it is usually up to the modpack maker to decide what is or isnt balance for their pack, and tune accordingly

**Comment by ZzamZ** [comment]
Yah understandable, just wish there was a way to keep them in instead of using kubejs to just remove them. I think they’re super cool just hopefully in the future there’s more options for them.

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
