### ISSUE TITLE
[Bug] Charge Overlay Does Not Animate Correctly

### ISSUE THREAD

**Issue by IdrisQe** [iron431/Irons-Spells-n-Spellbooks#612]
### Observed behaviour

When affected by Charge, the "Charged Creeper" overlay atop the player does not animate when the player casts spells. It only follows along with Vanilla animations.

See:

https://github.com/user-attachments/assets/d7a7188f-8460-445d-bb93-9b1dde408b1f

This occurs on both servers and singleplayer.

### Expected behaviour

The overlay should animate along with the rest of the player model.

### Steps to reproduce

1. Put Charge on a spellbook
2. Equip spellbook
3. Use Charge
4. Cast another spell

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.2

### Forge version

1.20.1-47.3.0

### Other mods

Caelus API 3.1.0
GeckoLib 4.4.9
PlayerAnimationLib 1.0.2
Curios 5.10.0

**Comment by iron431** [comment]
fixed in 3.8.0
