### ISSUE TITLE
[Bug] Staff Tooltips incorrectly show half cooldown time

### ISSUE THREAD

**Issue by IdrisQe** [iron431/Irons-Spells-n-Spellbooks#613]
### Observed behaviour

Staff Selected Spell Tooltips show the current spell's cooldown as 1/2 of what it actually is. This includes modifications to cooldown from attributes.

See:

https://github.com/user-attachments/assets/75f65e5b-5b99-4fdb-b0a1-f2af074e7663

This applies to both singleplayer and on servers. It was observed in both 3.4.0 and 3.4.0.2.

### Expected behaviour

The tooltip should accurately show spell cooldown.

### Steps to reproduce

1. Equip a spellbook with a spell in it.
2. Grab a staff
3. Look at tooltip

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.2

### Forge version

1.20.1-47.3.0

### Other mods

Caelus API 3.1.0
GeckoLib 4.4.9
PlayerAnimationLib 1.0.2
Curios 5.10.0

**Comment by iron431** [comment]
fixed in 3.8.0
