### ISSUE TITLE
[Bug] Hogskin not dropping

### ISSUE THREAD

**Issue by Renkyu** [iron431/Irons-Spells-n-Spellbooks#615]
### Observed behaviour

Running forge 1.20.1 and have this and butchers delight installed. Hogskin does not drop but hog hide does. 

### Expected behaviour

Expecting to get hogskin from hoglins

### Steps to reproduce

1)Install Butchers delight
2)Install Iron spells and spellbooks
3)Kill/Skin hoglin

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

3.4.0-1.20.1

### Forge version

1.20.1

### Other mods

Butchers Delight 1.20.12.1.0

Error on the Iron spells version that was my mistake.

**Comment by iron431** [comment]
old versions are not supported. try reproducing with updated mods

**Comment by Renkyu** [comment]
I put the wrong version number for irons spells sorry about that. 
![image](https://github.com/user-attachments/assets/53db869f-b6f3-44d3-810b-4a3b674c8723)
I see there is a 3.4.0.2 now so ill try that

**Comment by lab3** [comment]
This is likely an issue with Butcher's Delight as other folks are complaining in their discord that they overwrite loot tables.  We can't see what they are doing because they have not published their source code though

**Comment by Renkyu** [comment]
Thanks for your help. I guess I have no choice but to remove butchers delight until they fix this issue. Which is a shame because I really enjoyed it.

**Comment by iron431** [comment]
> We can't see what they are doing because they have not published their source code though

it is mcreator. they cant see what theyre doing

**Comment by lab3** [comment]
<img width="1305" alt="image" src="https://github.com/user-attachments/assets/9cc0122d-d55c-4e3e-85ee-5bfdc8d6d546">
@Renkyu, looks like they are going to patch the issue
