### ISSUE TITLE
[Bug] Creeper explosions can launch the Healing Circle spell entity

### ISSUE THREAD

**Issue by sweetn3ss** [iron431/Irons-Spells-n-Spellbooks#616]
### Observed behaviour

Upon casting healing circle, a creeper walked up to me and exploded. The healing circle then traveled at about 1-2 blocks per second for its duration.

### Expected behaviour

Presumably the Healing Circle spell should be rooted in place, or at least not be launched by creeper explosions.

### Steps to reproduce

1. Cast Healing Circle
2. Have Creeper explosion occur within the boundaries of the circle.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.2

### Forge version

1.20.1-47.3.0

### Other mods

Over a hundred other mods, none of which interact with creeper explosions.

**Comment by lab3** [comment]
Any explosion would also push the circle.  That will all be resolved when this is released.

**Comment by iron431** [comment]
fixed in 3.8.0/3.4.0.3
