### ISSUE TITLE
[Bug] Server Crash after Bloodstep

### ISSUE THREAD

**Issue by Soeinfloo** [iron431/Irons-Spells-n-Spellbooks#620]
### Observed behaviour

I was in my Monster Farm, i tried  to teleport through alot of Enemies into a 1 Block Hole
![image](https://github.com/user-attachments/assets/d11a8d31-bafd-4b31-a49a-7043c86d1f1c)
![image](https://github.com/user-attachments/assets/14185335-6ae6-403f-b1e8-79b942dcf8b6)

EDIT:
Tried to Chain Lightning the Mobs that where all on 1 Block, Server Crashed with the Same problem:
https://mclo.gs/YKzfHJC

### Expected behaviour
Blood Step:
get ported through or before the hole

Chain Lightning:
Mobs get Killed

### Steps to reproduce

could'nt reproduce

EDIT: 
Could reproduce with Chain Lightning now, Hitting Alot of Enemies at the Same Block Crashes the Server
### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Soeinfloo/3b0dfb148bc8d6686e1066844975a234

### Iron's Spells N Spellbooks version

1.20.1-3.4.0

### Forge version

1.20.1 - 47.3.7

### Other mods

ATM9 - 9-0.3.2

**Comment by Soeinfloo** [comment]
It Seems like this is a Problem for Multiple Spells, The Moment i hit a large Group of Mobs that are on the Same Block the Server Crashes

**Comment by iron431** [comment]
this is already fixed, update the mod
