### ISSUE TITLE
[Bug] Max damage guiding bolt breaks game

### ISSUE THREAD

**Issue by Flaes2** [iron431/Irons-Spells-n-Spellbooks#621]
### Observed behaviour

Upon using guiding bolt with max holy power orbs used, the game crashes when it hits any modded creature, no matter the health. I was able to reopen the modded profile, but upon trying to rejoin the world, the game crashed again. Interestingly, the launcher I used, Curseforge, Did not make any crash reports.

### Expected behaviour

I expected the guiding bolt to hit the modded creature, and hurt or kill it and apply it effect.

### Steps to reproduce

1. Create a modded profile with Iron's Spells 'n Spellbooks and its dependencies on Forge, and/or add other mods.
 
2. create a new single player world.

3. Using only holy upgrade orbs, apply +3 to:
Villager Bible
Artificer's Cane
Priest Mask
Priest Robes
Priest Leggings
Priest Boots

4. Put Guiding Bolt Scroll (Level 10) onto the Villager Bible using an Inscription Table.

5. Use Guiding bolt on any vanilla mob.

6. Use guiding bolt on any modded mob.

7. If game crashes, try to re-open the world.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.7.1

### Forge version

Neoforge - 21.0.167

### Other mods

Adorned (Curios): 9.1.4+1.21.0
Caelus API (Forge/NeoForge): 7.0.2+1.21.1
GeckoLib: 1.21-4.5.8
playerAnimator: 2.0.0-alpha1+1.21

**Comment by iron431** [comment]
attach a crash log
