### ISSUE TITLE
[Bug] my server with irons spells and spellbooks on it won't let me load in even with the mod and dependency's installed

### ISSUE THREAD

**Issue by Streamwhirr** [iron431/Irons-Spells-n-Spellbooks#622]
### Observed behaviour

![image_2024-10-17_210807286](https://github.com/user-attachments/assets/71e31ad3-b7b3-4ddc-9665-d5da8c8c149b)

### Expected behaviour

I expect to be able to join the game

### Steps to reproduce

have all mods installed and attempt to join the server is how this happened for me

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.21.1

### Forge version

1.21.1

**Comment by lab3** [comment]
You posted the MC version not the versions we need.

- What version of Iron's Spells N Spellbooks are you using on the client (full name of the jar file would suffice)?
- What version of Iron's Spells N Spellbooks is on the server (full name of the jar file would suffice)?

If the above 2 items don't match that's your problem.  If they match continue on.

- What version of forge are you using (latest neoforge is: 21.1.71)?
- Run /modlist on the client and the sever and post them
- Post the debug/latest log from the client and server
- Do you have a client mod that is filtering out entities
