### ISSUE TITLE
[Bug][1.21.1] guide book dont work

### ISSUE THREAD

**Issue by CubeTwo** [iron431/Irons-Spells-n-Spellbooks#623]
### Observed behaviour

guide book don't work. after craft gives book that dont work and on tooltip says "no ID defined"

### Expected behaviour

guide book after craft and open shows guide

### Steps to reproduce

craft book and arcane essence

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.7.1

### Forge version

NeoForge: 21.1.69

**Comment by iron431** [comment]
fixed in 3.8.2
