### ISSUE TITLE
[Suggestion] Support for JER and EMI Traders for Alchemist, Pyromancer, Priest 

### ISSUE THREAD

**Issue by ffuentesm** [iron431/Irons-Spells-n-Spellbooks#624]
### Feature description

Just make so that the trades provided by Irons Spellbook show up in the JEI/EMI tab trading menu
![image](https://github.com/user-attachments/assets/970a5515-9b16-4bb0-af77-9c45d864c556)

I know they are not villagers, but they still provide trades to the player. 

### How it improves the player experience

This helps in knowing what those traders provide and also helps in knowing how the villager bible is acquired in-game.

**Comment by iron431** [comment]
closing because feature requests are now exclusively being handled on discord https://discord.gg/TRzEdrndM2
