### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Arch23-tech** [iron431/Irons-Spells-n-Spellbooks#626]
### Feature description

plz Mr. iron431 can you tell me which hotkey or button to press that allows scrolling between different spells that stored in the current spell book UI that  appears in the bottom left corner of the screen
![2024-10-19_15 55 34](https://github.com/user-attachments/assets/d0b7c2a9-0b2c-444f-abb2-fd12912216bb)

### How it improves the player experience

nothing to improve

**Comment by meeprdib** [comment]
R

**Comment by iron431** [comment]
![image](https://github.com/user-attachments/assets/9dc3f497-f0aa-4fbc-979f-90a577c6b78d)

**Comment by Arch23-tech** [comment]
Thanks for you both & a special one to you sir iron431 for helping me out   ...
i didn't mean to cause headaches to you
