### ISSUE TITLE
[Bug] 1.18.2 not compatible with JEI

### ISSUE THREAD

**Issue by astryx-xyrtsa** [iron431/Irons-Spells-n-Spellbooks#63]
### Observed behaviour

On 1.18.2, Jei does not show recipes for the scroll forge or arcane anvil

### Expected behaviour

For the recipes to show when using Jei

### Steps to reproduce

1. Install forge 1.18.2
2. Install Iron's Spells n' Spellbooks for 1.18.2
3. Install JEI for 1.18.2

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.1

### Forge version

1.18.2 - 40.2.9

**Comment by iron431** [comment]
Just launched 1.18.2 and everything is working perfectly. Can you be more specific with what is going  wrong?

**Comment by astryx-xyrtsa** [comment]
None of the recipes for the scroll forge or the arcane anvil are visible in JEI and you can't see any of the recipes for the scrolls. besides that everything seems fine.

**Comment by iron431** [comment]
What other mods are you using? All recipes are visible as far as I can see

**Comment by astryx-xyrtsa** [comment]
just this mod, JEI and any dependencies

**Comment by iron431** [comment]
This is what I see. You're saying there is an issue?
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/34083081/dbb83ea0-238b-4f96-950a-004119ae4f89)

**Comment by astryx-xyrtsa** [comment]
On 1.19.2 it works fine but on 1.18.2 none of these recipes are visible through JEI. Are you sure you're testing this on 1.18.2 and not 1.19.2

**Comment by iron431** [comment]
this is 1.18.2. can you send a screenshot?

**Comment by astryx-xyrtsa** [comment]
not really much I can take a screenshot of, there just aren't any modded recipes visible in JEI. Are you using the same mod version from curseforge?

**Comment by iron431** [comment]
yes. are you sure you are using jei?

**Comment by astryx-xyrtsa** [comment]
Update: just tried it with the newest update and the latest beta release of JEI and it seems to be working now
