### ISSUE TITLE
[Bug] v1.21-3.8.0 crashes

### ISSUE THREAD

**Issue by darock830** [iron431/Irons-Spells-n-Spellbooks#630]
### Observed behaviour

server fails to load, and client fails to load. Everything works fine when I revert the mod version back to 3.7.1

### Expected behaviour

Expected the newest release to work

### Steps to reproduce

1. Install the latest iron spell mod version.
2. crash

### Server Type

Dedicated Server

### Crashlog

CRASHLOG FOR CLIENT: https://pastebin.com/g4UF2jDJ  ////////  CRASHLOG FOR SERVER: https://pastebin.com/P41kyRDv

### Iron's Spells N Spellbooks version

v1.21-3.8.0

### Forge version

1.21.1

**Comment by iron431** [comment]
ive fixed the dedicated server issue. i cannot reproduce the client issue. if it persists after 3.8.1, please make a separate issue for it
