### ISSUE TITLE
[Bug] new update crashes the game on launch

### ISSUE THREAD

**Issue by ffuentesm** [iron431/Irons-Spells-n-Spellbooks#631]
### Observed behaviour

Game crashes on launch

### Expected behaviour

the game should launch and not crash

### Steps to reproduce

launch the new update on Neoforge

### Server Type

Single Player

### Crashlog

https://pastebin.com/zR1QDmQm

### Iron's Spells N Spellbooks version

[3.8.0] (1.21) 2024-10-21

### Forge version

21.1.72

**Comment by iron431** [comment]
try in 3.8.1

**Comment by ffuentesm** [comment]
The 3.8,1 Still Crashes on launch.
Crash: https://pastebin.com/jTbvTZ00

**Comment by iron431** [comment]
this looks like an AlltheCompatibility issue. try launching without it

**Comment by ffuentesm** [comment]
It is not, I have seen this type of issue before. 
It's a cascading effect up in the stream, but the output error comes off as AlltheCompatibility. 

Removing AlltheCompatibility, gives an error on Toolbelt, then Crafttweaker, then Twilight forests.

You can see it here: https://github.com/wisp-forest/accessories/issues/126

In the current error, I have tried removing Json Things thinking it was the same mod compact problem but no. It seems to be a different mod compat with Irons. 
I think there is something to dod with owo, like before, feel that is causing some compat issue in some level.

**Comment by iron431** [comment]
and it does not happen when only iss is downgraded to 3.7.1?

**Comment by iron431** [comment]
due to the hidden nature, its not clear what is causing this. however, i have published a snapshot that might fix the issue if you want to try it @ffuentesm https://code.redspace.io/snapshots/io/redspace/irons_spellbooks/1.21-3.8-SNAPSHOT/irons_spellbooks-1.21-3.8-20241022.161943-3.jar
otherwise, i cannot reproduce this on my own

**Comment by ffuentesm** [comment]
> and it does not happen when only iss is downgraded to 3.7.1?

Yep, with ISS on 3.7.1 I can play it normally. 
The snapshot does not work, sorry. Get the same error. 

As I disable mods one by one, this is the crash that I get stuck on. 
https://pastebin.com/Qb1KVNvx

there is some owo library component causing the crash, and I do not have the owo lib mod installed, so is a mod using it.

**Comment by iron431** [comment]
accessories uses owo lib

**Comment by iron431** [comment]
@ffuentesm are you still able to reproduce this with the latest versions and with/without accessories?

**Comment by ffuentesm** [comment]
Yes, when I first tested I replaced accessories for Adorned. And it still did not launch. 
I will try a binary search to see if I can find the problematic mod.

**Comment by ffuentesm** [comment]
No idea what happened, it's just working now. 
Haven't deleted anything.
