### ISSUE TITLE
[Bug] [1.20.1] Interacting with a Priest Villager crash the game

### ISSUE THREAD

**Issue by Urias0** [iron431/Irons-Spells-n-Spellbooks#634]
### Observed behaviour

I was gonna check his trade and the game froze instantly before opening the trade menu and crashed

### Expected behaviour

Trading as normal (did it in the past some month ago , worked fine)

### Steps to reproduce

Locate a priest villager from the mod and interact with it (right click)

### Server Type

Single Player

### Crashlog

https://gist.github.com/Urias0/701cee974b9c5ccf6304443215f4b893

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.4.0.3

### Forge version

47.2.20 (I updated to 47.3.0 , Same result)

### Other mods

(All the mods should be in the crash report that i added in the gist)

**Comment by Urias0** [comment]
Oh and  i have the same issue as the one you just mentioned this in , trying to trade with a pyromancer also freeze and crash , if you have any question or want me to do some testing don't hesitate , i genuinely love this mod and i'll help if i can

**Comment by sherpascott** [comment]
I'm having the same issue. Also on 1.20.1

**Comment by SiverDX** [comment]
Can you post the entire `latest.log`?

**Comment by Buckskinseven1** [comment]
I can I am having the same issue with the pyromancer
[crash-2024-10-23_12.17.45-server.txt](https://github.com/user-attachments/files/17495264/crash-2024-10-23_12.17.45-server.txt)
[latest.log](https://github.com/user-attachments/files/17495290/latest.log)
Reading the log it seems to be a issue with the restock function see here:
Receiver class io.redspace.ironsspellbooks.entity.mobs.wizards.pyromancer.PyromancerEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.world.level.Level level()' of interface io.redspace.ironsspellbooks.entity.mobs.wizards.IMerchantWizard.

**Comment by iron431** [comment]
fixed in 3.4.0.4
