### ISSUE TITLE
Make new spellbooks for some schools

### ISSUE THREAD

**Issue by Spider2200** [iron431/Irons-Spells-n-Spellbooks#635]
### Feature description

Add an ice book that has a recipie using permafrost shard, make the necromonion add extra blood power and remove locked spells, make a lightning book a rare drop from charged creepers

### How it improves the player experience

It's uncomfortable to look at the dragonskin spellbook(extra power to ender) next to the druidic tome(extra power to nature) and the others(blaze i.m. fire, villager b. Holy, grimoire of e. Evocation) without the books for blood, ice and lightning.

**Comment by Spider2200** [comment]
Plus, don't make one for eldrich because it is already op

**Comment by CubeTwo** [comment]
> ### Feature description
> 
> Add an ice book that has a recipie using permafrost shard, make the necromonion add extra blood power and remove locked spells, make a lightning book a rare drop from charged creepers
> ### How it improves the player experience
> 
> It's uncomfortable to look at the dragonskin spellbook(extra power to ender) next to the druidic tome(extra power to nature) and the others(blaze i.m. fire, villager b. Holy, grimoire of e. Evocation) without the books for blood, ice and lightning.

Yes, it will be good to have  books for blood, ice and lightning.

**Comment by iron431** [comment]
new content is always planned, there is no need to open an issue for it
