### ISSUE TITLE
API for creating new schools

### ISSUE THREAD

**Issue by ben132** [iron431/Irons-Spells-n-Spellbooks#636]
### Feature description

This may already be possible for the ability to create additional Magic Schools.  I know that new schools are planned but if someone could create an addon for Botania, and add Flower style magic, and Thaumcraft or even other types of schools that relate to Tech based mods, a tech based magic could be to have a Fuel conjuration spell that create the equivalent fuel to cook 1/2/4/8 etc.

### How it improves the player experience

Simply that it would allow for new powers that link to specific mods, or modpacks.

**Comment by Spider2200** [comment]
I'm not really keen on having to install more mods because I want as least as possible

**Comment by Spider2200** [comment]
No offense

**Comment by iron431** [comment]
there already is, and there are already addons that add schools for mods such as cataclysm https://iron.wiki/developers/
