### ISSUE TITLE
[Bug] Crash on atm9 startup

### ISSUE THREAD

**Issue by 893203** [iron431/Irons-Spells-n-Spellbooks#639]
### Observed behaviour

launch pack as normal, tried fresh install, tried graphics driver updates, computer restart. I know this should be working as the server i am trying to join, to my knowledge, does not have this problem. 

### Expected behaviour

it should just work and not crash before the pack launches

### Steps to reproduce

1. launch the pack on its most current version:
atm9-0.3.2

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/893203/412917c06ceadb42014ebe3edf3bad3b

### Iron's Spells N Spellbooks version

1.20.1-3.4.0

### Forge version

47.3.7

### Other mods

there are a lot of other mods, around 400 in the modpack.

**Comment by iron431** [comment]
this is caused by pufferfish_unofficial_additions, not spellbooks

**Comment by 893203** [comment]
thanks
