### ISSUE TITLE
[Bug] Ruined Booked not accessible in 1.18.2

### ISSUE THREAD

**Issue by Kasualix** [iron431/Irons-Spells-n-Spellbooks#64]
### Observed behaviour

My friend failed to find Ruined Book in 1.18.2 because Ancient City doesn't exist in 1.18.2.

[related data](https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.18.2/src/main/resources/data/irons_spellbooks/loot_modifiers/chest_loot/ancient_city_modifier.json)

I'm just a helper submitting issue, and I don't play 1.18.2 at all.

### Expected behaviour

Use another impl, such as ocean monument.

### Steps to reproduce

N/A

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.1

### Forge version

40.2.9

**Comment by Kasualix** [comment]
related data: https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.18.2/src/main/resources/data/irons_spellbooks/loot_modifiers/chest_loot/ancient_city_modifier.json

**Comment by zinerith** [comment]
Nor are the Void spellscrolls craftable since Echo Shards don't exist in 1.18

**Comment by iron431** [comment]
the void spells were merged into ender for this reason. they should be craftable with ender pearls

**Comment by zinerith** [comment]
Ok, I see that is the case, by bad. I was just going by the wiki and creative menu, didn't think to check that. 
Still, without the ruined book being obtainable in 1.18, it means there is no way to craft a legendary spellbook anyway.

**Comment by iron431** [comment]
fixed in v1.1.4.2
