### ISSUE TITLE
[Bug] Shriving Stone used on Necronomicon removes all spell slots.

### ISSUE THREAD

**Issue by Subw00fer** [iron431/Irons-Spells-n-Spellbooks#640]
### Observed behaviour

Use of the Shriving Stone to remove the mid-tier blood spells removes all spell slots from the Necronomicon.

### Expected behaviour

Expected behavior is to use the Shriving Stone to remove the mid-tier blood spells and upgrades, not the base spell slots.

### Steps to reproduce

1. Obtain Shriving Stone and Necronomicon.
2. Place Necronomicon in the left slot of an Anvil.
3. Place Shriving Stone in right slot of same Anvil.
4. Retrieve resulting Necronomicon.
5. Open resulting Necronomicon in an Inscription Table and note loss of **_all_** spell slots.

### Server Type

Single Player

### Crashlog

No crash.

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.2

### Forge version

1.20.1 - 47.3.0

### Other mods

Caelus API (Forge/NeoForge): caelus-forge-3.2.0+1.20.1.jar
Curios API (Forge/NeoForge): curios-forge-5.10.0+1.20.1.jar
GeckoLib: geckolib-forge-1.20.1-4.4.9.jar
playerAnimator: player-animation-lib-forge-1.0.2-rc1+1.20.jar

**Comment by iron431** [comment]
i dont think you are actually using that version of the mod, double check it
![image](https://github.com/user-attachments/assets/b069c2c6-56f3-4728-bdd5-8f7a89c210b3)

**Comment by Subw00fer** [comment]
![2024-10-22_19 37 13](https://github.com/user-attachments/assets/d8360c27-e895-46b7-9e52-c01cf023c361)
![2024-10-22_19 37 27](https://github.com/user-attachments/assets/001dca75-152a-4f8d-a038-3edd75b9959d)
![2024-10-22_19 37 33](https://github.com/user-attachments/assets/d1bae3a1-0217-4d8e-9121-862c83fa773f)
> i dont think you are actually using that version of the mod, double check it ![image](https://private-user-images.githubusercontent.com/34083081/379046209-b069c2c6-56f3-4728-bdd5-8f7a89c210b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2Mzk1MjcsIm5iZiI6MTcyOTYzOTIyNywicGF0aCI6Ii8zNDA4MzA4MS8zNzkwNDYyMDktYjA2OWMyYzYtNTZmMy00NzI4LWJkZDUtOGY3YTg5YzIxMGIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDIzMjAyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OTM3N2Q2ODY3ZjdjZWNkODVkMDczYzEzOTk5MzE3MDJkYmRjNTUzZWY4MDAzM2FjMjFhNWI2YTNiOThlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jDHiv6AD7PoiJhT0uKbdtc9u0oBtd34UDI8A5nfEG6s)

Regular anvil, not arcane.

**Comment by iron431** [comment]
fixed in 3.4.0.4
