### ISSUE TITLE
[Bug] Shield spell bugged with Better Combat mod

### ISSUE THREAD

**Issue by TietAsnee** [iron431/Irons-Spells-n-Spellbooks#642]
### Observed behaviour

When Shield from the [Shield spell] is casted and broken using melee attacks from the Better Combat mod, the area where the spell was casted becomes impassable until the "total duration" of the spell runs out.

### Expected behaviour

I expected the melee attack to break the casted Shield and for me to pass through the casted area

### Steps to reproduce

1. Cast Shield spell (Use lvl 1 as it breaks the easiest)
2. Melee with any sword until the construct breaks
3. [Issue] Try to walk past the area where it was casted, the player will be blocked and unable to walk through

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1 - 3.4.0.4

### Forge version

1.20.1 - 47.3.5

### Other mods

Better Combat - Forge - 1.8.6+1.20.1

**Comment by iron431** [comment]
fixed in 3.8.6
