### ISSUE TITLE
[Bug] [1.21.1] v.3.8.2 guide book dont work

### ISSUE THREAD

**Issue by CubeTwo** [iron431/Irons-Spells-n-Spellbooks#644]
### Observed behaviour

guide book don't work. after craft gives book that dont work and on tooltip says "no ID defined"

### Expected behaviour

guide book after craft and open shows guide

### Steps to reproduce

craft book and arcane essence
![2024-10-26_00 35 27](https://github.com/user-attachments/assets/e384d5d5-fa31-4f65-9e59-115ca44328dd)
![2024-10-26_00 36 18](https://github.com/user-attachments/assets/814271c0-4ba0-48a3-aef6-29f1f631dc40)

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.8.2

### Forge version

NeoForge: 21.1.72

**Comment by iron431** [comment]
fixed in 3.8.3
