### ISSUE TITLE
[Bug] [1.21.1]v3.8.2 max mana value always say 100

### ISSUE THREAD

**Issue by CubeTwo** [iron431/Irons-Spells-n-Spellbooks#645]
### Observed behaviour

 max mana value always say 100 even after you get items for mana boost
![2024-10-26_00 45 01](https://github.com/user-attachments/assets/3644239c-3f70-466a-ae4b-3512c2fbd83a)

### Expected behaviour

 max mana value displays max mana pool

### Steps to reproduce

equip mana boost items

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.8.2

### Forge version

NeoForge: 21.1.72

**Comment by iron431** [comment]
what other mods are you using

**Comment by CubeTwo** [comment]
https://gist.github.com/CubeTwo/ae643540a9106a8a7a09766937cab35a

**Comment by iron431** [comment]
i cannot reproduce this. your current mana seems accurate. is this a visual bug for max mana only?

**Comment by CubeTwo** [comment]
yep, for max mana,  current mana numeral value displays correct, but mana bar and max mana numeral value stays frozen all time, after i spent mana below 100 its start move mana in mana bar.
here clip of what i tell https://www.twitch.tv/cube_two/clip/FunnyBlindingMilkFrankerZ-nYpLedhwZ7DMAydh

**Comment by iron431** [comment]
it seems like a mod you have installed is changing how the client reads attributes. does this ring any bells? i dont recognize any red flags after reading your modlist

**Comment by CubeTwo** [comment]
O_O im find its lithium-neoforge-0.14.0-snapshot+mc1.21.1-build.88.jar  strange, im find its on random, lithium have random crashes and im deleted it  and its fixed now mana bar
