### ISSUE TITLE
[Bug] [1.21.1] v3.8.2 Trial gives no loot

### ISSUE THREAD

**Issue by CubeTwo** [iron431/Irons-Spells-n-Spellbooks#646]
### Observed behaviour

Trial gives no loot after defeating all mobs.
Clip: https://www.twitch.tv/cube_two/clip/HappyUninterestedAubergineSaltBae-BnBpJf4rf-WqenXb
f3 screenshot: 
![2024-10-27_15 39 26](https://github.com/user-attachments/assets/6bd9ab57-8409-428e-8aac-df3303c7c50f)

### Expected behaviour

Trial gives loot after defeating all mobs.

### Steps to reproduce

1.start trial
2.defeat mobs
3.Spawner gives no loot

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.8.2

### Forge version

NeoForge: 21.1.72

**Comment by iron431** [comment]
this is intended, the reward is an infinite supply of knights
