### ISSUE TITLE
[Bug] crash when listening to sounds of the black skeleton boss?

### ISSUE THREAD

**Issue by VaporeonScripts** [iron431/Irons-Spells-n-Spellbooks#647]
### Observed behaviour

https://mclo.gs/5HDqpt5

### Expected behaviour

to not crash

### Steps to reproduce

add the mod,
play it

### Server Type

Dedicated Server

### Crashlog

https://mclo.gs/5HDqpt5

### Iron's Spells N Spellbooks version

latest

### Forge version

.73

### Other mods

alot
https://mclo.gs/5HDqpt5

**Comment by VaporeonScripts** [comment]
the dead king is the boss name, also may i know whats the music string name? its annoying

**Comment by iron431** [comment]
this is an issue with explosiveenhancement particles, has nothing to do with dead king or sound effects

**Comment by VaporeonScripts** [comment]
Oh,ty so much
