### ISSUE TITLE
[Bug] Unable to save world with portal frames present

### ISSUE THREAD

**Issue by TheAoW** [iron431/Irons-Spells-n-Spellbooks#648]
### Observed behaviour

I'm unable to save my world when I have my portal frames setup. Its hangs for ever. When trying to replicate it on a server it throws an error after an hour or so of waiting for it to save.

[27okt2024 14:29:45.679] [Server thread/ERROR] [net.minecraft.world.level.chunk.LevelChunk/]: A BlockEntity type io.redspace.ironsspellbooks.block.portal_frame.PortalFrameBlockEntity has thrown an exception trying to write state. It will not persist, Report this to the mod author
net.minecraft.ReportedException: Exception loading chunk

### Expected behaviour

Save world

### Steps to reproduce

Place portals in world including in different dimensions
world refuses to save.

### Server Type

Single Player

### Crashlog

https://gist.github.com/TheAoW/3d61192f916559f3fbd74cebfde2ee04

### Iron's Spells N Spellbooks version

1.21-3.8.2

### Forge version

21.1.72

### Other mods

ATM10 modpack

**Comment by iron431** [comment]
can you consistently recreate this bug?

**Comment by TheAoW** [comment]
Yeah, If i remove the portals my game saves fine and when I put them back i get the same issue.

**Comment by iron431** [comment]
can you try with this build of the mod (direct maven download link): https://code.redspace.io/snapshots/io/redspace/irons_spellbooks/1.21-3.8-SNAPSHOT/irons_spellbooks-1.21-3.8-20241028.142705-4.jar

**Comment by TheAoW** [comment]
Yeah seems to work fine with this one

**Comment by iron431** [comment]
fixed in 3.8.3
