### ISSUE TITLE
[Bug] [1.21.1] Mixin Crash due to Lecterns

### ISSUE THREAD

**Issue by Cyranos** [iron431/Irons-Spells-n-Spellbooks#649]
### Observed behaviour

Updated from version 3.5.0 to 3.8.0 and I got a crash while loading the game

### Expected behaviour

I hope it doesn't come across crass, though not crash on loading

### Steps to reproduce

Use the latest version.

### Server Type

Single Player

### Crashlog

https://mclo.gs/pWDeaEq

### Iron's Spells N Spellbooks version

1.21-3.8.0

### Forge version

Neoforge 21.1.68

### Other mods

A Good Place || Version: [1.21-1.2.4] by MehVahdJukaar, Enjarai || URL: (https://modrinth.com/mod/BwPeriwJ)
AE2 Import Export Card || Version: [1.21-1.4.0] by Ultramega || URL: (https://www.curseforge.com/projects/982512)
AE2 JEI Integration || Version: [1.2.0] by Tamaized, mezz || URL: (https://www.curseforge.com/projects/1074338)
AE2 QoL Recipes || Version: [1.2.0] by Christofmeg, Lafen99 || URL: (https://www.curseforge.com/projects/907026)
AE2 Things || Version: [1.4.2-beta
] by ProjectET, Technici4n || URL: (https://www.curseforge.com/projects/609977)
AE2:Crafting Tree || Version: [1.21.1-1.0.3-beta] by Neuvillette || URL: (https://www.curseforge.com/projects/1086241)
AE2WTLib || Version: [19.1.6-beta] by mari_023, Ridanisaurus || URL: (https://www.curseforge.com/projects/459929)
Accessories || Version: [1.1.0-beta.16+1.21.1] by Blodhgarm, chyzman, Dr.Zeal || URL: (https://modrinth.com/mod/jtmvUHXj)
ActuallyHarvest || Version: [1.1.1.1] by wendall911 || URL: (https://modrinth.com/mod/sUbuUC7R)
Additional Lights || Version: [2.1.9] by mgen256 || URL: (https://www.curseforge.com/projects/384991)
Advanced AE || Version: [1.0.6-1.21.1] by Pedroksl || URL: (https://modrinth.com/mod/rxYaglEe)
All Arrows Infinity Fix || Version: [1.7] by Jackbusters || URL: (https://modrinth.com/mod/M4qHqBBo)
Alternate Current || Version: [1.9.0] by Space   Walker || URL: (https://modrinth.com/mod/r0v8vy1s)
Amendments || Version: [1.21-1.2.19] by MehVahdJukaar, Plantkillable || URL: (https://www.curseforge.com/projects/896746)
Apothic Attributes || Version: [2.4.0] by Shadows_of_Fire || URL: (https://www.curseforge.com/projects/898963)
Apothic Enchanting || Version: [1.2.3] by Shadows_of_Fire || URL: (https://www.curseforge.com/projects/1063926)
Apothic Spawners || Version: [1.1.1] by Shadows_of_Fire || URL: (https://www.curseforge.com/projects/986583)
Applied Energistics 2 || Version: [19.0.23-beta] by TeamAppliedEnergistics || URL: (https://www.curseforge.com/projects/223794)
Architectury || Version: [13.0.6] by shedaniel || URL: (https://modrinth.com/mod/lhGA9TYQ)
Ars Additions || Version: [1.21.1-21.1.2] by Jarva || URL: (https://www.curseforge.com/projects/974408)
Ars Elemental || Version: [0.7.0.8
] by Alexthw || URL: (https://www.curseforge.com/projects/561470)
Ars Nouveau || Version: [5.2.2
] by Bailey Hollingsworth || URL: (https://www.curseforge.com/projects/401955)
Artifacts || Version: [12.0.5] by ochotonida || URL: (https://www.curseforge.com/projects/312353)
Athena || Version: [4.0.1] by ThatGravyBoat || URL: (https://modrinth.com/mod/b1ZV3DIJ)
Automaticons || Version: [1.8] by  || URL: (https://modrinth.com/mod/JAWG0K7l)
Bad Packets || Version: [0.8.1] by deirn || URL: (https://www.curseforge.com/projects/615134)
BadOptimizations || Version: [2.2.0] by Thosea || URL: (https://modrinth.com/mod/g96Z4WVZ)
Balanced Crates || Version: [1.8.1.1.21.1] by Licit Lettuce || URL: (https://modrinth.com/mod/jL77Iazm)
Balm || Version: [21.0.20] by BlayTheNinth || URL: (https://modrinth.com/mod/MBAkmtvl)
Baubley Heart Canisters || Version: [1.21.1-1.1.2] by Traverse_Joe || URL: (https://modrinth.com/mod/fPdy2fCM)
Better Beacon Placement || Version: [3.4] by Rick South || URL: (https://modrinth.com/mod/GOKA9KZY)
Better Climbing || Version: [4] by artemis || URL: (https://www.curseforge.com/projects/655619)
Better Combat || Version: [2.0.3+1.21.1] by Daedelus || URL: (https://modrinth.com/mod/5sy6g3kz)
Better Conduit Placement || Version: [3.3] by Rick South || URL: (https://modrinth.com/mod/lRF5nzIz)
BetterF3 || Version: [11.0.2] by TreyRuffy and cominixo || URL: (https://modrinth.com/mod/8shC1gFX)
Building Gadgets 2 || Version: [1.3.7] by Direwolf20 || URL: (https://www.curseforge.com/projects/298187)
Caelus API || Version: [7.0.1+1.21.1] by Illusive Soulworks || URL: (https://modrinth.com/mod/40FYwb4z)
Carry On || Version: [2.2.2] by Tschipp, PurpliciousCow || URL: (https://modrinth.com/mod/joEfVgkn)
Chalk || Version: [NONE] by mortuusars || URL: (https://www.curseforge.com/projects/533748)
Charging Gadgets || Version: [1.14.1] by Direwolf20, ErrorMikey || URL: (https://www.curseforge.com/projects/399757)
ChickensShed || Version: [1.6.1+mc1.21] by holmraven || URL: (https://modrinth.com/mod/cRJuLZ2D)
Chipped || Version: [4.0.2] by Alex Nijjar, Grimbop, Kekie6, ThatGravyBoat || URL: (https://modrinth.com/mod/BAscRYKm)
ClickThrough Plus || Version: [3.0+1.21] by cassiancc || URL: (https://modrinth.com/mod/fJi8nm80)
ClientSort || Version: [1.0.0] by NotRyken || URL: (https://modrinth.com/mod/K0AkAin6)
Cloth Config v15 API || Version: [15.0.140] by shedaniel || URL: (https://modrinth.com/mod/9s6osm5g)
Clumps || Version: [19.0.0.1] by Jared || URL: (https://modrinth.com/mod/Wnxd13zP)
Collective || Version: [7.84] by Rick South || URL: (https://modrinth.com/mod/e0M1UDsY)
Common Networking || Version: [1.0.16-1.21.1
] by Mysticdrew || URL: (https://modrinth.com/mod/HIuqnQpi)
Connected Glass || Version: [1.1.12] by SuperMartijn642 || URL: (https://modrinth.com/mod/DghO0R02)
Controlling || Version: [19.0.3] by Jaredlll08 || URL: (https://modrinth.com/mod/xv94TkTM)
CosmeticArmorReworked || Version: [1.21.1-v1-neoforge] by zlainsama || URL: (https://www.curseforge.com/projects/237307)
Crafting Tweaks || Version: [21.1.2] by BlayTheNinth || URL: (https://modrinth.com/mod/DMu0oBKf)
CreativeCore || Version: [2.12.17] by CreativeMD || URL: (https://modrinth.com/mod/OsZiaDHq)
Cristel Lib || Version: [1.2.8] by Cristelknight || URL: (https://www.curseforge.com/projects/856996)
Cucumber Library || Version: [8.0.6] by BlakeBr0 || URL: (https://modrinth.com/mod/Rw1NrDzF)
Cupboard mod || Version: [2.8] by Someaddon || URL: (https://www.curseforge.com/projects/326652)
Curios Compat Layer for Accessories || Version: [9.0.12+1.21.1] by  || URL: (https://modrinth.com/mod/izkDUlrJ)
Deeper and Darker || Version: [1.3.2] by Kyanite Team || URL: (https://www.curseforge.com/projects/659011)
DimStorage || Version: [9.0.2] by Edivad99 || URL: (https://www.curseforge.com/projects/353882)
Dis-Enchanting Table || Version: [3.0.1] by Lupin, Jason13 || URL: (https://modrinth.com/mod/9BgYgXE4)
Divine Farmland || Version: [1.21-1.1.0] by Sora Setsuna || URL: (https://modrinth.com/mod/rZOfebzE)
Dungeons and Taverns || Version: [1-v4.4.4] by NovaWostra, Konci, Walls || URL: (https://modrinth.com/mod/tpehi7ww)
Dungeons and Taverns Ancient City Overhaul || Version: [1-v2] by NovaWostra, Konci, Walls || URL: (https://www.curseforge.com/projects/920418)
Dynamic Lights || Version: [5.0] by o-Peepo || URL: (https://modrinth.com/mod/AK1n0IqM)
EMI || Version: [1.1.16+1.21.1+neoforge] by Emi || URL: (https://modrinth.com/mod/fRiHVvU7)
EMI Enchanting || Version: [0.1.2+1.21+neoforge] by fzzyhmstrs || URL: (https://modrinth.com/mod/wbWoo11W)
EMI Loot || Version: [0.7.4+1.21+neoforge] by fzzyhmstrs, lxly9 (art), unilock (ports) || URL: (https://modrinth.com/mod/qbbO7Jns)
EMI Ores || Version: [1.0+1.21.1+neoforge] by Abbie || URL: (https://modrinth.com/mod/sG4TqDb8)
EMI Professions (EMIP) || Version: [1.0.2
] by Mrbysco, ShyNieke || URL: (https://modrinth.com/mod/LGVihYcz)
Easy Piglins || Version: [1.21.1-1.0.13] by Max Henkel || URL: (https://modrinth.com/mod/l6n94pax)
Easy Villagers || Version: [1.21.1-1.1.23] by Max Henkel || URL: (https://modrinth.com/mod/Kaov2qgi)
EdivadLib || Version: [3.0.0] by Edivad99 || URL: (https://www.curseforge.com/projects/638508)
Enchantment Level Language Patch || Version: [2.2.8] by teddyxlandlee || URL: (https://modrinth.com/mod/Lf4kDKU9)
EnchantmentMachine || Version: [1.1.5-beta.1] by Cheaterpaul, maxanier || URL: (https://modrinth.com/mod/oNqn5GfR)
Ender IO || Version: [7.0.8-alpha] by CrazyPants, tterrag, HenryLoenwind, MatthiasM, CyanideX, EpicSquid, Rover656, HypherionSA, agnor99, Ferri_Arnus, mystchonky || URL: (https://modrinth.com/mod/49ZofO4f)
Entangled || Version: [1.3.19+a] by SuperMartijn642 || URL: (https://www.curseforge.com/projects/301034)
EntityCulling || Version: [1.7.0] by tr7zw || URL: (https://modrinth.com/mod/NNAgCjsB)
Euphoria Patcher || Version: [0.3.4-neoforge] by isuewo || URL: (https://www.curseforge.com/projects/915902)
Expanded Storage || Version: [14.1.5] by Quinn Semele || URL: (https://modrinth.com/mod/jCCPlP3c)
Explorer's Compass || Version: [1.21.1-3.0.3-neoforge] by ChaosTheDude || URL: (https://www.curseforge.com/projects/491794)
ExtendedAE || Version: [1.21-2.1.1-neoforge] by GlodBlock || URL: (https://www.curseforge.com/projects/892005)
Extreme Reactors || Version: [1.21.1-2.4.9] by ZeroNoRyouki || URL: (https://modrinth.com/mod/idkvShUy)
Extreme Sound Muffler || Version: [3.48.2] by LeoBeliik || URL: (https://modrinth.com/mod/5IIKsxiL)
FTB Chunks || Version: [2101.1.1] by FTB Team || URL: (https://www.curseforge.com/projects/314906)
FTB Library || Version: [2101.1.4] by FTB Team || URL: (https://www.curseforge.com/projects/404465)
FTB Teams || Version: [2101.1.0] by FTB Team || URL: (https://www.curseforge.com/projects/404468)
FTB Ultimine || Version: [2101.1.1] by FTB Team || URL: (https://www.curseforge.com/projects/386134)
FancyBlockParticles || Version: [21.1.1.2] by Hantonik, TominoCZ || URL: (https://modrinth.com/mod/S2guHrs2)
Farmer's Delight || Version: [1.2.4a] by vectorwing || URL: (https://modrinth.com/mod/R2OftAxM)
Farming for Blockheads || Version: [21.1.2] by BlayTheNinth || URL: (https://modrinth.com/mod/4WJZr8JU)
Fast Developing Bonus Chest || Version: [1.0.1] by Cusagine || URL: (https://modrinth.com/mod/tVgKG65B)
Ferrite Core || Version: [7.0.1] by malte0811 || URL: (https://modrinth.com/mod/uXXizFIs)
Fishermens Trap || Version: [3.0.2] by Uraneptus || URL: (https://www.curseforge.com/projects/883029)
Fixed Anvil Repair Cost || Version: [3.4] by Rick South || URL: (https://www.curseforge.com/projects/390913)
Flat Bedrock || Version: [87.0.0] by  || URL: (https://www.curseforge.com/projects/398623)
Followers Teleport Too || Version: [2.6] by Rick South || URL: (https://modrinth.com/mod/E5YVNsbH)
ForceCraft || Version: [6.0.6
] by Mrbysco || URL: (https://www.curseforge.com/projects/454802)
Forge Config API Port || Version: [21.1.1] by Fuzs || URL: (https://modrinth.com/mod/ohNO6lps)
FramedBlocks || Version: [10.2.0] by XFactHD || URL: (https://www.curseforge.com/projects/441647)
Functional Storage || Version: [1.21.1-1.3.4
] by Buuz135, Rid || URL: (https://modrinth.com/mod/cO40ZIg3)
Fusion || Version: [1.1.1+a] by SuperMartijn642 || URL: (https://modrinth.com/mod/p19vrgc2)
Fzzy Config || Version: [0.5.6+1.21+neoforge] by fzzyhmstrs || URL: (https://modrinth.com/mod/hYykXjDp)
GeckoLib 4 || Version: [4.6.6] by Gecko, Eliot, AzureDoom, DerToaster, Tslat, Witixin || URL: (https://www.curseforge.com/projects/388172)
Global Packs || Version: [21.0.1] by JTK222 || URL: (https://www.curseforge.com/projects/317134)
Glodium || Version: [1.21-2.2-neoforge] by GlodBlock || URL: (https://www.curseforge.com/projects/957920)
Grimoire of Gaia 4 || Version: [6.0.0-alpha.7
] by Silentine, Mrbysco || URL: (https://www.curseforge.com/projects/228948)
Haunt Furnace || Version: [0.3.3] by jshipley || URL: (https://modrinth.com/mod/G05u0Ety)
Heads || Version: [2.1.0
] by Mrbysco || URL: (https://modrinth.com/mod/q81yaQZO)
Hostile Neural Networks || Version: [6.1.0] by Shadows_of_Fire || URL: (https://www.curseforge.com/projects/552574)
Icarus || Version: [4.1.0] by Cammie, Up || URL: (https://www.curseforge.com/projects/428151)
ImmediatelyFast || Version: [1.3.0+1.21.1] by RK_01 || URL: (https://modrinth.com/mod/5ZwdcRci)
Immersive Lanterns || Version: [1.0.2] by Toni || URL: (https://www.curseforge.com/projects/1116812)
Industrial Foregoing || Version: [1.21-3.6.15] by Buuz135 || URL: (https://modrinth.com/mod/lWxpUd04)
Infinite Trading || Version: [4.5] by Rick South || URL: (https://modrinth.com/mod/U3eoZT3o)
Iris || Version: [1.8.0-beta.5+mc1.21.1] by coderbot, IMS212 || URL: (https://modrinth.com/mod/YL57xq9U)
Iron Furnaces || Version: [4.2.6] by Qelifern (pizzaatime), XenoMustache || URL: (https://modrinth.com/mod/yPlaLxD1)
Iron Jetpacks || Version: [8.0.4] by BlakeBr0 || URL: (https://modrinth.com/mod/DWIEOniQ)
Iron's Spells 'n Spellbooks || Version: [1.21-3.5.0] by Iron431, Lab3 || URL: (https://modrinth.com/mod/s4OWxYQQ)
Item Collectors || Version: [1.1.10] by SuperMartijn642 || URL: (https://www.curseforge.com/projects/395620)
Jade || Version: [15.8.2+neoforge
] by Snownee || URL: (https://modrinth.com/mod/nvQzSEkH)
JourneyMap Integration || Version: [1.21.1-1.6
] by frankV || URL: (https://modrinth.com/mod/M1ZKbfkJ)
Journeymap || Version: [1.21.1-6.0.0-beta.28] by Techbrew, Mysticdrew || URL: (https://modrinth.com/mod/lfHFW1mp)
Just Enough Breeding || Version: [1.4.0] by Christofmeg || URL: (https://modrinth.com/mod/9Pk89J3g)
Just Enough Items || Version: [19.21.0.247] by mezz || URL: (https://www.curseforge.com/projects/238222)
Just Enough Professions (JEP) || Version: [4.0.3
] by Mrbysco, ShyNieke || URL: (https://www.curseforge.com/projects/417645)
Katters Structures || Version: [2.0.1] by  || URL: (https://modrinth.com/mod/V6LLU8Gf)
Keep My Soil Tilled || Version: [2.4] by Rick South || URL: (https://modrinth.com/mod/OC5Zubbe)
Kotlin for Forge || Version: [tdvjylfz] by  || URL: (https://modrinth.com/mod/ordsPcFz)
KubeJS || Version: [2101.7.1-build.181] by latvian.dev || URL: (https://www.curseforge.com/projects/238086)
LaserIO || Version: [1.9.11] by Direwolf20, ErrorMikey || URL: (https://www.curseforge.com/projects/626839)
Lighty || Version: [3.0.0-beta.4] by andi_makes, agnor99, Alveel || URL: (https://www.curseforge.com/projects/986380)
Lithium || Version: [0.14.0-snapshot+mc1.21.1-build.88] by 2No2Name, JellySquid || URL: (https://modrinth.com/mod/gvQqBUqZ)
Lithosphere || Version: [1.3] by Jayzet || URL: (https://modrinth.com/mod/iv9jp2k9)
Lithostitched || Version: [1.3.4
] by Apollo || URL: (https://www.curseforge.com/projects/936015)
LootJS || Version: [1.21.1-3.2.2] by AlmostReliable || URL: (https://modrinth.com/mod/fJFETWDN)
Lootr || Version: [1.21-1.10.33.85] by Noobanidus || URL: (https://www.curseforge.com/projects/361276)
Luki's Crazy Chambers || Version: [1.0] by lukidonu || URL: (https://www.curseforge.com/projects/1082929)
Luki's Grand Capitals || Version: [1.0] by lukidonu || URL: (https://www.curseforge.com/projects/1003666)
ME Requester || Version: [1.21.1-1.1.8] by Almost Reliable || URL: (https://www.curseforge.com/projects/688367)
MEGA Cells || Version: [4.0.2] by 90 || URL: (https://www.curseforge.com/projects/622112)
Macaw's Bridges || Version: [3.0.0] by Sketch Macaw & Peachy Macaw || URL: (https://modrinth.com/mod/GURcjz8O)
Macaw's Doors || Version: [1.1.1] by Sketch Macaw & Sketch Peachy || URL: (https://modrinth.com/mod/kNxa8z3e)
Macaw's Fences and Walls || Version: [1.1.2] by Sketch Macaw & Peachy Macaw || URL: (https://modrinth.com/mod/GmwLse2I)
Macaw's Furniture || Version: [3.3.0] by Sketch Macaw || URL: (https://modrinth.com/mod/dtWC90iB)
Macaw's Holidays || Version: [1.1.0] by Sketch Macaw & Peachy Macaw || URL: (https://modrinth.com/mod/rH20L2Lp)
Macaw's Lights and Lamps || Version: [1.1.1] by Sketch Macaw & Peachy Macaw || URL: (https://modrinth.com/mod/w4an97C2)
Macaw's Roofs || Version: [2.3.1] by Sketch Macaw & Sketch Peachy || URL: (https://modrinth.com/mod/B8jaH3P1)
Macaw's Trapdoors || Version: [1.1.3] by Sketch Macaw & Peachy Macaw || URL: (https://modrinth.com/mod/n2fvCDlM)
Macaw's Windows || Version: [2.3.2] by Sketch Macaw & Peachy Macaw || URL: (https://modrinth.com/mod/C7I0BCni)
Measurements || Version: [3.0.0
] by Mrbysco || URL: (https://www.curseforge.com/projects/478559)
Mekanism || Version: [10.7.7] by Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd || URL: (https://www.curseforge.com/projects/268560)
Mekanism Turrets || Version: [2.0.9] by x3r || URL: (https://www.curseforge.com/projects/1031448)
Mekanism Unleashed || Version: [1.21-0.2.1] by WhitePhantom || URL: (https://modrinth.com/mod/IZciqufR)
Mekanism: Generators || Version: [10.7.7] by Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd || URL: (https://www.curseforge.com/projects/268566)
Mekanism: Tools || Version: [10.7.7] by Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd || URL: (https://www.curseforge.com/projects/268567)
MendableAnvils || Version: [1.2.2] by MincraftEinstein || URL: (https://modrinth.com/mod/9p1fvkRO)
Mining Gadgets || Version: [1.18.6] by Direwolf20, ErrorMikey || URL: (https://www.curseforge.com/projects/351748)
Mob Grinding Utils || Version: [1.1.6+mc1.21.1
] by vadis365, flanks255 || URL: (https://www.curseforge.com/projects/254241)
ModernFix || Version: [5.19.3+mc1.21.1] by embeddedt || URL: (https://modrinth.com/mod/nmDcB62a)
MonoLib || Version: [1.3.0] by Jason13 || URL: (https://modrinth.com/mod/9leXt4A5)
Moonlight Lib || Version: [1.21-2.14.34] by MehVahdJukaar || URL: (https://modrinth.com/mod/twkfQtEc)
More Culling || Version: [1.0.0] by FX - PR0CESS, 1Foxy2 || URL: (https://modrinth.com/mod/51shyZVL)
More Delight || Version: [24.09.27-1.21-neoforge] by Axperty || URL: (https://modrinth.com/mod/znHQQtuU)
More Mekanism Processing || Version: [6.1] by gisellevonbingen || URL: (https://www.curseforge.com/projects/511965)
MoreBeeInfo || Version: [1.3] by anvian || URL: (https://modrinth.com/mod/N2XKPu4u)
Mouse Tweaks || Version: [2.26.1] by Ivan Molodetskikh (YaLTeR) || URL: (https://modrinth.com/mod/aC3cM3Vq)
Move Boats || Version: [3.4] by Rick South || URL: (https://modrinth.com/mod/7qPEjpyt)
Moving Elevators || Version: [1.4.9] by SuperMartijn642 || URL: (https://modrinth.com/mod/9KZOe6HD)
Mystical Agradditions || Version: [8.0.1] by BlakeBr0 || URL: (https://modrinth.com/mod/pl0jGXIx)
Mystical Agriculture || Version: [8.0.7] by BlakeBr0 || URL: (https://modrinth.com/mod/C95ReXie)
Nature's Compass || Version: [1.21.1-3.0.2-neoforge] by ChaosTheDude || URL: (https://www.curseforge.com/projects/252848)
NetherPortalFix || Version: [21.1.1] by BlayTheNinth || URL: (https://modrinth.com/mod/nPZr02ET)
No Animal Tempt Delay || Version: [1.2] by Rick South || URL: (https://modrinth.com/mod/7YM5AXYm)
Noisium || Version: [2.3.0+mc1.21-1.21.1] by Steveplays28 || URL: (https://modrinth.com/mod/KuNKN7d2)
Not Enough Glyphs || Version: [4.0.2
] by Porting by Alexthw to 1.19.2 and up || URL: (https://www.curseforge.com/projects/1023517)
Nullscape || Version: [1.2.8] by Stardust Labs || URL: (https://modrinth.com/mod/LPjGiSO4)
Nyf's Spiders || Version: [2.3.1] by Nyfaria || URL: (https://www.curseforge.com/projects/686058)
Observable || Version: [5.4.3] by tasgon || URL: (https://modrinth.com/mod/VYRu7qmG)
OctoLib || Version: [0.4.2] by OctoStudios || URL: (https://modrinth.com/mod/RH2KUdKJ)
Packet Fixer || Version: [1.4.2] by TonimatasDEV || URL: (https://modrinth.com/mod/c7m1mi73)
Panda's Falling Tree's || Version: [0.12.7] by The Panda Oliver || URL: (https://modrinth.com/mod/i2kUe4lq)
PandaLib || Version: [0.4.2] by The Panda Oliver || URL: (https://modrinth.com/mod/mEEGbEIu)
Patchouli || Version: [1.21-87-NEOFORGE
] by Vazkii || URL: (https://modrinth.com/mod/nU0bVIaL)
Permanent Sponges || Version: [21.1.0] by Fuzs || URL: (https://modrinth.com/mod/p6prwv2Q)
Placebo || Version: [9.5.3] by Shadows_of_Fire || URL: (https://www.curseforge.com/projects/283644)
Player Animator || Version: [2.0.0-alpha1+1.21] by KosmX || URL: (https://modrinth.com/mod/gedNE4y2)
Player Plates || Version: [21.1.0+mc1.21.1] by Gaz || URL: (https://modrinth.com/mod/ADYYN3JG)
Portable Mobs || Version: [1.2.1] by Dremoline || URL: (https://www.curseforge.com/projects/503922)
Powah || Version: [6.1.2] by owmii,Technici4n,shartte || URL: (https://www.curseforge.com/projects/633483)
Productive Bees || Version: [1.21.1-13.6.1] by LobsterJonn || URL: (https://modrinth.com/mod/jH6iiqkd)
Puzzles Lib || Version: [21.1.22] by Fuzs || URL: (https://modrinth.com/mod/QAGBst4M)
Railcraft Reborn || Version: [1.2.2] by Sm0keySa1m0n, Edivad99 || URL: (https://www.curseforge.com/projects/901491)
Random Bone Meal Flowers || Version: [4.6] by Rick South || URL: (https://modrinth.com/mod/17enPZMC)
Realistic Bees || Version: [4.0] by Rick South || URL: (https://modrinth.com/mod/tG6HkcWx)
Redstone Pen || Version: [1.11.41] by wilechaote || URL: (https://www.curseforge.com/projects/461710)
Reese's Sodium Options || Version: [1.8.0-beta.4+mc1.21.1] by FlashyReese || URL: (https://www.curseforge.com/projects/511319)
Relics || Version: [0.9.2.0] by SSKirillSS || URL: (https://modrinth.com/mod/OCJRPujW)
Repeatable Trial Vaults || Version: [1.0.2] by Buuz135 || URL: (https://www.curseforge.com/projects/1070541)
Resourceful Lib || Version: [3.0.11] by ThatGravyBoat, Epic_Oreo || URL: (https://modrinth.com/mod/G1hIVOrD)
Resourcefulconfig || Version: [3.0.4] by  || URL: (https://www.curseforge.com/projects/714059)
Resourcify || Version: [1.5.0] by DeDiamondPro || URL: (https://modrinth.com/mod/RLzHAoZe)
Revamped Shipwrecks || Version: [1.0.1] by Wpgradford, WightofShadows || URL: (https://modrinth.com/mod/ZnZ8uqXN)
Rhino || Version: [${version}] by latvian.dev, Mozilla || URL: (https://www.curseforge.com/projects/416294)
Scaffolding Drops Nearby || Version: [3.3] by Rick South || URL: (https://modrinth.com/mod/uO522mgw)
Searchables || Version: [1.0.2] by Jaredlll08 || URL: (https://modrinth.com/mod/fuuu3xnx)
Shulker Drops Two || Version: [3.4] by Rick South || URL: (https://modrinth.com/mod/UjXIyw47)
Simple Magnets || Version: [1.1.12] by SuperMartijn642 || URL: (https://www.curseforge.com/projects/394140)
Skart's Decorations || Version: [0.3.2] by Skart2000 || URL: (https://www.curseforge.com/projects/823139)
Sleep Sooner || Version: [4.6] by Rick South || URL: (https://modrinth.com/mod/NHjSAFFN)
Small Ships || Version: [2.0.0-b1.5] by talhanation, metroite || URL: (https://modrinth.com/mod/rGWEHQrP)
Smarter Farmers || Version: [1.21-2.1.4] by MehVahdJukaar || URL: (https://modrinth.com/mod/Bh6ZOMvp)
Smoothchunk mod || Version: [3.6] by Someaddon || URL: (https://www.curseforge.com/projects/582327)
Sodium || Version: [0.6.0-beta.2+mc1.21.1] by JellySquid, IMS212 || URL: (https://www.curseforge.com/projects/394468)
Sodium Dynamic Lights || Version: [1.0.9] by toni, LambdAurora || URL: (https://modrinth.com/mod/PxQSWIcD)
Sodium Extra || Version: [0.6.0-beta.3+mc1.21.1] by FlashyReese || URL: (https://modrinth.com/mod/PtjYWJkn)
Sodium Extra Information || Version: [2.2-beta.1] by anvian || URL: (https://modrinth.com/mod/696WgnvT)
Sodium Extras || Version: [1.0.5] by toni || URL: (https://modrinth.com/mod/vqqx0QiE)
Sooty Chimneys || Version: [1.3.1] by mortuusars || URL: (https://modrinth.com/mod/b3w1XM9H)
Sophisticated Backpacks || Version: [3.20.17] by P3pp3rF1y, Ridanisaurus || URL: (https://www.curseforge.com/projects/422301)
Sophisticated Core || Version: [0.6.45] by P3pp3rF1y || URL: (https://www.curseforge.com/projects/618298)
Spyglass Improvements || Version: [1.5.7] by juancarloscp52 (Im_JC) || URL: (https://modrinth.com/mod/Z6ykjRlM)
Storage Delight || Version: [24.09.11-1.21-neoforge] by Axperty || URL: (https://modrinth.com/mod/LTTvOp5L)
Storage Drawers || Version: [13.8.1] by Texelsaur || URL: (https://www.curseforge.com/projects/223852)
Structory || Version: [1.3.6] by Stardust Labs || URL: (https://modrinth.com/mod/aKCwCJlY)
Structory: Towers || Version: [1.0.8] by Stardust Labs || URL: (https://modrinth.com/mod/j3FONRYr)
SuperMartijn642's Config Library || Version: [1.1.8] by SuperMartijn642 || URL: (https://www.curseforge.com/projects/438332)
SuperMartijn642's Core Lib || Version: [1.1.17+i] by SuperMartijn642 || URL: (https://modrinth.com/mod/rOUBggPv)
TNT Breaks Bedrock || Version: [3.4] by Rick South || URL: (https://modrinth.com/mod/eU2O6Xp1)
Tax Free Levels || Version: [1.4.0] by Fourmisain || URL: (https://www.curseforge.com/projects/462128)
Thaumon || Version: [2.3.0+1.21] by jdlenl, shizotoaster || URL: (https://www.curseforge.com/projects/926511)
TinyCoal || Version: [1.0.3] by AzureDoom || URL: (https://www.curseforge.com/projects/395272)
Titanium || Version: [4.0.21
] by TheCodedOne, Buuz135 || URL: (https://modrinth.com/mod/1Ro7m06l)
Toast Control || Version: [9.0.0] by Shadows_of_Fire || URL: (https://www.curseforge.com/projects/271740)
Torchmaster || Version: [21.1.5-beta] by Xalcon || URL: (https://www.curseforge.com/projects/254268)
Tower of Chambers || Version: [22.35.] by SmartStreamLabs_Studios || URL: (https://www.curseforge.com/projects/1096777)
Towns and Towers || Version: [1.13.2] by Kubek and Biban_Auriu, Cristelknight999 || URL: (https://www.curseforge.com/projects/626761)
TxniLib || Version: [1.0.2] by Toni || URL: (https://www.curseforge.com/projects/1104882)
Underground Bunkers || Version: [1.0.4] by Zephyrusjz, Aureljz || URL: (https://www.curseforge.com/projects/961418)
UsefulSlime || Version: [1.11.0] by MincraftEinstein || URL: (https://modrinth.com/mod/CzM6C1W0)
Vanilla Plus Tools || Version: [1.0.3] by Raycoms || URL: (https://www.curseforge.com/projects/308705)
Village Spawn Point || Version: [4.4] by Rick South || URL: (https://modrinth.com/mod/KplTt9Ku)
Villager Names || Version: [8.1] by Rick South || URL: (https://modrinth.com/mod/gqRXDo8B)
Villager Trading Plus || Version: [1.1+1.21] by cassiancc || URL: (https://modrinth.com/mod/fRhq4ueb)
WITS || Version: [1.3.0+1.21-neoforge] by TelepathicGrunt || URL: (https://www.curseforge.com/projects/909375)
WaterFrames || Version: [2.1.6b] by SrRapero720 || URL: (https://modrinth.com/mod/eBzFuVTM)
WaterMedia || Version: [2.0.75] by SrRapero720, Goedix || URL: (https://modrinth.com/mod/G922NeHS)
WaveyCapes || Version: [1.4.10] by tr7zw || URL: (https://modrinth.com/mod/kYuIpRLv)
Waystones || Version: [21.1.5] by BlayTheNinth || URL: (https://modrinth.com/mod/LOpKHB2A)
What Durability? || Version: [1.3] by Rick South || URL: (https://modrinth.com/mod/lKY2kyjj)
When Dungeons Arise || Version: [2.1.60] by Aureljz, DiamondTown & Zephyrusjz || URL: (https://modrinth.com/mod/8DfbfASn)
When Dungeons Arise: Seven Seas || Version: [1.0.3.2] by Zephyrusjz, Aureljz || URL: (https://modrinth.com/mod/ZsrrjDbP)
Zero CORE 2 || Version: [1.21.1-2.4.9] by ZeroNoRyouki || URL: (https://modrinth.com/mod/rHpb85Mf)
chunksending mod || Version: [2.8] by Someaddon || URL: (https://www.curseforge.com/projects/831663)
oωo || Version: [0.12.15-beta.6+1.21] by glisco, Blodhgarm, BasiqueEvangelist, Noaaan || URL: (https://modrinth.com/mod/ccKDOlHs)
spark || Version: [1.10.109] by Luck || URL: (https://modrinth.com/mod/l6YH9Als)

**Comment by iron431** [comment]
this looks like an issue that has already been fixed, update the mod and see if it persists

**Comment by Cyranos** [comment]
I just re-updated the mod to 3.8.0 on 1.21.1 and still crashing https://mclo.gs/782UReB

I believe it's an incompatibility with Amendments; (https://www.curseforge.com/projects/896746)
Which tweaks the lectern.

**Comment by iron431** [comment]
no, update to 3.8.2. how do you expect to install a bugfix if youre not downloading the latest version

**Comment by Cyranos** [comment]
That version isn't up on modrinth
![image](https://github.com/user-attachments/assets/9e429c34-5e28-4a8d-9271-047a67380495)

**Comment by iron431** [comment]
use curseforge

**Comment by Cyranos** [comment]
3.8.2 fixed it, but may I ask why your mod versions are so split between Modrinth & Curseforge?

**Comment by iron431** [comment]
modrinth is so small i forget it exists

**Comment by iron431** [comment]
and it takes several additional steps to upload files compared to curseforge
