### ISSUE TITLE
[Bug] Crash when killing entities using Electrocute

### ISSUE THREAD

**Issue by demonVenerable123** [iron431/Irons-Spells-n-Spellbooks#652]
### Observed behaviour

When using the electrocute spell, if you kill any entity with it, it will crash with the message "The game crashed whilst ticking entity" this happened while playing ATM10 in NeoForge, it is unknown if this is due to me being extremely small (as I was shrunk using the Personal Shrinking Device from Shrink mod, though I could be wrong about my conjecture) this was the only thing I had on my person other than Iron's Spells equipment

### Expected behaviour

I'm not sure, I attempted killing multiple mobs with it, modded ones and vanilla alike all crashed the instant before or during their death, closing my minecraft before I could see anything else.

### Steps to reproduce

1. Use Electrocute spell with Villager Bible
2. Kill any entity with it

### Server Type

Single Player

### Crashlog

https://gist.github.com/demonVenerable123/2bd5140382dcb832a984fe20a1b4f0be#file-crash-2024-10-31_20-11-56-server

### Iron's Spells N Spellbooks version

v1.21-3.8.4

### Forge version

Neoforge 21.1.73

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by demonVenerable123** [comment]
Update: This happens with ball of lightning too (inconsistently) 

Clip: https://streamable.com/rh7neh

**Comment by iron431** [comment]
your log says 3.8.3, this is fixed in 3.8.4
