### ISSUE TITLE
[Bug] Crushes the game when open inventory with enchanted armor

### ISSUE THREAD

**Issue by MotilQR** [iron431/Irons-Spells-n-Spellbooks#653]
### Observed behaviour

When i try to open inventory with enchanted electromancer armor on, the game crushes

### Expected behaviour

I wanted open the inventory

### Steps to reproduce

Take the electromancer armor, enchant it and put it on. When trying to open inventory or turn the third person view, the game crushes

### Server Type

Single Player

### Crashlog

https://gist.github.com/MotilQR/f722d24001144e6bc5f12b3adde30f34

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.4

### Forge version

forge 1.20.1-47.2.18

### Other mods

apple skin 1.20.1-2.5.1
create 1.20.1-0.5.1
FarmersDelight 1.20.1-1.2.4
travelersbackpack 1.20.1-9.1.16

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
looks like an issue of using outdated geckolib
