### ISSUE TITLE
[Bug] Incompatibility with Eternal Starlight (MC 1.21.1)

### ISSUE THREAD

**Issue by uhloin** [iron431/Irons-Spells-n-Spellbooks#654]
### Observed behaviour

Evoker Fort structure is generated in the abnormal dimension (from Eternal Starlight mod)

### Expected behaviour

No Iron's structures in irrelevant dimensions

### Steps to reproduce

Enter to Starlight dimension as instructed on the main page
https://www.curseforge.com/minecraft/mc-mods/eternal-starlight

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.8.4

### Forge version

Neoforge 21.1.68

### Other mods

eternalstarlight-0.1.17+1.21.1+neoforge.jar

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
this is due to eternal starlight biomes being added to tags used for structure generation, such as "desert". i do not believe this is correct practice on their part, so I will not do anything about it

**Comment by uhloin** [comment]
I've sent a link to this explanation to Starlight developer here:
https://github.com/LeoMinecraftModding/eternal-starlight/issues/24
