### ISSUE TITLE
Can priests be nerfed?

### ISSUE THREAD

**Issue by trevorjd** [iron431/Irons-Spells-n-Spellbooks#656]
### Description

We're finding the village priests are becoming hostile to players on our server.  Is that a feature of this mod?  If so, is it possible to render them non-hostile?

### Not a feature request

- [ ] I understand this is not a content/feature request for the mod (as those are on discord), but for the codebase

**Comment by iron431** [comment]
priests are neutral. if they are attacking, they are being angered

**Comment by trevorjd** [comment]
Sorry, I should've been more specific.  It seems they are becoming angered by players opening chests.  Is that part of this mod?

**Comment by iron431** [comment]
yes, the first time looting a chest angers them

**Comment by trevorjd** [comment]
OK, so that's the feature we'd like to disable.  Can that be done?

**Comment by lab3** [comment]
I don't think there would be a way to disable it.  You could do it with an addon
