### ISSUE TITLE
[Bug] Use the bottle directly on an empty cauldron can get blood vial

### ISSUE THREAD

**Issue by Boshigiri** [iron431/Irons-Spells-n-Spellbooks#657]
### Observed behaviour

Tested, only ISS installed, no other mods

### Expected behaviour

As the title says

### Steps to reproduce

I found this bug when I was trying the cauldron system in amendments. 

I thought it was an amendments bug, but after removing all other mods, the bug still exists.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.8.4

### Forge version

neoforge-21.1.73

### Other mods

none

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
fixed in 3.8.6
