### ISSUE TITLE
Show spell bar when the "Scroll Modifier" key is pressed and spell bar visibility is set to "contextual"

### ISSUE THREAD

**Issue by SofiG2658** [iron431/Irons-Spells-n-Spellbooks#658]
### Description

Currently, when set to "Contextual", the spell bar only shows when the player casts a spell or press the "Open Wheel" keybind. It would be helpful if it also showed when the "Spell Bar Scroll Modifier" key was pressed, potentially eliminating the need for a dedicated keybing for the wheel if the player only wants to use the modifier key and scroll, while also eliminating need to try and remember which spell was selected prior to the spell bar disappearing

### Not a feature request

- [X] I understand this is not a content/feature request for the mod (as those are on discord), but for the codebase

**Comment by iron431** [comment]
added in 3.8.5
