### ISSUE TITLE
Idea: Clone spell

### ISSUE THREAD

**Issue by IvoryJustie** [iron431/Irons-Spells-n-Spellbooks#659]
### Description

i just got this idea from fighting a mutant enderman with ender and i thought it would be cool for ender to have clones : D.

the clone spell could either be clones that follow you around like the illusioner or a summon type thing that makes 2-4 clones that has a player model that has their own weapons or sumthing. i just realy like the concept of having clones on end spells.

it would be epic - legendary with legendary having max 4 clones and epic with 1 so the spell would have 4 levels.
cost would be 80-120 mana 80 being lvl1 and 120 would be lvl 4.

hp of the clones should scale of magic str like the more end or magic str you have the more hp and dmg the clones would do.
would be funny if the clones could use spells ngl.

( the idea kind of comes from the  Ars Nouveau  mod with their clones )

### Not a feature request

- [X] I understand this is not a content/feature request for the mod (as those are on discord), but for the codebase

**Comment by iron431** [comment]
discord is a much better place to share ideas, github is for issue tracking https://discord.gg/TRzEdrndM2
