### ISSUE TITLE
Changing School of Spells

### ISSUE THREAD

**Issue by Aenast28** [iron431/Irons-Spells-n-Spellbooks#663]
Exactly as title says. I'm trying to convert Most of eldritch spells from eldritch to ender, so they benefit from the ender robes and spellbook bonuses. (ignore obvious balancing issues)
I've made some changes such as changing the public class to extend AbstractSpell instead of its eldritch variant, and also put it under .spells.ender package. But still, when I compile it and launch the game it does not work as intended.
All the spells disappeared from eldritch manuscript (yay), but they are still listed as "eldritch" not "ender" when listing through scrolls.

Do you guys know what else am I missing, or is there much simpler way to implement this? (1.19.2 btw)

Thanks alot.

**Comment by iron431** [comment]
do not edit source code. spell schools are already configurable.
