### ISSUE TITLE
[Bug] Vexes fading out of world early.

### ISSUE THREAD

**Issue by Nath560** [iron431/Irons-Spells-n-Spellbooks#665]
### Observed behaviour

My vexes just vanish the moment they're summoned

### Expected behaviour

They stay around for 9 minutes

### Steps to reproduce

I'm not sure they're just vanishing

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-3.4.0

### Forge version

forge 47.3.6

### Other mods

The entire prodigium reforged modpack 1.20.1

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by meeprdib** [comment]
are you in peaceful mode

**Comment by meeprdib** [comment]
Nevermind, that wouldn't effect vexes despawning anyway.

**Comment by Nath560** [comment]
Update: it isn't just vexes almost every summon that will fight for me fades out the world instantly so I can't raise the dead either.

**Comment by iron431** [comment]
works fine for me 
![image](https://github.com/user-attachments/assets/b786348b-441c-404c-976d-d9c21f62ab75)

**Comment by Nath560** [comment]
> works fine for me ![image](https://private-user-images.githubusercontent.com/34083081/386866845-b786348b-441c-404c-976d-d9c21f62ab75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3ODA5OTQsIm5iZiI6MTczMTc4MDY5NCwicGF0aCI6Ii8zNDA4MzA4MS8zODY4NjY4NDUtYjc4NjM0OGItNDQxYy00MDRjLTk3NmQtZDljMjFmNjJhYjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDE4MTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViODAzMzMzNmM5NzgwMDM4ZWEwYjI1ODcwYjViNWY0NzhjODYxZDRlZjY0MTMzYzQxMDFiMmZlMWU2MWE2MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3AirbwgrImzxRiNs2YSFWXGBMBq9gZ3vFM-jEsYu1wE)

I figured out what causes it, if you purchase the nullification skill in the wizard skill tree of prodigium it causes the vexes to loose their "summoned vex 9:50" which causes them to fade
