### ISSUE TITLE
[Bug] Cant put Ingots into Alchemist Cauldron

### ISSUE THREAD

**Issue by LoganOfDoom** [iron431/Irons-Spells-n-Spellbooks#666]
### Observed behaviour

I tried to upgrade ink, but i cant put ingots into the Cauldron
Yes the Cauldron is empty
I also tried a Hopper

### Expected behaviour

Normal ink upgrade process

### Steps to reproduce

1. Place Alchemist Cauldron
2. Try to put Ingot into Cauldron
3. Fail

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.4

### Forge version

Forge 47.3.0

### Other mods

.connector
3D Placeable food (https://www.curseforge.com/projects/886102)
3d-Skin-Layers (https://www.curseforge.com/projects/521480)
A Man With Plushies (https://www.curseforge.com/projects/441249)
Additional Attributes (https://www.curseforge.com/projects/986624)
Additional Lanterns (https://www.curseforge.com/projects/501590)
Additional Lights (https://www.curseforge.com/projects/384991)
Alex's Caves (https://www.curseforge.com/projects/924854)
Alex's Mobs (https://www.curseforge.com/projects/426558)
All The Wizard Gear (https://www.curseforge.com/projects/927064)
AllTheOres (https://www.curseforge.com/projects/405593)
Allthemodium (https://www.curseforge.com/projects/364466)
Amendments (https://www.curseforge.com/projects/896746)
AnimaticaReforged (https://modrinth.com/mod/6ABF6Pv3)
Apotheosis (https://www.curseforge.com/projects/313970)
Apothic Attributes (https://www.curseforge.com/projects/898963)
Aquamirae (https://www.curseforge.com/projects/536254)
Architectury (https://www.curseforge.com/projects/419699)
Artifacts (https://www.curseforge.com/projects/312353)
Athena (https://www.curseforge.com/projects/841890)
Bad Packets (https://modrinth.com/mod/ftdbN0KK)
Balm (https://www.curseforge.com/projects/531761)
Better village (https://www.curseforge.com/projects/615352)
BetterF3 (https://modrinth.com/mod/8shC1gFX)
Biomes O' Plenty (https://www.curseforge.com/projects/220318)
Blossom Blade (https://www.curseforge.com/projects/920268)
Blueprint (https://www.curseforge.com/projects/382216)
Bookshelf (https://modrinth.com/mod/uy4Cnpcm)
Botania (https://www.curseforge.com/projects/225643)
Caelus API (https://www.curseforge.com/projects/308989)
Carbon Config Library (https://www.curseforge.com/projects/898104)
Chat Heads (https://www.curseforge.com/projects/407206)
Chimes (https://www.curseforge.com/projects/350464)
Chipped (https://www.curseforge.com/projects/456956)
Chunk Pregenerator (https://www.curseforge.com/projects/267193)
Chunky (https://www.curseforge.com/projects/485681)
Citadel (https://www.curseforge.com/projects/331936)
Cloth Config v10 API (https://www.curseforge.com/projects/348521)
Colorful Hearts (https://modrinth.com/mod/wQfMUdZT)
Comforts (https://www.curseforge.com/projects/276951)
Common Networking (https://www.curseforge.com/projects/806044)
CommonCapabilities (https://www.curseforge.com/projects/247007)
Connectivity Mod (https://www.curseforge.com/projects/470193)
Connector Extras (https://www.curseforge.com/projects/913445)
Controlling (https://modrinth.com/mod/xv94TkTM)
CorgiLib (https://www.curseforge.com/projects/693313)
Corpse (https://www.curseforge.com/projects/316582)
CosmeticArmorReworked (https://www.curseforge.com/projects/237307)
CraftingTweaks (https://modrinth.com/mod/DMu0oBKf)
Cupboard utilities (https://www.curseforge.com/projects/326652)
Curios API (https://www.curseforge.com/projects/309927)
Customizable Elytra (https://www.curseforge.com/projects/440047)
Cut Through (https://www.curseforge.com/projects/969423)
Cyclops Core (https://www.curseforge.com/projects/232758)
DarkBlades - End Game Weapons (https://www.curseforge.com/projects/901948)
Decent Biomes (https://www.curseforge.com/projects/969912)
Distant Horizons (https://modrinth.com/mod/uCdwusMi)
Doggy Talents Next (https://www.curseforge.com/projects/694492)
Duckling (https://www.curseforge.com/projects/597248)
Dynamic FPS (https://modrinth.com/mod/LQ3K71Q1)
Easy Anvils (https://www.curseforge.com/projects/682567)
Embeddium (https://www.curseforge.com/projects/908741)
Enchantment Info (https://modrinth.com/mod/eqtPjP5L)
EnchantmentDescriptions (https://modrinth.com/mod/UVtY3ZAC)
Entity Model Features (https://modrinth.com/mod/4I1XuqiY)
Entity Texture Features (https://modrinth.com/mod/BVzZfTc1)
EntityCulling (https://modrinth.com/mod/NNAgCjsB)
Equipment Compare (https://modrinth.com/mod/CYSUVOdj)
Euphoria Patcher (https://modrinth.com/mod/4H6sumDB)
Every Compat (https://www.curseforge.com/projects/628539)
Fairy Lights (https://www.curseforge.com/projects/233342)
Farsight mod (https://www.curseforge.com/projects/495693)
Ferrite Core (https://modrinth.com/mod/uXXizFIs)
Forgified Fabric API (https://www.curseforge.com/projects/889079)
Framework (https://www.curseforge.com/projects/549225)
GeckoLib 4 (https://www.curseforge.com/projects/388172)
GlitchCore (https://www.curseforge.com/projects/955399)
Goblin Traders (https://www.curseforge.com/projects/363703)
HT's TreeChop (https://www.curseforge.com/projects/421377)
Hexerei (https://www.curseforge.com/projects/548599)
Icarus (https://www.curseforge.com/projects/428151)
Ice and Fire (https://www.curseforge.com/projects/264231)
Iceberg (https://modrinth.com/mod/5faXoLqX)
Illager-Warship (https://www.curseforge.com/projects/1091632)
ImmediatelyFast (https://modrinth.com/mod/5ZwdcRci)
Inventory Essentials (https://modrinth.com/mod/Boon8xwi)
Inventory HUD+ (https://www.curseforge.com/projects/357540)
Inventory Pets (https://www.curseforge.com/projects/229380)
Inventory Tweaks Refoxed (https://modrinth.com/mod/uqnMI1kq)
Iron Chests (https://www.curseforge.com/projects/228756)
Iron Spells Dungeons (https://www.curseforge.com/projects/1117039)
Iron's Spells 'n Spellbooks (https://www.curseforge.com/projects/855414)
Iron's Spells Artifacts (https://www.curseforge.com/projects/1131213)
Just Enough Breeding (https://modrinth.com/mod/9Pk89J3g)
Just Enough Resources (https://modrinth.com/mod/uEfK2CXF)
Just Zoom (https://modrinth.com/mod/iAiqcykM)
JustInWIZARDHAT (https://www.curseforge.com/projects/1068761)
Konkrete (https://modrinth.com/mod/J81TRJWm)
LegendaryMonsters (https://www.curseforge.com/projects/944035)
Lexiconfig (https://www.curseforge.com/projects/1019452)
Library ferret (https://www.curseforge.com/projects/532727)
Lootr (https://www.curseforge.com/projects/361276)
MC Dungeons Armors (https://www.curseforge.com/projects/426206)
MC Dungeons Weapons (https://www.curseforge.com/projects/407311)
Macaw's Bridges (https://www.curseforge.com/projects/351725)
Macaw's Bridges - BWG (https://www.curseforge.com/projects/535960)
Macaw's Doors (https://www.curseforge.com/projects/378646)
Macaw's Fences - BWG (https://www.curseforge.com/projects/620582)
Macaw's Fences and Walls (https://www.curseforge.com/projects/453925)
Macaw's Furniture (https://www.curseforge.com/projects/359540)
Macaw's Holidays (https://www.curseforge.com/projects/930232)
Macaw's Lights and Lamps (https://www.curseforge.com/projects/502372)
Macaw's Paintings (https://www.curseforge.com/projects/438116)
Macaw's Paths and Pavings (https://www.curseforge.com/projects/629153)
Macaw's Roofs (https://www.curseforge.com/projects/352039)
Macaw's Roofs - BYG (https://www.curseforge.com/projects/577356)
Macaw's Trapdoors (https://www.curseforge.com/projects/400933)
Macaw's Windows (https://www.curseforge.com/projects/363569)
ModernFix (https://modrinth.com/mod/nmDcB62a)
Moog's Nether Structures (https://www.curseforge.com/projects/967466)
Moonlight Library (https://www.curseforge.com/projects/499980)
More Vanilla Potions (https://www.curseforge.com/projects/627825)
Mouse Tweaks (https://modrinth.com/mod/aC3cM3Vq)
Mowzie's Mobs (https://www.curseforge.com/projects/250498)
Obscure API (https://www.curseforge.com/projects/638417)
Oculus (https://modrinth.com/mod/GchcoXML)
Oh The Biomes We've Gone (https://www.curseforge.com/projects/1070751)
Oh The Trees You'll Grow (https://www.curseforge.com/projects/962544)
Patchouli (https://www.curseforge.com/projects/306770)
Placebo (https://www.curseforge.com/projects/283644)
Player Animator (https://www.curseforge.com/projects/658587)
Potacore (https://www.curseforge.com/projects/951521)
Puzzles Lib (https://www.curseforge.com/projects/495476)
Quad (https://www.curseforge.com/projects/932715)
Quark (https://www.curseforge.com/projects/243121)
REI Plugin Compatibilities (https://www.curseforge.com/projects/521393)
Resourceful Lib (https://www.curseforge.com/projects/570073)
Resourcefulconfig (https://www.curseforge.com/projects/714059)
Rings of Ascension (https://www.curseforge.com/projects/379208)
Roughly Enough Items (REI) (https://www.curseforge.com/projects/310111)
Roughly Enough Professions (https://modrinth.com/mod/V8XJ8f5f)
Searchables (https://modrinth.com/mod/fuuu3xnx)
SeasonHUD (https://www.curseforge.com/projects/690971)
Serene Seasons (https://www.curseforge.com/projects/291874)
Simple Voice Chat (https://www.curseforge.com/projects/416089)
Sinytra Connector (https://www.curseforge.com/projects/890127)
Snowy Spirit (https://www.curseforge.com/projects/566142)
Sodium Dynamic Lights (https://modrinth.com/mod/PxQSWIcD)
Sodium Extras (https://modrinth.com/mod/vqqx0QiE)
Sodium Options API (https://modrinth.com/mod/Es5v4eyq)
Sophisticated Backpacks (https://www.curseforge.com/projects/422301)
Sophisticated Core (https://www.curseforge.com/projects/618298)
Sophisticated Storage (https://www.curseforge.com/projects/619320)
SuperMartijn642's Core Lib (https://www.curseforge.com/projects/454372)
Supplementaries (https://www.curseforge.com/projects/412082)
TerraBlender (https://www.curseforge.com/projects/563928)
The Abyss: The Other Side (https://www.curseforge.com/projects/440647)
The Outer End (https://www.curseforge.com/projects/430404)
TipsyLib (https://www.curseforge.com/projects/880879)
Trading Post (https://www.curseforge.com/projects/539057)
Unusual End (https://www.curseforge.com/projects/617757)
Waystones (https://www.curseforge.com/projects/245755)
Whisperwoods (https://www.curseforge.com/projects/349597)
Xaero's Map - Waystones Compability (https://modrinth.com/mod/7mLhyqIY)
Xaero's Minimap (https://www.curseforge.com/projects/263420)
Xaero's World Map (https://modrinth.com/mod/NcUtCpym)
YUNG's API (https://www.curseforge.com/projects/421850)
YUNG's Better Desert Temples (https://www.curseforge.com/projects/631016)
Zeta (https://www.curseforge.com/projects/968868)
aleki's Nifty Ships (https://www.curseforge.com/projects/1068445)
wthit (https://modrinth.com/mod/6AQIaxuO)

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by lab3** [comment]
That's not how it works

https://iron.wiki/blocks/?s=irons_spellbooks:alchemist_cauldron#irons_spellbooks:alchemist_cauldron

**Comment by iron431** [comment]
@lab3 unless i misunderstand the post this is how it works

**Comment by lab3** [comment]
I might have misread

**Comment by iron431** [comment]
@LoganOfDoom how are you trying to put ingots into the cauldron, and have you tried without connector?

**Comment by LoganOfDoom** [comment]
> @LoganOfDoom how are you trying to put ingots into the cauldron, and have you tried without connector?

rightclick with a ingot equipped ( with just the spell mod installed it works that way)
i tried without connector and it changes nothing

**Comment by iron431** [comment]
I cannot reproduce this. it is likely a conflict with your mods. I would try removing batches until the functionality works again in order to narrow down what it might be.
