### ISSUE TITLE
[Bug] Catacombs generating in the ocean

### ISSUE THREAD

**Issue by proxyline77** [iron431/Irons-Spells-n-Spellbooks#667]
### Observed behaviour

I am not sure if this is intentional or not, but catacombs can spawn above the ground in oceans

### Expected behaviour

Catacombs spawning below the ground

### Steps to reproduce

Just loaded a new world and explored for a bit

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.1.4.3

### Forge version

40.2.17

### Other mods

- [[Ice and fire 1.17.1 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)  2.1.12 *
- [[Alex’s mobs 1.18.1 - 1.19.4](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)  1.18.6 *
- [[Macaw’s windows 1.17.1 - 1.19.3](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)  2.2.1
- [[Better Villages 1.17.1 - 1.19.4](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)  3.1.0
- [[Biomes O’ Plenty 1.17.1 - 1.19.4](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)  16.0.0.134 *
- [[Fantasy’s Furniture 1.16.5 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture/files/all?page=1&pageSize=20)  3.14.0
- [[Dramatic Doors 1.14.4 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/dramatic-doors/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/dramatic-doors/files/all?page=1&pageSize=20)  2.3.1_2
- [[Farmer’s Delight 1.17.1 - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)  1.2.2
- [[ItemPhysic Full 1.18 - 1.19.4](https://www.curseforge.com/minecraft/mc-mods/itemphysic)](https://www.curseforge.com/minecraft/mc-mods/itemphysic) 1.4.23
- [[Right click, get crops 1.18.2 - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/right-click-get-crops)](https://www.curseforge.com/minecraft/mc-mods/right-click-get-crops)  1.4.0.10
- [[Chimes 1.17.1 - 1.19.4](https://www.curseforge.com/minecraft/mc-mods/chimes)](https://www.curseforge.com/minecraft/mc-mods/chimes)  2.0.1
- [[Additional Bars 1.15.1 - 1.19](https://www.curseforge.com/minecraft/mc-mods/additional-bars)](https://www.curseforge.com/minecraft/mc-mods/additional-bars)  3.0.1
- [[Immersive paintings 1.16.5 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings/files/all?page=1&pageSize=20)  0.6.3
- [[Sit 1.17.1 - 1.19.4](https://www.curseforge.com/minecraft/mc-mods/sit)](https://www.curseforge.com/minecraft/mc-mods/sit)  1.3.3
- [[Iron’s Spellbooks 1.18.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)  1.1.4.3
- [[Bottle your xp 1.12.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp)](https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp)  3.1
- [[Double doors 1.12.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/double-doors)](https://www.curseforge.com/minecraft/mc-mods/double-doors)  5.0
- [[Measurements 1.16.5 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/measurements)](https://www.curseforge.com/minecraft/mc-mods/measurements)  1.3.1
- [[Paragliders 1.10.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/paragliders)](https://www.curseforge.com/minecraft/mc-mods/paragliders) *  1.6.0.6
- [[Pet pass 1.12 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/pet-transfer-trade-your-pets/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/pet-transfer-trade-your-pets/files/all?page=1&pageSize=20) -
- [[Player trade 1.12.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/player-trade-secure-trading-between-players)](https://www.curseforge.com/minecraft/mc-mods/player-trade-secure-trading-between-players)  1.0
- [[Re:skin 1.12.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/re-skin)](https://www.curseforge.com/minecraft/mc-mods/re-skin)  2.5.0
- [[Trading post 1.16.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/trading-post)](https://www.curseforge.com/minecraft/mc-mods/trading-post)  3.2.0
- [[Inventory totem 1.12.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/inventory-totem)](https://www.curseforge.com/minecraft/mc-mods/inventory-totem)  3.0
- [[Corpse 1.12.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/corpse/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/corpse/files/all?page=1&pageSize=20)  1.0.1
- [[Easy anvils 1.18.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/easy-anvils/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils/files/all?page=1&pageSize=20)  3.0.0
- [[YUNG’S Better Mineshafts 1.12 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge/files/all?page=1&pageSize=20)  2.2
- [[YUNG's Better Strongholds 1.16 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds/files/all?page=1&pageSize=20)  2.1.0
- [[YUNG's Better Ocean Monuments 1.18.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments/files/all?page=1&pageSize=20)  1.0.3
- [[YUNG's Better Desert Temples 1.18.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples/files/all?page=1&pageSize=20)  1.3.1
- [[Elytra Slot 1.13.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/elytra-slot/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot/files/all?page=1&pageSize=20)  5.0.1.0
- [[Botany pots 1.14.4 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/all?page=1&pageSize=20)  8.1.32
- [[Farmer’s Respite 1.16.5 - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/farmers-respite/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/farmers-respite/files/all?page=1&pageSize=20)  1.3.0
- [[Cultural delight 1.16.5 - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/cultural-delights/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/cultural-delights/files/all?page=1&pageSize=20)  0.14
- [[Ice and fire: Dragonseeker 1.16.4 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragonseeker/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragonseeker/files/all?page=1&pageSize=20)  1.1.1
- [[HT's TreeChop 1.12.1 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/treechop)](https://www.curseforge.com/minecraft/mc-mods/treechop)  0.17.7
- [[Nature's Compass 1.7.10 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/natures-compass/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/natures-compass/files/all?page=1&pageSize=20)  1.9.7
- [[Chipped 1.16.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/chipped/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/chipped/files/all?page=1&pageSize=20)  2.0.1
- [[Comforts 1.12 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/comforts/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/comforts/files/all?page=1&pageSize=20)  5.0.0.6
- [[Simply swords 1.18 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/simply-swords/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/simply-swords/files/all?page=1&pageSize=20)  1.40
- [[Diagonal Fences 1.16.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/diagonal-fences/files/all?page=1&pageSize=20)  3.2.3
- [[Alcocraft 1.18.1 - 1.19](https://www.curseforge.com/minecraft/mc-mods/alcocraft-beer-and-stuff/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/alcocraft-beer-and-stuff/files/all?page=1&pageSize=20)  1.0.0
- [[Nyf's Wearable Backpacks 1.16.5 - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/nyfs-wearable-backpacks/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/nyfs-wearable-backpacks/files/all?page=1&pageSize=20) * 0.1.0
- [[Trample Stopper 1.12.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/trample-stopper/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/trample-stopper/files/all?page=1&pageSize=20)  3.1.0
- [[Small Ships 1.16.1 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/small-ships/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/small-ships/files/all?page=1&pageSize=20)  2.0.0-b1.1.1
- [[Horse combat controls 1.16.5 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/horse-combat-controls/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/horse-combat-controls/files/all?page=1&pageSize=20)  1.0.1
- [[Callable horses 1.12.1 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/callable-horses/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/callable-horses/files/all?page=1&pageSize=20)  1.2.2.5
- [[Shiny horses 1.18 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/shiny-horses-forge-enchantable-horse-armor/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/shiny-horses-forge-enchantable-horse-armor/files/all?page=1&pageSize=20)  1.1
- [[Majruszs enchantments 1.12 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments/files/all?page=1&pageSize=20&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments/files/all?page=1&pageSize=20&gameVersionTypeId=1)  1.9.2
- [[Easier Sleeping 1.14.4 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/easier-sleeping/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/easier-sleeping/files/all?page=1&pageSize=20) 2.1.3
- [[EasyMagic 1.15.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/easy-magic/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/easy-magic/files/all?page=1&pageSize=20)  3.3.0
- [[Passable Foliage 1.15.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/passable-foliage/files/all?page=1&pageSize=20&version=1.18.2&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/passable-foliage/files/all?page=1&pageSize=20&version=1.18.2&gameVersionTypeId=1)  4.3.0
- [[HorseInBoat 1.18.1 - 1.20](https://www.curseforge.com/minecraft/mc-mods/horseinboat/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/horseinboat/files/all?page=1&pageSize=20)  1.1.2
- [[Nyf’s spiders 1.16.4 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/nyfs-spiders/files/all?page=1&pageSize=20)  2.0.3
- [[Additional lanterns 1.12 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns/files/all?page=1&pageSize=20)  1.1.1a
- [[When dungeons arise 1.14.4 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise/files/all?page=1&pageSize=20)  2.1.52
- [[Another furniture 1.18.1 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/another-furniture/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/another-furniture/files/all?page=1&pageSize=20)  1.2.2
- [[Elenai dodge 2 1.12.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/elenai-dodge-2/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/elenai-dodge-2/files/all?page=1&pageSize=20)  1.0.2
- [[Kobolds 1.16.5 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/kobolds/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/kobolds/files/all?page=1&pageSize=20)  2.9.3
- [[Shield Expansion 1.16.3 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/shield-expansion/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/shield-expansion/files/all?page=1&pageSize=20)  1.1.7a
- [[Visual Workbench 1.16.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/visual-workbench/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/visual-workbench/files/all?page=1&pageSize=20)  3.3.0
- [[Better combat 1.18.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus/files/all?page=1&pageSize=20) *  1.6.2
- [[Diet 1.16.5 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/diet/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/diet/files/all?page=1&pageSize=20)  1.3.2.1
- [[Simple RPC 1.12.2 - 1.21](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc/files/all?page=1&pageSize=20)  3.3.1
- [[Lootr 1.12.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/lootr/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/lootr/files/all?page=1&pageSize=20)  0.3.29.71
- [[Beautify! 1.18.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/beautify-decorate/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/beautify-decorate/files/all?page=1&pageSize=20)  1.4.1
- [[Lenient Creepers 1.12 - 1.21](https://www.curseforge.com/minecraft/mc-mods/lenient-creepers/files/all?page=1&pageSize=20&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/lenient-creepers/files/all?page=1&pageSize=20&gameVersionTypeId=1)  1.0.1
- [[Bed benefits 1.15.2 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/bed-benefits/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/bed-benefits/files/all?page=1&pageSize=20)  6.0.4
- [[Better safe bed 1.16.5 - 1.21](https://www.curseforge.com/minecraft/mc-mods/better-safe-bed/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/better-safe-bed/files/all?page=1&pageSize=20)  a
- [[Zombie Awareness 1.7.10 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/zombie-awareness/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/zombie-awareness/files/all?page=1&pageSize=20)  1.12.3
- [[Realistic horse genetics 1.12.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/realistic-horse-genetics/files/all?page=1&pageSize=20) 11.5
- [[Bushier flowers 1.18.2 - 1.20.2](https://www.curseforge.com/minecraft/mc-mods/bushier-flowers/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/bushier-flowers/files/all?page=1&pageSize=20)  0.0.2
- [[Friendly fire 1.7.10 - 1.20.4](https://www.curseforge.com/minecraft/mc-mods/friendly-fire/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/friendly-fire/files/all?page=1&pageSize=20)  11.0.4
- [[MmmMmmMmm 1.7.10 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm/files/all?page=1&pageSize=20)  1.5.2
- [[Astikor carts [Pig crash fix] 1.18.2](https://www.curseforge.com/minecraft/mc-mods/astikorcarts-horse-carts-pigcrash-fix-fork)](https://www.curseforge.com/minecraft/mc-mods/astikorcarts-horse-carts-pigcrash-fix-fork)  1.1.7
- [[Sparse Structures Reforged 1.16.5 - 1.20.2](https://www.curseforge.com/minecraft/mc-mods/ssr/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/ssr/files/all?page=1&pageSize=20)  1.0.0
- [[Oh the biomes you’ll go 1.12.2 - 1.19.4](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/all?page=1&pageSize=20) * 1.5.1
- [[Let’s do vinery 1.19.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery/files/all?page=1&pageSize=20)  1.2.8
- [[Genetic animals 1.14 - 1.18.2](https://www.curseforge.com/minecraft/mc-mods/genetic-animals/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/genetic-animals/files/all?page=1&pageSize=20) * 0_8_25
- [[Magical Jewelry 1.15.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/magical-jewelry/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/magical-jewelry/files/all?page=1&pageSize=20)  1.4.2
- [[Pots and mimics 1.12.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/pots-and-mimics-rpg/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/pots-and-mimics-rpg/files/all?page=1&pageSize=20)  1.0.2
- [[Villager comfort 1.18.2 - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/villager-comfort/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/villager-comfort/files/all?page=1&pageSize=20)  1.0.1
- [[Straw golem 1.14.4 - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/strawgolem-reborn/files/all?page=1&pageSize=20)
- [[Amplified Nether 1.18 - 1.21](https://www.curseforge.com/minecraft/mc-mods/amplified-nether/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether/files/all?page=1&pageSize=20)
- [[Fishing real 1.14.4 - 1.21](https://www.curseforge.com/minecraft/mc-mods/fishing-real/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/fishing-real/files/all?page=1&pageSize=20)?
- [[Better than mending 1.10 - 1.21.1](https://modrinth.com/mod/better-than-mending/versions)](https://modrinth.com/mod/better-than-mending/versions)
- [[Better Invisibility 1.12 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/better-invisibility/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/better-invisibility/files/all?page=1&pageSize=20)
- [[Carry on 1.10 - 1.21.1](https://www.curseforge.com/minecraft/mc-mods/carry-on/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/carry-on/files/all?page=1&pageSize=20)
- [[Waystones 1.7.10 - 1.21.3](https://www.curseforge.com/minecraft/mc-mods/waystones/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/waystones/files/all?page=1&pageSize=20)
- [[Storage drawers 1.7.10 - 1.21.3](https://www.curseforge.com/minecraft/mc-mods/storage-drawers/files/all?page=1&pageSize=20&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/storage-drawers/files/all?page=1&pageSize=20&gameVersionTypeId=1)
- [[Craftable nametags 1.12.2 - 1.20.1](https://www.curseforge.com/minecraft/mc-mods/nametag/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/nametag/files/all?page=1&pageSize=20)
- [[Hexerei 1.16.5 - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/hexerei/files/all?page=1&pageSize=20)](https://www.curseforge.com/minecraft/mc-mods/hexerei/files/all?page=1&pageSize=20)
- [[Basic nether ores 1.12.2 - 1.21.1](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores/files/all?page=1&pageSize=20&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores/files/all?page=1&pageSize=20&gameVersionTypeId=1)
- [[Every compat 1.18.1 - 1.21.1](https://www.curseforge.com/minecraft/mc-mods/every-compat/files/all?page=1&pageSize=20&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/every-compat/files/all?page=1&pageSize=20&gameVersionTypeId=1)
- [[Vein mining 1.16.4 - 1.21](https://www.curseforge.com/minecraft/mc-mods/vein-mining/files/all?page=1&pageSize=20&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/vein-mining/files/all?page=1&pageSize=20&gameVersionTypeId=1)
- [[Macaw’s roofs 1.12.2 - 1.21.1](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs/files/all?page=1&pageSize=20&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs/files/all?page=1&pageSize=20&gameVersionTypeId=1)
- [[You shall not spawn 1.17 - 1.21.3](https://www.curseforge.com/minecraft/mc-mods/you-shall-not-spawn/files/all?page=1&pageSize=20&gameVersionTypeId=1)](https://www.curseforge.com/minecraft/mc-mods/you-shall-not-spawn/files/all?page=1&pageSize=20&gameVersionTypeId=1)

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by proxyline77** [comment]
![2024-11-15 (1)](https://github.com/user-attachments/assets/12c04a1e-f2bc-49bc-945f-6ef6c1557fde)

**Comment by iron431** [comment]
this is a limitation of 1.18.2 structure generation
