### ISSUE TITLE
[Bug] Servercrash

### ISSUE THREAD

**Issue by HelenaxD** [iron431/Irons-Spells-n-Spellbooks#668]
### Observed behaviour

Our Hostinger Minecraft Java Server is crashing pretty often. I dont know what exactly the issue is. Please help me with that 

### Expected behaviour

no crash

### Steps to reproduce

1. player joined server
2. does something (probably in a new chunk)
3. Server crash

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/HelenaxD/bfffd71580a44057614e5e615ee63fd0.js

### Iron's Spells N Spellbooks version

iron spell version ist 1.20.1-3.4.0.4

### Forge version

Forge 47.3.0

### Other mods

[Just-In WIZARD HAT (by justinoway)](https://www.curseforge.com/minecraft/mc-mods/just-in-wizard-hat)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Connector Extras (by Su5eD)](https://www.curseforge.com/minecraft/mc-mods/connector-extras)
[Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
[REI Plugin Compatibilities (REIPC) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Inventory Pets (by Purplicious_Cow_)](https://www.curseforge.com/minecraft/mc-mods/inventory-pets)
[Icarus (by Cammie)](https://www.curseforge.com/minecraft/mc-mods/icarus)
[A Man With Plushies (AMWPlushies) (by maxsteelbro)](https://www.curseforge.com/minecraft/mc-mods/a-man-with-plushies)
[Ok Zoomer Forge (by matyrobbrt)](https://www.curseforge.com/minecraft/mc-mods/ok-zoomer-forge)
[Sophisticated Storage (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage)
[Macaw's Holidays (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-holidays)
[GlitchCore (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/glitchcore)
[Ice and Fire: Dragons (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
[Mowzie's Mobs (by bobmowzie)](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)
[Additional Attributes (by Cadentem)](https://www.curseforge.com/minecraft/mc-mods/additional-attributes)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[FTB Essentials (Forge & Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials)
[MC Dungeons Armors (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcda)
[Chat Heads (by dzwdz)](https://www.curseforge.com/minecraft/mc-mods/chat-heads)
[Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[Blossom Blade (by joshieman)](https://www.curseforge.com/minecraft/mc-mods/blossom-blade)
[CorgiLib (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/corgilib)
[Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[The Outer End (by BlueDuck)](https://www.curseforge.com/minecraft/mc-mods/the-outer-end)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Lootr (Forge & NeoForge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[Legendary Monsters (by miauczel)](https://www.curseforge.com/minecraft/mc-mods/legendary-monsters)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Unusual End (by Sweetygamer)](https://www.curseforge.com/minecraft/mc-mods/unusual-end)
[Lexiconfig (by CodinGlitch)](https://www.curseforge.com/minecraft/mc-mods/lexiconfig)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Aquamirae (Forge) (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/ob-aquamirae)
[Chunky (Forge/NeoForge) (by pop4959)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator-forge)
[Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
[Additional Lights (by mgen256)](https://www.curseforge.com/minecraft/mc-mods/additional-lights)
[FTB Library (Forge) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-forge)
[Sinytra Connector (by Su5eD)](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Macaw's Furniture (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-furniture)
[Chimes (by CicadaBluw)](https://www.curseforge.com/minecraft/mc-mods/chimes)
[Cut Through (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/cut-through)
[Trading Post [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/trading-post)
[Alex's Caves (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-caves)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Fairy Lights (by pau101)](https://www.curseforge.com/minecraft/mc-mods/fairy-lights)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Decent Biomes (enhanced cherry grove, luminiscent biome, autumnal biomes) (by LillouArts)](https://www.curseforge.com/minecraft/mc-mods/decent-biomes)
[Common Capabilities (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/common-capabilities)
[Obscure API (Forge) (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/obscure-api)
[Long NBT Killer (by Dovecot_Official)](https://www.curseforge.com/minecraft/mc-mods/long-nbt-killer)
[Quad (by LieOnLion)](https://www.curseforge.com/minecraft/mc-mods/quad)
[MC Dungeons Weapons (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdw)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[DarkBlades - RPG End-Game Weapons, Armor, Tools (Fabric/Forge/NeoForge) (by GamerPotion)](https://www.curseforge.com/minecraft/mc-mods/darkblades)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Macaw's Roofs - Oh The Biomes You'll Go / Oh The Biomes We've Gone (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-oh-the-biomes-youll-go)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[Iron’s Spells Artifacts (by Project_Count)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-artifacts)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Apothic Attributes (AttributesLib) (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apothic-attributes)
[Easy Anvils [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-anvils)
[.3D Placeable Food (by LillouArts)](https://www.curseforge.com/minecraft/mc-mods/d-placeable-food-fabric-forge)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[Common Network (by Mysticdrew)](https://www.curseforge.com/minecraft/mc-mods/common-network)
[Carbon Config (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/carbon-config)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Snowy Spirit (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/snowy-spirit)
[aleki's Nifty Ships (by alekiponi)](https://www.curseforge.com/minecraft/mc-mods/alekiships)
[Zeta (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/zeta)
[Balm (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Duckling (by Frogipher)](https://www.curseforge.com/minecraft/mc-mods/duckling)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Rings of Ascension (Forge/NeoForge) (by focamacho)](https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension)
[Embeddium (by FiniteReality)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Macaw's Fences - Oh The Biomes You'll Go / Oh The Biomes We've Gone (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-oh-the-biomes-youll-go)
[The Abyss II - The Other Side (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii)
[Chunk-Pregenerator (by Speiger)](https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Iron Spells Dungeons (by Project_Count)](https://www.curseforge.com/minecraft/mc-mods/iron-spells-dungeons)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Oh The Biomes We've Gone (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-weve-gone)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Cyclops Core (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
[Forgified Fabric API (by Su5eD)](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api)
[Doggy Talents Next (by dashiedev)](https://www.curseforge.com/minecraft/mc-mods/doggy-talents-next)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Every Compat (Wood Good) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/every-compat)
[TipsyLib (by Yirmiri)](https://www.curseforge.com/minecraft/mc-mods/tipsylib)
[BSL Shaders (by capttatsu)](https://www.curseforge.com/minecraft/shaders/bsl-shaders)
[Amendments (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/amendments)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[Whisperwoods (by itsmeowdev)](https://www.curseforge.com/minecraft/mc-mods/whisperwoods)
[Customizable Elytra (by Hidoni)](https://www.curseforge.com/minecraft/mc-mods/customizable-elytra)
[Hexerei (by JoeFoxe)](https://www.curseforge.com/minecraft/mc-mods/hexerei)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[ATO - All the Ores (by ATMTeam)](https://www.curseforge.com/minecraft/mc-mods/ato)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Roughly Enough Items Fabric/Forge/NeoForge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[MNS - Moog's Nether Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/mns-moogs-nether-structures)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[SeasonHUD (by IanAnderson)](https://www.curseforge.com/minecraft/mc-mods/seasonhud)
[All the Wizard Gear (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/all-the-wizard-gear)
[Potacore (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/potacore)
[Illager Warship (by SuperWarioModTeam)](https://www.curseforge.com/minecraft/mc-mods/illager-warship)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[More Vanilla Potions [FORGE&FABRIC] (by SariusPlayz)](https://www.curseforge.com/minecraft/mc-mods/more-vanilla-potions)
[Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
[Allthemodium (by ATMTeam)](https://www.curseforge.com/minecraft/mc-mods/allthemodium)
[Oh The Trees You'll Grow (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/oh-the-trees-youll-grow)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Macaw's Bridges - Oh The Biomes You'll Go / Oh The Biomes We've Gone (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-oh-the-biomes-youll-go)

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
something in your modpack seems to be hanging entity pathfinding. this doesn't look like an issue with this mod

**Comment by HelenaxD** [comment]
You know maybe what could be the problem then?

**Comment by iron431** [comment]
i would try without connector
