### ISSUE TITLE
[Bug] Crash with SimplySwords mod

### ISSUE THREAD

**Issue by TheBooz** [iron431/Irons-Spells-n-Spellbooks#67]
### Observed behaviour

I don't know if this is an issue on SimplySwords' Side or Iron's Spells side, So I apologise if this issue doesn't stem from this mod and will open an Issue ticket over on Simply Swords if it is the case

Using Special abilites of Storm's Edge or Thunderbrand (Both Charged Dash abilities) will crash the game after the Dash ends
However, Applying a Scroll overrides their Special and works fine

### Expected behaviour

Both Storm's Edge and Thunderbrand should be able to Dash without crashing

### Steps to reproduce

1. Have either Storm's Edge or Thunderbrand from Simply Swords
2. Hold M2 To charge their Special abilities
3. It should crash after the Dash ends

### Server Type

Single Player

### Crashlog

https://gist.github.com/TheBooz/17d08fb4e259d1188a4822d2e00b0758

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.1

### Forge version

1.18.2 - 40.2.9

### Other mods

  [✔] architectury-4.11.93-forge
  [✔] bettercombat-forge-1.6.2+1.18.2
  [✔] caelus-forge-1.18.1-3.0.0.2
  [✔] cloth-config-6.4.90-forge
  [✔] curios-forge-1.18.2-5.0.9.1
  [✔] geckolib-forge-1.18-3.0.57
  [✔] irons_spellbooks-1.18.2-1.1.4.1
  [✔] player-animation-lib-forge-1.0.2+1.18
  [✔] simplyswords-forge-1.40-1.18.2

**Comment by iron431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FinishUsingEvent is causing crash](https://trello.com/c/7EznDXE1/645-finishusingevent-is-causing-crash)

**Comment by iron431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [FinishUsingEvent is causing crash](https://trello.com/c/7EznDXE1/645-finishusingevent-is-causing-crash)

**Comment by iron431** [comment]
fixed in v1.1.4.2
