### ISSUE TITLE
Teleport

### ISSUE THREAD

**Issue by Rivik073** [iron431/Irons-Spells-n-Spellbooks#670]
### Description

I think teleport spell is a bit too good for a spell that can be found or made with uncommon ink. It should either be harder to get or have a much longer cooldown.

### Not a feature request

- [X] I understand this is not a content/feature request for the mod (as those are on discord), but for the codebase

**Comment by iron431** [comment]
please keep this kind of discourse on discord, and also you should check the config 👍
