### ISSUE TITLE
[Bug] Functional Blocks (Scroll Forge, ect) do not appear in JEI or Creative (1.20.1)

### ISSUE THREAD

**Issue by Irritated-Badger** [iron431/Irons-Spells-n-Spellbooks#671]
### Observed behaviour

The Alchemist Cauldron, Scroll Forge, Inscription Table, and Arcane Anvil do not appear in JEI or the Creative Menu (even checked the Functional Blocks tab).

![2024-11-18_14 12 57](https://github.com/user-attachments/assets/6b6beae0-4f99-4bf2-9586-93f071ff96e1)
![2024-11-18_14 13 08](https://github.com/user-attachments/assets/3c518301-1191-4cf9-a157-e204891f771b)
![2024-11-18_14 13 29](https://github.com/user-attachments/assets/72902a7f-8851-45e0-aad6-fc329c2721da)
![2024-11-18_14 18 36](https://github.com/user-attachments/assets/772d83a0-d273-4451-9997-89495ab289e8)

### Expected behaviour

For them to appear in JEI and in the Creative Menu

### Steps to reproduce

1. Load Game 
2. Open World
3. Search for one of the functional blocks
4. They do not appear.

### Server Type

Single Player

### Crashlog

https://gist.github.com/Irritated-Badger/4dc0bdf2b08db384c121fa647f84379c

### Iron's Spells N Spellbooks version

3.4.0.4

### Forge version

Forge 37.3.0

### Other mods

[mod list.txt](https://github.com/user-attachments/files/17805989/mod.list.txt)

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
seems to work 
![image](https://github.com/user-attachments/assets/4b736a7b-5a04-4ff1-a013-9d472ecc62a8)
![image](https://github.com/user-attachments/assets/56238032-4fb4-467a-8172-b37ca0748466)

**Comment by Irritated-Badger** [comment]
Checked it with just JEI, Iron's, and Iron's dependencies and they appear without issue. I'll start debugging my modpack tonight. If you'd be willing to keep this issue open for a couple days I'll report back with what I find out.

**Comment by lab3** [comment]
Let us know what you find

**Comment by NebbyTheProtogen** [comment]
do you have any addons to iron's? i have the galosphere addon, arcane essence blocks, and ice and fire addon and i have the same problem, i'll boot up the game without the addons and see what i find

**Comment by NebbyTheProtogen** [comment]
it seems it was not the addons

**Comment by Irritated-Badger** [comment]
No addons, and the bug is inconsistent. It's a combination of mods that I can't pin.

> it seems it was not the addons

What mods do you installed?

**Comment by NebbyTheProtogen** [comment]
[modlist.txt](https://github.com/user-attachments/files/17875019/modlist.txt)

**Comment by NebbyTheProtogen** [comment]
authentic_wizardry is a shitty mcreator mod that adds a few recipies btw, by yours truly

**Comment by NebbyTheProtogen** [comment]
just so you don't overthink that because it's not really worth considering

**Comment by Irritated-Badger** [comment]
We have several mods in common, so it's has to be one or a combination of them. I'm not going to be able to get on my pc for a couple days due to irl things but when I get back I'll start debugging again.

**Comment by lab3** [comment]
Also, this may be related to https://github.com/iron431/irons-spells-n-spellbooks/issues/675

**Comment by NebbyTheProtogen** [comment]
i checked for it and no, ironbound tome appears for me

**Comment by Irritated-Badger** [comment]
I don't have issues with the tomes other than the textures in JEI are broken, but figured that was related to Modern Fix.

**Comment by VaporeonScripts** [comment]
same, broken texture for me too

**Comment by Irritated-Badger** [comment]
So far I've narrowed the issue about the missing blocks to two mods, Balm and Polymorph. Together with just JEI, Iron's, and Iron's requirements they work fine. The issue is somewhere in this mod list:

[sussymods.txt](https://github.com/user-attachments/files/17891326/sussymods.txt)

On the subject of the broken tome textures, yeah, their busted.
![2024-11-23_16 54 32](https://github.com/user-attachments/assets/0b8798a9-a1a8-4ee9-93af-5cd4f63347eb)
 That's just with Irons and it's dependencies installed (plus JEI).

**Comment by iron431** [comment]
> On the subject of the broken tome textures, yeah, their busted.

apparently this is a jei issue. ive reported it to them
https://github.com/mezz/JustEnoughItems/issues/3856

**Comment by Irritated-Badger** [comment]
I added a comment to the bug report you made adding that the issue also appears in JEI version 15.20.0.105 on Forge version 47.3.0.

As for the missing functional blocks go, I give up. The blocks disappear after 45 mods are loaded. **Any** 45 mods. I've tried various combinations mods to pin it down but it's always the same thing. Forge loads up 45 mods, the blocks vanish. 44 or less, their there. 
I tried creating a fresh instance with completely unrelated mods, switching Forge versions, switching to NeoForge, adding EMI, removing JEI just for EMI, all end in the same result, 45 mods loaded, the blocks disappear. There is some combination of mods withing mine and [NebbyTheProtogen](https://github.com/NebbyTheProtogen)'s mod lists that causing the issue.

The crazy thing is, I downloaded a random pack that had 200+ mods, including Iron's, and the blocks were present. So I don't know what to do.

**Comment by Irritated-Badger** [comment]
It's Supplementaries Squared with something else, I can't figure out what though. With Iron's + Dependencies, JEI, Supplementaries, and Supplementaries Squared, no issue. As soon as more mods are added to the pack the blocks will disappear. They come as soon as Supplementaries Squared is removed.

**Comment by AquaticPlush** [comment]
Apologies for dredging up an old issue, but for those still experiencing this issue:
While far less than ideal, there is a slight work-around to view these recipes in JEI. 

The Iron's recipes will be listed if you check the uses for a material in JEI (hover over the item and tap the 'U' key by default.)
Ex: Searching for avail uses will list the Arcane Anvil. 
Then you can add the item to your personal JEI bookmarks (hover over the item and tap the 'A' key)

Here's a list of materials that tend to have fewer uses:
Any Wood Fence > Inscription Table
Cauldron > Alchemist's Cauldron
Anvil > Arcane Anvil
Lantern > Firefly Jar
