### ISSUE TITLE
[Bug] Griefing

### ISSUE THREAD

**Issue by BazZziliuS** [iron431/Irons-Spells-n-Spellbooks#673]
### Observed behaviour

I think you won't do it, but I have to try
I have a server where I use your mod and we play and have fun, but spells don't check if they can come from a fake player so that the private territory check works
Why do players kill other players in a place where it is not allowed

### Expected behaviour

I hope you can add checks for everything that can kill or break territory or build on it like portals

### Steps to reproduce

It's trivial to put a portal on the private territory of World Guard or FTB Chunks

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.4.0

### Forge version

Forge: 47.3.10

### Other mods

https://paste.fuix.net/RPo3hte

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
sorry, can you explain the issue? what is strictly not working

**Comment by BazZziliuS** [comment]
> извините, можете ли вы объяснить проблему? Что именно не работает?

Check for private territory
Spells can be used where the player is not a participant or owner of the region

**Comment by lab3** [comment]
What does "private territory" mean?  This is not a vanilla feature.  Is this compatibility with a specific mod?  We can't do anything if you don't provide the full details of your issues including your specific configuration and reproduction steps.

**Comment by BazZziliuS** [comment]
Private territory is a place where the player who has privated it can use it, and PvP is disabled in it, as well as the ability to break blocks for players who are not included in the list of participants in the territory.

As an example, there is such a plugin https://dev.bukkit.org/projects/worldguard or mod https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-forge

**Comment by lab3** [comment]
1. Please provide the EXACT mod you are using not examples of mods that are like it.
2. Provide the configuration for that mod
3. Provide the EXACT set of steps to reproduce the problem.

**Comment by BazZziliuS** [comment]
I use https://dev.bukkit.org/projects/worldguard
Just lock the territory and let another player who is not in your private conjure a portal and it will appear although it should not because this player is not in your region and he does not have access to it
A similar situation with other spells

**Comment by BazZziliuS** [comment]
I understood from our communication that you did not play on servers where there are privates, but believe me that the problem is quite serious since it destroys what it should not or damages

**Comment by iron431** [comment]
we do not support plugins

**Comment by BazZziliuS** [comment]
Just specify checks from the fake player if you cast or install something, and the plugin will handle it itself
