### ISSUE TITLE
[Bug] Missing Ingot Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [iron431/Irons-Spells-n-Spellbooks#674]
### Expected behaviour

Mithril Ingots should have the `c:ingots` item tag.
Arcane Ingots should have the `c:ingots` item tag, as well as the `c:ingots/arcane` item tag.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21.1 - 3.8.4

### Forge version

Neoforge - 21.1.79

### Other mods

Observed in ATM10 - 1.22.

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
Arcane ingots do not have a tag because they are not a generic material; Arcane Ingot is the one and only arcane ingot. The other tags will be added

**Comment by iron431** [comment]
fixed in 3.8.5
