### ISSUE TITLE
[Bug] missing tome in jei

### ISSUE THREAD

**Issue by VaporeonScripts** [iron431/Irons-Spells-n-Spellbooks#675]
### Observed behaviour

if i try to search the tome (the one u craft with 3 chains, leather and paper) it wont appear
![image](https://github.com/user-attachments/assets/7f7713b8-7f23-4283-858f-b1a9d37aa448)

### Expected behaviour

jei showing the tome

### Steps to reproduce

install jei and the mod

### Server Type

Single Player

### Crashlog

no?

### Iron's Spells N Spellbooks version

latest

### Forge version

neoforge .80

### Other mods

many

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by meeprdib** [comment]
Are you playing a premade modpack or one you made yourself?

**Comment by VaporeonScripts** [comment]
NeoTech Reborn

**Comment by meeprdib** [comment]
Ask the modpack developers, they may have removed the item from the game.

**Comment by VaporeonScripts** [comment]
im the owner of the modpack :sob: and i defo didnt hide it bruh, its craftable, but i cant find it by searching it

**Comment by meeprdib** [comment]
oh LMAO my bad

**Comment by lab3** [comment]
Can you launch the game, enter the world search for the items and then send the latest and debug logs.  Maybe something there will help us understand what is going on.

**Comment by lab3** [comment]
This may be related to https://github.com/iron431/irons-spells-n-spellbooks/issues/671

**Comment by VaporeonScripts** [comment]
> Can you launch the game, enter the world search for the items and then send the latest and debug logs. Maybe something there will help us understand what is going on.

aight, doing it rn

**Comment by VaporeonScripts** [comment]
https://mclo.gs/XCnyDg0

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/6db78a33-4efa-40fe-9ac3-29c422592e22)

**Comment by VaporeonScripts** [comment]
found it, but buggy texture

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/f79ffcde-2746-446c-a22f-eeda5ad22fc9)

**Comment by iron431** [comment]
@VaporeonScripts the texture is due to a JEI issue. ~~How did you get it to appear?~~ I see it was always there, just hard to see

**Comment by VaporeonScripts** [comment]
should i report to jei then

**Comment by iron431** [comment]
i already have https://github.com/mezz/JustEnoughItems/issues/3856
