### ISSUE TITLE
[Bug] Whitelisting a Item for Arcane Anvil's imbue system still showing other JEI Recipes

### ISSUE THREAD

**Issue by Sebedidep** [iron431/Irons-Spells-n-Spellbooks#676]
### Observed behaviour

So when i put a single item into the whitelist in irons_spellbooks-server.toml, for example:
`imbueWhitelist = "minecraft:iron_sword"]`
its still showing up all possible recipes for the arcane anvil imbue system in JEI. 

### Expected behaviour

I would expect to only show the white listed items. All the other should not get registered. 

The list for the arcana anvil in my modpack has 45 sites and is using around 1GB of memory alone for these recipes to show up in jei. 
The memory allocation would be even higher if i would use more weapon mods. At the moment i have mods installed like simplyswords or l2weaponry.
This problem doesnt exist in EMI, cause emi isnt showing anvil recipes without jei. 

I would love to have an option to completly disable the feature to imbue weapons from other mods. 

Have a nice weekend!

### Steps to reproduce

Whitelist a single item from minecraft for the imbue system in the server config
look up the recipe in jei for arcane anvil, all scrolls and weapon combinations are showing up
 

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.4

### Forge version

47.3.12

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
i would double check what version you are using because the arcane anvil jei memory has been significantly optimized; unless there are hundreds of imbueable items i would not expect it to be using that much memory anymore. if you could provide a memory dump, that would also be helpful

**Comment by Sebedidep** [comment]
Your guess is correct. It is heavily optimized. (using <1MB for recipes in my case)
EMI does not have all the features from JEI and thats the point. The features just need memory. 
After i used spark to clean up the memory i saw that the difference in memory allocation between loaded with and without jei and it is sticking around 300MB (2.4GB -> 2.7GB). 
So probably another mod having issues. 

Good weekend and have a nice day
