### ISSUE TITLE
[Bug] Crash when picking up Apothecarist with entity moving devices

### ISSUE THREAD

**Issue by MuteTiefling** [iron431/Irons-Spells-n-Spellbooks#677]
### Observed behaviour

If I pick up an apothecarist with a Soul Gem (Occultism) or Creature Catcher (Just Dire Things), the game crashes.

### Expected behaviour

No crash

### Steps to reproduce

1. spawn in apothecarist
2. attempt to pick up with any creature moving device
3. crash

### Server Type

Single Player

### Crashlog

https://mclo.gs/Pv28wc7

### Iron's Spells N Spellbooks version

irons_spellbooks-1.21-3.8.4

### Forge version

21.1.80

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
fixed in 3.8.6
