### ISSUE TITLE
[Bug] Error crash during loading with Tetra

### ISSUE THREAD

**Issue by rndmninja** [iron431/Irons-Spells-n-Spellbooks#678]
### Observed behaviour

I got a crash during starting up the game with Tetra and Iron's Spellbooks

### Expected behaviour

I expected Iron's Spellbook to have support to Tetra, and my game would load normally.

### Steps to reproduce

1. Download latest version of Forge (47.3.12) MC Version 1.20.1 in CurseForge
2. Download Tetra and Iron's Spellbook
3. Start up the game
4. Crash!

### Server Type

Single Player

### Crashlog

https://gist.github.com/rndmninja/57d40a7cbfebf6965ea2923ca4f6c20f

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.4

### Forge version

Forge 47.3.12

### Other mods

I tried it without my massive mods and the issue still occurred. These are the only mods that I used and they are the dependencies.
- Caelus API (Forge-3.20+1.20.1)
- Curious API (Forge-5.11.0+1.20.1)
- playerAnimator (Forge-1.0.2-rc1+1.20)
- mutil (1.20.1-6.1.1)
- GeckoLib (Forge-1.20.1-4.4.9)

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by meeprdib** [comment]
The Tetra compat that ISS has seems to be outdated with Tetra's new update. Reach out to the Tetra developer and see what needs to be changed to resolve the issue.

**Comment by iron431** [comment]
according to mickelus it sounds like an issue on his end

**Comment by iron431** [comment]
fixed in 3.4.0.5

**Comment by slottwo** [comment]
Is this mod's page on [Modrinth](https://modrinth.com/mod/irons-spells-n-spellbooks/versions?g=1.20.1&l=forge) official? Because there is only version 3.4.0 for Minecraft Forge 1.20.1. It took me a while to realize that the latest version would be on CurseForge.

**Comment by meeprdib** [comment]
Yes, it's official, just behind.
