### ISSUE TITLE
[Bug] absurd amount of magic tower houses in village.

### ISSUE THREAD

**Issue by Darkmega18** [iron431/Irons-Spells-n-Spellbooks#68]
### Observed behaviour

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/8104689/51781762-224c-4263-91d6-5930a12b8ff0)

Not sure what happened, but the vast majority of houses in this village are the towered ones that have a chest and go up to a book table. My friend who's actually wanting to really get into the mod is loving it, but I just think it's a little sus over-all.

### Expected behaviour

that there might be something other than wizard houses.

### Steps to reproduce

yes. I'm just playing the video game.

I have better villages if thats any indication of what could happen. did you overdo the weight on them...? :V

### Server Type

Playing on server currently.

### Crashlog

there isn't.

### Iron's Spells N Spellbooks version

irons_spellbooks-1.19.2-1.1.5.jar

### Forge version

1.19.2: 43.2.14

### Other mods

yes. (it's a pretty big pack...)

**Comment by briarss** [comment]
this is a bug with "Better Villages", and only in plains biomes.

**Comment by Darkmega18** [comment]
I thought one would have to apply a weight to the structures etc and how often they'd spawn meaning it'd be the offender's structure that was set too high?

**Comment by iron431** [comment]
This is already fixed, just pending release in the next update.

**Comment by Darkmega18** [comment]
roger that. thanks iron.
