### ISSUE TITLE
[Bug] [1.21.1] playerAnimator dependency is not supporting 1.21.1

### ISSUE THREAD

**Issue by DKSteffenDE** [iron431/Irons-Spells-n-Spellbooks#680]
### Observed behaviour

On curseforge, I can add "Iron's Spells 'n Spellbooks" as a mod to my modpack for 1.21.1, using NeoForge.
But when running Minecraft, I get an error that playerAnimator 2.0.0-alpha1+1.21 or above is required.

The problem is that playerAnimator have not yet made a version that can be added with curseforge, for 1.21.1 for NeoForge.
(see: https://www.curseforge.com/minecraft/mc-mods/playeranimator/files/all?page=1&pageSize=20&gameVersionTypeId=6 )

### Expected behaviour

I expected that the dependency would be valid for 1.21.1,
or at least a note somewhere that it needs to be added manually for now.

### Steps to reproduce

Create new modpack in curseforge, for Minecraft 1.21.1, with neoforge.
add "Iron's Spells 'n Spellbooks" mod.
start minecraft.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.21-3.8.5

### Forge version

Neoforge - 21.1.81

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
playeranimator 1.21 is compatible with 1.21.1
