### ISSUE TITLE
Missing item

### ISSUE THREAD

**Issue by MuteTiefling** [iron431/Irons-Spells-n-Spellbooks#681]
![image](https://github.com/user-attachments/assets/90e5662a-5960-4977-9b47-06425383c69a)

The recipes for mithril weave and paladin chestplate are erroring out in KubeJS, seemingly because the base item is disabled

https://github.com/iron431/irons-spells-n-spellbooks/blob/01d4eca3985e00798b37a45e00fcec32fa78c0c6/src/main/java/io/redspace/ironsspellbooks/registries/ItemRegistry.java#L173

![image](https://github.com/user-attachments/assets/02c27b28-562e-4388-ba71-90ff4a44e097)
![image](https://github.com/user-attachments/assets/2ea292b7-faf9-4449-9907-6d9c79e95321)
![image](https://github.com/user-attachments/assets/005ba0e5-b5a8-487c-bfdf-1ede4b0a0a6e)

**Comment by iron431** [comment]
that would be because the items are indeed disabled. is this causing compatible errors or just a warning?

**Comment by MuteTiefling** [comment]
Just error spam. Nothing big just figured I'd bring it up

**Comment by iron431** [comment]
this will be naturally resolved when the items are added, not concerned about it otherwise

**Comment by Neverywhere** [comment]
Came here to report this, very sleek mod :+1:
