### ISSUE TITLE
[Performance] Memory Leak of entities

### ISSUE THREAD

**Issue by pietro-lopes** [iron431/Irons-Spells-n-Spellbooks#682]
### Observed behaviour

Follow up of #651 as it is the same issue.
It is leaking some discarded projectiles in this map.

maybe change this to consider a logic when Entity is null and remove from the map? (need to use iterator to not throw CME)
https://github.com/iron431/irons-spells-n-spellbooks/blob/19768be79186a6438396b42b3b5ee7868a147804/src/main/java/io/redspace/ironsspellbooks/effect/guiding_bolt/GuidingBoltManager.java#L107-L120

![image](https://github.com/user-attachments/assets/76a5c6b8-93e7-4664-ae0a-53596a470273)

### Expected behaviour

Not leak

### Steps to reproduce

This was a heapdump from a server.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

3.8.4

### Forge version

neoforge 21.1.81

### Other mods

ATM10 Modpack

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
fixed in 3.8.6
