### ISSUE TITLE
[Bug] irons_spellbooks-1.20.1-3.4.0.5 Multiple "Failed to Load texture" errors shown in logs

### ISSUE THREAD

**Issue by Minebrah** [iron431/Irons-Spells-n-Spellbooks#684]
### Observed behaviour

The game will unexpectedly crash while exploring. I check my logs and it shows this mod throwing some errors before crashing. 

[02Dec2024 10:26:45.355] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: minecraft:textures/models/armor/archevoker_layer_2.png
java.io.FileNotFoundException: minecraft:textures/models/armor/archevoker_layer_2.png
[02Dec2024 10:26:45.461] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: minecraft:textures/models/armor/wandering_magician_layer_1.png
java.io.FileNotFoundException: minecraft:textures/models/armor/wandering_magician_layer_1.png

### Expected behaviour

No log spam and for the game to run smoothly

### Steps to reproduce

Explore. Errors will be thrown in logs

### Server Type

Single Player

### Crashlog

https://gist.github.com/Minebrah/d7f5e2ec1b53f228d56454d791a8bc48

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-3.4.0.5

### Forge version

FORGE 1.20.1 - 47.3.12

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by meeprdib** [comment]
Those aren't fatal issues by the looks of it, and the log seems to end abruptly. Can you send a crash log file instead?

**Comment by iron431** [comment]
that is not a crashlog, attach the corresponding file from the crashlogs direcctory.

**Comment by Minebrah** [comment]
Hello good people and thank you for the quick response. So the thing is that whenever the game crashes it doesn't give me a crash log. It just hard crashes and sends me to the main menu or sometimes even the pc will just freeze and I am forced to restart it. It happens repeatedly and your mod is always one of the last things to pop up on the logs before it crashes. This mod is amazing and I doubt its the only culprit but I question if these errors contribute some way to the game lagging and inevitably crashing. Any help would be appreciated. Thank you.

**Comment by meeprdib** [comment]
You checked your `crash-reports` folder and there was nothing?

**Comment by lab3** [comment]
If you launch the app using the prism launcher you should see the hard crash in the output from prism

**Comment by lab3** [comment]
Also, from the log you did post it looks like it's missing a registry item from apotheosis

<img width="2017" alt="image" src="https://github.com/user-attachments/assets/6a07750b-ddd3-41d3-8c38-6b33216dbb7e">

**Comment by Minebrah** [comment]
> If you launch the app using the prism launcher you should see the hard crash in the output from prism

Thank you, I just downloaded Prism Launcher and transferred all my files over. It looks promising, its midnight now, I only got a quick chance to test it out on the new launcher and the game did show those errors in the log before the game crashed again. 

[23:50:03] [Render thread/WARN] [minecraft/TextureManager]: Failed to load texture: minecraft:textures/models/armor/archevoker_layer_1.png
java.io.FileNotFoundException: minecraft:textures/models/armor/archevoker_layer_1.png
	at net.minecraft.server.packs.resources.ResourceProvider.m_215590_(ResourceProvider.java:21) ~[client-1.20.1-20230612.114412-srg.jar%231656!/:?] {re:classloading,re:mixin}

However in this case it looks like even though its spitting out errors from this mod, it looks like another mod "parcool" ultimately caused the game to crash. I could be wrong though I'm not very good at reading these logs. 

https://[gist.githubusercontent.com/Minebrah/a0b8b89c77f8cd3182b80884cafcbd34/raw/557c9dd49fd932db342099da75db8de4e356fbd1/gistfile1.txt](https://gist.githubusercontent.com/Minebrah/a0b8b89c77f8cd3182b80884cafcbd34/raw/557c9dd49fd932db342099da75db8de4e356fbd1/gistfile1.txt)

Thank you again for the help. I will run some tests tomorrow and see if anything related to this mod comes up.

**Comment by meeprdib** [comment]
Issue is not caused by ISS
https://github.com/Shadows-of-Fire/Apotheosis/issues/1403#issuecomment-2519168859

**Comment by Minebrah** [comment]
Understood. I've redirected the reports to the appropriate mod authors. Before closing the bug report I was wondering, does this mean I can disregard the errors being shown in the logs? Do they not affect or have a significant effect on the game?

02Dec2024 10:21:43.606] [Render thread/ERROR] [placebo/]: Codec failure for type gear_sets, message: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: irons_spellbooks:scarecrow_helmet; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: irons_spellbooks:scarecrow_chestplate; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: irons_spellbooks:scarecrow_leggings; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: irons_spellbooks:scarecrow_boots
[02Dec2024 10:21:43.606] [Render thread/ERROR] [placebo/]: Failed parsing gear_sets file apotheosis_ascended:overworld/irons_spellbooks/scarecrow.
[02Dec2024 10:21:43.606] [Render thread/ERROR] [placebo/]: Underlying Exception: 
java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: irons_spellbooks:scarecrow_helmet; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: irons_spellbooks:scarecrow_chestplate; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: irons_spellbooks:scarecrow_leggings; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: irons_spellbooks:scarecrow_boots

[02Dec2024 10:26:45.467] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: minecraft:textures/models/armor/wandering_magician_layer_1.png
java.io.FileNotFoundException: minecraft:textures/models/armor/wandering_magician_layer_1.png

02Dec2024 10:26:45.355] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: minecraft:textures/models/armor/archevoker_layer_2.png
java.io.FileNotFoundException: minecraft:textures/models/armor/archevoker_layer_2.png

There are more errors being shown these are just a few.

**Comment by iron431** [comment]
these are not problematic, no
