### ISSUE TITLE
[Bug] Frostward Ring making a constant ice breaking sound that only other players can hear

### ISSUE THREAD

**Issue by TheBloodSamurai2** [iron431/Irons-Spells-n-Spellbooks#685]
### Observed behaviour

When equipped, the frostward ring makes annoying, constant ice-breaking sounds that only players around you can hear. The ring's functionality is normal, but its loud sound is not.

### Expected behaviour

The frostward ring would not make any sound.

### Steps to reproduce

1. Equip a frostward ring
2. Ask a player to go near you, or go near a player.
3. The other player will hear this loud noise

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

Version: 1.20.1-3.4.0.5

### Forge version

1.20.1 - 47.3.10

### Other mods

Curios API: 5.11.0-1.20.1

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
the frostward ring does not do anything with sounds. attach all mods you are using; there is probably one that plays a sound when player freeze is cleared

**Comment by meeprdib** [comment]
This is an issue with Ice and Fire: Spellbooks.
https://github.com/AceTheEldritchKing/Ice_And_Fire_Spellbooks/issues/4
