### ISSUE TITLE
Crash when entering mage tower (something related to rendering an entity/couldn't find bone)

### ISSUE THREAD

**Issue by DeadGator** [iron431/Irons-Spells-n-Spellbooks#688]
### Observed behaviour

I was playing cisco's rpg modpack (added some mods for myself as well) and i went to visit a mage tower and the game froze and said ''saving world'' and crashed.

This happened when i visited the infested temple from Dungeons Arise as well, not sure what this is causing it, but wanted to report this just in case.

### Expected behaviour

Not crash lol

### Steps to reproduce

Install Cisco's RPG Modpack (ULTIMTATE)
Find a mage tower
Try entering it

### Server Type

Single Player

### Crashlog

https://gist.github.com/DeadGator/d559ee24f79f4008c40e70d432e1af42

### Iron's Spells N Spellbooks version

1.19.2 - 3.4.0

### Forge version

43.3.5

### Other mods

![1](https://github.com/user-attachments/assets/a246a5fa-f8e3-4008-8a52-0ec84f6b8e63)
![2](https://github.com/user-attachments/assets/1a276695-1ca7-4b17-a781-7c3fcfd064c8)

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
because this does not happen with just 1.19.2 spells n spellbooks and because 1.19.2 is no longer supported, this will not be handled

**Comment by DeadGator** [comment]
> because this does not happen with just 1.19.2 spells n spellbooks and because 1.19.2 is no longer supported, this will not be handled

But do you have an idea what causes this? An incompatibility with a certain mod? Should i post on geckolib's github page? Idk how to read crash reports

**Comment by iron431** [comment]
geckolib 3 is also no longer supported. i would ask the cisco discord, esepcially if they have any custom configuration or made any big changes recently
