### ISSUE TITLE
[Bug] Priests are getting seen as hostile mobs by Iron golems and this mod Guard Villagers

### ISSUE THREAD

**Issue by GgGuysYouKnowWhy** [iron431/Irons-Spells-n-Spellbooks#689]
### Observed behaviour

Priests are getting killed and treated as hostile mobs by iron golems and the guard villagers somehow?

### Expected behaviour

Priests to not be killed by these non hostile mobs as well

### Steps to reproduce

Just spawn a priest next to an iron golem or if u have the guard villagers mod try to spawn it near them they'll insta lock on as if they're a hostile mob

### Server Type

Single Player

### Iron's Spells N Spellbooks version

v1.20.1-3.4.0.5

### Forge version

Forge 1.20.1

### Other mods

Guard Villagers

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
Looks fine to me. Event accidently spellcasts don't aggro them, as they are allied mobs. what other mods are you using?
![image](https://github.com/user-attachments/assets/e06a48bb-eb7a-4257-965e-ba7a0c2f7258)
