### ISSUE TITLE
balance and useability thoughts

### ISSUE THREAD

**Issue by Darkmega18** [iron431/Irons-Spells-n-Spellbooks#69]
### Feature description

I feel like the boosts that you're giving in a lot of places, from apoth gems to armor in areas such as cooldown, magic type strength and cast rate etc are all hilariously low. Mana might be somewhat decent, but all others are in such miniscule percentages that they might aswell do nothing.
like adding 1 damage but only if you round up, pretty much at all times on all levels of spells. I feel like better values, atleast for the skill damage strengths that I'm seeing around, would be atleast in the 10s or 20s of percentages so that something of 10 damage becomes 11-12 damage and so on. This is especially the case where to get any benefit you require a level of school focusing in a mod that requires rng and semi-rng loot finding and enchant like crafting for spells, the percentages should be a lot higher so you feel like you really are specializing and becoming powerful in your chosen class and feel rewarded for finding your spell sets.

Same when it comes to such tiny percentages with cooldown or cast rate like 2 or 3%. These won't make any mentally discernable change to a long cooldown spell... _(woohoo, 1.2 seconds off a 60 second recharge, I'm glad I took several hours of exploring to find that one thing!)_
Unless you do some serious multi equipment piece upgrading and stacking specifically for equipment basically the whole entire game over multi sources and gear tiers (affix rolling, gem sticking, piece upgrading, book.) just for like maybe 20% if you're lucky. That should be the upper bounds for a set's natural cooldown reduction before anything is tacked on it especially If it's the mod's specialized armors etc _(but so you never reach the point where it's free/timeless casting when stacked they should be multiplicatively scaled rather than a total additive percentage then subtracted.)_

I consistently see around 25-50 mana boosts on affixed armors etc on blue and below dropping randomly or from bosses which is half decent when stacked. But I haven't strongly gotten into casting yet, however my friend seems to be enjoying looting and pillaging for spells and gear pieces to augment himself. But I don't think he can get anywhere close to bursting large things down as fast as I can with a mere dagger and some stealth+parkour skills. :V

so please consider raising the levels on your offered bonuses and such so that you can actually feel a real difference between having and not having such benefits so it's competitive with simply going with anything else like more armor or sets that provide potions etc etc.

### How it improves the player experience

yes.

**Comment by iron431** [comment]
The base mod is balanced towards vanilla. If you're using in a modpack, such as when using apotheosis, you have the ability to use datapacks or other mods such as crafttweaker to balance all attributes and bonuses to your liking.

**Comment by Darkmega18** [comment]
welp. frick.

**Comment by Darkmega18** [comment]
I honestly still don't think even for vanilla 1.2 seconds of cooldown reduction is worth anything at all. this isn't just me saying, "stonks the damage, more big numbers" this is actually an in general hot take that concerns me that you think it's ok for a "benefit" that can take several hours to an entire playthrough to even find... :V Vanilla or not, it's a little sucky.

**Comment by SiverDX** [comment]
you can easily adjust the balance via datapack here

https://github.com/iron431/Irons-Spells-n-Spellbooks/tree/1.19.2/src/main/resources/data/irons_spellbooks/affixes

https://github.com/iron431/Irons-Spells-n-Spellbooks/tree/1.19.2/src/main/resources/data/irons_spellbooks/gems

**Comment by Darkmega18** [comment]
and whatabout the balance on equipment, not affixes and gems? I might be able to tweak apotheosis, but I can't tweak the stuff you give things innately like the books, robes and upgrades. I only see a way to adjust the damage itself and the actual point for point cooldowns etc, not the benefits gained from upgraded gear that intrinsically comes with items from the mod.

**Comment by iron431** [comment]
there are many mods that let you change item's attributes

**Comment by Darkmega18** [comment]
!!! oh right. they're attributes? cause apoth can actually manipulate them and usually it runs on attribute related things. 

that... completely passed me by honestly. so, sorry.
In that case, I do have a mod I'm using right now that I can use to fiddle with them.
