### ISSUE TITLE
[Bug] add option to disable book from being given on first join (forge 1.20.1)

### ISSUE THREAD

**Issue by VaporeonScripts** [iron431/Irons-Spells-n-Spellbooks#692]
### Observed behaviour

title

### Expected behaviour

title

### Steps to reproduce

no

### Server Type

Single Player

### Crashlog

no

### Iron's Spells N Spellbooks version

latest

### Forge version

forge 1.20.1 .12

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by meeprdib** [comment]
This isn't a bug, and you can remove the book from spawning at world join through a datapack.

**Comment by VaporeonScripts** [comment]
Idk how to make a datapack

**Comment by meeprdib** [comment]
try this https://www.curseforge.com/minecraft/texture-packs/iron-spellbooks-patchouli-book-removal

**Comment by VaporeonScripts** [comment]
Wouldn't it be just easier to add a config option to disable it ? 🤔

**Comment by meeprdib** [comment]
![image](https://github.com/user-attachments/assets/29e3f39a-f10e-472b-8c4f-1c4f4257f40a)

**Comment by VaporeonScripts** [comment]
i cant code :sob:

**Comment by iron431** [comment]
1) you installed patchouli
2) datapacks arent coding
3) thats literally a link to an already made datapack
4) if its so much easier to make a config, go make a pull request https://github.com/iron431/irons-spells-n-spellbooks/pulls
