### ISSUE TITLE
[Bug] Incompatibility with Vampirism mod

### ISSUE THREAD

**Issue by SoyKato** [iron431/Irons-Spells-n-Spellbooks#693]
### Observed behaviour

Hello, im using Iron's Spells on a modpack with Vampirism Mod by maxanier on a serer and this one crashes, i took a look in the logs/crash reports and apparently there's a issue with this two mods, here the log and crash report:
[Crash-report.txt](https://github.com/user-attachments/files/18232167/Crash-report.txt)
[last_log.txt](https://github.com/user-attachments/files/18232168/last_log.txt)

### Expected behaviour

Fix a posible incompatibility

### Steps to reproduce

1. Start Server
2. Go arround and found a village with vampire villages
3. Server crashes

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/SoyKato/afb1480dd662ab4d343016aaee4e05d0

### Iron's Spells N Spellbooks version

1.20.1-3.4.0.5

### Forge version

1.20.1 - 47.3.0

### Other mods

|Vampirism                     |vampirism                     |1.10.12  

### Crashlog Check

- [X] I understand if this is a crashbug and I did not attach a crashlog, this will not be handled

**Comment by iron431** [comment]
nothing in this log suggests it is spellbooks or vampirism... how are you drawing that conclusion?

**Comment by SoyKato** [comment]
I send the crash report on forge server at first, because i didnt know what
happend and i’ve never seen that error before, someone there told me is a
posible incompatibility

**Comment by iron431** [comment]
well there is nothing i can fix or even investigate, so i will be closing this issue
