### ISSUE TITLE
[Bug] Mod ID: 'caelus', Requested by: 'irons_spellbooks', Expected range: '[1.19.4-3.0.0.10,)', Actual version: '[MISSING]'

### ISSUE THREAD

**Issue by ProsperCraft** [iron431/Irons-Spells-n-Spellbooks#70]
### Observed behaviour

As found in the debug log-

[27Jun2023 09:01:35.524] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'caelus', Requested by: 'irons_spellbooks', Expected range: '[1.19.4-3.0.0.10,)', Actual version: '[MISSING]'

### Expected behaviour

It would know what it is looking for.

### Steps to reproduce

Install on a dedicated server.

### Server Type

Dedicated Server

### Crashlog

https://gist.githubusercontent.com/ProsperCraft/09b9bdb5c197a836cc472e8e04e0949e/raw/73701aa950c1b239305c2de4279391b9f8635a57/gistfile1.txt

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.6

### Forge version

forge-1.20.1-47.0.34

### Other mods

TownCraft for 1.20.1 modpack

**Comment by iron431** [comment]
do you have the latest version of Caelus installed?
