### ISSUE TITLE
[Bug] Quick cast shortcut throws java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by AlterazGohg** [iron431/Irons-Spells-n-Spellbooks#72]
### Observed behaviour

When using a spellbook with X spell slots, using the Quick Cast shortcut for slots above X throws a java.lang.ArrayIndexOutOfBoundsException and crashes.

### Expected behaviour

The game should ignore the shortcut if it is invalid, or at least display an error, not to crash entirely.

### Steps to reproduce

1. Get any spellbook. For instance, the Ironbound spellbook. It has 5 slots.
2. Use any Quick Cast shortcut above the available slots. With the Ironbound spellbook: any slot above 5
3. The game crashes.

### Server Type

Single Player

### Crashlog

https://gist.github.com/AlterazGohg/ca25493a57c60b51d9d282e1d39389ab

### Iron's Spells N Spellbooks version

1.19.2-1.1.6

### Forge version

1.19.2-forge-43.2.14

**Comment by iron431** [comment]
yep. this is a pretty dumb oversight on our end. im surprised no one has run into it sooner

**Comment by AlterazGohg** [comment]
I assume nobody ran into it because keys being valuable in large modpacks, they used the spell wheel instead.

Thank you for the fix ! Keep up the good work,  your mod is incredible !
