### ISSUE TITLE
[Bug] After I dig Armor Pile in the server, the server crashes.

### ISSUE THREAD

**Issue by Js23333** [iron431/Irons-Spells-n-Spellbooks#73]
### Observed behaviour

After I dig Armor Pile in the server, the server crashes.

### Expected behaviour

After I dig Armor Pile in the server, the server crashes.

### Steps to reproduce

After I dig Armor Pile in the server, the server crashes.

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Js23333/f60c9aee9e60893834c42b2ccd6f1a1e

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.5

### Forge version

1.20.1-47.0.34

**Comment by iron431** [comment]
I cannot reproduce this, and your log does not reference this mod. Are you sure this is the issue?

**Comment by Js23333** [comment]
v1.20.1-1.1.6.1 does not have this problem

**Comment by Js23333** [comment]
v1.20.1-1.1.6.1 does not have this problem
I'm not very good at using email

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年6月29日 2:55
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [iron431/Irons-Spells-n-Spellbooks] [Bug] After I dig Armor Pile in the server, the server crashes. (Issue #73)


I cannot reproduce this, and your log does not reference this mod. Are you sure this is the issue?

―
