### ISSUE TITLE
[Bug] Sidnedness issue when run on a dedicated server

### ISSUE THREAD

**Issue by ProsperCraft** [iron431/Irons-Spells-n-Spellbooks#74]
### Observed behaviour

Please reference https://github.com/KosmX/minecraftPlayerAnimator/issues/68 

### Expected behaviour

No clientside code running on the server.

### Steps to reproduce

Install the mod and deps.
Run on a dedicated server.

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.6

### Forge version

forge-1.20.1-47.0.19

### Other mods

TownCraft for 1.20.1

**Comment by iron431** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks/relations/dependencies

**Comment by ProsperCraft** [comment]
Are you going to fix the clientside code loading on the server? 

The link to your deps doesn't answer anything.  

A link to changed code would be more of what I was looking for.

**Comment by iron431** [comment]
> HorseStatsMod (horsestatsmod) has failed to load correctly

Read your own log. stop spamming issues. this has nothing to do with spellbooks.

**Comment by itsdinkd** [comment]
I think this might be the same issue I experienced Iron, where with the client mixins trying to load on the server instance.

https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/c392d5fe5f31e823ad56ad455509f325429fcc8b/src/main/resources/mixins.irons_spellbooks.json#L8
