### ISSUE TITLE
[Bug] Spectral Steed Glitches if Summoned right on death

### ISSUE THREAD

**Issue by TheBooz** [iron431/Irons-Spells-n-Spellbooks#76]
### Observed behaviour

If you use Summon Horse while having an already summoned Spectral Steed, It'll glitch the death animation while still being alive

[Example Clip](https://streamable.com/25vwqk)

### Expected behaviour

It should summon the steed without glitching

### Steps to reproduce

1. Summon Horse
2. Wait for the CD
3. Summon Horse again right as the horse dies
4. It should now glitch out

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.18.2-1.1.4.1

### Forge version

40.2.9

### Other mods

  [✔] architectury-4.11.93-forge
  [✔] caelus-forge-1.18.1-3.0.0.2
  [✔] cloth-config-6.4.90-forge
  [✔] curios-forge-1.18.2-5.0.9.1
  [✔] geckolib-forge-1.18-3.0.57
  [✔] irons_spellbooks-1.18.2-1.1.4.1
  [✔] player-animation-lib-forge-1.0.2+1.18
  [✔] RoughlyEnoughItems-8.3.618

**Comment by TheBooz** [comment]
Unrelated to Original, but Summoned Polar Bears cannot move when you mount them and stay in place even with a target enemy, same Mod version and mods as above

**Comment by iron431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Horse health can be set even if it's dead](https://trello.com/c/XvElkHVm/664-horse-health-can-be-set-even-if-its-dead)
