### ISSUE TITLE
[Bug] Charge spell aura doesn't keep up with Parcool's running animation

### ISSUE THREAD

**Issue by Sketano** [iron431/Irons-Spells-n-Spellbooks#77]
### Observed behaviour

Parcool [https://www.curseforge.com/minecraft/mc-mods/parcool] adds a unique running animation, and if you use the "Charge" spell, the aura around the player doesn't fit in with the parcool running animation, Can the aura be placed on the player's limbs instead of playing a pre-determined animation for the action?

### Expected behaviour

.

### Steps to reproduce

1. Parcool + ISS installed
2. use charge spell, and run around in 3rd person

### Server Type

Single Player

### Iron's Spells N Spellbooks version

Latest

### Forge version

40.2.9

### Other mods

Parcool, latest

**Comment by iron431** [comment]
The charge layer is already based on the limbs. If parcool breaks render layers, that seems to me a parcool problem
