### ISSUE TITLE
[Bug] Summon Polar Bear scroll crashing game

### ISSUE THREAD

**Issue by LakefishMonster** [iron431/Irons-Spells-n-Spellbooks#79]
### Observed behaviour

Used legendary polar bear scroll in creative mode, game crashed, cant rejoin world without disabling and re-enabling it

### Expected behaviour

Polar bear to be summoned without game crashing

### Steps to reproduce

1. Use Summon Polar Bear Scroll (Level 10 Legendary) in creative mode
2. Crash when spell windup is finished

### Server Type

Single Player

### Crashlog

https://gist.github.com/LakefishMonster/7ed8b84a5a83d7d078ee8f44dfc9d9b2

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.6.2.jar

### Forge version

47.0.34

### Other mods

Listed in crash report

**Comment by iron431** [comment]
use latest version
