### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Hatchlinn** [iron431/Irons-Spells-n-Spellbooks#81]
### Observed behaviour

Spells would cancel charge mid cast when held

### Expected behaviour

spells would complete charge and cast when held

### Steps to reproduce

I dont even know, its just doing this on and off sometimes

1 try and use a hold spell with this modpack
2 see if it stops mid hold

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2-1.1.6

### Forge version

43.2.8

### Other mods

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/138748656/bf0e6160-e638-4975-bc4d-d8eb055335f6)
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/138748656/b5f4b3f6-933a-4e47-befe-202b4ae9b4e2)
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/138748656/fe2d5ca3-1fea-43f3-a2da-0f658a0a6e5f)
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/138748656/08e6d8b9-8bb0-40a4-a886-e783d9616b58)
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/138748656/44735629-500e-4402-920c-4c8e861d0492)

**Comment by iron431** [comment]
does it happen when you take damage?

**Comment by Hatchlinn** [comment]
nope

**Comment by iron431** [comment]
i suggest checking

**Comment by Hatchlinn** [comment]
on it

**Comment by Hatchlinn** [comment]
that may be the problem

**Comment by iron431** [comment]
That is intended behavior.
