### ISSUE TITLE
[Bug] 1.20crash-report

### ISSUE THREAD

**Issue by windy664** [iron431/Irons-Spells-n-Spellbooks#83]
### Observed behaviour

I'm running on server , and stop working after a while

### Expected behaviour

it can run as usual

### Steps to reproduce

1.Add mods into server
2.call some players to play
3.wait for a while

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/suiheng/4b58a709c7871956cd3483d2de39cdad#file-gistfile1-txt-L30

### Iron's Spells N Spellbooks version

least

### Forge version

least

### Other mods

[作物盛景]Croptopia-1.20-FORGE-2.3.1.jar
[倒置火把] ceilingtorch-1.20-1.25.jar
[前置]architectury-9.0.8-forge.jar
[前置]cloth-config-11.0.99-forge.jar
[前置]geckolib-forge-1.20.1-4.2.1.jar
[前置]supermartijn642corelib-1.1.9-forge-mc1.20.jar
[前置][化学]chemlib-1.20.1-2.0.17.jar
[前置][妖怪之山通用库] mysterious_mountain_lib-1.2.7-1.20.jar
[前置][怕愁死手册]Patchouli-1.20.1-80-FORGE-20230623.045847-5.jar
[前置][懒人厨房]balm-forge-1.20-7.0.4.jar
[前置][手册]modonomicon-1.20.1-1.37.0.jar
[前置][柠檬核心]lemon_core-1.20.1-1.0.17.jar
[前置][生物群系]TerraBlender-forge-1.20.1-3.0.0.165.jar
[前置][神秘主义][聪明大脑库]SmartBrainLib-fabric-1.20-1.11.jar
[前置][自然音效][创造核心]CreativeCore_FORGE_v2.10.26_mc1.20.1.jar
[前置][铁魔法]caelus-forge-3.1.0+1.20.jar
[前置][铁魔法]player-animation-lib-forge-1.0.2-rc1+1.20.jar
[前置][集成动力]CommonCapabilities-1.20.1-2.9.0.jar
[前置][集成动力]CyclopsCore-1.20.1-1.18.5.jar
[前置][饰品栏]curios-forge-5.2.0-beta.3+1.20.1.jar
[动态联合／集成动力] IntegratedDynamics-1.20.1-1.16.7.jar
[卡哇伊菜肴]KawaiiDishes_1.9.1-1.20.1.jar
[原神仪器]genshinstrument-1.20.1-2.7.8.jar
[史蒂夫模型]yesstevemodel-1.20-release-1.1.4.jar
[天空村庄] SkyVillages-1.0.2-1.20.1-forge-release.jar
[工匠之家]workshop_for_handsome_adventurer--mc1.20.1--1.01.jar
[循环] Cyclic-1.20-1.11.1.jar
[懒人厨房] cookingforblockheads-forge-1.20-16.0.0.jar
[摩登生活] modernlife-1.20.1-1.61.jar
[更多光源] additional_lights-1.20.1-2.1.7.jar
[更多实用工具]scalar_utils-1.20.1-5.4.9.jar
[更多灯笼] additionallanterns-1.0.4-forge-mc1.20.jar
[更多生物群系]BiomesOPlenty-1.20.1-18.0.0.592.jar
[更多磁盘] ExtraDisks-1.20.1-3.0.0.jar
[更多箱子]ironchest-1.20.1-14.4.4.jar
[机械动力] create-1.20.1-0.5.1.d.jar
[汉堡包]burgermod-2.9.4-1.20.1.jar
[浩渺能源]VoluminousEnergy-1.20-0.4 Beta 1.jar
[炼金术]theurgy-1.20.1-1.3.7.jar
[照相机]camera-1.20.1-1.0.4.jar
[神秘主义]occultism-1.20.1-1.80.12.jar
[管道]pipez-1.20.1-1.1.2.jar
[精致存储] refinedstorage-1.12.2.jar
[精致存储附属] refinedstorageaddons-0.10.0.jar
[自然罗盘／生物群系指南针] NaturesCompass-1.20.1-1.11.1-forge.jar
[豆腐工艺]TofuCraftReload-1.20.1-5.2.2.1.jar
[选装]oculus-mc1.20-1.6.4.jar
[选装][FPS减速器] FpsReducer2-forge-1.20-2.5.jar
[选装][JEI物品管理器] jei-1.20.1-forge-15.2.0.22.jar
[选装][Xaero的世界地图] XaerosWorldMap_1.30.6_Forge_1.20.jar
[选装][Xaero的小地图] Xaeros_Minimap_23.5.0_Forge_1.20.jar
[选装][区块加载]farsight-1.20.1-3.1.jar
[选装][夜间模式无处不在] DarkModeEverywhere-1.20.1-1.2.1.jar
[选装][更好的fps]betterfpsdist-1.20.1-2.9.jar
[选装][游戏菜单模组设定] gamemenumodoption-mc1.20-2.2.0.jar
[选装][点歌][forge-1.20]AllMusic-2.6.8.jar
[选装][玉]Jade-1.20-forge-11.1.4.jar
[选装][现代化 UI] ModernUI-1.20.1-3.7.0.5-universal.jar
[选装][聊天头像] chat_heads-0.10.16-forge-1.20.jar
[选装][自然音效] AmbientSounds_FORGE_v5.2.19_mc1.20.jar
[选装][苹果皮] appleskin-forge-mc1.20.1-2.5.0.jar
[选装][铷] rubidium-0.6.5.jar
[选装][镁／铷：动态光源] dynamiclightsreforged-1.20.1_v1.5.0.jar
[通电动力]energizedpower-1.20.1-1.7.6.jar
[铁氧体磁芯] ferritecore-6.0.0-forge.jar
[铁魔法]irons_spellbooks-1.20.1-1.1.6.2.jar
[集成合成学] IntegratedCrafting-1.20.1-1.1.3.jar
[飞车奇匠] automobility-0.4.2+1.20.1-forge.jar
[马儿蹦跳] umapyoi-0.2.14-1.20.jar
[魔法使]mahoutsukai-1.20.1-v1.34.50.jar

**Comment by iron431** [comment]
fixed in latest version
