### ISSUE TITLE
[Bug] Mob tries to cast null spell

### ISSUE THREAD

**Issue by Greygreygod** [iron431/Irons-Spells-n-Spellbooks#85]
### Observed behaviour

My friend crash the server,I don't know what's reason cause,i test some behaviour and fine.All I can tell from the log is that this is the problem.
From the log i just know entity has problem.

### Expected behaviour

When the problem player login,then the server down.

### Steps to reproduce

When the problem player login,then the server down.

### Server Type

Dedicated Server

### Crashlog

https://gist.github.com/Greygreygod/e1afd14e0ab221e7e4904e1ff5a77d23

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.7

### Forge version

forge 1.20.1-47.1.0

**Comment by iron431** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [something is fucked up with entities](https://trello.com/c/JwEM6NO8/675-something-is-fucked-up-with-entities)

**Comment by iron431** [comment]
this should be fixed in the latest version
