### ISSUE TITLE
[Bug] Recursive when checking loot tables causing crash

### ISSUE THREAD

**Issue by rozbrajaczpoziomow** [iron431/Irons-Spells-n-Spellbooks#87]
### Observed behaviour

I try to open a chest in Lost Cities and it crashes.

### Expected behaviour

Would be expecting it not to crash

### Steps to reproduce

Go to Lost Cities and open a chest (though from crashlog it seems that you'd also need PneumaticCraft as it's causing the start of the chain)

After further consideration it seems to just be one specific chest that crashes.

### Server Type

Single Player

### Crashlog

https://gist.github.com/rozbrajaczpoziomow/17027e014ee5809b938f4c3f784d4443

### Iron's Spells N Spellbooks version

1.20.1-1.1.6.2

### Forge version

47.1.0

### Other mods

A lot, since this is from the All The Mods 9 modpack, see crash log

**Comment by lab3** [comment]
try downgrading your forge or updating spellbooks
