### ISSUE TITLE
Priest spawn in the village

### ISSUE THREAD

**Issue by Augustio377** [iron431/Irons-Spells-n-Spellbooks#88]
### Feature description

Hi, sorry my english not good enough. Hopefully, u will read this. I wanted to spawn Priest inside the village, so they can heal and protect the villager. Sadly, After spawned, they disappear. I dont know that it bugs or some mechanic of Priest. I hope to receive a reponse from you soon. Thanks you.

### How it improves the player experience

In the begin, Priest can help player protect village as well, he can healing and support us in protect the village. He can protect while Raids

**Comment by iron431** [comment]
This was actually supposed to be the case originally, but it has been added now
