### ISSUE TITLE
[Bug] spell aoe/status effects not respecting pvp/friendly fire settings

### ISSUE THREAD

**Issue by milkembers** [iron431/Irons-Spells-n-Spellbooks#89]
### Observed behaviour

when using spells that have status effects / aoe components, friendly entities take damage or receive the status effect such as poison, etc even with proper settings in place

### Expected behaviour

when pvp is disabled on the server, players are on the same team, and friendlyfire is set to OFF for the team, spells should not be affecting them

### Steps to reproduce

1. turn off pvp
2. join team, disable friendly fire
3. use spells near/on your friends such as Magma Bomb, Wall of Fire, Poison Splash, etc
4. look at your poisoned/on fire/etc friends

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.1.7

### Forge version

47.1.0

### Other mods

all latest Forge versions of:
Alex's Mobs, Biomes O' Plenty, Croptopia, Domestication Innovation, GraveStone Mod, Hardcore Revival, Jade, JEI, ModernFix, Passive Shield, Project MMO, Security Craft, Serene Seasons, Shields+, Supplementaries, Tough as Nails, Traveler's Backpack, Universal Enchants, Waystones, Xaero's Minimap, Xaero's World Map

**Comment by KamiSami** [comment]
This shouldn't be a thing at all, i made similar issue before, unsure whether dev read my latest reply in there.. I mean, it's kinda dumb, you **need** an admin to be around manually doing commands if wanting to make non-pvp server, instead automatically it being non-pvp with one line of true or false in server config... So even if disable friendly fire was a thing, it needs manual input every time.
