### ISSUE TITLE
[Bug] Necromancer healing ring not despawning / need a command to get rid of it

### ISSUE THREAD

**Issue by SKY2SART** [iron431/Irons-Spells-n-Spellbooks#90]
### Observed behaviour

![Screenshot_4](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/139112615/b3b2d090-03db-4326-8504-02b285ab862b)

You can't "hit" the ring to remove it

### Expected behaviour

A way to remove it without an OP /kill command

### Steps to reproduce

1. Fight a necromancer until it does the healing ring

### Server Type

Dedicated Server

### Iron's Spells N Spellbooks version

1.19.2-1.1.3

### Forge version

43.2.10

**Comment by iron431** [comment]
"version: 1.1.3"
