### ISSUE TITLE
[Bug] Patchouli Book doesn't work

### ISSUE THREAD

**Issue by Peach774** [iron431/Irons-Spells-n-Spellbooks#92]
### Observed behaviour

The book doesn't work - says its invalid
![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/5171184/b8025934-7d45-4223-a87c-7e0f3ce70f37)

### Expected behaviour

Book should work

### Steps to reproduce

1. Play the game
2. Try to use the book

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.20.1-1.1.7

### Forge version

1.20.1 - 47.1.1

### Other mods

Patchouli 1.20.1-81

**Comment by drakray** [comment]
Same thing with Forge 47.1.3

**Comment by iron431** [comment]
linked to the wrong commit but it will still be fixed in the next release
