### ISSUE TITLE
[Bug] Spells do not cast properly for some players

### ISSUE THREAD

**Issue by EricIsntSmart** [iron431/Irons-Spells-n-Spellbooks#93]
### Observed behaviour

Certain spells that require a held input will stop a few frames after starting, i see nothing in the player's data that causes the issue, and it only applies to some players in our server. This issue persists in creative mode and even after quitting and rejoining.

### Expected behaviour

Spells with held inputs should continue until they run out of duration.

### Steps to reproduce

1. Put a spell like Siphoning Ray in a spell book
2. Try to cast the spell, hold down right click
3. Some players it will work for, some it wont.

### Server Type

Single Player

### Iron's Spells N Spellbooks version

irons_spellbooks-1.20.1-1.1.7

### Forge version

1.20.1 - 47.1.3

### Other mods

![image](https://github.com/iron431/Irons-Spells-n-Spellbooks/assets/102300342/ce2e8735-4f60-4d4b-b884-eed0e668c7b4)

**Comment by iron431** [comment]
there are many things that can cause spells to be interrupted. please give more info, like what specific spells and what else is happening that coincides with the spell being cancelled

**Comment by Keita974** [comment]
Hi, I have the same problem with my spells. But I'm the only one on the server to have it.
I found a solution to maintain a spell. I must first hold the right click on a block at my feet and then hold the left click. So i can't use fire magic or i burn too :/
