### ISSUE TITLE
Don't show cooldown text if button is held

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#95]
### Feature description

When you fire a spell, the text "this spell is on cooldown" immediately appears on screen - perhaps it would be better to only show this text if the player has let go of the attack button and tries to re-cast the spell?

### How it improves the player experience

Less clutter on the screen is always better!

**Comment by iron431** [comment]
this was already a feature on 1.19.2+, maybe the new title message messed something up

**Comment by iron431** [comment]
this bug seems to only affect instant casts
