### ISSUE TITLE
Use skeleton horse for summon horse spell

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#96]
### Feature description

It could be cool to have the summoned horse be a skeleton horse rather than a standard white horse.

### How it improves the player experience

I think a skeleton horse fits better thematically with the summoning aspects, and since they tend to be somewhat weaker (lower health etc) it would help balance out the ability to place a horse anywhere at any time.  
Additionally, with lowered stats one would still have some incentive to tame and breed regular horses.

**Comment by iron431** [comment]
Adding variants to spells is planned but is not a priority right now. Summon skeletal horse is already planned as a variant of the summon horse spell once we get around to it
