### ISSUE TITLE
[Bug] Summoned horse teleports to the player like a pet

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#97]
### Observed behaviour

Not sure if this classifies as a bug or a feature request so I'll just make it a bug for now!  

Horses summoned by the Summon Horse spell will teleport to the player like a pet.

### Expected behaviour

Horses don't usually do this and since they can't be told to sit I think it may make more sense to have the summoned horse not try to follow the player, acting more as a tamed creature than a pet.

### Steps to reproduce

1. Cast Summon Horse
2. Run around
3. Horse will follow and teleport to you

### Server Type

Single Player

### Iron's Spells N Spellbooks version

1.1.7

### Forge version

47.1.0

**Comment by iron431** [comment]
this is intended behavior

**Comment by MarioSMB** [comment]
Fair enough, there's merits to both ways of handling it, the current behaviour is fine as is!
