### ISSUE TITLE
Don't show summoned creature deaths in the chat

### ISSUE THREAD

**Issue by MarioSMB** [iron431/Irons-Spells-n-Spellbooks#98]
### Feature description

The game is currently treating summons like pets; when they die (or fade away in Vex's case) a message is shown in the chat. It may be better for gameplay to have their deaths be silent.

### How it improves the player experience

It will be a more immersive experience without pet deaths spammed in the chat!

**Comment by iron431** [comment]
treating summons like pets is intended

**Comment by MarioSMB** [comment]
Treating them like pets makes some sense, though I do believe their death messages should be suppressed from showing in the chat - afterall, they're not actually pets and have a limited lifespan.
